
("MIS.DGO"
  ;; ("target-racer-h.o" "target-racer-h")
  ;; ("racer-part.o" "racer-part")
  ;; ("racer.o" "racer")
  ;; ("target-racer.o" "target-racer")
  ;; ("racer-states.o" "racer-states")
  ;; ("collide-reaction-racer.o" "collide-reaction-racer")
  ("eichar-racer+0-ag.go" "eichar-racer+0")
  ("tpage-1119.go" "tpage-1119")
  ("battlecontroller.o" "battlecontroller")
  ("mistycannon.o" "mistycannon")
  ("babak-with-cannon.o" "babak-with-cannon")
  ("blocking-plane.o" "blocking-plane")
  ("misty-obs.o" "misty-obs")
  ("misty-warehouse.o" "misty-warehouse")
  ("misty-conveyor.o" "misty-conveyor")
  ("mud.o" "mud")
  ("muse.o" "muse")
  ("bonelurker.o" "bonelurker")
  ("quicksandlurker.o" "quicksandlurker")
  ("misty-teetertotter.o" "misty-teetertotter")
  ("balloonlurker.o" "balloonlurker")
  ("misty-part.o" "misty-part")
  ("sidekick-human.o" "sidekick-human")
  ("tpage-516.go" "tpage-516")
  ("tpage-521.go" "tpage-521")
  ("tpage-518.go" "tpage-518")
  ("tpage-520.go" "tpage-520")
  ("babak-ag.go" "babak")
  ("balloonlurker-ag.go" "balloonlurker")
  ("boatpaddle-ag.go" "boatpaddle")
  ("bonelurker-ag.go" "bonelurker")
  ("breakaway-left-ag.go" "breakaway-left")
  ("breakaway-mid-ag.go" "breakaway-mid")
  ("breakaway-right-ag.go" "breakaway-right")
  ("darkecocan-ag.go" "darkecocan")
  ("ef-plane-ag.go" "ef-plane")
  ("keg-ag.go" "keg")
  ("keg-conveyor-ag.go" "keg-conveyor")
  ("keg-conveyor-paddle-ag.go" "keg-conveyor-paddle")
  ("mis-bone-bridge-ag.go" "mis-bone-bridge")
  ("mis-bone-platform-ag.go" "mis-bone-platform")
  ("mistycam-ag.go" "mistycam")
  ("mistycannon-ag.go" "mistycannon")
  ("muse-ag.go" "muse")
  ("orb-cache-top-ag.go" "orb-cache-top")
  ("plat-eco-ag.go" "plat-eco")
  ("quicksandlurker-ag.go" "quicksandlurker")
  ("racer-ag.go" "racer")
  ("ropebridge-36-ag.go" "ropebridge-36")
  ("rounddoor-ag.go" "rounddoor")
  ("sack-ag.go" "sack")
  ("sharkey-ag.go" "sharkey")
  ("sidekick-human-ag.go" "sidekick-human")
  ("silostep-ag.go" "silostep")
  ("teetertotter-ag.go" "teetertotter")
  ("water-anim-misty-ag.go" "water-anim-misty")
  ("wheel-ag.go" "wheel")
  ("windturbine-ag.go" "windturbine")
  ("misty-vis.go" "misty-vis")
  )