
("ROL.DGO"
  ;; ("target-racer-h.o" "target-racer-h")
  ;; ("racer-part.o" "racer-part")
  ;; ("racer.o" "racer")
  ;; ("target-racer.o" "target-racer")
  ;; ("racer-states.o" "racer-states")
  ;; ("collide-reaction-racer.o" "collide-reaction-racer")
  ("eichar-racer+0-ag.go" "eichar-racer+0")
  ("tpage-1119.go" "tpage-1119")
  ("blocking-plane.o" "blocking-plane")
  ("rolling-obs.o" "rolling-obs")
  ("rolling-lightning-mole.o" "rolling-lightning-mole")
  ("rolling-robber.o" "rolling-robber")
  ("rolling-race-ring.o" "rolling-race-ring")
  ("tpage-923.go" "tpage-923")
  ("tpage-926.go" "tpage-926")
  ("tpage-924.go" "tpage-924")
  ("tpage-925.go" "tpage-925")
  ("tpage-1353.go" "tpage-1353")
  ("babak-ag.go" "babak")
  ("dark-plant-ag.go" "dark-plant")
  ("ecovalve-ag.go" "ecovalve")
  ("ef-plane-ag.go" "ef-plane")
  ("happy-plant-ag.go" "happy-plant")
  ("lightning-mole-ag.go" "lightning-mole")
  ("pusher-ag.go" "pusher")
  ("race-ring-ag.go" "race-ring")
  ("racer-ag.go" "racer")
  ("robber-ag.go" "robber")
  ("rolling-start-ag.go" "rolling-start")
  ("rollingcam-ag.go" "rollingcam")
  ("water-anim-rolling-ag.go" "water-anim-rolling")
  ("rolling-vis.go" "rolling-vis")
  )