("SWA.DGO"
 ("battlecontroller.o"
  "blocking-plane.o"
  ;; "flut-part.o"
  ;; "flutflut.o"
  ;; "target-flut.o"
  "eichar-flut+0-ag.go"
  "swamp-obs.o"
  "swamp-bat.o"
  "swamp-rat.o"
  "swamp-rat-nest.o"
  "kermit.o"
  "swamp-part.o"
  "billy.o"
  "eichar-pole+0-ag.go"
  "tpage-358.go"
  "tpage-659.go"
  "tpage-629.go"
  "tpage-630.go"
  "babak-ag.go"
  "balance-plat-ag.go"
  "billy-ag.go"
  "billy-sidekick-ag.go"
  "ecovalve-ag.go"
  "ef-plane-ag.go"
  "farthy-snack-ag.go"
  "flut-saddle-ag.go"
  "kermit-ag.go"
  "sharkey-ag.go"
  "swamp-bat-ag.go"
  "swamp-rat-ag.go"
  "swamp-rat-nest-ag.go"
  "swamp-rock-ag.go"
  "swamp-spike-ag.go"
  "swampcam-ag.go"
  "tar-plat-ag.go"
  "swamp-vis.go"
 ))
