("TIT.DGO"
  ("static-screen.o" "static-screen")
  ("title-obs.o" "title-obs")
  ("tpage-1609.go" "tpage-1609")
  ("tpage-416.go" "tpage-416")
  ("tpage-415.go" "tpage-415")
  ("tpage-397.go" "tpage-397")
  ("tpage-1499.go" "tpage-1499")
  ("logo-ag.go" "logo")
  ("logo-black-ag.go" "logo-black")
  ("logo-cam-ag.go" "logo-cam")
  ("logo-volumes-ag.go" "logo-volumes")
  ("ndi-ag.go" "ndi")
  ("ndi-cam-ag.go" "ndi-cam")
  ("ndi-volumes-ag.go" "ndi-volumes")
  ("title-vis.go" "title-vis")
  )