files:
  - source: /game/assets/jak1/text/game_custom_text_en-US.json
    translation: /game/assets/jak1/text/game_custom_text_%locale%.json
  - source: /game/assets/jak1/subtitle/subtitle_lines_en-US.json
    translation: /game/assets/jak1/subtitle/subtitle_lines_%locale%.json
    excluded_target_languages:
      - fr
      - de
      - es-ES
      - it
      - ja
      - en-GB
  - source: /game/assets/jak2/text/game_custom_text_en-US.json
    translation: /game/assets/jak2/text/game_custom_text_%locale%.json
  - source: /game/assets/jak2/subtitle/subtitle_lines_en-US.json
    translation: /game/assets/jak2/subtitle/subtitle_lines_%locale%.json
    excluded_target_languages:
      - "fr"
      - "de"
      - "es-ES"
      - "it"
      - "ja"
      - "ko"
      - "en-GB"
