version: '3'

tasks:
  format:
    cmds:
      - python ./third-party/run-clang-format/run-clang-format.py -r common decompiler game goalc test -i
  run-game:
    cmds:
      - ./out/build/Debug/bin/gk.exe -fakeiso -debug -nodisplay
  repl:
    cmds:
      - ./out/build/Debug/bin/goalc.exe -auto-lt
  decomp:
    cmds:
      - ./out/build/Debug/bin/decompiler.exe "./decompiler/config/jak1_ntsc_black_label.jsonc" "./iso_data/jak1" "./decompiler_out/jak1"
  decomp-clean:
    cmds:
      - rm ./decompiler_out/**/*.asm
      - rm ./decompiler_out/**/*disasm.gc