version: '3'

tasks:
  format:
    cmds:
      - python ./third-party/run-clang-format/run-clang-format.py -r common decompiler game goalc test -i
  run-game:
    cmds:
      - ./out/build/Debug/bin/gk.exe -fakeiso -debug
  repl:
    cmds:
      - ./out/build/Debug/bin/goalc.exe