os: Visual Studio 2017

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmake --version
  - cmake -DCOMPILE_TESTS=ON -DCOMPILE_EXAMPLES=ON .
  - cmake --build .
  - Debug\jsonrpccpp-test.exe -s
  - Debug\example-warehouse.exe
