
("MAI.DGO"
  ("cavecrystal-light.o" "cavecrystal-light")
  ("maincave-obs.o" "maincave-obs")
  ("maincave-part.o" "maincave-part")
  ("spiderwebs.o" "spiderwebs")
  ("dark-crystal.o" "dark-crystal")
  ("baby-spider.o" "baby-spider")
  ("mother-spider-h.o" "mother-spider-h")
  ("mother-spider-egg.o" "mother-spider-egg")
  ("mother-spider-proj.o" "mother-spider-proj")
  ("mother-spider.o" "mother-spider")
  ("gnawer.o" "gnawer")
  ("driller-lurker.o" "driller-lurker")
  ("launcherdoor.o" "launcherdoor")
  ("tpage-1313.go" "tpage-1313")
  ("tpage-1315.go" "tpage-1315")
  ("tpage-1314.go" "tpage-1314")
  ("tpage-1312.go" "tpage-1312")
  ("tpage-767.go" "tpage-767")
  ("baby-spider-ag.go" "baby-spider")
  ("cavetrapdoor-ag.go" "cavetrapdoor")
  ("dark-crystal-ag.go" "dark-crystal")
  ("driller-lurker-ag.go" "driller-lurker")
  ("ecovalve-ag.go" "ecovalve")
  ("gnawer-ag.go" "gnawer")
  ("launcherdoor-maincave-ag.go" "launcherdoor-maincave")
  ("maincavecam-ag.go" "maincavecam")
  ("mother-spider-ag.go" "mother-spider")
  ("plat-ag.go" "plat")
  ("spider-egg-ag.go" "spider-egg")
  ("spiderwebs-ag.go" "spiderwebs")
  ("water-anim-maincave-ag.go" "water-anim-maincave")
  ("water-anim-maincave-water-ag.go" "water-anim-maincave-water")
  ("maincave-vis.go" "maincave-vis")
  )