
("ROB.DGO"
  ("cave-trap.o" "cave-trap")
  ("spider-egg.o" "spider-egg")
  ("robocave-part.o" "robocave-part")
  ("eichar-pole+0-ag.go" "eichar-pole+0")
  ("tpage-1318.go" "tpage-1318")
  ("tpage-1319.go" "tpage-1319")
  ("tpage-1317.go" "tpage-1317")
  ("tpage-1316.go" "tpage-1316")
  ("babak-ag.go" "babak")
  ("baby-spider-ag.go" "baby-spider")
  ("cavecrusher-ag.go" "cavecrusher")
  ("caveelevator-ag.go" "caveelevator")
  ("cavespatulatwo-ag.go" "cavespatulatwo")
  ("cavetrapdoor-ag.go" "cavetrapdoor")
  ("driller-lurker-ag.go" "driller-lurker")
  ("ecovalve-ag.go" "ecovalve")
  ("plat-ag.go" "plat")
  ("plat-eco-ag.go" "plat-eco")
  ("spider-egg-ag.go" "spider-egg")
  ("spiderwebs-ag.go" "spiderwebs")
  ("water-anim-robocave-ag.go" "water-anim-robocave")
  ("robocave-vis.go" "robocave-vis")
  )