
("SUB.DGO"
  ("tpage-163.go" "tpage-163")
  ("tpage-164.go" "tpage-164")
  ("tpage-166.go" "tpage-166")
  ("tpage-162.go" "tpage-162")
  ("tpage-764.go" "tpage-764")
  ("babak-ag.go" "babak")
  ("blue-eco-charger-ag.go" "blue-eco-charger")
  ("blue-eco-charger-orb-ag.go" "blue-eco-charger-orb")
  ("bully-ag.go" "bully")
  ("ecovalve-ag.go" "ecovalve")
  ("floating-launcher-ag.go" "floating-launcher")
  ("helix-button-ag.go" "helix-button")
  ("helix-slide-door-ag.go" "helix-slide-door")
  ("shover-ag.go" "shover")
  ("steam-cap-ag.go" "steam-cap")
  ("sunkencam-ag.go" "sunkencam")
  ("sunkenfisha-ag.go" "sunkenfisha")
  ("wall-plat-ag.go" "wall-plat")
  ("water-anim-sunken-ag.go" "water-anim-sunken")
  ("water-anim-sunken-dark-eco-ag.go" "water-anim-sunken-dark-eco")
  ("sunkenb-vis.go" "sunkenb-vis")
  )