("TRA.DGO"
  ("training-obs.o" "training-obs")
  ("training-part.o" "training-part")
  ("tpage-1309.go" "tpage-1309")
  ("tpage-1311.go" "tpage-1311")
  ("tpage-1310.go" "tpage-1310")
  ("tpage-1308.go" "tpage-1308")
  ("tpage-775.go" "tpage-775")
  ("ecovalve-ag-TRA.go" "ecovalve")
  ("jng-iris-door-ag-TRA.go" "jng-iris-door")
  ("plat-eco-ag-TRA.go" "plat-eco")
  ("pontoonfive-ag-TRA.go" "pontoonfive")
  ("scarecrow-a-ag.go" "scarecrow-a")
  ("scarecrow-b-ag.go" "scarecrow-b")
  ("sharkey-ag-BEA-TRA-VI2.go" "sharkey")
  ("trainingcam-ag.go" "trainingcam")
  ("warp-gate-switch-ag-TRA.go" "warp-gate-switch")
  ("warpgate-ag.go" "warpgate")
  ("water-anim-training-ag.go" "water-anim-training")
  ("training-vis.go" "training-vis")
  )