name: Bug Report
description: Create a bug report.
labels: ["bug"]
body:
- type: textarea
  attributes:
    label: Describe the Bug
    description: A clear and concise description of what the bug is. You may post screenshots or videos of the bug here.
  validations:
    required: true

- type: textarea
  attributes:
    label: How To Reproduce
    description: Steps to reproduce the behavior. You can also post a video of it here.
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear and concise description of the expected behavior.
    placeholder: When I do X, Y should happen.
  validations:
    required: true

- type: input
  attributes:
    label: Operating System
    description: Windows version, Linux distribution, etc.
  validations:
    required: true

- type: dropdown
  attributes:
    label: OpenGOAL Version
    options:
      - Release
      - Compiled from source
  validations:
    required: true

- type: dropdown
  attributes:
    label: Game Version
    options:
      - NTSC 1.0 (black label)
      - NTSC Greatest Hits version (red label)
      - PAL
      - JP
  validations:
    required: true