blank_issues_enabled: true
contact_links:
  - name: Feature Requests and Ideas
    url: https://github.com/open-goal/jak-project/discussions/new/choose
    about: Please use the discussion board to bring up feature requests and ideas. If there is interest in them, they can then be converted to an issue(s).
  - name: Discord Help Channel
    url: https://discord.gg/dPRCfsju3N
    about: The best place for general help and asking questions.
