name: "\U0001F41B Jak 1 Bug Report"
description: Create a bug report for Jak 1.
labels: ["bug", "jak1"]
body:
  - type: checkboxes
    attributes:
      label: Acknowledgements
      description: Take a couple minutes to help our maintainers work faster.
      options:
        - label: I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
          required: true
        - label: I understand that I am supposed to provide my own legitimately obtained copy of the game
          required: true

  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is. You may post screenshots or videos of the bug here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How To Reproduce
      description: Steps to reproduce the behavior. You can also post a video of it here.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Does this problem occur on original hardware or PCSX2?
      description: Some things that may seem like bugs are actually exactly how the original game behaved.
      options:
        - Yes, it's unique to OpenGOAL
        - Didn't check
        - Not needed, bug is obvious
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of the expected behavior.
      placeholder: When I do X, Y should happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment Information
      description: "You can upload the [Support Package](https://github.com/open-goal/launcher#asking-for-help) provided by the Launcher here, or you can provide the following information: CPU, GPU, OS Version, OpenGOAL Version (found in the window's title bar)"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Game Version
      options:
        - NTSC 1.0 (black label)
        - NTSC Greatest Hits version (red label)
        - PAL
        - JP
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Have you set the game to something other than `60fps`?
      options:
        - "No"
        - "Yes"
    validations:
      required: true

