(language-id 3)

;; -----------------
;; intro
;; -----------------

("sage-intro-sequence-a"
  (24 :offscreen "SAMOS" "ME HE PASADO LA VIDA BUSCANDO RESPUESTAS QUE MI PADRE Y SUS ANTEPASADOS NO PUDIERON ENCONTRAR.")
  (260 :offscreen "SAMOS" "¿QUIÉNES ERAN LOS PRECURSOR? ¿POR QUÉ CREARON LOS ENORMES MONOLITOS QUE ENSUCIAN NUESTRO PLANETA?")
  (454 :offscreen "SAMOS" "¿CÓMO PUDIERON DOMINAR EL ECO? LA ENERGÍA VITAL DEL MUNDO.")
  (581 :offscreen "SAMOS" "¿Y POR QUÉ SE DESVANECIERON?")
  (708)
  (720 :offscreen "SAMOS" "HE PREGUNTADO A LAS PLANTAS PERO ELLAS NO LO RECUERDAN.")
  (818 :offscreen "SAMOS" "LAS PLANTAS SE LO HAN PREGUNTADO A LAS PIEDRAS, PERO ELLAS TAMPOCO SE ACUERDAN.")
  (955 :offscreen "SAMOS" "NI SIQUIERA LAS PIEDRAS SE ACUERDAN...")
  (1064)
  (1090 :offscreen "SAMOS" "CADA HUESO DE MI CUERPO ME DICE QUE LAS RESPUESTAN DESCANSAN EN LOS HOMBROS DE UN JOVEN.")
  (1297 :offscreen "SAMOS" "INCONSCIENTE DE SU DESTINO, A QUIEN NO LE INTERESA AVERIGUAR LA VERDAD, Y QUE RECHAZA MI GUÍA!")
  (1536)
  (1545 :offscreen "SAMOS" "¿Y POR QUÉ IBA ÉL A ESCUCHAR AL VIEJO SAMOS EL SABIO DE TODAS FORMAS?")
  (1680)
  (1686 :offscreen "SAMOS" "TAN SOLO SOY EL MAESTRO DEL ECO VERDE, UNO DE LOS HOMBRES MÁS SABIOS DEL PLANETA.")
  (1875)
  (1958 :offscreen "SAMOS" "ASÍ QUE PARECE QUE LA RESPUESTA NO ESTRIBA EN UNA CUIDADOSA INVESTIGACIÓN NI EN SENSATAS DELIBERACIONES, NO.")
  (2141)
  (2145 :offscreen "SAMOS" "COMO EN MUCHOS MISTERIOS DEL DESTINO")
  (2281 :offscreen "SAMOS" "COMIENZA CON UN PEQUEÑO ACTO DE DESOBEDIENCIA.")
  (2440 "DAXTER" "¡EH, JAK! EL AMIGUETE VERDE NOS DIJO QUE NO VINIÉSEMOS POR AQUÍ.")
  )

("sage-intro-sequence-d1"
  (137 "SAMOS" "¿PERO QUÉ DEMONIOS QUERÉIS VOSOTROS DOS?")
  (220 "DAXTER" "E- E- E- E- EEEESTÁBAMOS- MMMM- MMMM-")
  (283 "SAMOS" "¡NO SIGAS! EN LUGAR DE SEGUIR MI CONSEJO, FUISTEIS A TRASTEAR AL ÚNICO SITIO")
  (440 "SAMOS" "EN EL QUE OS DIJE QUE NO ENTRARAIS: ¡LA ISLA DE MISTY!")
  (550 "DAXTER" "¡BUENO SÍ! Y-")
  (579 "SAMOS" "Y TÚ, DAXTER, AL FINAL TE DISTE UN BAÑO, QUE TE HACÍA FALTA, PERO EN UNA BAÑERA REBOSANTE DE ECO OSCURO.")
  (793 "DAXTER" "MIRA ABUELETE, ¿VAS A SEGUIR REZONGANDO, O ME VAS A AYUDAR A SALIR DE ESTE LÍO?")
  (920 "SAMOS" "¡VOY A SEGUIR REZONGANDO! PORQUE EN MI DOCTA OPINIÓN, ESTE CAMBIO ES MÁS BIEN UNA MEJORA.")
  (1130 "SAMOS" "AUNQUE QUISIERA NO PODRÍA AYUDARTE.")
  (1186 "DAXTER" "¿¡QUÉ!?")
  (1220 "SAMOS" "SOLO HAY UNA PERSONA QUE HA ESTUDIADO EL TEMA DEL ECO OSCURO EL TIEMPO NECESARIO")
  (1329 "SAMOS" "COMO PARA PODER DEVOLVERTE A TU ESTADO ANTERIOR:")
  (1431 "SAMOS" "GOL ACHERON, EL SABIO.")
  (1493)
  (1496 :offscreen "SAMOS" "PERO VIVE LEJOS EN EL NORTE. MUY LEJOS EN EL NORTE. HACE AÑOS QUE NADIE HA HABLADO CON ÉL.")
  (1718 "SAMOS" "OS TELETRANSPORTARÍA ALLÍ, PERO TAMPOCO PUEDO HACERLO.")
  (1831 "SAMOS" "NINGUNO DE LOS TRES SABIOS QUE GUARDAN LAS OTRAS PUERTAS")
  (1934 "SAMOS" "HA VISTO ADECUADO ACTIVAR SU LADO DESDE HACE TIEMPO.")
  )

("sage-intro-sequence-d2"
  (3 "SAMOS" "LA OTRA ÚNICA MANERA DE IR AL NORTE ES ATRAVESANDO EL DESFILADERO DEL FUEGO")
  (114 :offscreen "SAGE" "PERO SU SUELO VOLCÁNICO ES TAN CALIENTE QUE FUNDE EL METAL.")
  (224 "SAMOS" "NO PODÉIS CAMINAR ENCIMA.")
  (270 "KEIRA" "PERO PODRÍAIS VOLAR ENCIMA, SI TUVIESEIS UN ZOOMER CON ESCUDO TÉRMICO.")
  (393)
  (396 "KEIRA" "DA LA CASUALIDAD DE QUE ESTOY TRABAJANDO EN ESO AHORA MISMO.")
  (512)
  (515 "KEIRA" "SOLO NECESITO VEINTE BATERÍAS QUE LE DEN LA ENERGÍA")
  (605 "KEIRA" "PARA RESISTIR EL CALOR DEL DESFILADERO. ¿VERDAD, PAPÁ?")
  (696)
  (699 "SAMOS" "SÍ, KEIRA, PODRÍA FUNCIONAR. ¿PERO DE DÓNDE VAN A SACAR UN CHICO")
  (826 :offscreen "SAMOS" "Y UN BICHO")
  (857 "SAMOS" "VEINTE BATERÍAS?")
  (910 "KEIRA" "DE LOS ALDEANOS. LA MAYORÍA TIENE UNA BATERÍA O DOS GUARDADAS EN ALGUNA PARTE.")
  (1050 :offscreen "KEIRA" "Y SI NO QUIEREN DÁROSLAS POR LAS BUENAS")
  (1133 "KEIRA" "SOBORNADLES CON UNAS CUANTAS ESFERAS DE PRECURSOR. Y YA VERÉIS CÓMO OS LAS DAN.")
  (1243)
  (1246 :offscreen "KEIRA" "Y ESTOY SEGURA DE QUE HABRÁ MÁS POR ESAS TIERRAS SALVAJES")
  (1364 "KEIRA" "ESPERANDO A QUE LAS ENCUENTRE UN BRAVO AVENTURERO.")
  (1435 "DAXTER" "POR LO MENOS TENEMOS AL BRAVO AVENTURERO.")
  (1529)
  (1532 "SAMOS" "¿BRAVO AVENTURERO?")
  (1582 "SAMOS" "¡VOSOTROS DOS NO PODRÍAIS ENCONTRAR LA SALIDA DE LA ALDEA SIN ENTRENAMIENTO!")
  (1685)
  (1689 "SAMOS" "ANTES DE NADA, ATRAVESAD LA PUERTA TRANSPORTADORA")
  (1810 "SAMOS" "Y PRACTICAD UN POCO EN LA ROCA DE GEYSER.")
  (1872)
  (1878 "DAXTER" "AAAMMMM, ¿NO IREMOS A ENCONTRAR MÁS ECO OSCURO DE ESE, VERDAD?")
  (1993 "DAXTER" "PORQUE NO ME GUSTARÍA CAERME DE NUEVO DENTRO Y ¡CONVERTIRME EN TÍ!")
  (2069)
  (2072 "SAMOS" "¡METEOS AHÍ ANTES DE QUE OS CONVIERTA EN ALFALFA!")
  (2189)
  )

("sage-intro-sequence-e"
  (200 "SAMOS" "BUEN ENTRENAMIENTO, CHICOS, PERO ESO NO ES NADA COMPARADO CON LOS DESAFÍOS QUE OS AGUARDAN.")
  (359 "DAXTER" "BUEEENO, NO HAY PROBLEEEMA. SABEMOS MOVERNOS, ¿EH, JAK?")
  (496 "DAXTER" "NOS ENCANTARÍA QUEDARNOS A CHARLAR, PERO, ARDEMOS EN DESEOS DE EMPRENDER AVENTURAS.")
  (660 "SAMOS" "BIEN, BIEN. PUES A LA \"AVENTURA\" ENTONCES..")
  (787 "SAMOS" "Y DURANTE ESAS \"AVENTURAS,\" PODRÍAIS HACER ALGO ÚTIL.")
  (940)
  (952 :offscreen "SAMOS" "MIS MALDITOS RECOLECTORES DE ECO VERDE ESTÁN ATASCADOS DE NUEVO.")
  (1043)
  (1046 :offscreen "SAMOS" "ID AL EXTREMO DE LA PLAYA Y DESBLOQUEADLOS, ¿DE ACUERDO?")
  (1160)
  (1169 :offscreen "SAMOS" "SEGUID LAS LUCES. OS LLEVARÁN ALLÍ.")
  (1310)
  (1313 :offscreen "SAMOS" "AHORA, LOS DOS...")
  (1415)
  (1439 :offscreen "SAMOS" "FUEEEEERA DE AQUÍ!")
  )

("sidekick-human-intro-sequence-b"
  (547 "ANCIANO" "SEGUID BUSCANDO ARTEFACTOS Y ECO.")
  (674 "ANCIANO" "SI LA GENTE DEL LUGAR TIENE OBJETOS DE PRECURSOR, YA SABÉIS QUÉ HACER.")
  (842 "MUJER" "OCUPAOS BIEN DE AQUELLOS QUE SE DESPISTEN FUERA DE LA ALDEA.")
  (937 "MUJER" "ATACAREMOS EN SU MOMENTO.")
  (1027)
  )

("sidekick-human-intro-sequence-c"
  (12 "DAXTER" "PERO ¿QUÉ HACEMOS AQUÍ, JAK? ¡ESTE SITIO ME ASUSTA!")
  (151)
  (369 "DAXTER" "EEH?")
  (404 "DAXTER" "OH...¡MALDITA PORQUERÍA PRECURSOR!")
  (496)
  (577 "DAXTER" "¡AAY! ¿QUÉ ES ESO OSCURO QUE REZUMA? NO PARECE MUY AMISTOSO.")
  (721)
  (777 "DAXTER" "EL SABIO SE PASA EL DÍA REFUNFUÑANDO SOBRE LOS PRECURSOR QUE CONSTRUYERON ESTE SITIO.")
  (909 "DAXTER" "\"¿A DÓNDE SE FUERON? ¿POR QUÉ CONSTRUYERON ESTA PORQUERÍA?\"")
  (1014 "DAXTER" "ME GUSTAN LAS ESFERAS DE PRECURSOR Y LAS BATERÍAS TANTO COMO A CUALQUIERA")
  (1124 "DAXTER" "PERO, SI TE DIGO LA VERDAD, DEBIERON DE SER UNOS PRINGAOS.")
  (1212 "DAXTER" "¡VAAYA! ¿CÓMO HAS HECHO ESO?")
  (1271)
  (1331 "DAXTER" "JAK, CREO QUE TENEMOS PROBLEMAS.")
  (1386)
  (1622 "DAXTER" "¡SOCORROOOO!")
  (1660)
  (1857 "DAXTER" "¡CHICO, ESO HA DOLIDO!.")
  (1913)
  (1941 "DAXTER" "TE DIJE QUE NO TENÍAMOS QUE HABER VENIDO, ¿HABÍAS OÍDO...")
  (2028)
  (2057 "DAXTER" "¿¿QUÉ??")
  (2101)
  (2189 "DAXTER" "AAAAAAAAHHHHHHHH!!")
  (2307 "DAXTER" "¡VAALE!, VALE. ESTOY BIEN, ¿ESTOY BIEN?")
  (2431)
  (2481 "DAXTER" "AAAAAAAAAAAAAAAAAAAHHHHHHHH!!")
  )

;; -----------------
;; sidekick
;; -----------------

("sksp0001" :hint #x280
  (0 "DAXTER" "¡EH! ESE BOMBÓN DE KEIRA TENÍA RAZÓN. ¡AQUÍ HAY TRANS-PADS!")
  )

("sksp0002" :hint #x281
  (0 "DAXTER" "¡CRÉEME, ESAS CAJAS DE ECO OSCURO TIENEN MUUUUUUY MALA PINTA!")
  )

("sksp0003" :hint #x282
  (0 "DAXTER" "SEGURO QUE SI ENCONTRAMOS A TODAS ESAS CONDENADAS MOSCAS EXPLORADORAS DE CADA NIVEL")
  (215 "DAXTER" "AL MENOS UNO TENDRÁ UNA BATERÍA!")
  )

("sksp0004" :hint #x283
  (0 "DAXTER" "¡SÍ SEÑOR, UN TESORO!")
  )

("sksp0005" :hint #x284
  (0 "DAXTER" "¡SEGURO QUE CAJAS DE MADERA Y METAL NO SON TAN RESISTENTES!")
  (166 "DAXTER" "VERÁS COMO SE ROMPEN SI SALTAS EN PICADO ENCIMA.")
  )

("sksp0006" :hint #x285
  (0 "DAXTER" "ESAS CAJAS DE METAL SON MÁS GRUESAS QUE EL CRANEO DE UNA YAKOW.")
  (188 "DAXTER" "PERO DEBE DE HABER UNA FORMA DE ABRIRLAS.")
  )

("sksp0007" :hint #x286
  (0 "DAXTER" "DOS PALABRAS: LAS BATERÍAS. HAY QUE ENCONTRARLAS. Y PARA ESO HAY QUE BUSCARLAS BIEN DE UNA VEZ.")
  )

("sksp0008" :hint #x287
  (0 "DAXTER" "NECESITAMOS ESFERAS, ¡EEEESFERAS, JAK! ¡¿CÓMO VAMOS A COMPRAR BATERÍAS SI NO REUNIMOS ESFERAS?!")
  )

("sksp0009" :hint #x251
  (0 "DAXTER" "¡QUÉ ASPECTO MÁS EXTRAÑO TIENE! SEGURO QUE LO PODEMOS ABRIR")
  (206 "DAXTER" "SI LE APLICAS UN POCO...DEL ECO AZUL ESE.")
  )

("sksp0014" :hint #x233
  (0 "DAXTER" "HEMOS REUNIDO LAS ESFERAS SUFICIENTES PARA UNA BATERÍA.")
  (215 "DAXTER" "¡VAYAMOS A HACER EL TRUEQUE!")
  )

("sksp0035" :hint #x25c
  (0 "DAXTER" "VALE, TENEMOS UN LANZADOR DE PRECURSOR AQUÍ.")
  (117 "DAXTER" "PERO COMO NO LE HAS APLICADO ENERGÍA AZUL, ¡NO NOS SERVIRÁ DE NADA!")
  )

("sksp0071" :hint #x2a5
  (0 "DAXTER" "¡CONSIGUE EL ECO ROJO!")
  )

("sksp0072" :hint #x2a6
  (0 "DAXTER" "EL ECO ROJO FORTALECE TUS ATAQUES.")
  )

("sksp0073" :hint #x2a7
  (0 "DAXTER" "NECESITAMOS ECO AZUL PARA RECARGAR ESTO.")
  )

("sksp009a" :hint #x0
  (0 "DAXTER" "¡JAJAJAJA! ¡LE HEMOS DADO UNA BUENA LECCIÓN!")
  )

("sksp009b" :hint #x28e
  (0 "DAXTER" "¡MUY BIEN, MÁS ESFERAS!")
  )

("sksp009c" :hint #x28f
  (0 "DAXTER" "¡HAZME UN FAVOR Y ALÉJATE DE ESAS CAJAS DE ECO OSCURO!")
  )

("sksp009d" :hint #x290
  (0 "DAXTER" "YUUUUUUJUJUJUJUJUUYY!")
  )

("sksp009e" :hint #x291
  (0 "DAXTER" "WUUUUUUUUU!")
  )

("sksp009f" :hint #x292
  (0 "DAXTER" "¡TOMA!, ¡TOMA! JAJAJAJA!")
  )

("sksp009g" :hint #x293
  (0 "DAXTER" "¡DETRÁS DE TÍ, JAK!")
  )

("sksp009i" :hint #x294
  (0 "DAXTER" "¿HEMOS ENCONTRADO TODAS LAS MOSCAS EXPLORADORAS DE ESTA ZONA?")
  )

("sksp009j" :hint #x295
  (0 "DAXTER" "¡EH! PARECE SER QUE LAS MOSCAS EXPLORADORAS SIEMPRE ESTÁN EN CAJAS ROJAS.")
  )

("sksp009k" :hint #x296
  (0 "DAXTER" "¡MUY BIEN! ¡HAS ENCONTRADO TODAS LAS MOSCAS EXPLORADORAS DE ESTA ZONA!")
  )

("sksp0145" :hint #x359
  (0 "DAXTER" "¡GUAAU! ¡CUANDO TIENES ECO AMARILLO PUEDES DISPARAR BOLAS DE FUEGO!")
  )

;; -----------------
;; village1
;; -----------------

("ASSTLP01" :hint #x0
  (0 "KEIRA" "HMM...")
  )

("ASSTLP02" :hint #x0
  (0 "KEIRA" "TENGO QUE ARREGLAR ESTE ESCUDO TÉRMICO...")
  )

("ASSTLP03" :hint #x0
  (0 "KEIRA" "NECESITAMOS BATERÍAS PARA ALIMENTAR EL ESCUDO TÉRMICO...")
  )

("ASSTLP04" :hint #x0
  (0 "KEIRA" "¿DÓNDE ESTÁ MI LLAVE?")
  )

("ASSTLP05" :hint #x0
  (0 "KEIRA" "EL DESFILADERO DEL FUEGO ESTÁ TAN CALIENTE...")
  )

("EXP-AM01" :hint #x0
  (0 "EXPLORADOR" "TENGO QUE IRME DE VIAJE PRONTO. NECESITO ESFERAS DE LOS PRECURSORES.")
  )

("EXP-AM02" :hint #x0
  (0 "EXPLORADOR" "VEAMOS...¿A DÓNDE VOY PRIMERO? MMM...")
  )

("EXP-AM03" :hint #x0
  (0 "EXPLORADOR" "OH...¡CÓMO ECHO DE MENOS VIAJAR!")
  )

("EXP-AM04" :hint #x0
  (0 "EXPLORADOR" "TANTOS LUGARES POR VER Y TAN POCO TIEMPO.")
  )

("EXP-AM05" :hint #x0
  (0 "EXPLORADOR" "EN MIS TIEMPOS, UNO PODÍA RECORRER EL MUNDO SIN QUE LE ASALTASEN MONSTRUOS.")
  )

("EXP-LO02" :hint #x0
  (0 "EXPLORADOR" "NECESITO MÁS ESFERAS DE LOS PRECURSORES.")
  )

("FAR-AM01" :hint #x0
  (0 "GRANJERO" "(RONQUIDOS)")
  )

("FAR-AM02" :hint #x0
  (0 "GRANJERO" "(RONQUIDOS)(BALBUCEO)")
  )

("FAR-AM2A" :hint #x0
  (0 "GRANJERO" "(BALBUCEO)...TENGO QUE RECOGER LA COSECHA ANTES DE QUE SE LA COMAN LOS BICHOS DE JUNE...(RONQUIDOS)")
  )

("FAR-LO01" :hint #x0
  (0 "GRANJERO" "(RONQUIDOS)")
  )

("FAR-LO1A" :hint #x0
  (0 "GRANJERO" "(RONQUIDOS)")
  )

("SAGELP03" :hint #x0
  (0 "SAMOS" "ESTOS DOS NO SON CAPACES NI DE DESBLOQUEARSE LA NARIZ...")
  )

("SAGELP04" :hint #x0
  (0 "SAMOS" "NUNCA SERÁ COMO SU TÍO...")
  (221 "SAMOS" "NO ME IMPORTA LO QUE DIGAN LOS DEMÁS.")
  )

("SAGELP05" :hint #x0
  (0 "SAMOS" "HOLA, ¿SABIO AZUL? ¡HOLA! ¿DÓNDE DIANTRE ESTARÁ...?")
  )

("SAGELP06" :hint #x0
  (0 "SAMOS" "VAYA, VAYA, VAYA...")
  )

("SAGELP11" :hint #x0
  (0 "SAMOS" "¿HAY ALGUIEN? ¡QUIEN SEA! ¡RESPONDED!")
  )

("assistant-introduction-blue-eco-switch"
  (23 "DAXTER" "¡EEH, NENA! ¿QUÉ TE PARECE SI TE DOY UNA VUELTA EN ESTE ZOOMER ANTIGRAVITATORIO?")
  (175)
  (193 "KEIRA" "REGLA NÚMERO UNO: NO SALGO CON ANIMALES.")
  (308)
  (312 "DAXTER" "VAAAYA, PUES NO SABES LO QUE TE PIERDES, JIJIJIJI.")
  (430)
  (505 "KEIRA" "ESCUCHAD, SI QUIERES ESTAR OCUPADO CON ALGO, MI PADRE SIEMPRE HABLABA")
  (635 "KEIRA" "DE UNA ANTIGUA TUBERÍA DE PRECURSOR ESCONDIDA PROFUNDAMENTE BAJO TIERRA.")
  (739)
  (742 :offscreen "KEIRA" "ALGUNAS DE ESTAS TUBERÍAS ACABAN EN RESPIRADEROS POR LOS QUE SALE ECO,")
  (842 :offscreen "KEIRA" "Y ALGUNAS HAN SIDO SELLADAS PARA QUE EL ECO QUEDE ENCERRADO.")
  (945)
  (954 "KEIRA" "DEBE DE HABER UNA MANERA DE ABRIR LOS RESPIRADEROS SELLADOS.")
  (1052 :offscreen "KEIRA" "HE SEGUIDO EL RASTRO DE LA TUBERÍA HASTA EL TEMPLO PROHIBIDO.")
  (1138 "KEIRA" "TAL VEZ DEBERÍAIS BUSCAR ALLÍ ALGÚN INTERRUPTOR.")
  (1246)
  )

("assistant-introduction-race-bike"
  (9 "DAXTER" "¡EH, NENA!, ¿EN QUÉ TRABAJAS?")
  (63 "KEIRA" "¡CUIDADO CON ESO! ESTOY INTENTANDO AVERIGUAR CÓMO TRANSPORTAR EL ZOOMER")
  (200 "KEIRA" "CON LOS TRANS-PAD QUE LOS PRECURSORS HAN DEJADO POR TODO EL MUNDO.")
  (308)
  (312 :offscreen "KEIRA" "SI OS ENCONTRÁIS CON UNO DE ESOS TRANS-PAD, PODRÉ DEJAR LA UBICACIÓN DE VUESTRO COMUNICADOR")
  (453 :offscreen "KEIRA" "Y ENVIAROS EL ZOOMER.")
  (508 "KEIRA" "ESTAD ATENTOS POR SI ENCONTRÁIS UN TRANS-PAD AL EXPLORAR MISTY ISLAND Y EN CUALQUIER OTRO SITIO.")
  (665)
  )

("assistant-reminder-1-blue-eco-switch"
  (23 "KEIRA" "ESTOY SEGURA DE QUE SI MIRÁIS DENTRO DEL TEMPLO PRECURSOR PROHIBIDO")
  (143 "KEIRA" "ENCONTRARÉIS LA MANERA DE ACTIVAR EL RESPIRADERO DE ECO AZUL DE LA PLAYA DEL CENTINELA.")
  (295)
  )

("assistant-reminder-1-generic"
  (25 "KEIRA" "¡EH, CHICOS! SEGUID REUNIENDO BATERÍAS. SON FUNDAMENTALES PARA SEGUIR NUESTRA TRAVESÍA HACIA EL NORTE.")
  )

("assistant-reminder-1-race-bike"
  (19 "KEIRA" "HE AVERIGUADO CÓMO USAR LOS TRANS-PAD.")
  (106 "KEIRA" "AHORA ID A MISTY ISLAND Y ENVIARÉ ALLÍ EL ZOOMER.")
  (229)
  )

("asstvb04" :hint #x2b1
  (0 "KEIRA" "BIEN, ¡HABÉIS REUNIDO LAS SUFICIENTES BATERÍAS PARA ACTIVAR MI ESCUDO TÉRMICO!")
  (233 "KEIRA" "ESCALAD EL ACANTILADO TRAS LA CASA DEL GRANJERO PARA REUNIROS CONMIGO EN LA ENTRADA DEL DESFILADERO DEL FUEGO.")
  (559 "KEIRA" "TRAED LAS BATERÍAS, ¡Y DAOS PRISA! ¡MI PADRE DICE QUE HA VISTO A MÁS LURKERS RONDANDO!")
  )

("asstvb08" :hint #x2b2
  (0 "KEIRA" "DAOS PRISA CON LAS BATERÍAS. OS ESPERO AL PRINCIPIO DEL DESFILADERO DEL FUEGO")
  (260 "KEIRA" "SUBIENDO EL ACANTILADO QUE HAY TRAS LA CASA DEL GRANJERO.")
  )

("explorer-introduction"
  (23 "EXPLORADOR" "VAYA, ¡HOLA, CHAVAL! ME HAS PILLADO EN EL MOMENTO MÁS INOPORTUNO.")
  (197 "EXPLORADOR" "IBA A MARCHARME DE VIAJE AYER,")
  (288 "EXPLORADOR" "PERO ME HE QUEDADO ALGO ESCASO DE ESFERAS DE LOS PRECURSORES.")
  (426)
  (430 "EXPLORADOR" "JURARÍA QUE TENÍA 90 ESFERAS,")
  (538 "EXPLORADOR" "PERO ME DA QUE TU AMIGUETE...YA SABES, LA SABANDIJA ESA...")
  (716 "EXPLORADOR" "ME LAS DEBE DE HABER QUITADO SOLO PARA DIVERTIRSE.")
  (829)
  (865 "EXPLORADOR" "EN CUALQUIER CASO, ¿SERÍAS TAN AMABLE DE PRESTARLE A TU QUERIDO TÍO 90 ESFERAS DE LOS PRECURSORES")
  (1043 "EXPLORADOR" "PARA QUE PUEDA PONERSE EN CAMINO? A CAMBIO, TE DARÍA UNA BATERÍA.")
  )

("explorer-reminder-1"
  (25 "EXPLORADOR" "¿QUÉ? ¿NO LAS TIENES TODAS?")
  (148 "EXPLORADOR" "PUES CON MENOS DE 90 ESFERAS DE LOS PRECURSORES,")
  (251 "EXPLORADOR" "NO PODRÉ IR A NINGÚN LADO, CHAVALÍN.")
  (387)
  )

("explorer-reminder-2"
  (33 "EXPLORADOR" "¡BUENO, VEAMOS! EL TRATO SON 90 ESFERAS DE LOS PRECURSORES POR UNA BATERÍA.")
  (187 "EXPLORADOR" "ME PARECE UN TRATO BASTANTE JUSTO.")
  )

("explorer-resolution"
  (28 "EXPLORADOR" "VEO QUE LOS DOS HABÉIS VUELTO PARA HACER NEGOCIOS. ¡MUY BIEN!, ¡MUY BIEN!")
  (179 "EXPLORADOR" "EH...¿TENÉIS LA CANTIDAD DE ESFERAS DE LOS PRECURSORES ACORDADA?")
  (310)
  (324 "EXPLORADOR" "ME HA COSTADO MUCHO CONSEGUIR ESTA BATERÍA. ¡USADLA BIEN! ¡HASTA LUEGO, CHAO, BYE BYE!")
  )

("farmer-introduction"
  (1 "GRANJERO" "TENGO QUE ORDEÑAR A LAS YAKOUS, TENGO QUE ORDENAR A LAS YAKOUS...")
  (113 "GRANJERO" "¡EH, ERES TÚ! AH...ESTABA DESCANSANDO UN POQUITO. LLEVO TODO EL DÍA INTENTANDO ENCERRAR A ESAS IRASCIBLES YAKOUS.")
  (317 "GRANJERO" "UNAS EXTRAÑAS CRIATURAS INTENTARON ROBARLAS ANTES.")
  (470 "GRANJERO" "¿CREÉIS QUE PODRÉIS AYUDAR A ESTE VIEJO A METERLAS EN EL CORRAL?")
  )

("farmer-reminder-1"
  (0 "GRANJERO" "¡EH, EHH! ¡MIS YAKOUS ESTÁN TODAVÍA SUELTAS! ¿ME...LAS PODRÍAIS TRAER PRONTO?")
  )

("farmer-reminder-2"
  (0 "GRANJERO" "¡ESAS MALDITAS YAKOUS SIGUEN DEAMBULANDO LIBRES!")
  (85 "GRANJERO" "¿VAIS A METERLAS EN EL CORRAL DE UNA VEZ?")
  )

("farmer-resolution"
  (0 "GRANJERO" "¡EH!, ¡BIEN HECHO, CHAVAL! HAS CONSEGUIDO METER A ESAS PESADAS EN EL CORRAL.")
  (134 "GRANJERO" "¡YA PUEDO DORMIR TRANQUILO! TOMA ESTA BATERÍA POR MOLESTARTE.")
  (340)
  )

("sage-introduction-misty-cannon"
  (24 "SAMOS" "OH, SON LOS CONQUISTADORES.")
  (136 "SAMOS" "BIEN, QUERÍA HABLAR CON VOSOTROS DOS DE COSAS SERIAS.")
  (258)
  (261 :offscreen "SAMOS" "PARECE SER QUE HAY CIERTA ACTIVIDAD LURKER EN MISTY ISLAND.")
  (387)
  (393 :offscreen "SAMOS" "PUEDO VER CÓMO BOMBARDEAN EL SILO PRECURSOR DESDE MI OBSERVATORIO.")
  (525)
  (528 "SAMOS" "SI LOS LURKERS LO ABREN Y LIBERAN EL ECO OSCURO, PODRÍAMOS ACABAR TODOS")
  (663 "SAMOS" "CON EL ASPECTO RIDÍCULO DE ESTE MOLESTO ESPÉCIMEN.")
  (788)
  (807 "SAMOS" "JAK, ES EL MOMENTO DE QUE DEMUESTRES LO QUE VALES.")
  (906 "SAMOS" "CONSIGUE QUE EL PESCADOR TE DEJE SU BARCO PARA IR A MISTY ISLAND")
  (1018 "SAMOS" "SUBE A LA CIMA DEL SILO DE PRECURSOR Y ACABA CON ESE CAÑÓN.")
  (1171)
  (1177 "DAXTER" "Y...¿QUÉ HAY DE MÍ?")
  (1232)
  (1235 "SAMOS" "¿TÚ? ¿POR QUÉ NO FRIEGAS EL SUELO? PARECE HABER PERDIDO BRILLO ÚLTIMAMENTE.")
  )

("sage-reminder-1-ecorocks"
  (28 "SAMOS" "MENUDOS \"AVENTUREROS VALIENTES\" QUE SOIS.")
  (132 "SAMOS" "YA HABÉIS VUELTO Y NO HABÉIS DESBLOQUEADO MIS COSECHADORES DE ECO.")
  (244)
  (252 :offscreen "SAMOS" "ESTÁN EN EL EXTREMO DE LA PLAYA, CHICOS.")
  (365)
  (366 :offscreen "SAMOS" "AHORA...")
  (412 :offscreen "SAMOS" "¡EN MARCHA!")
  )

("sage-reminder-1-generic"
  (54 "SAMOS" "¿QUÉ HACÉIS LOS DOS AQUÍ? ¡TENÉIS QUE IR A CONSEGUIR BATERÍAS!")
  (178)
  (181 "SAMOS" "HASTA QUE LAS CONSIGÁIS...¡DEJAZME EN PAZ!")
  )

("sage-reminder-1-misty-cannon"
  (28 "SAMOS" "MENUDOS \"AVENTUREROS VALIENTES\" QUE SOIS.")
  (132 "SAMOS" "YA HABÉIS VUELTO Y NO HABÉIS DESBLOQUEADO MIS COSECHADORES DE ECO.")
  (244)
  (252 :offscreen "SAMOS" "ESTÁN EN EL EXTREMO DE LA PLAYA, CHICOS.")
  (365)
  (366 :offscreen "SAMOS" "AHORA...")
  (412 :offscreen "SAMOS" "¡EN MARCHA!")
  )

("sage-reminder-2-generic"
  (27 "SAMOS" "NO ACABÁIS DE ENTENDER LA GRAVEDAD DE LA SITUACIÓN.")
  (137 "SAMOS" "LA COSA NO SE QUEDA EN LA TRANSFORMACIÓN DE UN CHAVAL EN BICHO PELUDO. ESTO CONCIERNE A LA VIDA TAL Y COMO LA CONOCEMOS.")
  (320)
  (323 "SAMOS" "AHORA MARCHÁOS Y COMPLETAD VUESTRA TAREA.")
  (455)
  )

("sksp0010" :hint #x231
  (0 "DAXTER" "¡EH! VAMOS A ECHAR UN VISTAZO A LA SUPER LANCHA DEL LOBO DE MAR EN EL PUERTO.")
  )

("sksp0013" :hint #x232
  (0 "DAXTER" "¿HAS VISTO EL PEDAZO DE BOCADO QUE LE PEGÓ UN TIBURÓN LURKER AL BARCO DEL PESCADOR?")
  (315)
  (337 "DAXTER" "¡MÁS NOS VALE ESTAR BIEN LEJITOS DE ELLOS! NO CREO QUE NOS PODAMOS ENFRENTAR A ALGO TAN TREMENDO.")
  )

("sksp0015" :hint #x234
  (0 "DAXTER" "ESTO DEBE DE SER EL ORÁCULO DE PRECURSOR DEL QUE SIEMPRE HABLA EL SABIO.")
  (228 "DAXTER" "¡ESPERABA QUE NO FUESE TAN FEO EN PERSONA!")
  )

("sksp0017" :hint #x235
  (0 "DAXTER" "¡GUAU! ¡ECHA UN VISTAZO A LA ESCULTURA TAN HORTERA QUE HAY EN AQUELLAS ROCAS!")
  )

("sksp0043" :hint #x24e
  (0 "DAXTER" "TAL VEZ DEBERÍAMOS IR A VER AL PESCADOR.")
  (106 "DAXTER" "HE OÍDO QUE SUELE PESCAR EN EL RÍO DE LA SELVA.")
  )

("sksp018a" :hint #x297
  (0 "DAXTER" "¡EL GANDUL DEL GRANJERO NOS DEBE UNA BATERÍA!")
  (156 "DAXTER" "¡HABLEMOS CON ÉL!")
  )

;; -----------------
;; oracle
;; -----------------

("oracle-intro-1"
  (0 "ORÁCULO" "¿QUIÉN DESPIERTA AL ORÁCULO?")
  (75)
  (81 "ORÁCULO" "¡ESPERA!, UNO DE LOS DOS LLEVA LA LUZ DENTRO.")
  (198)
  (206 "ORÁCULO" "HE ESTADO AGUARDANDO EL RETORNO DEL HÉROE VERDADERO DESDE HACE MILENIOS.")
  (390)
  (395 "ORÁCULO" "TREAEDME 120 ESFERAS DE PRECURSOR, POR CADA BATERÍA QUE ALBERGO.")
  )

("oracle-left-eye-1"
  (0 "ORÁCULO" "HABÉIS DEMOSTRADO SER HONESTOS. HE AQUÍ UNA BATERÍA.")
  )

("oracle-right-eye-1"
  (0 "ORÁCULO" "TOMAD UNA BATERÍA A CAMBIO DE VUESTRO REGALO.")
  )

("oracle-reminder-1"
  (0 "ORÁCULO" "TRAEDME 120 ESFERAS DE PRECURSOR, Y OS DARÉ UNA BATERÍA.")
  )

("oracle-left-eye-2"
  (0 "ORÁCULO" "POR VUESTRO SACRIFICIO, UNA BATERÍA OS DOY.")
  )

("oracle-right-eye-2"
  (0 "ORÁCULO" "HE AQUÍ OTRA BATERÍA POR VUESTROS ESFUERZOS.")
  )

("oracle-left-eye-3"
  (0 "ORÁCULO" "A CAMBIO DE VUESTRO DENUEDO, HE AQUÍ UNA BATERÍA.")
  )

("oracle-right-eye-3"
  (0 "ORÁCULO" "HABÉIS CONSEGUIDO OTRA BATERÍA.")
  )

;; -----------------
;; beach
;; -----------------

("BIR-AM01" :hint #x0
  (0 "MUJER PÁJARO" "¿ESTÁIS YA CERCA DEL HUEVO?")
  )

("BIR-AM02" :hint #x0
  (0 "MUJER PÁJARO" "¡ESO ES, UN POCO MÁS!")
  )

("BIR-AM03" :hint #x0
  (0 "MUJER PÁJARO" "ESTUPENDO. AHORA EMPUJADLO SUAVEMENTE")
  )

("BIR-AM04" :hint #x0
  (0 "MUJER PÁJARO" "¡DIOS MÍO! ¡HE DICHO SUAVEMENTE!")
  )

("BIR-AM05" :hint #x0
  (0 "MUJER PÁJARO" "¡VAMOS, EMPUJAD EL HUEVO POR EL BARRANCO!")
  )

("BIR-AM06" :hint #x0
  (0 "MUJER PÁJARO" "OOOOHH!")
  )

("BIR-AM07" :hint #x0
  (0 "MUJER PÁJARO" "¡AQUÍ, PAJARITO! ¡AQUÍ, PAJARITO! ¡PÍO, PÍO!")
  )

("BIR-AM08" :hint #x0
  (0 "MUJER PÁJARO" "AQUÍ, PAJARITO.")
  )

("BIR-AM09" :hint #x0
  (0 "MUJER PÁJARO" "¡CUIDADO! ¡AHÍ ARRIBA PARECE PELIGROSO!")
  )

("BIR-AM10" :hint #x0
  (0 "MUJER PÁJARO" "¡CUIDADO! ¡POCO A POCO!" )
  )

("BIR-AM11" :hint #x0
  (0 "MUJER PÁJARO" "¡BUEN TRABAJO! AHORA VENID AQUÍ, AL LADO DEL HUEVO.")
  )

("BIR-AM12" :hint #x0
  (0 "MUJER PÁJARO" "DEBES DE SER TODO UN AMANTE DE LOS ANIMALES.")
  )

("BIR-AM13" :hint #x0
  (0 "MUJER PÁJARO" "¿HAY MÁS PÁJAROS POR AHÍ ARRIBA?")
  )

("BIR-LO01" :hint #x0
  (0 "MUJER PÁJARO" "(SILBIDO)")
  )

("BIR-LO02" :hint #x0
  (0 "MUJER PÁJARO" "¡OH, MIRA!, ESE ES PRECIOSO.")
  )

("BIR-LO03" :hint #x0
  (0 "MUJER PÁJARO" "¡OH, MIRA! UN MUCKY-MUCK.")
  )

("CHI-AM01" :hint #x0
  (0 "MAYOR" "OH...¡ESTO ES UNA CATÁSTROFE! ¡UN ABSOLUTO DESASTRE!")
  )

("CHI-AM02" :hint #x0
  (0 "MAYOR" "QUIEREN QUE VAYA A LA SELVA...¡¡YO!!")
  (214)
  (219 "MAYOR" "¡ANTES DESPLUMARÍA A UN FLUT FLUT RABIOSO!")
  )

("CHI-AM03" :hint #x0
  (0 "ALCALDE" "¡...PRIMERO UN MONSTRUO ATACA EL BARCO DEL PESCADOR!")
  (352)
  (395 "ALCALDE" "...Y...Y...Y...AHORA....¡AHORA ESTO! ¡¿QUÉ MÁS PUEDE IR MAL?!")
  )

("CHI-AM04" :hint #x0
  (0 "ALCALDE" "OHHH...TAL VEZ...DEBA...EHHH...TAL VEZ DEBERÍA SUBIR LOS IMPUESTOS...PARA EHHH...¡COSTEAR ESTE DESASTRE!")
  )

("CHI-AM05" :hint #x0
  (0 "ALCALDE" "PROBLEMAS, ¡TODO SON...PROBLEMAS! ¡OOHHH...PROBLEMAS!")
  )

("CHI-AM06" :hint #x0
  (0 "ALCALDE" "(LLANTO) ¡AHORA VA A SER IMPOSIBLE QUE ME REELIJAN!")
  )

("CHI-AM07" :hint #x0
  (0 "ALCALDE" "(LLANTO) ¿QUÉ HA PASADO CON EL RAYO ENERGÉTICO DE LA ALDEA?")
  )

("CHI-AM08" :hint #x0
  (0 "ALCALDE" "(LLANTO) OHH...¿¿POR QUÉ?? OOOAAHHH ¿¿¿POR QUÉ???(LLANTO)")
  )

("CHI-LO01" :hint #x0
  (0 "ALCALDE" "(LLANTO)...MOLINO, MONSTRUOS, ELECTRICIDAD, REELECCIÓN...")
  )

("CHI-LO02" :hint #x0
  (0 "ALCALDE" "(LLANTO)...CUESTAS, MONSTRUOS, REELECCIÓN...")
  )

("SCU-AM01" :hint #x0
  (0 "ESCULTOR" "OH...YA NO ME SALE NADA.")
  )

("SCU-AM02" :hint #x0
  (0 "ESCULTOR" "OH...OJALÁ ESTUVIESE INSPIRADO.")
  )

("SCU-AM03" :hint #x0
  (0 "ESCULTOR" "ESTOY TAN INSPIRADO COMO...ESTA PIEDRA.")
  )

("SCU-AM04" :hint #x0
  (0 "ESCULTOR" "OH...¿DÓNDE ESTARÁ MI MUSA?")
  )

("SCU-AM05" :hint #x0
  (0 "ESCULTOR" "¡ASÍ NO PUEDO TRABAJAR!")
  )

("SCU-AM06" :hint #x0
  (0 "ESCULTOR" "OH DIOS MÍO...¿CUÁNDO VOLVERÁ CONMIGO?")
  )

("SCU-LO01" :hint #x0
  (0 "ESCULTOR" "OH...NO...")
  )

("bird-lady-beach-resolution"
  (30 "MUJER PÁJARO" "¡OH, CIELOS! ESPERO QUE EL POBRECITO ESTÉ BIEN. TOMAD UNA BATERÍA POR VUESTRO VALOR.")
  (243)
  (306 "FLUT FLUT" "¡MAMA!")
  (354)
  (406 "FLUT FLUT" "¡MAMA!")
  (430 "DAXTER" "¡OH, NO! ¡¡NO, NO, NO, NO, NOOO!!")
  (533)
  (535 "MUJER PÁJARO" "MIRAD, ¿A QUE ES MONO? CREO QUE PIENSA QUE ERES SU MAMÁ.")
  (696)
  (699 "DAXTER" "¿¿MAMÁ?? ¡NO SOY TU MADRE! ¿VES PLUMAS POR ALGÚN LADO? ¿MMM?")
  (803)
  (807 "MUJER PÁJARO" "OH, ¡AMOR A PRIMERA VISTA! BUENO...")
  (936)
  (939 "MUJER PÁJARO" "ESCUCHAD, CHICOS, ME LLEVARÉ AL PUEBLO AL POLLUELO")
  (1054 "MUJER PÁJARO" "Y TRATARÉ DE QUE EL SABIO SE OCUPE DE ÉL.")
  )

("bird-lady-introduction"
  (125 "MUJER PÁJARO" "¡CIELO SANTO! ¡QUÉ PAJARITO MÁS ENFERMO!")
  (245)
  (251 "DAXTER" "USTED TAMPOCO TIENE MUY BUENA PINTA, SEÑORA.")
  (326)
  (331 "MUJER PÁJARO" "OH, LO SIENTO. PENSÉ QUE ERAS UN RAIN FRAY DE VIENTRE NARANJA.")
  (454)
  (457 "MUJER PÁJARO" "¿SABES? AYER VI COMO UNAS MALVADAS CRIATURAS")
  (578 "MUJER PÁJARO" "CAPTURABAN A UNA MADRE FLUT FLUT CERCA DE LA PLAYA.")
  (648)
  (654 :offscreen "MUJER PÁJARO" "Y EN SU NIDO, EN LO ALTO DEL BARRANCO, SE HA QUEDADO UN POBRE HUEVO HUÉRFANO")
  (796 :offscreen "MUJER PÁJARO" " AL QUE NO PUEDO LLEGAR. ¿PODRÍAIS SUBIR Y EMPUJARLO PARA QUE CAIGA")
  (951 :offscreen "MUJER PÁJARO" "EN EL MONTÓN DE HENO QUE HE PUESTO DEBAJO?")
  (1041)
  (1044 "MUJER PÁJARO" "SI ME HACÉIS ESTE FAVOR, OS RECOMPENSARÉ CON UNA BATERÍA.")
  (1198)
  )

("bird-lady-reminder-1"
  (56 "MUJER PÁJARO" "OH, ¡HOLA DE NUEVO! ¿HABÉIS ENCONTRADO EL HUEVO AZUL QUE HAY EN EL BARRANCO?")
  (208)
  (211 "MUJER PÁJARO" "¡EMPUJADLO POR EL BORDE Y OS DARÉ UNA BATERÍA!")
  (348)
  )

("bird-lady-reminder-2"
  (58 "MUJER PÁJARO" "¿TODAVÍA REVOLOTEANDO POR AQUÍ? JAJAJAJA")
  (170)
  (174 "MUJER PÁJARO" "¡SEGURO QUE ESE POBRE HUEVO DEL BARRANCO ESTÁ PASANDO UN FRÍO TERRIBLE!")
  (313)
  (316 "MUJER PÁJARO" "¡ID A SALVARLO! EMPUJÁNDOLO POR EL BORDE...Y OS DARÉ UNA BATERÍA.")
  )

("mayor-introduction"
  (31 "ALCALDE" "¡¡NO!! (MURMURA) ¡NO ME DIGAS QUE VOSOTROS DOS TAMBIÉN TENÉIS PROBLEMAS!")
  (171)
  (174 "ALCALDE" "PRIMERO LAS APARICIONES DE MONSTRUOS CERCA DE LA ALDEA, ¡Y AHORA ESTO!")
  (313)
  (320 "ALCALDE" "¿VEIS ESOS ENGRANAJES AHÍ ARRIBA, CHICOS? ¿LOS VEIS? ¿VEIS LO PARADOS QUE ESTÁN?")
  (479 "ALCALDE" "ESO SIGNIFICA QUE NUESTRA ALDEA NO TIENE ELECTRICIDAD!")
  (569)
  (578 "ALCALDE" "¡EL RAYO ECO QUE PROVIENE DEL TEMPLO DE LA SELVA SE HA INTERRUMPIDO!")
  (685)
  (689 "ALCALDE" "Y LA VERDAD, A TODO EL MUNDO LE DA MIEDO. ID A VER QUÉ ES LO QUE HA PASADO.")
  (850)
  (864 "DAXTER" "¿HAS PAGADO LA FACTURA?")
  (915)
  (917 "ALCALDE" "¡AJÁ! JOOOJOOJAJAAAA, QUÉ GRACIOSO...")
  (1071)
  (1074 "ALCALDE" "MIRAD, SI ARREGLÁIS EL RAYO ECO, OS DARÉ...UNA BATERÍA.")
  (1262 "ALCALDE" "¡AH, AHH, AHH, OTRA COSA!")
  (1346 "ALCALDE" "SI POR CASUALIDAD OS INTERESA HACER UNA CONTRIBUCIÓN A MI CAMPAÑA DE REELECCIÓN,")
  (1551 "ALCALDE" "TAL VEZ CONSIDERE EL DAROS OTRA BATERÍA.")
  (1668)
  (1671 "ALCALDE" "LA CONTRIBUCIÓN MÍNIMA ES DE UNAS...MODESTAS...")
  (1797 "ALCALDE" "90 ESFERAS.")
  )

("mayor-reminder-beams"
  (25 "ALCALDE" "¿YA HABÉIS VUELTO? ¡¿Y SIN ARREGLAR EL RAYO ECO?!")
  (157 "ALCALDE" "(LLANTO) ¡VUESTRA ALDEA OS NECESITA, CHICOS!")
  )

("mayor-reminder-donation"
  (26 "ALCALDE"  "¿HABÉIS VENIDO A HACER UNA DONACIÓN A MI CAMPAÑA...?")
  (159 "ALCALDE" "CON 90 ESFERAS DE LOS PRECURSORES OS LLEVÁIS UNA BATERÍA, CHICOS.")
  )

("mayor-resolution-beams"
  (28 "ALCALDE" "JAAAAJAJAJAJA, ¡QUÉ VISTA TAN MARAVILLOSA! OS LO AGRADEZCO,")
  (205 "ALCALDE" "Y TODA LA ALDEA ME LO AGRADECERÁ A MÍ.")
  (269 "ALCALDE" "¡EH, CHICOS! ¡HABÉIS DEVUELTO LA ELECTRICIDAD A LA ALDEA Y GARANTIZADO MI REELECCIÓN!")
  (472)
  (475 "ALCALDE" "Y POR ELLO, AMIGOS MÍOS, OS DOY...¡UNA BATERÍA!")
  )

("mayor-resolution-donation"
  (28 "MAYOR" "ASÍ QUE...QUERÉIS REALIZAR UNA CONTRIBUCIÓN, ¡BIEN! SERÁ DE BUEN TAMAÑO, ESPERO.")
  (219)
  (224 "MAYOR" "¡GUAAAAAAU, SIII...! AAMM...ES UNA CONTRIBUCIÓN HERMOSA.")
  (365 "MAYOR" "BUENO, EMMM...ESPERO QUE ESTA BATERÍA SEA UNA BUENA MUESTRA DE MI GRATITUD.")
  )

("sagevb01" :hint #x288
  (0 "SAMOS" "WELL, I SEE THAT YOU TWO HAVE FINALLY DECIDED TO UNBLOCK MY COLLECTORS.")
  (347)
  (352 "SAMOS" "I WOULD OFFER MY CONGRATULATIONS, BUT YOU HAVE SO MUCH TO DO I WON'T WASTE YOUR TIME.")
  (705)
  (712 "SAMOS" "BY THE WAY, IF THINGS DON'T WORK OUT,")
  (884 "SAMOS" "DAXTER COULD ALWAYS GET A JOB CONTROLLING THE VILLAGE RAT PROBLEM.")
  (1116 "SAMOS" "NYEH HA HA HA HA.")
  )

("sculptor-introduction"
  (30 "SCULPTOR" "HEY... LITTLE FURRY DUDE!")
  (154)
  (161 "SCULPTOR" "AWW... I THOUGHT FOR A MOMENT YOU WERE MY MUSE.")
  (282)
  (285 "DAXTER" "YOUR WHAT?")
  (334)
  (343 "SCULPTOR" "HAVEN'T YOU EVER SEEN A MUSE BEFORE?")
  (430)
  (434 "SCULPTOR" "IT'S A LITTLE GLOWIN' SQUIRREL ABOUT YOUR SIZE, FULL OF SPUNK, AND CRAZY AS A LARK!")
  (622)
  (632 "DAXTER" "OH, I GET IT! LIKE A SIDEKICK.")
  (757)
  (763 "SCULPTOR" "AS A MATTER OF FACT, WITHOUT MY MUSE, I JUST CAN'T SCULPT.")
  (920)
  (923 "SCULPTOR" "BUT WITH HER AROUND... I SEE BEAUTY IN EVERYTHING, YOU KNOW?")
  (1087)
  (1091 "SCULPTOR" "RIGHT NOW I COULDN'T CHISEL MY WAY OUT OF A BOX.")
  (1182)
  (1191 :offscreen "SCULPTOR" "I THINK SHE RAN AWAY TO THAT MISTY ISLAND.")
  (1278)
  (1281 "SCULPTOR" "AWW, I JUST HOPE SHE'S ALL RIGHT.")
  (1370)
  (1376 "SCULPTOR" "IT'S WORTH A POWER CELL IF YOU BRING HER BACK TO ME!")
  (1441)
  (1467 "DAXTER" "WAIT A MINUTE! WE ARE NOT GOING BACK TO MISTY ISLAND!")
  (1646)
  (1649 "DAXTER" "ARE WE?")
  )

("sculptor-reminder-1"
  (27 "SCULPTOR" "AW HEY DUDES! DID YOU FIND MY MUSE YET?")
  (169)
  )

("sculptor-resolution"
  (87 "SCULPTOR" "OH, MY MUSE! YOU SAVED HER! AW, YOU REALLY ARE THE BEST!")
  (230 "SCULPTOR" "HERE, TAKE THIS POWER CELL. I WON'T NEED IT NOW THAT I HAVE MY INSPIRATION BACK!")
  )

("sksp0019" :hint #x236
  (0 "DAXTER" "¡EH, GAVIOTAS! VAMOS A ESPANTARLAS PARA DIVERTIRNOS.")
  )

("sksp0020" :hint #x268
  (0 "DAXTER" "¡YUUJUJUUUUY! ¡VENGA, OTRA VEZ!")
  )

("sksp0022" :hint #x26a
  (0 "DAXTER" "¡YUUUUUJUUUU JAJAJAJAAA YUUJUJUJUYY!")
  )

("sksp0023" :hint #x26b
  (0 "DAXTER" "¡WUUUUU!")
  )

("sksp0024" :hint #x26c
  (0 "DAXTER" "¡YAAAAHJAAAJAJAA, ¡¡SÍ!!")
  )

("sksp0025" :hint #x273
  (0 "DAXTER" "¡GUAU! ¡HAN CAUSADO UNA AVALANCHA! ¡VAMOS A VERLA!")
  )

("sksp0026" :hint #x237
  (0 "DAXTER" "¡EH, ESE PELÍCANO NOS HA BIRLADO UNA BATERÍA!")
  (197)
  (200 "DAXTER" "VAMOS A DARLE SU MERECIDO.")
  )

("sksp0027" :hint #x274
  (0 "DAXTER" "¡DEPRISA! ¡TENEMOS QUE LLEGAR A LA BATERÍA ANTES DE QUE EL PELÍCANO SE LA LLEVE DE NUEVO!")
  )

("sksp0029" :hint #x275
  (0 "DAXTER" "EMMM, DEBERÍAMOS HABLAR CON LA ORNITÓLOGA")
  (125 "DAXTER" "Y VER SI EL HUEVO DE FLUT FLUT HA ACABADO REVUELTO.")
  )

("sksp0030" :hint #x239
  (0 "DAXTER" "¡EH, PRUEBA A GOLPEAR LAS PIEDRAS PARA VER SI LAS QUITAS DE EN MEDIO!")
  )

("sksp0034" :hint #x23b
  (0 "DAXTER" "¡AUUUUUUU, AH AH AH AAAAAAAH! ¡BUCEA Y COGE LOS HUEVOS, JAK, BUCEA!")
  )

("sksp0443" :hint #x2af
  (0 "DAXTER" "¡GOLPEA ESAS PÉRTIGAS DESDE ABAJO!")
  )

;; -----------------
;; jungle
;; -----------------

("FIS-AM01" :hint #x0
  (0 "FISHERMAN" "GRR, THESE DARN FISH... I NEVER CATCH ME A SINGLE ONE.")
  )

("FIS-AM02" :hint #x0
  (0 "FISHERMAN" "THEM MONSTERS THAT DONE BIT ME SHIP WILL DRIVE ME BROKE.")
  )

("FIS-AM03" :hint #x0
  (0 "FISHERMAN" "DRAT, THESE BLIGHTERS!")
  (135 "FISHERMAN" "IN ME BASKET, DARN FISHIES, COME ON YEAH...")
  (419)
  (425 "FISHERMAN" "HEH HE HE HE HE...")
  )

("FIS-AM04" :hint #x0
  (0 "FISHERMAN" "OH I LOVE THE SMELL OF FISH IN THE MORNIN'.")
  )

("FIS-AM05" :hint #x0
  (0 "FISHERMAN" "OOH I COULD USE ME A SALTED FISH LIPS ON RYE.")
  )

("FIS-AM06" :hint #x0
  (0 "FISHERMAN" "I 'MEMBER THE BIG ONE THAT GOT AWAY...")
  )

("FIS-LO01" :hint #x0
  (0 "FISHERMAN" "GRR!")
  )

("FIS-LO03" :hint #x0
  (0 "FISHERMAN" "HA HA HA HA HA HAH!")
  )

("FIS-LO04" :hint #x0
  (0 "FISHERMAN" "DARN FISH... THEY NEVER GET IN ME NET!")
  )

("FIS-LO05" :hint #x0
  (0 "FISHERMAN" "HA HA HA AH HA HA HA HAH!")
  )

("FIS-TA01" :hint #x0
  (0 "FISHERMAN" "TO THE LEFT!")
  )

("FIS-TA02" :hint #x0
  (0 "FISHERMAN" "RIGHT WITH YA!")
  )

("FIS-TA03" :hint #x0
  (0 "FISHERMAN" "HERE COMES A BIG ONE!")
  )

("FIS-TA04" :hint #x0
  (0 "FISHERMAN" "YE MISSED A JUMBO, LADDIE!")
  )

("FIS-TA05" :hint #x0
  (0 "FISHERMAN" "DON'T MISS ONE LIKE THAT AGAIN!")
  )

("FIS-TA06" :hint #x0
  (0 "FISHERMAN" "STEADY BOY.")
  )

("FIS-TA07" :hint #x0
  (0 "FISHERMAN" "YOUR SAILS ARE SAGGING IN THE WIND, BOY.")
  )

("FIS-TA08" :hint #x0
  (0 "FISHERMAN" "MISSED.")
  )

("FIS-TA09" :hint #x0
  (0 "FISHERMAN" "LOOKS LIKE YOU COULD USE A BIGGER NET...")
  )

("FIS-TA10" :hint #x0
  (0 "FISHERMAN" "MISSED AGAIN!")
  )

("FIS-TA11" :hint #x0
  (0 "FISHERMAN" "HOLD STEADY! YOU'RE ALMOST THERE...")
  )

("FIS-TA1A" :hint #x0
  (0 "FISHERMAN" "LEFT!")
  )

("FIS-TA2A" :hint #x0
  (0 "FISHERMAN" "RIGHT!")
  )

("asstvb02" :hint #x289
  (0 "KEIRA" "¡GUAU!, ¿HABÉIS VISTO ESO? ¡LOS RESPIRADEROS DE ECO AZUL DEBEN DE HABERSE ACTIVADO EN TODO EL MUNDO!")
  (305)
  (315 "KEIRA" "SABÍA QUE HABÍA ALGUNA MANERA DE HACERLO.")
  (435)
  (442 "KEIRA" "DEBE DE HABER OTROS SITIOS EN LOS QUE ACTIVAR LOS DEMÁS RESPIRADEROS DE ECO.")
  )

("fisher-accept"
  (0 :offscreen "FISHERMAN" "THERE ARE TWO TYPES OF GOOD FISH TO CATCH: ONE-POUND FISHIES, AND FIVE-POUND FISHIES.")
  (220 :offscreen "FISHERMAN" "HEH. IF YOU MISS 20 POUNDS OF GOOD FISH, THEN I'M GONNA TAKE ME NET BACK FROM YA!")
  (432)
  (438 :offscreen "FISHERMAN" "THERE ARE POISONOUS EELS IN THIS RIVER.")
  (542)
  (545 :offscreen "FISHERMAN" "CATCH EVEN ONE OF THEM BOOGERS, AND YOU'LL POISON THE WHOLE DARN CATCH!")
  )

("fisher-introduction"
  (0 "DAXTER" "WHAT DO YOU HAVE IN THE BASKET?")
  (50 "FISHERMAN" "NOTHING TO TALK ABOUT.")
  (103)
  (106 "FISHERMAN" "THEM MONSTERS PATROLIN' THE OCEAN TOOK A BITE OUT OF ME FISHIN' RIG.")
  (226)
  (229 "FISHERMAN" "AND NOW THEY'RE GOBLIN' UP ME CATCH!")
  (290)
  (293 "FISHERMAN" "NO MATTER WHAT I TRY, I CAN'T SEEM TO CATCH A SINGLE FISH IN THIS RIVER.")
  (419)
  (425 "DAXTER" "WHOO! MAYBE... IT'S YOUR BREATH.")
  (515)
  (521 "FISHERMAN" "YOU THINK YOU CAN DO BETTER? TRY SCOOPIN' UP RIVER FISH WITH A TINY NET!")
  (665)
  (671 "FISHERMAN" "I'LL GIVE YOU A POWER CELL IF YOU CAN CATCH 200 POUNDS OF THEM CRITTERS!")
  (808)
  (814 "FISHERMAN" "AND I'LL LET YOU AND SHRIMP HERE USE MY SPEEDBOAT TO GET TO MISTY ISLAND.")
  (955)
  (961 "FISHERMAN" "YOU'S WANT TO TRY THE CHALLENGE?")
  )

("fisher-reject"
  (2 "FISHERMAN" "WELL, IF YOU WANT TO TRY FOR THE POWER CELL SOMETIME, YOU KNOW WHERE TO FIND ME.")
  )

("fisher-reminder-1"
  (6 "FISHERMAN" "WANT TO TRY AND BEAT THE RIVER, DO YA?")
  )

("fisher-resolution"
  (0 "FISHERMAN" "YOU DID IT! YOU CAUGHT 200 POUNDS OF FISH!")
  (115)
  (120 "FISHERMAN" "NOT BAD FOR A COUPLE OF LAND LUBBERS!")
  (185)
  (199 "FISHERMAN" "HERE'S THE POWER CELL I PROMISED, AND YOU CAN USE MY BOAT IN THE VILLAGE DOCK")
  (351 "FISHERMAN" "WHENEVER YOU LIKE!")
  )

("sksp0011" :hint #x240
  (0 "DAXTER" "DEBERÍAMOS PEDIRLE PRESTADA SU LANCHA AL PESCADOR DEL RÍO DE LA SELVA")
  (136 "DAXTER" "PARA IR A TODA PRISA A LA ISLA DE MISTY!")
  )

("sksp0018" :hint #x25e
  (0 "DAXTER" "¡DEBERÍAMOS DECIRLE AL CHARLATÁN DEL ALCALDE QUE NOS DEBE UNA")
  (223 "DAXTER" "POR CONECTARLE EL RAYO ENERGÉTICO DE LA ALDEA!")
  )

("sksp0037" :hint #x25f
  (0 "DAXTER" "ESA ESPECIE DE TORRES QUE HAY POR TODA LA SELVA DEBEN DE...REDIRIGIR EL RAYO ECO.")
  (214)
  (220 "DAXTER" "¡VAMOS A TRASTEAR CON ELLAS!")
  )

("sksp0038" :hint #x23c
  (0 "DAXTER" "MMMM, SI EL ECO AZUL PUEDE CONSTRUIR UN PUENTE, ¡SEGURO QUE TAMBIÉN ABRE PUERTAS!")
  (275)
  (281 "DAXTER" "¡VOLVAMOS PARA QUE PUEDAS REPOSTAR!")
  )

("sksp0039" :hint #x25b
  (0 "DAXTER" "¡EH!, HAY SEÑALES CON RELÁMPAGOS EN ESTOS POSTES.")
  (202 "DAXTER" "Y DE ESE RESPIRADERO SALE UN RELAMPAGUEO.")
  (391)
  (400 "DAXTER" "¿PIENSAS LO MISMO QUE YO?")
  )

("sksp0040" :hint #x23d
  (0 "DAXTER" "¡SUBÁMONOS A ESA MÁQUINA PARA ROMPER EL ESPEJO QUE DESVÍA EL RAYO DE PRECURSOR!")
  )

("sksp0041" :hint #x23e
  (0 "DAXTER" "¡TENEMOS QUE SUBIR A LA CIMA DE ESA TORRE!")
  )

("sksp0049" :hint #x29c
  (0 "DAXTER" "¡ALINEA EL RAYO APUNTÁNDOLE A LA TORRE SIGUIENTE!")
  )

("sksp0050" :hint #x29d
  (0 "DAXTER" "¡ROMPE EL ESPEJO, JAK!")
  )

("sksp0051" :hint #x29e
  (0 "DAXTER" "¡ATRAPA A LOS BICHOS, JAK! ¡ATRÁPALOS!")
  )

("sksp0052" :hint #x29f
  (0 "DAXTER" "¡VAYAMOS A LA SIGUIENTE TORRE A RECONECTAR EL RAYO!")
  )

("sksp0053" :hint #x2a0
  (0 "DAXTER" "¡EH! PARA ENCONTRAR LA SIGUIENTE TORRE PODEMOS SEGUIR EL RAYO.")
  )

("sksp0054" :hint #x2a1
  (0 "DAXTER" "TENEMOS QUE RECARGARTE DE COSA AZUL PARA QUE PUEDAS ABRIR ESTO.")
  )

("sksp0b42" :hint #x278
  (0 "DAXTER" "QUE NO SE TE ESCAPEN MÁS PECES AMARILLOS. ¡CADA UNO DE ELLOS PESA 5 KILOS! Y ESO ES UN MONTÓN, JAK.")
  )

;; -----------------
;; misty
;; -----------------

("asstvb03" :hint #x28b
  (0 "KEIRA" "GOOD! YOU STOPPED ALL THE MINE-DROPPING LURKERS!")
  (190 "KEIRA" "THEY'VE BEEN THREATENING THE WATERS AROUND OUR VILLAGE FOR WEEKS.")
  (391 "KEIRA" "BRING YOUR ZOOMER BACK TO THE TRANS-PAD AND I'LL TELEPORT IT BACK.")
  )

("sagevb02" :hint #x28a
  (6 "SAGE" "I HAVE TO ADMIT, I'M IMPRESSED. YOU TWO DIDN'T SCREW UP!")
  (385)
  (400 "SAGE" "NOW THAT THE LURKERS CAN'T OPEN THAT SILO, THEY CAN'T FLOOD THE WORLD WITH DARK ECO")
  (710 "SAGE" "AND CAUSE UNTOLD DESTRUCTION.")
  (863)
  (880 "SAGE" "WIPE THAT RIDICULOUS GRIN OFF YOUR FACE, DAXTER! THE TWO OF YOU HAVE PLENTY TO DO.")
  (1191 "SAGE" "GET ON WITH IT!")
  )

("sksp0031" :hint #x23a
  (0 "DAXTER" "¡OOH, VAMOS A USAR EL CAÑÓN PARA VOLAR COSAS POR LOS AIRES!")
  )

("sksp0056" :hint #x27b
  (0 "DAXTER" "¡EEH, VEO A LA MUSA DEL ESCULTOR!")
  )

("sksp0059" :hint #x26e
  (0 "DAXTER" "¡ESTE SITIO ME DA ESCALOFRÍOS! ¡NO TE ACERQUES A ESO QUE REZUMA! ¿VALE?")
  )

("sksp0060" :hint #x26f
  (0 "DAXTER" "¡UUUUY! ¡ESTE SITIO ME DA ESCALOFRÍOS! Y CRÉEME, ES TODA UNA EXPERIENCIA")
  (337 "DAXTER" "CUANDO ESTÁS RECUBIERTO DE PELO.")
  )

("sksp0062" :hint #x27e
  (0 "DAXTER" "¡VAMOS A ACABAR CON ESOS LURKERS GLOBO! ¡NO DEJEMOS NI UNO!")
  )

("sksp0063" :hint #x27f
  (0 "DAXTER" "HE DICHO QUE ATAQUEMOS A LOS LURKERS, JAK. ¡NO LAS MINAS!")
  (332)
  (344 "DAXTER" "REGLA NÚMERO UNO: ¡EVITA SIEMPRE LAS MINAS!")
  )

("sksp0064" :hint #x245
  (0 "DAXTER" "¡VIGILA TU ESPALDA! QUE NO SE NOS OLVIDE LO QUE PASÓ AQUÍ LA ÚLTIMA VEZ.")
  )

("sksp0067" :hint #x249
  (0 "DAXTER" "¡NO TE CAIGAS EN LA NEBLINA QUE HAY DEBAJO! NO CREO QUE PODAMOS SALIR DE ELLA.")
  )

("sksp0069" :hint #x2a3
  (0 "DAXTER" "ES UNA EMBOSCADA, JAK ¡ES UNA EMBOSCADA!")
  )

("sksp0070" :hint #x2a4
  (0 "DAXTER" "SALTA, Y LUEGO CAE EN PICADO SOBRE EL BALANCÍN.")
  )

("sksp0435" :hint #x2aa
  (0 "DAXTER" "DERRIBA ESOS HUESOS.")
  )

;; -----------------
;; firecanyon
;; -----------------

("assistant-firecanyon-resolution"
  (25 "KEIRA" "GREAT! YOU HAVE THE 20 CELLS NEEDED TO POWER MY HEAT SHIELD!")
  (140)
  (143 "KEIRA" "NOW BE CAREFUL, THE SHIELD WILL ONLY PROTECT YOUR ZOOMER TILL IT REACHES 500 DEGREES,")
  (295 "KEIRA" "SO TRY TO KEEP HER COOL.")
  (343)
  (346 :offscreen "KEIRA" "FLYING OVER OPEN LAVA WILL DEFINITELY HEAT YOU UP FAST.")
  (458)
  (462 "KEIRA" "HIT 500 DEGREES, AND IT'S OVER.")
  (546)
  (552 "DAXTER" "OVER?! LIKE BURNING MOLTEN METAL OVER?!")
  (636)
  (639 "KEIRA" "THE FIRE CANYON GETS PRETTY HOT, SO KEEP A LOOK OUT FOR JUMPS")
  (745 "KEIRA" "TO KEEP YOU OFF THE HOT GROUND.")
  (792)
  (795 :offscreen "KEIRA" "I'VE ALSO RELEASED SEVERAL BLUE COOLING BALLOONS YOU CAN USE TO DROP")
  (895 :offscreen "KEIRA" "THE SHIELD'S TEMPERATURE QUICKLY.")
  (956)
  (962 "KEIRA" "OH! AND WHEN YOU GET ACROSS, DON'T FORGET TO ACTIVATE")
  (1063 "KEIRA" "THE TELEPORT GATE IN THE BLUE SAGE'S LAB.")
  (1140)
  (1146 "KEIRA" "THEN WE'LL BE ABLE TO TELEPORT OVER AND MEET YOU!")
  (1222)
  (1228 "KEIRA" "GOOD LUCK!")
  )

("asstvb09" :hint #x24f
  (0 "KEIRA" "YOU DON'T HAVE ENOUGH POWER CELLS TO FUEL MY HEAT SHIELD.")
  (216)
  (234 "KEIRA" "YOU CAN'T CROSS FIRE CANYON UNTIL YOU COLLECT ENOUGH POWER CELLS.")
  )

("sksp0076" :hint #x501
  (0 "DAXTER" "¡JAK, SALTA PARA MANTENERNOS LEJOS DE LA LAVA!")
  )

("sksp0077" :hint #x502
  (0 "DAXTER" "LOS GLOBOS SON BUENOS, ¡LA LAVA ARDIENTE ES MALA!")
  )

("sksp0078" :hint #x503
  (0 "DAXTER" "SÚBETE AL CHISME PRECURSOR PARA QUE SIGAMOS FRESQUITOS.")
  )

("sksp0079" :hint #x504
  (0 "DAXTER" "¡AAAAYYY, ME VOY A MORIIIIIR! ¡SOY UN BICHEJO FIAMBREE!")
  (257)
  (270 "DAXTER" "¡TIENES QUE LLEGAR AL OTRO LADO ANTES DE QUE ESTE CHISME SE CALIENTE DEMASIADO!")
  )

("sksp0080" :hint #x505
  (0 "DAXTER" "¡TIRA BRINCANDO, PARA DAR CURVAS MÁS CERRADAS!")
  )

("sksp0081" :hint #x506
  (0 "DAXTER" "¡AAAAAAYY! ¡DEBERÍA CONDUCIR YO!")
  )

("sksp0082" :hint #x507
  (0 "DAXTER" "¿TÁS INTENTANDO ESQUIVAR LAS CAJAS DE ECO OSCURO, VERDAD?")
  )

("sksp0083" :hint #x508
  (0 "DAXTER" "¡OOH, A VER SI PODEMOS PONER DISTANCIA ENTRE ESOS LURKERS Y NOSOTROS!")
  )

("sksp0084" :hint #x509
  (0 "DAXTER" "¡MUY CERCA! ¡MUUUUUUUY CERCA!")
  )

("sksp0085" :hint #x50a
  (0 "DAXTER" "¡GUAU! ¡ESTE CHISME SE ESTÁ CALENTANDO DEMASIADO!")
  )

("sksp0086" :hint #x50b
  (0 "DAXTER" "¡UNOS SEGUNDOS MÁS Y ESTAREMOS MÁS FRITOS QUE UN HUEVO DE FLUT FLUT!")
  )

("sksp0087" :hint #x50d
  (0 "DAXTER" "¡CHOCA CONTRA LOS GLOBOS, PARA REFRIGERARNOS!")
  )

("sksp0088" :hint #x50e
  (0 "DAXTER" "¡AHÍ VIENE OTRO GLOBO!")
  )

("sksp0089" :hint #x50f
  (0 "DAXTER" "¡OJALÁ NO HUBIESE SONADO EL DESPERTADOR ESTA MAÑANA!")
  )

("sksp0090" :hint #x510
  (0 "DAXTER" "¡SE TE HA ESCAPADO UN GLOBO! ¡LOS NECESITAMOS PARA NO ACABAR ESTOFADOS!")
  )

("sksp0091" :hint #x511
  (0 "DAXTER" "¡ESTE BÓLIDO SE ESTÁ CALENTANDO DEMASIADO!")
  )

("sksp0092" :hint #x512
  (0 "DAXTER" "¿NO HUELES A QUEMADO?")
  )

("sksp0093" :hint #x513
  (0 "DAXTER" "¡CREO QUE TENGO LA COLA ARDIENDOO!")
  )

("sksp0094" :hint #x514
  (0 "DAXTER" "¡ESTO VA A ESTALLAR!")
  )

("sksp0095" :hint #x515
  (0 "DAXTER" "¡YUUUJUUUUU! ¡LO CONSEGUIMOS!")
  )

("sksp0096" :hint #x516
  (0 "DAXTER" "¡AQUÍ TAMBIÉN HAY MOSCAS EXPLORADORAS!")
  )

;; -----------------
;; swamp
;; -----------------

("billy-accept"
  (5 "BILLY" "GOOD! THOSE RATS WILL BE BACK ANYTIME.")
  (109 "BILLY" "SHOOT ALL THEM RATS, AND KEEP 'EM FROM EATING AT LEAST ONE OF THEM SNACKS.")
  )

("billy-introduction"
  (6 "BILLY" "HOWDY, FRIENDS! ENJOYIN' MY BEAUTIFUL SWAMP? I OWN THESE HERE PARTS. EVERYTHING THAT DOESN'T SINK INTO THE MUD, THAT IS! HA HA HA...")
  (349)
  (369 "DAXTER" "JUDGING BY THE SMELL, I'D WAGER YOUR BATHTUB SANK IN THE MUD LONG AGO.")
  (497)
  (519 "BILLY" "WHAT'S A BATHTUB? ANYWAY I GOT BIGGER PROBLEMS NOW...")
  (677)
  (691 "BILLY" "SEEMS SOME NASTY LURKER VARMINTS ARE GROUSIN' ABOUTS SNATCHIN' EVERYTHING THEY CAN GET THEIR GRUBBY LITTLE PAWS ON.")
  (910 "BILLY" "AND SCARED AWAY MY PET HIPHOG, FARTHY.")
  (1000 "BILLY" "HE'S BEEN MISSIN' FOR NIGH ON TO A COON'S AGE.")
  (1136 :offscreen "BILLY" "I'VE BEEN PUTTIN' OUT HIS FAVORITE SNACK, BUT THOSE ORNERY SWAMP RATS KEEP STEALIN' EM!")
  (1318 :offscreen "BILLY" "IF YOU COULD KEEP THOSE PESKY CRITTERS AWAY LONG ENOUGH, I JUST KNOW FARTHY WOULD SMELL THEM VITTLES AND COME BACK!")
  (1509)
  (1527 "BILLY" "WILL YA HELP ME OUT?")
  )

("billy-reject"
  (7 "BILLY" "WELL, IF YOU CHANGE YOUR MIND, YOU KNOW WHERE TO FIND ME! (LAUGHS)")
  )

("billy-reminder-1"
  (36 "BILLY" "AHH, Y'ALL BACK TO HELP STOP THEM RATS?")
  )

("billy-resolution"
  (1 "BILLY" "WELL FRY MY HIDE! YOU SURE KNOW HOW TO SHOOT! THANKS A HEAP FOR THE HELP.")
  )

;; -----------------
;; citadel
;; -----------------

("BLU-AM01" :hint #x0
  (0 "BLUE SAGE" "A LITTLE BIT OF HELP WOULD BE GOOD!")
  )

("BLU-AM02" :hint #x0
  (0 "BLUE SAGE" "OH, THIS IS A FINE MESS.")
  )

("BLU-AM03" :hint #x0
  (0 "BLUE SAGE" "HMM, QUITE AN ENIGMA WE'RE FACING.")
  )

("RED-AM01" :hint #x0
  (0 "RED SAGE" "IS ANYBODY THERE?")
  )

("RED-AM02" :hint #x0
  (0 "RED SAGE" "WELL...")
  )

("RED-AM03" :hint #x0
  (0 "RED SAGE" "WHAT KEPT YOU?")
  )

("YEL-AM01" :hint #x0
  (0 "RED SAGE" "TIME IS RUNNIN' OUT!")
  )

("YEL-AM02" :hint #x0
  (0 "RED SAGE" "HEY! GET ME OUTTA HERE!")
  )

("YEL-AM03" :hint #x0
  (0 "RED SAGE" "WHEN I GET OUTTA HERE, SOME SHOOTIN'S GONNA START!")
  )

("bluesage-resolution"
  (63 "BLUE SAGE" "GOOD WORK, FELLOWS! OLD SAMOS WAS RIGHT ABOUT YOU!")
  (162)
  (165 "BLUE SAGE" "GREAT PILES OF PRECURSOR METAL!")
  (253 "BLUE SAGE" "THAT INSIDIOUS MECHANICAL CREATION MUST NOT BE ALLOWED TO WREAK ITS TERRIBLE HAVOC!")
  (420 "BLUE SAGE" "I WILL TRY TO ACTUATE THE SHIELD DOOR BY ELLICITING A CONDUIT OF ENERGY")
  (563 "BLUE SAGE" "BETWEEN MYSELF AND THE VAST PORTAL BELOW!")
  (666 "DAXTER" "UH... YEAH. YOU DO THAT. WE'LL UH... JUST GO FIND MORE HELP.")
  (873)
  (891 :offscreen "DAXTER" "WEIRDO!")
  (980)
  )

("green-sagecage-introduction"
  (130 "SAGE" "IT'S ABOUT TIME YOU TWO DECIDED TO SHOW UP!")
  (207 "DAXTER" "NICE TO SEE YOU TOO! DO THEY HAVE YOU MOPPING THE FLOORS NOW?")
  (343 "SAGE" "THERE'S NO TIME FOR JOKES, DAXTER. GOL AND MAIA KIDNAPPED US")
  (477 "SAGE" "TO SAP OUR ENERGIES TO POWER THEIR ABOMINABLE MACHINE.")
  (574)
  (577 :offscreen "SAGE" "IT APPEARS THEY HAVE COMBINED THE FUNCTIONAL REMAINS OF A PRECURSOR ROBOT")
  (710 :offscreen "SAGE" "WITH SCAVENGED ARTIFACTS FROM ACROSS THE LAND.")
  (800)
  (803 :offscreen "SAGE" "THEN THEY ADDED A FEW DIABOLICAL ADDITIONS OF THEIR OWN,")
  (921 :offscreen "SAGE" "CREATING THE ONE THING CAPABLE OF OPENING THE DARK ECO SILOS.")
  (1060 "SAGE" "IF YOU CAN FREE THE FOUR OF US, WE CAN USE OUR COMBINED POWERS")
  (1180 "SAGE" "TO BREAK THE FORCE SHIELD SURROUNDING THE ROBOT, BEFORE THEY USE IT TO DESTROY THE WORLD.")
  )

("green-sagecage-outro-preboss"
  (56 "GOL" "YOU'RE TOO LATE, SAMOS.")
  (125 "GOL" "ONCE I POSSESS LIMITLESS DARK ECO, I WILL HAVE THE KEY TO CREATION ITSELF!")
  (335 "SAGE" "THIS IS MADNESS! RELEASING THAT MUCH DARK ECO WILL DESTROY EVERYTHING WE KNOW!")
  (504 "SAGE" "JUST LOOK WHAT IT'S DONE TO YOU!")
  (578)
  (581 "MAIA" "IT HAS GIVEN US A BEAUTY BEYOND ANYTHING YOU COULD UNDERSTAND.")
  (693)
  (696 "DAXTER" "BEAUTY? HAVE YOU TWO LOOKED IN A MIRROR LATELY?")
  (825)
  (828 "MAIA" "JUST WAIT UNTIL WE OPEN THE SILOS, LITTLE ONE. YOU THINK SHORT AND FUZZY IS BAD?")
  (1030 "GOL" "AND TO THINK, YOU TWO TRAVELLED ALL THIS WAY FOR MY HELP.")
  (1180 "GOL" "FOOLS! ENJOY YOUR FRONT ROW SEATS TO THE RECREATION OF THE WORLD!")
  (1391)
  (1605 "SAGE" "JAK! TAKE THE ELEVATOR UP AND STOP THAT ROBOT!")
  )

("green-sagecage-resolution"
  (35 "SAGE" "GOOD WORK, BOYS! YOU'RE REAL HEROES NOW.")
  (158 "SAGE" "I'LL COMBINE MY GREEN ECO POWER WITH THE OTHER THREE SAGES")
  (280 "SAGE" "AND TOGETHER WE'LL OPEN THE SHIELD DOOR SURROUNDING THE PRECURSOR ROBOT.")
  (405 "DAXTER" "YEAH YEAH THAT SOUNDS LIKE A GOOD START.")
  (457 "DAXTER" "AND THEN AFTER YOU GUYS OPEN THAT SHIELD, WHAT ARE YOU GONNA DO ABOUT THE ROBOT?")
  (576 "SAGE" "NOTHING, DAXTER. WE HAVE TO KEEP THE SHIELD OPEN.")
  (705 "SAGE" "IT'S UP TO YOU TWO TO FIGURE OUT HOW TO DESTROY THE ROBOT.")
  (823 "DAXTER" "OH, GREAT. I GET TO HELP THE GUY THAT TURNED ME INTO A FURBALL")
  (983 "DAXTER" "DESTROY THE ONLY PERSON WHO CAN TURN ME BACK!")
  (1111)
  (1161 "SAGE" "FIRST, SAVE THE WORLD! THEN WE'LL TRY TO CONVINCE GOL TO HELP DAXTER.")
  )

("redsage-resolution"
  (58 "RED SAGE" "(CHUCKLES) YOU'VE FINALLY COME TO RESCUE ME.")
  (190 "RED SAGE" "DO YOU KNOW HOW LONG I'VE BEEN IN HERE? WHAT TOOK YOU SO LONG? AND UH... (CHUCKLES)")
  (378 "RED SAGE" "WHAT ARE YOUR NAMES?")
  (429)
  (432 "DAXTER" "I'M DAXTER! HE'S JAK, HE'S WITH ME.")
  (540 :offscreen "RED SAGE" "GOOD JOB, DAXTER. YOU'RE A REAL HERO.")
  (677)
  (703 "RED SAGE" "YOU'VE GOT TO STOP GOL FROM LAUNCHING THE ROBOT.")
  (837 "RED SAGE" "I'LL USE MY ECO POWER TO HELP OPEN THE SHIELD DOOR.")
  )

("sksp0378" :hint #x813
  (0 "DAXTER" "LA PUERTA ESTÁ ABIERTA, ¡VÁMONOS!")
  )

("sksp0381" :hint #x806
  (0 "DAXTER" "¡ROMPE EL GENERADOR PARA LIBERAR AL SABIO!")
  )

("sksp0382" :hint #x807
  (0 "DAXTER" "¡AGUANTA EN EL BORDE!")
  )

("sksp0383" :hint #x808
  (0 "DAXTER" "TENEMOS COMPAÑÍA, JAK. ¡MONTONES DE LURKERS!")
  )

("sksp0384" :hint #x809
  (0 "DAXTER" "¡DESTRUYE LOS GENERADORES!")
  )

("sksp0385" :hint #x80a
  (0 "DAXTER" "¡PULSA EL BOTÓN!")
  )

("sksp0386" :hint #x80b
  (0 "DAXTER" "¡ESE ROBOT NO ME DA MIEDO!")
  )

("sksp0387" :hint #x80c
  (0 "DAXTER" "¡SUBAMOS A ESAS PLATAFORMAS!")
  )

("sksp0388" :hint #x80d
  (0 "DAXTER" "¡QUE NO SE TE ESCAPE EL PRÓXIMO LANZADOOOOOR!")
  )

("sksp0389" :hint #x80e
  (0 "DAXTER" "¡CUIDADO!")
  )

("sksp0390" :hint #x80f
  (0 "DAXTER" "TENEMOS QUE RESCATAR A TODOS LOS SABIOS.")
  )

("sksp0391" :hint #x810
  (0 "DAXTER" "¿TÚ CREES QUE GOL ME DEVOLVERÁ MI ASPECTO?")
  )

("sksp0392" :hint #x811
  (0 "DAXTER" "ASÍ QUE ESTA ES LA CIUDADELA DE GOL Y MAIA. ¡QUÉ MOOONA!")
  )

("sksp0393" :hint #x812
  (0 "DAXTER" "¡ATERRIZA EN EL PRÓXIMO LANZADOR!")
  )

("yellowsage-resolution"
  (57 "YELLOW SAGE" "WHO WOULDA THOUGHT I'D LIVE TO SEE THE DAY")
  (137 "YELLOW SAGE" "WHEN I NEEDED TO BE RESCUED BY A BOY AND HIS MUSKRAT!")
  (271 "YELLOW SAGE" "(SIGHS) I'M GONNA GIVE GOL AND MAIA A LITTLE PAYBACK FOR THIS EMBARRASSMENT!")
  (471)
  (480 "YELLOW SAGE" "THEN WE'LL SEE ABOUT COOKING UP SOME MUSKRAT STEW...")
  (605)
  )

;; -----------------
;; finalboss
;; -----------------

("GOL-AM01" :hint #x0
  (0 "GOL" "YOU JUST WON'T GIVE UP, WILL YOU?")
  )

("GOL-AM02" :hint #x0
  (0 "GOL" "SOON, THE DARK ECO WILL BE OURS!")
  )

("GOL-AM03" :hint #x0
  (0 "GOL" "FINISH THEM!")
  )

("GOL-AM04" :hint #x0
  (0 "GOL" "FIRE!")
  )

("GOL-AM05" :hint #x0
  (0 "GOL" "BLAST THEM!")
  )

("GOL-AM06" :hint #x0
  (0 "GOL" "WHAT? THEM AGAIN!")
  )

("GOL-AM07" :hint #x0
  (0 "GOL" "IT'S TOO LATE!")
  )

("GOL-AM08" :hint #x0
  (0 "GOL" "YOU ARE MINE!")
  )

("GOL-AM09" :hint #x0
  (0 "GOL" "I HAVE YOU NOW!")
  )

("GOL-AM10" :hint #x0
  (0 "GOL" "AH HA HA HA HA!")
  )

("GOL-AM11" :hint #x0
  (0 "GOL" "NO MERCY!")
  )

("GOL-AM12" :hint #x0
  (0 "GOL" "TAKE THAT!")
  )

("GOL-AM13" :hint #x0
  (0 "GOL" "NICE TRY!")
  )

("GOL-AM14" :hint #x0
  (0 "GOL" "STAND STILL!")
  )

("GOL-AM15" :hint #x0
  (0 "GOL" "PATHETIC!")
  )

("GOL-AM16" :hint #x0
  (0 "GOL" "NOOO!")
  )

("GOL-AM17" :hint #x0
  (0 "GOL" "AHHH!")
  )

("GOL-AM18" :hint #x0
  (0 "GOL" "WE'LL OPEN THE SILO ALL THE WAY AND DESTROY YOU TWO!")
  )

("GOL-AM19" :hint #x0
  (0 "GOL" "LIGHT ECO! IT DOES EXIST!")
  )

("GOL-AM20" :hint #x0
  (0 "GOL" "WE'RE NOT GONNA TAKE IT!")
  )

("MAI-AM01" :hint #x0
  (0 "MAIA" "FINISH THEM BOTH OFF ONCE AND FOR ALL!")
  )

("MAI-AM02" :hint #x0
  (0 "MAIA" "TAKE THEM OUT!")
  )

("MAI-AM03" :hint #x0
  (0 "MAIA" "HA HA HA!")
  )

("MAI-AM04" :hint #x0
  (0 "MAIA" "ECO WON'T PROTECT YOU NOW!")
  )

("MAI-AM05" :hint #x0
  (0 "MAIA" "DO SOMETHING!")
  )

("MAI-AM06" :hint #x0
  (0 "MAIA" "AGH!")
  )

("MAI-AM07" :hint #x0
  (0 "MAIA" "NOOOOO!")
  )

("MAI-AM08" :hint #x0
  (0 "MAIA" "WE'LL OPEN THE SILO ALL THE WAY AND DESTROY YOU TWO!")
  )

("MAI-AM09" :hint #x0
  (0 "MAIA" "THEY MUST NOT BE ALLOWED TO GET IT!")
  )

("finalbosscam-white-eco"
  (163 :offscreen "GOL" "LIGHT ECO! IT DOES EXIST!")
  (268 :offscreen "MAIA" "THEY MUST NOT BE ALLOWED TO GET IT!")
  )

("green-sagecage-daxter-sacrifice"
  (0 "DAXTER" "LIGHT ECO! THAT COULD BE THE STUFF TO CHANGE ME BACK!")
  (114)
  (123 "DAXTER" "OR... IT MIGHT STOP THAT ROBOT.")
  (235)
  (274 "DAXTER" "STAY FUZZY, SAVE THE WORLD... CHOICES...")
  (404)
  (437 "DAXTER" "OKAY FINE WE'LL SAVE THE WORLD, BUT DO IT QUICKLY BEFORE I CHANGE MY MIND!")
  (634)
  )

("green-sagecage-outro-beat-boss-a"
  (165 :offscreen "MAIA" "DO SOMETHING!")
  (216)
  (596 :offscreen "GOL" "NOOO!")
  )

("green-sagecage-outro-beat-boss-b"
  (522 "SAGE" "WELL IT LOOKS LIKE I MAY HAVE BEEN TOO HARD ON YOU BOYS.")
  (640 "SAGE" "YOU DO HAVE WHAT IT TAKES TO BE HEROES!")
  (745)
  (751 "KEIRA" "BUT, DAXTER, NOW WE CAN'T CHANGE YOU BACK.")
  (845)
  (847 "DAXTER" "DON'T WORRY ABOUT ME, BABY. YOU KNOW WHAT THEY SAY: BIG THINGS COME IN SMALL PACKAGES.")
  (1096)
  (1100 "BLUE SAGE" "JAK, YOU HAVE AN INCREDIBLE TALENT FOR CHANNELING ECO!")
  (1219)
  (1222 "BLUE SAGE" "SAMOS, YOU MAY HAVE BEEN RIGHT ABOUT THIS ONE AFTER ALL!")
  (1321)
  (1323 "RED SAGE" "AND KEIRA, WITHOUT YOUR HELP AND INGENUITY NONE OF THIS WOULD HAVE BEEN POSSIBLE.")
  (1515 "RED SAGE" "HM-HM-HM. PERHAPS WE FOUND ANOTHER SAGE NOW THAT GOL AND MAIA ARE LOST...")
  (1728)
  (1731 "SAGE" "YES, GOL AND MAIA... THE DARK ECO PROBABLY DESTROYED THEM.")
  (1916 :offscreen "SAGE" "EH, PROBABLY...")
  (1999)
  (2003 "DAXTER" "AH WHO CARES? BRING 'EM ON WE CAN TAKE 'EM AGAIN, RIGHT JAK?")
  (2168)
  (2172 "DAXTER" "I SAID, RIGHT, JAK?")
  (2256)
  (2302 "DAXTER" "WHOA! PUT IT ON ICE, BIG GUY!")
  )

("green-sagecage-outro-beat-boss-enough-cells"
  (151 "SAGE" "HOLY YAKOW! WHAT COULD THAT BE?")
  (247 "KEIRA" "WOW, IT'S AN ANCIENT PRECURSOR DOOR!")
  (342 :offscreen "KEIRA" "IT LOOKS LIKE IT WILL ONLY OPEN IF WE FILL ALL 100 HOLES WITH POWER CELLS!")
  (485 "DAXTER" "UH, WE'RE HEROES, REMEMBER? WE HAVE 100 POWER CELLS!")
  )

("green-sagecage-outro-beat-boss-need-cells"
  (151 "SAGE" "HOLY YAKOW! WHAT COULD THAT BE?")
  (247 "KEIRA" "WOW, IT'S AN ANCIENT PRECURSOR DOOR!")
  (342 :offscreen "KEIRA" "IT LOOKS LIKE IT WILL ONLY OPEN IF WE FILL ALL 100 HOLES WITH POWER CELLS!")
  (485 "DAXTER" "OH BOY... HERE WE GO AGAIN!")
  )

("green-sagecage-outro-big-finish"
  (322 "DAXTER" "¡GUAAAU! ¿QUÉ ES?")
  (425)
  (428 "KEIRA" "ES...TAN BONITO...")
  (516)
  (519 "SAMOS" "¡POR TODOS LOS PRECURSOR!")
  (602)
  )

;; -----------------
;; training
;; -----------------

("asstvb40" :hint #x900
  (0 "KEIRA" "THIS DEVICE IS A COMMUNICATOR. WITH IT, MY FATHER AND I")
  (181 "KEIRA" "CAN GIVE YOU ADVICE AT ANY TIME DURING YOUR QUEST.")
  )

("asstvb41" :hint #x901
  (0 "KEIRA" "THESE FLOATING EGG-SHAPED THINGS ARE PRECURSOR ORBS.")
  (176)
  (180 "KEIRA" "COLLECT ENOUGH OF THEM, AND SOME OF THE VILLAGERS WILL GIVE YOU")
  (315 "KEIRA" "A POWER CELL IN EXCHANGE.")
  )

("asstvb42" :hint #x902
  (0 "KEIRA" "THIS IS A POWER CELL, THE MOST IMPORTANT PRECURSOR ARTIFACT YOU CAN FIND!")
  (327)
  (333 "KEIRA" "YOU NEED TO COLLECT 20 OF THESE SO I CAN POWER THE HEAT SHIELD")
  (507 "KEIRA" "FOR YOUR A-GRAV ZOOMER.")
  )

("asstvb44" :hint #x903
  (0 "KEIRA" "HEY, YOU FOUND ONE OF MY SCOUT FLIES!")
  (160 "KEIRA" "I SENT 7 OF THEM TO EACH AREA TO LOOK FOR POWER CELLS")
  (343 "KEIRA" "BUT THE LURKERS MUST HAVE CAPTURED THEM ALL!")
  )

("asstvb45" :hint #x904
  (0 "KEIRA" "WOW! THAT LAST SCOUT FLY HAD A POWER CELL!")
  (219 "KEIRA" "I'LL BET IF YOU COLLECT ALL 7 IN EACH AREA YOU CAN FIND EVEN MORE POWER CELLS.")
  )

("asstvb46" :hint #x905
  (0 "KEIRA" "BE CAREFUL IN THE OCEAN, THE WATERS ARE CHOCK-FULL OF LURKER SHARKS")
  (258 "KEIRA" "AND I'VE NEVER SEEN ANYONE DEFEAT ONE.")
  (419)
  (426 "KEIRA" "STAY CLEAR OF THEM IF YOU KNOW WHAT'S GOOD FOR YOU!")
  )

("asstvb47" :hint #x906
  (0 "KEIRA" "REMEMBER, THAT'S A POWER CELL. YOU NEED TO COLLECT AS MANY OF THOSE AS YOU CAN.")
  )

("asstvb48" :hint #x907
  (0 "KEIRA" "THAT'S A BLUE ECO VENT! MORE CONCENTRATED THAN THE FLOATING CLUSTERS,")
  (253 "KEIRA" "THIS VENT WILL GIVE YOU A FULL CHARGE OF BLUE ECO,")
  (419 "KEIRA" "LETTING YOU USE IT FOR THE MAXIMUM TIME.")
  )

("sagevb21" :hint #x908
  (3 "SAGE" "THOSE LITTLE GREEN BALLS OF ENERGY ON THE GROUND ARE A TYPE OF ECO.")
  (280 "SAGE" "PICK UP 50 SMALL GREEN ECOES, OR ONE BIG GREEN ONE TO INCREASE YOUR HEALTH.")
  )

("sagevb22" :hint #x909
  (0 "SAGE" "THAT'S BLUE ECO, WHICH CONTAINS THE ENERGY OF MOTION.")
  (291 "SAGE" "BLUE ECO ALLOWS YOU TO RUN FAST, BREAK BOXES, AND EVEN ACTIVATE SOME PRECURSOR")
  (640 "SAGE" "ARTIFACTS WHEN YOU GET NEAR THEM.")
  )

("sagevb23" :hint #x90a
  (0 "SAGE" "NOTICE HOW EACH BLUE ECO CLUSTER YOU PICK UP INCREASES THE TIME YOU CAN USE ITS POWER.")
  )

("sagevb24" :hint #x90b
  (3 "SAGE" "THIS IS A PRECURSOR DOOR. IT CAN ONLY BE OPENED BY APPROACHING THE DOOR")
  (357 "SAGE" "WHILE CHANNELING BLUE ECO THROUGH YOUR BODY.")
  )

("sagevb25" :hint #x90c
  (3 "SAGE" "GOOD WORK, THE BLUE ECO CAUSED THE DOOR TO OPEN. WITH BLUE ECO, YOU CAN BREATHE")
  (365 "SAGE" "ENERGY INTO ALL KINDS OF PRECURSOR ARTIFACTS THAT HAVE LAIN DORMANT FOR YEARS.")
  )

("sagevb26" :hint #x90d
  (0 "SAGE" "USE YOUR GOGGLES TO VIEW YOUR PROGRESS DURING THE ADVENTURE.")
  )

("sagevb27" :hint #x90e
  (1 "SAGE" "YOU CAN JUMP ONCE, THEN JUMP AGAIN IN THE AIR TO REACH EVEN HIGHER LEDGES.")
  )

("sagevb28" :hint #x90f
  (0 "SAGE" "WHEN YOU'RE SURROUNDED BY ENEMIES, USE YOUR SPIN KICK.")
  )

("sagevb29" :hint #x910
  (0 "SAGE" "THAT'S NOT A SPIN KICK! TRY AGAIN.")
  )

("sagevb30" :hint #x911
  (0 "SAGE" "COME ON, JAK! DO A SPIN KICK.")
  )

("sagevb31" :hint #x912
  (0 "SAGE" "GOOD WORK. USE THE SPIN KICK WHEN YOU WANT A GOOD ALL-ROUND ATTACK.")
  )

("sagevb32" :hint #x913
  (0 "SAGE" "FOR A STRAIGHT LINE, MOVING ATTACK, USE YOUR FIST TO PUNCH.")
  )

("sagevb33" :hint #x914
  (0 "SAGE" "THAT'S NOT A PUNCH ATTACK! LET'S SEE YOU PUNCH ALREADY.")
  )

("sagevb34" :hint #x915
  (0 "SAGE" "JAK! USE A PUNCH.")
  )

("sagevb35" :hint #x916
  (0 "SAGE" "GREAT JOB. USE THE PUNCH TO CLOSE DISTANCE QUICKLY IN A TOUGH SPOT.")
  )

("sagevb36" :hint #x917
  (0 "SAGE" "SOMETIMES YOU'LL WANT TO HIT THINGS WITH A GREATER FORCE.")
  (218 "SAGE" "TO BREAK ONE OF THESE BOXES, YOU SHOULD JUMP IN THE AIR")
  (420 "SAGE" "AND THEN DIVE DOWN ONTO IT, HANDS FIRST.")
  )

("sagevb37" :hint #x918
  (0 "SAGE" "WHEN YOU GET SOME CONFIDENCE, TRY USING SOME OF YOUR MOVES IN COMBINATIONS.")
  )

("sagevb38" :hint #x919
  (0 "SAGE" "YOU CAN'T COME BACK THROUGH THE WARP GATE UNTIL YOU FIND")
  (168 "SAGE" "ALL 4 POWER CELLS ON THIS ISLAND.")
  )

("sagevb39" :hint #x91a
  (0 "SAGE" "GREAT! YOU FOUND ALL OF THE POWER CELLS ON THE ISLAND.")
  (269 "SAGE" "COME BACK TO THE WARP GATE SO I CAN BRING YOU BACK TO THE LAB. HURRY UP!")
  )

;; -----------------
;; uncategorized
;; -----------------
