(language-id 4)

;; -----------------
;; intro
;; -----------------

("sage-intro-sequence-a"
  (45 :offscreen "???" "HO PASSATO LA VITA CERCANDO DI DARE RISPOSTE ALLE DOMANDE CHE MIO PADRE, E IL PADRE DI MIO PADRE, SI ERANO POSTI INUTILMENTE:")
  (285 :offscreen "???" "CHI ERANO I PRECURSOR? PERCHÉ HANNO CREATO I GRANDI MONOLITI CHE VEDIAMO SU TUTTO IL PIANETA?")
  (467 :offscreen "???" "COME RIUSCIVANO A CONTROLLARE L'ECO, L'ENERGIA VITALE DEL MONDO?")
  (602 :offscreen "???" "QUAL ERA IL LORO OBIETTIVO, E PERCHÉ SONO SCOMPARSI?")
  (708)
  (738 :offscreen "???" "HO CHIESTO ALLE PIANTE, MA NON RICORDAVANO.")
  (837 :offscreen "???" "LE PIANTE HANNO CHIESTO ALLE ROCCE, MA NEANCHE LE ROCCE RAMMENTAVANO,")
  (967 :offscreen "???" "NEANCHE LE ROCCE RIUSCIVANO A RICORDARE...")
  (1064)
  (1102 :offscreen "???" "OGNI GOCCIA DEL MIO SANGUE MI DICE CHE TUTTE LE RISPOSTE GIACCIONO SULLE SPALLE DI UN GIOVANE,")
  (1306 :offscreen "???" "IGNARO DEL SUO DESTINO, A CUI NON INTERESSA LA RICERCA DELLA VERITÀ, E CHE RIFIUTA IL MIO CONSIGLIO!")
  (1536)
  (1558 :offscreen "???" "E D'ALTRA PARTE, PERCHÉ DOVREBBE DARE ASCOLTO AL VECCHIO SAMOS?")
  (1680)
  (1701 :offscreen "SAMOS" "IO SONO SOLO IL MAESTRO DELL'ECO VERDE, UNO DEGLI UOMINI PIÙ SAGGI DEL PIANETA...")
  (1875)
  (1972 :offscreen "SAMOS" "PURTROPPO, SEMBRA CHE LE RISPOSTE NON NASCANO MAI DA ATTENTE RICERCHE, O DA PROFONDI RAGIONAMENTI.")
  (2141)
  (2162 :offscreen "SAMOS" "NO. PROPRIO COME MOLTI DEI MISTERI DEL FATO")
  (2286 :offscreen "SAMOS" "NASCONO SEMPLICEMENTE DA UN PICCOLO ATTO... DI DISOBBEDIENZA.")
  (2440 "DAXTER" "EHI, ASCOLTA JAK, IL VECCHIO VERDE CI AVEVA DETTO DI NON VENIRE QUI!")
  )

("sage-intro-sequence-d1"
  (137 "SAMOS" "ADESSO SI PUÒ SAPERE COSA VOLETE DA ME VOI DUE?")
  (220 "DAXTER" "ECCO, NOI ERAVAMO- CIOÈ- IO- IO ERO-")
  (283 "SAMOS" "NO! NON DIRMELO. INVECE DI DARMI RETTA, VOI DUE SIETE ANDATI A COMBINARE GUAI")
  (440 "SAMOS" "NELL'UNICO POSTO CHE VI AVEVO DETTO DI EVITARE ASSOLUTAMENTE: L'ISOLA DELLA NEBBIA!")
  (550 "DAXTER" "SÌ, ESATTO, E POI-")
  (579 "SAMOS" "E POI, DAXTER, TI SEI FATTO FINALMENTE UN BEL BAGNO. MA IN UNA POZZA DI ECO OSCURO, DOVE TI SEI RIDOTTO COSÌ!")
  (793 "DAXTER" "BENE, ORA VUOI CONTINUARE A CIARLARE O VUOI AIUTARMI A RISOLVERE QUESTO CASINO?!")
  (920 "SAMOS" "PENSO CHE CONTINUERÒ A CIARLARE PERCHÉ, A MIO PARERE, LA TRASFORMAZIONE È UN NOTEVOLE MIGLIORAMENTO.")
  (1079 "SAMOS" "E D'ALTRA PARTE... NON POTREI AIUTARTI NEANCHE SE VOLESSI.")
  (1186 "DAXTER" "COSA?!")
  (1220 "SAMOS" "C'È SOLTANTO UNA PERSONA CHE HA STUDIATO L'ECO OSCURO ABBASTANZA A LUNGO")
  (1329 "SAMOS" "DA POTERTI FAR TORNARE ALLA TUA FORMA ORIGINARIA:")
  (1431 "SAMOS" "GOL ACHERON IL SAGGIO.")
  (1493)
  (1496 :offscreen "SAMOS" "MA GOL VIVE NEL LONTANO NORD... NEL LONTANISSIMO NORD. NESSUNO GLI PARLA ORMAI DA ANNI.")
  (1718 "SAMOS" "TI TELETRASPORTEREI LÌ, MA PURTROPPO NON POSSO FARLO,")
  (1831 "SAMOS" "VISTO CHE DEI TRE SAGGI CHE CUSTODISCONO I TELETRASPORTI")
  (1934 "SAMOS" "ORMAI NON SI HANNO NOTIZIE DA TEMPO IMMEMORABILE.")
  )

("sage-intro-sequence-d2"
  (3 "SAMOS" "L'UNICA ALTRA VIA È A NORD E PASSA ATTRAVERSO IL CANYON DI FUOCO.")
  (114 :offscreen "SAMOS" "MA È UN TERRENO VULCANICO E POTREBBE FONDERE ANCHE IL METALLO PRECURSOR,")
  (224 "SAMOS" "NON PUOI ATTRAVERSARLO A PIEDI.")
  (270 "???" "MA POTRESTI TENTARE DI SORVOLARLO, SE AVESSI UNO ZOOMER CON UNO SCUDO CONTRO IL CALORE!")
  (393)
  (396 "???" "PER PURO CASO IO STAREI LAVORANDO SU UN GINGILLO DEL GENERE IN QUESTI GIORNI.")
  (512)
  (515 "???" "MI SERVIREBBERO SOLO 20 BATTERIE PER AVERE ABBASTANZA ENERGIA")
  (605 "???" "DA RESISTERE AL CALORE DEL CANYON! VERO PAPÀ?")
  (696)
  (699 "SAMOS" "CERTO KEIRA, POTREBBE FUNZIONARE... MA QUESTO GIOVANE RAGAZZO")
  (843 :offscreen "SAMOS" "E LA CREATURA!")
  (880 "SAMOS" "DOVE TROVERANNO 20 BATTERIE?")
  (930 "KEIRA" "LÀ AL VILLAGGIO! MOLTI LAGGIÙ HANNO UNA O DUE BATTERIE NASCOSTE DA QUALCHE PARTE.")
  (1050 :offscreen "KEIRA" "ANCHE SE LORO NON SARANNO DELL'IDEA DI SCAMBIARLE,")
  (1133 "KEIRA" "METTETE NELLE LORO MANI QUALCHE GLOBO PRECURSOR E RIUSCIRETE A RAGGIRARLI!")
  (1243)
  (1246 :offscreen "KEIRA" "E SCOMMETTO CHE CE NE SONO MOLTE DI PIÙ ABBANDONATE NEL DESERTO IN ATTESA CHE QUALCHE")
  (1364 "KEIRA" "PRODE AVVENTURIERO VADA A RECUPERARLE!")
  (1435 "DAXTER" "BEH, ECCO FINALMENTE IL CORAGGIOSO AVVENTURIERO!")
  (1529)
  (1532 "SAMOS" "\"CORAGGIOSO AVVENTURIERO?\"")
  (1582 "SAMOS" "VOI DUE NON RIUSCIRESTE A USCIRE DAL VILLAGGIO, SENZA ALLENAMENTO!")
  (1685)
  (1689 "SAMOS" "PRIMA DI FARE QUALUNQUE ALTRA COSA, FARESTE MEGLIO AD ANDARE AL TELETRASPORTO")
  (1810 "SAMOS" "PER ALLENARVI SULLA ROCCIA DEL GEYSER!")
  (1872)
  (1878 "DAXTER" "EHM, NON È CHE TROVEREMO ANCORA DELL'ALTRA BRUTTA ROBACCIA OSCURA, VERO?")
  (1993 "DAXTER" "NON VORREI CADERCI DENTRO DI NUOVO E DIVENTARE COME TE!")
  (2069)
  (2072 "SAMOS" "ENTRATE SUBITO LÌ, PRIMA CHE VI TRASFORMI ENTRAMBI IN FELCI!")
  (2189)
  )

("sage-intro-sequence-e"
  (200 "SAMOS" "OTTIMO ALLENAMENTO! MA QUESTO NON È NULLA IN CONFRONTO ALLE SFIDE CHE ANCORA VI ATTENDONO!")
  (359 "DAXTER" "NAH, NON C'È NESSUN PROBLEMA! DOBBIAMO DARCI UNA MOSSA, VERO JAK?")
  (496 "DAXTER" "CI PIACEREBBE RESTARE A PARLARE CON L'OMINO VERDE, MA ORA DOBBIAMO RIPRENDERE LE NOSTRE FATICHE!")
  (660 "SAMOS" "BENE, BENE. ALLORA PARTITE PER \"L'AVVENTURA\"...")
  (787 "SAMOS" "E MENTRE VIAGGIATE, IN CERCA DI \"AVVENTURA\", CERCATE ALMENO DI RENDERVI UTILI!")
  (940)
  (952 :offscreen "SAMOS" "QUEI RACCOGLITORI DI ECO VERDE SI SONO INTASATI DI NUOVO.")
  (1043)
  (1046 :offscreen "SAMOS" "ANDATE ALL'ESTREMITÀ PIÙ LONTANA DELLA SPIAGGIA E DATEGLI UNA PULITA.")
  (1160)
  (1169 :offscreen "SAMOS" "SEGUITE LE LAMPADE: VI CONDURRANNO FIN LAGGIÙ.")
  (1310)
  (1330 :offscreen "SAMOS" "E ORA, TUTTI QUANTI...")
  (1415)
  (1439 :offscreen "SAMOS" "FUORI DI QUI!")
  )

("sidekick-human-intro-sequence-b"
  (547 "???" "DEVE CONTINUARE LA TUA RICERCA DI ARTEFATTI E ECO.")
  (674 "???" "SE GLI INDIGENI HANNO DEGLI OGGETTI PRECURSOR, SAI BENE CHE COSA FARE!")
  (842 "???" "REGOLARE I CONTI CON CHIUNQUE OSI ALLONTANARSI DAL VILLAGGIO.")
  (937 "???" "PER IL RESTO LO ATTACCHEREMO A TEMPO DEBITO!")
  (1027)
  )

("sidekick-human-intro-sequence-c"
  (12 "DAXTER" "INSOMMA, CHE STIAMO FACENDO QUI, JAK? QUESTO POSTO MI FA VENIRE I BRIVIDI.")
  (151)
  (220 "DAXTER" "ACK!")
  (260)
  (384 "DAXTER" "UH?")
  (420 "DAXTER" "AH, STUPIDA SPAZZATURA DEI PRECURSOR!")
  (496)
  (577 "DAXTER" "EHI, CHE COS'È QUELLA ROBACCIA SCURA? NON PROMETTE NIENTE DI BUONO...")
  (721)
  (777 "DAXTER" "IL SAGGIO HA FARNETICATO QUALCOSA SUI PRECURSOR CHE AVEVANO COSTRUITO QUESTO LUOGO.")
  (909 "DAXTER" "\"DOVE SARANNO ANDAAAATI? PERCHÉ LO AVRANNO COSTRUIIIITO?\"")
  (1014 "DAXTER" "ORA, SE DEVO DIRE LA VERITÀ I GLOBI PRECURSOR E LE BATTERIE MI PIACCIONO,")
  (1124 "DAXTER" "MA SECONDO ME I PRECURSOR ERANO SOLO DEI PERDENTI.")
  (1212 "DAXTER" "SI È ACCESA! COME DIAVOLO HAI FATTO?")
  (1271)
  (1331 "DAXTER" "OH JAK, CREDO CHE SIAMO NEI GUAI!")
  (1386)
  (1622 :offscreen "DAXTER" "UAH, AIUTOOOOO!")
  (1722)
  (1800 "DAXTER" "OUCH! ARGH!")
  (1845)
  (1857 "DAXTER" "RAGAZZI SE BRUCIA!")
  (1913)
  (1941 "DAXTER" "TE L'AVEVO DETTO CHE NON DOVEVAMO VENIRE QUI, PERCIÒ...")
  (2028)
  (2057 "DAXTER" "CHE C'È?")
  (2101)
  (2189 "DAXTER" "AAAAAAAAAAAAAAAAAAAAAAH!!")
  (2307 "DAXTER" "OK... OK, VA TUTTO BENE... STO BENE!")
  (2431)
  (2481 "DAXTER" "AAAAAAAAAAAAAAAAAAAAAAH!!")
  )

;; -----------------
;; sidekick
;; -----------------

("sksp0001" :hint #x280
  (0 "DAXTER" "EHI! MA QUELLA BAMBOLINA DI KEIRA AVEVA RAGIONE. QUI FUORI CI SONO DEI TRANS-PAD.")
  )

("sksp0002" :hint #x281
  (0 "DAXTER" "CREDIMI, QUELLE SCATOLE CON L'ECO OSCURO SONO MOLTO PERICOLOSE!")
  )

("sksp0003" :hint #x282
  (0 "DAXTER" "SCOMMETTO CHE FRA TUTTE LE MOSCHE SCOUT PRESENTI IN OGNI LIVELLO")
  (195 "DAXTER" "CE NE SARÀ ALMENO UNA CON UNA BATTERIA.")
  )

("sksp0004" :hint #x283
  (0 "DAXTER" "SÌÌÌ, UN TESORO!")
  )

("sksp0005" :hint #x284
  (0 "DAXTER" "QUELLE SCATOLE DI LEGNO E DI METALLO NON SEMBRANO COSÌ RESISTENTI.")
  (166 "DAXTER" "SCOMMETTO CHE SI ROMPONO SE TI TUFFI IN SALTO SU DI LORO.")
  )

("sksp0006" :hint #x285
  (0 "DAXTER" "QUELLE SCATOLE DI METALLO SONO PIÙ SPESSE DEL CRANIO DI UNA YAKOW")
  (188 "DAXTER" "MA CI DEVE ESSERE UN MODO PER APRIRLE.")
  )

("sksp0007" :hint #x286
  (0 "DAXTER" "UNA SOLA PAROLA, BATTERIE. DOBBIAMO TROVARLE MA NON STIAMO CERCANDO CON LA DOVUTA CURA.")
  )

("sksp0008" :hint #x287
  (0 "DAXTER" "ABBIAMO BISOGNO DEI GLOBI. GLOBI JAK! COME POTREMMO COMPRARE LE BATTERIE SE NON RACCOGLIAMO I GLOBI!")
  )

("sksp0009" :hint #x251
  (0 "DAXTER" "CHE OGGETTO PARTICOLARE... SCOMMETTO CHE POTREMMO APRIRLO")
  (206 "DAXTER" "UTILIZZANDO QUELLO STRANO ECO BLU.")
  )

("sksp0014" :hint #x233
  (0 "DAXTER" "ABBIAMO RACCOLTO ABBASTANZA GLOBI PER SCAMBIARLI CON UNA BATTERIA.")
  (215 "DAXTER" "TORNIAMO INDIETRO E CONCLUDIAMO L'AFFARE.")
  )

("sksp0035" :hint #x25c
  (0 "DAXTER" "YEAH, E COSÌ ABBIAMO UN LANCIATORE PRECURSOR.")
  (117 "DAXTER" "EHI, MA NON SEI CARICATO CON L'ECO BLU! UFFA, ALLORA NON CI SERVE A NULLA!")
  )

("sksp0071" :hint #x2a5
  (0 "DAXTER" "PRENDI L'ECO ROSSO!")
  )

("sksp0072" :hint #x2a6
  (0 "DAXTER" "L'ECO ROSSO AUMENTA LA FORZA DEI TUOI ATTACCHI!")
  )

("sksp0073" :hint #x2a7
  (0 "DAXTER" "ABBIAMO BISOGNO DELL'ECO BLU PER CARICARLO!")
  )

("sksp009a" :hint #x0
  (0 "DAXTER" "HA HA! GLIELE ABBIAMO FATTE VEDERE.")
  )

("sksp009b" :hint #x28e
  (0 "DAXTER" "BEEENE, ALTRI GLOBI!")
  )

("sksp009c" :hint #x28f
  (0 "DAXTER" "FAMMI UN FAVORE: STAI ALLA LARGA DALL'ECO OSCURO!")
  )

("sksp009d" :hint #x290
  (0 "DAXTER" "YEAH-HA-HA-HA!")
  )

("sksp009e" :hint #x291
  (0 "DAXTER" "WA-HOO!")
  )

("sksp009f" :hint #x292
  (0 "DAXTER" "PRENDILO, PRENDILO! HA HA HA!")
  )

("sksp009g" :hint #x293
  (0 "DAXTER" "PROPRIO DIETRO DI TE JAK!")
  )

("sksp009i" :hint #x294
  (0 "DAXTER" "ABBIAMO TROVATO TUTTE LE MOSCHE SCOUT DI QUESTA ZONA?")
  )

("sksp009j" :hint #x295
  (0 "DAXTER" "EHI! SEMBRA CHE LE MOSCHE SCOUT SI TROVINO SEMPRE NELLE SCATOLE ROSSE.")
  )

("sksp009k" :hint #x296
  (0 "DAXTER" "BENE! ABBIAMO TROVATO TUTTE LE MOSCHE SCOUT DI QUESTA ZONA.")
  )

("sksp0145" :hint #x359
  (0 "DAXTER" "PUOI SPARARE DELLE PALLE DI FUOCO QUANDO SEI CARICATO CON L'ECO GIALLO!")
  )

;; -----------------
;; village1
;; -----------------

("ASSTLP01" :hint #x0
  (0 "KEIRA" "MMH!")
  )

("ASSTLP02" :hint #x0
  (0 "KEIRA" "BISOGNA FAR FUNZIONARE QUESTO SCUDO TERMICO...")
  )

("ASSTLP03" :hint #x0
  (0 "KEIRA" "CI SERVONO DELLE BATTERIE PER ALIMENTARLO...")
  )

("ASSTLP04" :hint #x0
  (0 "KEIRA" "DOV'È LA MIA CHIAVE?")
  )

("ASSTLP05" :hint #x0
  (0 "KEIRA" "IL CANYON DI FUOCO È COSÌ CALDO...")
  )

("EXP-AM01" :hint #x0
  (0 "ZIO" "DEVO METTERMI IN VIAGGIO AL PIÙ PRESTO. HO BISOGNO DEI GLOBI DEI PRECURSOR!")
  )

("EXP-AM02" :hint #x0
  (0 "ZIO" "VEDIAMO... DOVE POSSO ANDARE PRIMA?")
  )

("EXP-AM03" :hint #x0
  (0 "ZIO" "OH, COME MI MANCA VIAGGIARE...")
  )

("EXP-AM04" :hint #x0
  (0 "ZIO" "COSÌ TANTI POSTI DA VEDERE, E COSÌ POCO TEMPO.")
  )

("EXP-AM05" :hint #x0
  (0 "ZIO" "AI MIEI TEMPI, SI POTEVA VIAGGIARE SENZA ESSERE AGGREDITI... DAI MOSTRI!")
  )

("EXP-LO02" :hint #x0
  (0 "ZIO" "MI SERVONO ALTRI GLOBI DEI PRECURSOR.")
  )

("FAR-AM01" :hint #x0
  (0 "CONTADINO" "RONF... QUIII, BESSIE... QUIII, BESSIE... SU DA BRAVA...")
  )

("FAR-AM02" :hint #x0
  (0 "FARMER" "RONF- DEVO PORTARE DENTRO IL RACCOLTO PRIMA CHE GLI INSETTI ME LO ROVININO...")
  )

("FAR-AM2A" :hint #x0
  (0 "FARMER" "DEVO PORTARE DENTRO IL RACCOLTO PRIMA CHE GLI INSETTI ME LO ROVININO...")
  )

("FAR-LO01" :hint #x0
  (0 "CONTADINO" "RONF...")
  )

("FAR-LO1A" :hint #x0
  (0 "CONTADINO" "RONF...")
  )

("SAMOSLP03" :hint #x0
  (0 "SAMOS" "QUESTI DUE NON RIUSCIREBBERO NEMMENO A STAPPARSI LE ORECCHIE...")
  )

("SAMOSLP04" :hint #x0
  (0 "SAMOS" "NON SARÀ MAI COME SUO ZIO... MH, BAH.")
  (221 "SAMOS" "NON MI IMPORTA COSA DICONO GLI ALTRI.")
  )

("SAMOSLP05" :hint #x0
  (0 "SAMOS" "SALVE, SAGGIO BLU? SALVE? IN QUALE FIAMMA BLU POTRÀ MAI ESSERE...")
  )

("SAMOSLP06" :hint #x0
  (0 "SAMOS" "ODDIO, DIO, DIO...")
  )

("SAMOSLP11" :hint #x0
  (0 "SAMOS" "EHI? C'È NESSUNO? ENTRIAMO...")
  )

("assistant-introduction-blue-eco-switch"
  (23 "DAXTER" "EHI DOLCEZZA, CHE NE DIRESTI DI FARE UN GIRO SU QUESTO ZOOMER ANTI-GRAVITÀ, EH?")
  (175)
  (193 "KEIRA" "REGOLA NUMERO UNO: MAI. USCIRE. CON ANIMALI.")
  (308)
  (312 "DAXTER" "AAAH, PEGGIO PER TE, NON SAI COSA TI PERDI, HEHEHE-")
  (430 "DAXTER" "AH! EHI!")
  (490)
  (505 "KEIRA" "ASCOLTA, SE TI SERVE QUALCOSA PER OCCUPARE IL TEMPO, MIO PADRE MI HA PARLATO")
  (635 "KEIRA" "PIÙ VOLTE DI UN ANTICHISSIMO CONDOTTO REALIZZATO DAI PRECURSOR, NASCOSTO NEL SOTTOSUOLO.")
  (739)
  (742 :offscreen "KEIRA" "LE TUBATURE SFOCIANO NEI CAMINI DI VENTILAZIONE;")
  (842 :offscreen "KEIRA" "DA ALCUNI DI ESSI, L'ECO FUORIESCE LIBERAMENTE, ALTRI SONO STATI BLOCCATI.")
  (945)
  (954 "KEIRA" "DEVE PUR ESSERCI UN MODO PER RIAPRIRE QUEI CAMINI!")
  (1052 :offscreen "KEIRA" "IO HO INDIVIDUATO UNA PARTE DEL CONDOTTO AL TEMPIO PROIBITO.")
  (1138 "KEIRA" "MAGARI POTRESTI CERCARE LAGGIÙ QUALCHE INTERRUTTORE.")
  (1246)
  )

("assistant-introduction-race-bike"
  (9 "DAXTER" "EHI BELLEZZA, A COSA STAI LAVORANDO?")
  (63 "KEIRA" "NO! FA' ATTENZIONE! GAH! STO CERCANDO DI CAPIRE COME TRASPORTARE LO ZOOMER")
  (200 "KEIRA" "UTILIZZANDO I TRANS-PAD CHE I PRECURSOR HANNO LASCIATO IN TUTTO IL MONDO.")
  (308)
  (312 :offscreen "KEIRA" "SE TROVI UNO DI QUESTI APPARECCHI, INFORMAMI. IO POSSO CALCOLARNE LA POSIZIONE COL TUO COMUNICATORE")
  (453 :offscreen "KEIRA" "E SPEDIRTI LO ZOOMER.")
  (508 "KEIRA" "CERCA I TRANS-PAD MENTRE ESPLORI L'ISOLA DELLA NEBBIA, O QUALSIASI ALTRO LUOGO!")
  (665)
  )

("assistant-reminder-1-blue-eco-switch"
  (23 "KEIRA" "SONO SICURA CHE SE OSSERVI IL TEMPIO PROIBITO DEI PRECURSOR")
  (143 "KEIRA" "TROVERAI UN MODO PER APRIRE I CAMINI DI VENTILAZIONE DELL'ECO BLU NELLA SPIAGGIA DELLE SENTINELLE!")
  (295)
  )

("assistant-reminder-1-generic"
  (25 "KEIRA" "RAGAZZI, CONTINUATE A RACCOGLIERE LE BATTERIE, È IL SOLO MODO PER POTER PROSEGUIRE IL VIAGGIO VERSO NORD.")
  )

("assistant-reminder-1-race-bike"
  (19 "KEIRA" "HO FINALMENTE CAPITO COME USARE I TRANS-PAD!")
  (106 "KEIRA" "ADESSO DIRIGETEVI ALL'ISOLA DELLA NEBBIA. VI SPEDIRÒ LO ZOOMER!")
  (229)
  )

("asstvb04" :hint #x2b1
  (0 "KEIRA" "BENE! AVETE RACCOLTO BATTERIE SUFFICIENTI PER ALIMENTARE IL MIO SCUDO TERMICO!")
  (233 "KEIRA" "INCONTRIAMOCI ALL'ENTRATA DEL CANYON DEL FUOCO, SALENDO LA RUPE DIETRO LA CASA DELL'AGRICOLTORE.")
  (559 "KEIRA" "PORTATE LE BATTERIE, E SBRIGATEVI. MIO PADRE DICE DI AVER VISTO ALTRI LURKER NEI DINTORNI!")
  )

("asstvb08" :hint #x2b2
  (0 "KEIRA" "SBRIGATEVI CON QUELLE BATTERIE! STO ASPETTANDO AL CANYON DEL FUOCO")
  (260 "KEIRA" "IN CIMA ALLA RUPE DIETRO LA CASA DELL'AGRICOLTORE!")
  )

("explorer-introduction"
  (23 "ZIO" "ECCO, ALOHA CARO IL MIO RAGAZZO. MI COGLI IN UN MOMENTO VERAMENTE INOPPORTUNO.")
  (197 "ZIO" "SAI IERI STAVO FINALMENTE PER METTERMI IN VIAGGIO")
  (288 "ZIO" "MA MI SONO RESO CONTO DI ESSERE A CORTO DI VECCHI GLOBI DEI PRECURSOR.")
  (426)
  (430 "ZIO" "PER MILLE BALENE, IO AVREI GIURATO DI AVERNE 90!")
  (538 "ZIO" "CREDO CHE QUEL TUO GIOAVANE AMICO, SI QUEL... QUEL TIPO IRRITANTE, BRUTTO E MISERABILE")
  (716 "ZIO" "ME GLI ABBIA APPENA RUBATI, SOLO PER DIVERTIRSI UN PO'.")
  (829)
  (865 "ZIO" "COMUNQUE, POTRESTI ESSERE COSI' GENTILE DA PRESTARE AL TUO VECCHIO ZIO 90 GLOBI DEI PRECURSOR")
  (1043 "ZIO" "IN MODO CHE POSSA METTERSI IN VIAGGIO? IN CAMBIO TI OFFRIREI UNA BELLA BATTERIA.")
  )

("explorer-reminder-1"
  (25 "ZIO" "COME?! NON GLI HAI TUTTI QUANTI HAI DETTO?!")
  (148 "ZIO" "ACCIDENTI, EBBENE ALLORA CON MENO DI 90 GLOBI DI PRECURSOR")
  (251 "ZIO" "NON POSSO ASSOLUTAMENTE METTERMI IN VIAGGIO, MIO CARO NIPOTE.")
  (387)
  )

("explorer-reminder-2"
  (33 "ZIO" "CI HO PENSATO SU, FACCIAOMO UN PATTO, 90 GLOBI DI PRECURSOR PER UNA BATTERIA.")
  (187 "ZIO" "MI SEMBRA UNO SCAMBIO MOLTO EQUO.")
  )

("explorer-resolution"
  (28 "ZIO" "VEDO CHE SIETE TORNATI PER CONCLUDERE L'AFFARE. BENE, BENE, MOLTO BENE!")
  (179 "ZIO" "HEY, MA GLI AVETE I GLOBI DEI PRECUROS SU CUI CI SIAMO ACCORDATI?")
  (310)
  (324 "ZIO" "SPERO CHE USERETE IN MODO INTELLIGENTE QUESTA BATTERIA, VE LA SIETE GUADAGNATA. CIAO, CIAO, AU REVOIR, BYE BYE!")
  )

("farmer-introduction"
  (1 "CONTADINO" "MHMH, LE MIE YAKOW MUNGERÒ, LE MIE YAKOW MUNGERÒ...")
  (113 "CONTADINO" "HUFF! SEI TU! AAH, STAVO RIPOSANDO LE MIE STANCHE OSSA, È TUTTO IL GIORNO CHE CERCO DI FAR TORNARE")
  (317 "CONTADINO" "NEL RECINTO QUELLE BESTIACCE! DEGLI STRANI ESSERI HANNO TENTATO DI RUBARLE.")
  (454)
  (456 "CONTADINO" "PENSI CHE POTRESTI AIUTARE UN POVERO VECCHIO A RIPORTARLE NEL RECINTO?")
  )

("farmer-reminder-1"
  (0 "CONTADINO" "EHI! LE MIE YAKOW SONO TUTTE FUORI DAL RECINTO! NON SEI ANCORA RIUSCITO A RIPORTARLE DENTRO?!")
  )

("farmer-reminder-2"
  (0 "CONTADINO" "QUELLE DANNATE SE NE VANNO ANCORA A ZONZO!!")
  (85 "CONTADINO" "DI DECIDI A FARLE RIENTRARE NEL RECINTO?!")
  )

("farmer-resolution"
  (0 "CONTADINO" "OOH, BEN FATTO RAGAZZO, SEI RIUSCITO A FAR RIENTRARE QUEI SACCHI DI PULCI!")
  (134 "CONTADINO" "OH, ORA POSSO DORMIRE IN PACE. AHEM, GRAZIE AMICO, PRENDI QUESTA BATTERIA.")
  (340)
  )

("sage-introduction-misty-cannon"
  (24 "SAMOS" "OH, ECCO I NOSTRI EROICI CONQUISTATORI...")
  (136 "SAMOS" "BENE! VOLEVO APPUNTO PARLARVI DI UNA FACCENDA PIUTTOSTO SERIA.")
  (258)
  (261 :offscreen "SAMOS" "SEMBRA CI SIANO PARECCHI LURKER IN FERMENTO SULL'ISOLA DELLA NEBBIA.")
  (379)
  (385 :offscreen "SAMOS" "DALLA MIA TORRE DI OSSERVAZIONE POSSO VEDERLI, STANNO BORBANDANDO IL SILOS DEL PRECURSOR.")
  (525)
  (528 "SAMOS" "SE I LURKER DOVESSERO RIUSCIRE AD APRIRLO LIBERANDO L'ECO OSCURO")
  (642 "SAMOS" "SAREMO COSTRETTI A FUGGIRE A GAMBE LEVATE, RICOPRENDOCI DI RIDICOLO NON SO SE MI SPIEGO.")
  (788)
  (807 "SAMOS" "JAK, E' IL MOMENTO DI DIMOSTRARE IL TUO CORAGGIO.")
  (906 "SAMOS" "RECATI DAL PESCATORE E FATTI RIPORTARE IN BARCA ALL'ISOLA DELLA NEBBIA.")
  (1018 "SAMOS" "RAGGIUNGI LA CIMA DEL SILOS DEL PRECURSOR E TOGLI DI MEZZIO QUEL CANNONE, CHIARO?!")
  (1171)
  (1177 "DAXTER" "E IO CHE DEVO FARE?")
  (1232)
  (1235 "SAMOS" "TU? PERCHE' NON PULISCI I PAVIMENTI? HANNO PERSO UN PO' DELLA LORO LUCENTEZZA ULTIMAMENTE.")
  )

("sage-reminder-1-ecorocks"
  (28 "SAMOS" "DEVO RICONOSCERE CHE AVETE PROPRIO UN BEL CORAGGIO!")
  (132 "SAMOS" "DI NUOVO QUI E SENZA ESSERE RIUSCITI A SBLOCCARE I MIEI ECO-RACCOGLIOTRI!")
  (244)
  (252 :offscreen "SAMOS" "EBBENE, SI TROVANO DALL'ALTRA PARTE DELLA SPIAGGIA RAGAZZI.")
  (365)
  (366 :offscreen "SAMOS" "E ADESSO...")
  (412 :offscreen "SAMOS" "DATEVI UNA MOSSA!")
  )

("sage-reminder-1-generic"
  (54 "SAMOS" "E VOI DUE CHE CI FATE QUI, DOVETE PENSARE A RACCOGLIERE LE BATTERIE!")
  (178)
  (181 "SAMOS" "NON OSATE PIU' DISTURBARMI FINCHE' NON LE AVRETE TROVATE, CAPITO?!")
  )

("sage-reminder-1-misty-cannon"
  (24 "SAMOS" "IL BOMBARDAMENTO SI STA INTENSIFICANDO!")
  (86 :offscreen "SAMOS" "TROVA IL PESCATORE NELLA GIUNGLA, OTTIENI IL PERMESSO DI USARE LA SUA BARCA")
  (215 :offscreen "SAMOS" "E RAGGIUNGI L'ISOLA DELLA NEBBIA PER FERMARE IL CANNONE.")
  (317)
  (320 "SAMOS" "E TU DAXTER, DAI UNA BELLA RIPULITA. QUESTO POSTO SEMBRA UN PROCILE!")
  )

("sage-reminder-2-generic"
  (27 "SAMOS" "YOU TWO JUST DON'T UNDERSTAND THE GRAVITY OF THE SITUATION.")
  (137 "SAMOS" "THIS IS ABOUT MORE THAN A SINGLE BOY GONE FUZZY. THIS IS ABOUT LIFE AS WE KNOW IT.")
  (320)
  (323 "SAMOS" "NOW, GET OUT THERE AND FULFILL YOUR DESTINY.")
  (455)
  )

("sksp0010" :hint #x231
  (0 "DAXTER" "EHI! ANDIAMO GIÙ AL PORTO, ALLA NAVE DEL VECCHIO PESCATORE!")
  )

("sksp0013" :hint #x232
  (0 "DAXTER" "HAI VISTO LE DIMENSIONI DEL MORSO DI QUELLO SQUALO LURKER? HA PORTATO VIA TUTTO UN PEZZO DELLO SCAFO!")
  (315)
  (337 "DAXTER" "FAREMMO MEGLIO A STARNE ALLA LARGA. NON PENSO CHE POTREMMO AFFRONTARE UNA CREATURA DEL GENERE...")
  )

("sksp0015" :hint #x234
  (0 "DAXTER" "QUESTO DEVE ESSERE UNO DI QUEGLI ORACOLI PRECURSOR DI CUI PARLANO SEMPRE I SAGGI.")
  (228 "DAXTER" "SPERO SOLO CHE NON FOSSERO VERAMENTE COSÌ BRUTTI!")
  )

("sksp0017" :hint #x235
  (0 "DAXTER" "UAO! GUARDA QUELLA STRANA SCULTURA ADAGIATA SOPRA LE ROCCE!")
  )

("sksp0043" :hint #x24e
  (0 "DAXTER" "DOVREMMO CERCARE IL PESCATORE.")
  (106 "DAXTER" "PARE CHE SI TROVI NELLA GIUNGLA, NELLA PARTE PIÙ MERIDIONALE DEL FIUME!")
  )

("sksp018a" :hint #x297
  (0 "DAXTER" "QUEL CONTADINO SFATICATO CI DEVE UNA BATTERIA!")
  (156 "DAXTER" "ANDIAMO A PARLARGLI!")
  )

;; -----------------
;; oracle
;; -----------------

("oracle-intro-1"
  (0 "ORACOLO" "CHI HA SVEGLIATO L'ORACOLO?")
  (75)
  (81 "ORACOLO" "ASPETTATE, UNO DI VOI HA IN SÉ LA LUCE.")
  (198)
  (206 "ORACOLO" "DA PRIMA DEI TEMPI, HO CERCATO E ATTESO IL RITORNO DEL VERO EROE.")
  (390)
  (395 "ORACOLO" "PORTAMI 120 GLOBI PRECURSOR PER OGNI BATTERIA CHE CONTENGO.")
  )

("oracle-left-eye-1"
  (0 "ORACOLO" "TI SEI DIMOSTRATO ANCORA UNA VOLTA MERITEVOLE. ECCOTI UNA BATTERIA.")
  )

("oracle-left-eye-2"
  (0 "ORACOLO" "FOR YOUR SACRIFICE, I OFFER YOU A POWER CELL.")
  )

("oracle-left-eye-3"
  (0 "ORACOLO" "FOR YOUR EFFORT, A POWER CELL IS THE REWARD.")
  )

("oracle-reminder-1"
  (0 "ORACOLO" "PORTAMI 120 GLOBI PRECURSOR E TI DARO' IN CAMBIO UNA BATTERIA.")
  )

("oracle-right-eye-1"
  (0 "ORACOLO" "PER I VOSTRI DONI, VI MERITATE UN'ALTRA BATTERIA.")
  )

("oracle-right-eye-2"
  (0 "ORACOLO" "HERE IS ANOTHER POWER CELL FOR YOUR QUEST.")
  )

("oracle-right-eye-3"
  (0 "ORACOLO" "YOU HAVE OBTAINED ANOTHER POWER CELL.")
  )

;; -----------------
;; beach
;; -----------------

("BIR-AM01" :hint #x0
  (0 "ORNITOLOGA" "SEI GIÀ VICINO ALL'UOVO?")
  )

("BIR-AM02" :hint #x0
  (0 "ORNITOLOGA" "ECCO, SOLO UN POCHINO PIÙ AVANTI!")
  )

("BIR-AM03" :hint #x0
  (0 "ORNITOLOGA" "OH, BENE, SPINGILO. OH-OH, PIANO!")
  )

("BIR-AM04" :hint #x0
  (0 "ORNITOLOGA" "OH, MAMMA MIA, AVEVO DETTO PIANO!")
  )

("BIR-AM05" :hint #x0
  (0 "ORNITOLOGA" "CORAGGIO, SPINGI L'UOVO GIÙ DALLA SCOGLIERA!")
  )

("BIR-AM06" :hint #x0
  (0 "ORNITOLOGA" "OOOOH!")
  )

("BIR-AM07" :hint #x0
  (0 "ORNITOLOGA" "QUI, UCCELLINO. QUI, UCCELLINO BELLO.")
  )

("BIR-AM08" :hint #x0
  (0 "ORNITOLOGA" "QUI, UCCELLINO.")
  )

("BIR-AM09" :hint #x0
  (0 "ORNITOLOGA" "STATE ATTENTI! NON SEMBRA UN POSTO MOLTO SICURO!")
  )

("BIR-AM10" :hint #x0
  (0 "ORNITOLOGA" "ATTENZIONE, ADAGIO!")
  )

("BIR-AM11" :hint #x0
  (0 "ORNITOLOGA" "BUON LAVORO. CI VEDIAMO GIÙ VICINO ALL'UOVO!")
  )

("BIR-AM12" :hint #x0
  (0 "ORNITOLOGA" "VOI SÌ CHE SIETE DEI VERI AMANTI DEGLI ANIMALI!")
  )

("BIR-AM13" :hint #x0
  (0 "ORNITOLOGA" "VEDETE QUALCHE ALTRO UCCELLINO LASSÙ?")
  )

("BIR-LO01" :hint #x0
  (0 "ORNITOLOGA" "SMACK... FIRULÌ...")
  )

("BIR-LO02" :hint #x0
  (0 "ORNITOLOGA" "OH, QUELLO È PROPRIO GRAZIOSO.")
  )

("BIR-LO03" :hint #x0
  (0 "ORNITOLOGA" "OOH GUARDA, UN MUCKY-MUCK!")
  )

("CHI-AM01" :hint #x0
  (0 "SINDACO" "HOO... QUESTA È UNA CATASTROFE! UNA VERA... CATASTROFE...")
  )

("CHI-AM02" :hint #x0
  (0 "SINDACO" "VOGLIONO CHE IO VADA NELLA GIUNGLA - IO! HO HO OH...")
  (214)
  (219 "SINDACO" "PREFERIREI LOTTARE CON UN FLUT FLUT IMBESTIALITO.")
  )

("CHI-AM03" :hint #x0
  (0 "SINDACO" "UGH... PRIMA LA BARCA DEL PESCATORE VIENE A-ATTACCATA DA UN M-MOSTRO...")
  (352)
  (395 "SINDACO" "E ORA- ORA QUESTO... CHE ALTRO... CHE ALTRO POTREBBE ANDARE STORTO?!")
  )

("CHI-AM04" :hint #x0
  (0 "SINDACO" "OHH... IO- NON SO IO- IOIOIOIO... OOOOH... FORSE DOVREI AUMENTARE LE TASSE... ERGH... PER POTER RIMEDIARE A QUESTO PASTICCIO.")
  )

("CHI-AM05" :hint #x0
  (0 "SINDACO" "PROBLEMI... IOIOIOIO... P-PROBLEMI... OH... PROBLEMI...!")
  )

("CHI-AM06" :hint #x0
  (0 "SINDACO" "SOB... SIGH... A-A-ADESSO È IMPOSSIBILE... CHE MI RIELEGGANO...")
  )

("CHI-AM07" :hint #x0
  (0 "SINDACO" "OOOOHHH... CHE COSA È SUCCESSO... ALL'ECO-RAGGIO?")
  )

("CHI-AM08" :hint #x0
  (0 "SINDACO" "SIGH... PERCHÉ... IO DEVO... PERCHÉ? PERCHÉ? SOB...")
  )

("CHI-LO01" :hint #x0
  (0 "SINDACO" "HOO... MULINI A VENTO, MOSTRI, ENERGIA, RIELEZIONE...")
  )

("CHI-LO02" :hint #x0
  (0 "SINDACO" "MHMH... VOTAZIONI... M-MOSTRI... RIELEZIONE...")
  )

("SCU-AM01" :hint #x0
  (0 "SCULTORE" "OHH... NON CI RIESCO PROPRIO PIÙ.")
  )

("SCU-AM02" :hint #x0
  (0 "SCULTORE" "COME VORREI RITROVARE L'ISPIRAZIONE.")
  )

("SCU-AM03" :hint #x0
  (0 "SCULTORE" "SONO ISPIRATO COME... COME UN SASSO.")
  )

("SCU-AM04" :hint #x0
  (0 "SCULTORE" "OOHH... DOV'È LA MIA MUSA?")
  )

("SCU-AM05" :hint #x0
  (0 "SCULTORE" "NON POSSO LAVORARE COSÌ!")
  )

("SCU-AM06" :hint #x0
  (0 "SCULTORE" "OH DIO... TORNERÀ MAI DA ME?")
  )

("SCU-LO01" :hint #x0
  (0 "SCULTORE" "ODDIO...")
  )

("bird-lady-beach-resolution"
  (30 "BIRDWATCHER" "OH MY, I HOPE THE POOR DEAR'S OKAY. HERE'S A POWER CELL FOR YOUR VALOR.")
  (243)
  (306 "FLUT FLUT" "MAMA!")
  (354)
  (406 "FLUT FLUT" "MAMA!")
  (430 "DAXTER" "OH NO! NO, NO, NO, NO!")
  (533)
  (535 "BIRDWATCHER" "LOOK... ISN'T THAT CUTE? IT THINKS YOU'RE ITS MAMA.")
  (696)
  (699 "DAXTER" "EH? I'M NOT YOUR MOM! YOU SEE ANY FEATHERS HERE?")
  (803)
  (807 "BIRDWATCHER" "OH, LOVE AT FIRST SIGHT! AH...")
  (936)
  (939 "BIRDWATCHER" "LISTEN, BOYS, I'LL TAKE THIS LITTLE CHICK BACK TO THE VILLAGE WITH ME")
  (1054 "BIRDWATCHER" "AND WORK WITH THE SAMOS TO TAKE CARE OF HER.")
  )

("bird-lady-introduction"
  (125 "ORNITOLOGA" "OH CIELO, MA QUESTO UCCELLINO È VERAMENTE MOLTO MALATO!")
  (245)
  (251 "DAXTER" "HA! NON MI PARE TU SIA MOLTO MEGLIO, PICCOLA!")
  (326)
  (331 "ORNITOLOGA" "OH, SCUSA. CREDEVO CHE FOSSI UN RING-FRING DAL PETTO A MACCHIE ARANCIONI!")
  (454)
  (457 "ORNITOLOGA" "SAPETE, IERI HO VISTO CERTI ESSERI TERRIBILMENTE MALVAGI")
  (578 "ORNITOLOGA" "CATTURARE UNA FEMMINA DI FLUT FLUT SULLA SPIAGGIA.")
  (648)
  (654 :offscreen "ORNITOLOGA" "COSÌ IL SUO POVERO OVETTO È RIMASTO ORFANO IN UN NIDO IN CIMA ALLA SCOGLIERA")
  (796 :offscreen "ORNITOLOGA" "E IO NON RIESCO AD ARRIVARCI. SE POTESTE ARRAMPICARVI FIN LÌ E SPINGERLO GIÙ... HO MESSO DEL FIENO")
  (951 :offscreen "ORNITOLOGA" "SOTTO LA SCOGLIERA, ATTERRERÀ SENZA ROMPERSI.")
  (1041)
  (1044 "ORNITOLOGA" "FATE QUESTO PIACERE A UNA VECCHIA SIGNORA E IO VI DARÒ UNA BELLA BATTERIA.")
  (1198)
  )

("bird-lady-reminder-1"
  (56 "ORNITOLOGA" "OH, CIAO RAGAZZI. AVETE GIÀ TROVATO L'UOVO AZZURRO SULLA SCOGLIERA?")
  (208)
  (211 "ORNITOLOGA" "SE RIUSCITE A SPINGERLO GIÙ DAL BORDO IO VI DARÒ UNA BATTERIA.")
  (348)
  )

("bird-lady-reminder-2"
  (58 "ORNITOLOGA" "EHI, STATE ANCORA BIGHELLONANDO QUI ATTORNO? AH AH AH AH!")
  (170)
  (174 "ORNITOLOGA" "SCOMMETTO CHE QUEL POVERO OVETTO AZZURRO SULLA SCOGLIERA SARÀ GIÀ CONGELATO!")
  (313)
  (316 "ORNITOLOGA" "SALVATELO SPINGENDOLO OLTRE IL BORDO DELLA SCOGLIERA E IO VI REGALERÒ UNA BELLA BATTERIA.")
  )

("mayor-introduction"
  (31 "MAYOR" "NO... (MUTTERS) DON'T TELL ME THAT YOU TWO HAVE PROBLEMS AS WELL!")
  (171)
  (174 "MAYOR" "FIRST I HEAR OF MONSTER SIGHTINGS NEAR THE VILLAGE, AND NOW THIS.")
  (313)
  (320 "MAYOR" "SEE THOSE GEARS UP THERE, BOYS? SEE THEM? SEE HOW THEY'RE NOT MOVING?")
  (479 "MAYOR" "THAT MEANS OUR VILLAGE HAS NO POWER!")
  (569)
  (578 "MAYOR" "THE ECO BEAM COMING FROM THE JUNGLE TEMPLE HAS BEEN INTERRUPTED!")
  (685)
  (689 "MAYOR" "AND BOYS, EVERYONE'S TOO FRIGHTENED TO GO OUT AND FIND OUT WHAT'S HAPPENED.")
  (850)
  (864 "DAXTER" "DID YOU PAY THE BILL?")
  (915)
  (917 "MAYOR" "YEAH-HMM? OH-HUH-OH, YOU'RE FUNNY.")
  (1071)
  (1074 "MAYOR" "NOW LOOK, IF YOU TWO FIX THE ECO BEAM, I'LL GIVE YOU A POWER CELL.")
  (1262 "MAYOR" "OH OOH OOH AND-AND ANOTHER THING, UH...")
  (1346 "MAYOR" "IF BY ANY CHANCE YOU'RE INTERESTED IN MAKING A CONTRIBUTION TO MY RE-ELECTION CAMPAIGN,")
  (1551 "MAYOR" "I-I MIGHT BE WILLING TO PART WITH YET ANOTHER POWER CELL!")
  (1668)
  (1671 "MAYOR" "THE MINIMUM CONTRIBUTION IS, OH, A VERY MODEST...")
  (1797 "MAYOR" "90 PRECURSOR ORBS.")
  )

("mayor-reminder-beams"
  (25 "MAYOR" "BACK ALREADY? AND WITHOUT FIXING THE ECO BEAMS?")
  (157 "MAYOR" "(SOBS) YOUR VILLAGE NEEDS YOU, BOYS!")
  )

("mayor-reminder-donation"
  (26 "MAYOR" "AH, HERE TO MAKE A DONATION TO MY CAMPAIGN, OH HO HO HO.")
  (159 "MAYOR" "90 PRECURSOR ORBS BUYS YOU A POWER CELL, THANK YOU.")
  )

("mayor-resolution-beams"
  (28 "MAYOR" "OH HO HO, WHAT A WONDERFUL SIGHT! I THANK YOU!")
  (205 "MAYOR" "AND THE ENTIRE VILLAGE WILL THANK ME -")
  (269 "MAYOR" "UH, BOYS, YOU HAVE RESTORED POWER TO THE VILLAGE AND GUARANTEED MY RE-ELECTION!")
  (472)
  (475 "MAYOR" "AND FOR THAT, MY BOY, YOU'VE EARNED A POWER CELL.")
  )

("mayor-resolution-donation"
  (28 "MAYOR" "SO EH, YOU UH, WANNA MAKE A CONTRIBUTION? GOOD... A-A-A SIZABLE ONE I HOPE.")
  (219)
  (224 "MAYOR" "YOOH! EH HE HE, IT'S A, OH, THIS IS A SIZABLE CONTRIBUTION!")
  (365 "MAYOR" "I, WH-WH-WH-WHY I JUST HOPE THIS POWER CELL ADEQUATELY REPRESENTS MY GRATITUDE.")
  )

("sagevb01" :hint #x288
  (0 "SAMOS" "WELL, I SEE THAT YOU TWO HAVE FINALLY DECIDED TO UNBLOCK MY COLLECTORS.")
  (347)
  (352 "SAMOS" "I WOULD OFFER MY CONGRATULATIONS, BUT YOU HAVE SO MUCH TO DO I WON'T WASTE YOUR TIME.")
  (705)
  (712 "SAMOS" "BY THE WAY, IF THINGS DON'T WORK OUT,")
  (884 "SAMOS" "DAXTER COULD ALWAYS GET A JOB CONTROLLING THE VILLAGE RAT PROBLEM.")
  (1116 "SAMOS" "NYEH HA HA HA HA.")
  )

("sculptor-introduction"
  (30 "SCULTORE" "EHI... ESSERINO PELOSO!")
  (154)
  (161 "SCULTORE" "AWW... PER UN ATTIMO AVEVO PENSATO CHE FOSSI LA MIA MUSA.")
  (282)
  (285 "DAXTER" "LA TUA COSA?")
  (334)
  (343 "SCULTORE" "NON AVETE MAI VISTO UNA MUSA PRIMA D'ORA?")
  (430)
  (434 "SCULTORE" "È UNA SPECIE DI SCOIATTOLINA LUMINOSA GRANDE COSÌ, PIENA DI CORAGGIO E MATTA COME UNA CAVALLA!")
  (622)
  (632 "DAXTER" "AAAH, CERTO HO CAPITO! SAREBBE UNA SPECIE DI AMICONE.")
  (757)
  (763 "SCULTORE" "SE DEVO DIRE IL VERO, SENZA LA MIA CARA MUSA, NON RIESCO PIÙ A SCOLPIRE NIENTE.")
  (920)
  (923 "SCULTORE" "MA QUANDO LEI È QUI CON ME... AH-HA! VEDO LA BELLEZZA IN OGNI COSA, SAPETE?")
  (1087)
  (1091 "SCULTORE" "ORA INVECE NON FAREI DI CESELLO NEANCHE A UNA SCATOLA.")
  (1182)
  (1191 :offscreen "SCULTORE" "CREDO SIA SCAPPATA ALL'ISOLA DELLA NEBBIA.")
  (1278)
  (1281 "SCULTORE" "AHH, SPERO SOLO STIA BENE.")
  (1370)
  (1376 "SCULTORE" "VI DARÒ UNA BATTERIA SE ME LA RIPORTATE!")
  (1441)
  (1467 "DAXTER" "EHI UN MOMENTO! *NOI* NON ABBIAMO NESSUNA INTENZIONE DI RITORNARE SULL'ISOLA DELLA NEBBIA!")
  (1646)
  (1649 "DAXTER" "DICO BENE?")
  )

("sculptor-reminder-1"
  (27 "SCULTORE" "AH! ALLORA, RAGAZZI! ... AVETE GIÀ TROVATO LA MIA MUSA?")
  (169)
  )

("sculptor-resolution"
  (87 "SCULTORE" "OH, LA MIA MUSA! L'AVETE SALVATA! AAH, SIETE DAVVERO STUPENDI!")
  (230 "SCULTORE" "ECCO, PRENDETE UNA BATTERIA. NON MI SERVE PIÙ, ORA HO RITROVATO L'ISPIRAZIONE!")
  )

("sksp0019" :hint #x236
  (0 "DAXTER" "EHI, DEI GABBIANI! AVANTI, INSEGUIAMOLI!")
  )

("sksp0020" :hint #x268
  (0 "DAXTER" "YAAH HA HA! FACCIAMOLO DI NUOVO!")
  )

("sksp0022" :hint #x26a
  (0 "DAXTER" "YEAH HA HA HA HA HA!! WOO HO HO HO!")
  )

("sksp0023" :hint #x26b
  (0 "DAXTER" "WOOHOO!")
  )

("sksp0024" :hint #x26c
  (0 "DAXTER" "YEAH HA HA! YEAH!")
  )

("sksp0025" :hint #x273
  (0 "DAXTER" "UAO! HANNO PROVOCATO UNA SLAVINA! SU, ANDIAMO A VEDERE!")
  )

("sksp0026" :hint #x237
  (0 "DAXTER" "EHI! QUEL DANNATO PELLICANO HA APPENA PRESO UNA BATTERIA!")
  (197)
  (200 "DAXTER" "ANDIAMO A DARE UNA BELLA BATTUTA AL SUO GROSSO SEDERE!")
  )

("sksp0027" :hint #x274
  (0 "DAXTER" "SPICCIATI! DOBBIAMO PRENDERE LA BATTERIA PRIMA CHE IL PELLICANO LA RACCOLGA DI NUOVO!")
  )

("sksp0029" :hint #x275
  (0 "DAXTER" "EH, POTREMMO PARLARE CON LA VECCHIA SIGNORA")
  (125 "DAXTER" "E VEDERE SE ABBIAMO ROTTO L'UOVO DEL FLUT FLUT.")
  )

("sksp0030" :hint #x239
  (0 "DAXTER" "EHI, PER SPOSTARE LE ROCCE, PROVA A COLPIRLE CON UN PUGNO!")
  )

("sksp0034" :hint #x23b
  (0 "DAXTER" "AHOOGA! AHOOGA! TUFFATI PER PRENDERE QUELLE UOVA JAK, TUFFATI!")
  )

("sksp0443" :hint #x2af
  (0 "DAXTER" "COLPISCI QUEI PALI CON UN PUGNO DAL BASSO!")
  )

;; -----------------
;; jungle
;; -----------------

("FIS-AM01" :hint #x0
  (0 "PESCATORE" "GRR, DANNATI PESCI... NON RIUSCIRÒ A PRENDERNE NEANCHE UNO.")
  )

("FIS-AM02" :hint #x0
  (0 "PESCATORE" "QUEI MOSTRI CHE MI HANNO MORSO LA BARCA MI MANDERANNO IN ROVINA.")
  )

("FIS-AM03" :hint #x0
  (0 "PESCATORE" "DANNATE CANAGLIE!")
  (135 "PESCATORE" "QUI NEL CESTO, MALEDETTI PESCI, QUI DOVETE VENIRE...")
  (419)
  (425 "PESCATORE" "HEH HE HE HE HE...")
  )

("FIS-AM04" :hint #x0
  (0 "PESCATORE" "AAH, COME MI PIACE IL PROFUMO DEL PESCE LA MATTINA...")
  )

("FIS-AM05" :hint #x0
  (0 "PESCATORE" "MMH, COME MI MANGEREI DELLE BELLE CODE DI PESCE SOTTO SALE...")
  )

("FIS-AM06" :hint #x0
  (0 "PESCATORE" "MI RICORDO ANCORA QUELLO GROSSO CHE È SCAPPATO...")
  )

("FIS-LO01" :hint #x0
  (0 "PESCATORE" "GRR!")
  )

("FIS-LO03" :hint #x0
  (0 "PESCATORE" "HA HA HA HA HA HAH!")
  )

("FIS-LO04" :hint #x0
  (0 "PESCATORE" "DANNATI PESCI! NON ENTRANO MAI NELLA MIA RETE!")
  )

("FIS-LO05" :hint #x0
  (0 "PESCATORE" "HA HA HA AH HA HA HA HAH!")
  )

("FIS-TA01" :hint #x0
  (0 "PESCATORE" "A SINISTRA!")
  )

("FIS-TA02" :hint #x0
  (0 "PESCATORE" "VAI A DESTRA!")
  )

("FIS-TA03" :hint #x0
  (0 "PESCATORE" "NE ARRIVA UNO GROSSO!")
  )

("FIS-TA04" :hint #x0
  (0 "PESCATORE" "NE HAI MANCATO UNO ENORME!")
  )

("FIS-TA05" :hint #x0
  (0 "PESCATORE" "NON PERDERNE UN ALTRO DI QUELLI!")
  )

("FIS-TA06" :hint #x0
  (0 "PESCATORE" "FERMA...")
  )

("FIS-TA07" :hint #x0
  (0 "PESCATORE" "HAI LE VELE AFFLOSCIATE, FIGLIOLO.")
  )

("FIS-TA08" :hint #x0
  (0 "PESCATORE" "ARGH! MANCATO.")
  )

("FIS-TA09" :hint #x0
  (0 "PESCATORE" "MI SA CHE TI CI VUOLE UNA RETE PIÙ GROSSA...")
  )

("FIS-TA10" :hint #x0
  (0 "PESCATORE" "MANCATO DI NUOVO!")
  )

("FIS-TA11" :hint #x0
  (0 "PESCATORE" "FERMA! CI SEI QUASI...")
  )

("FIS-TA1A" :hint #x0
  (0 "PESCATORE" "SINISTRA!")
  )

("FIS-TA2A" :hint #x0
  (0 "PESCATORE" "DESTRA!")
  )

("asstvb02" :hint #x289
  (0 "KEIRA" "WOW, HAI VISTO? HAI APERTO I CAMINI DI VENTILAZIONE DELL'ECO BLU DI TUTTO IL MONDO!")
  (305)
  (315 "KEIRA" "SAPEVO CHE C'ERA UN MODO PER FARLO!")
  (435)
  (442 "KEIRA" "DEVONO ESSERCI LUOGHI NEI QUALI È POSSIBILE APRIRE TUTTI GLI ALTRI CAMINI DI VENTILAZIONE.")
  )

("fisher-accept"
  (0 :offscreen "PESCATORE" "È CHE CI SONO DUE TIPI DI PESCE BUONO: I PESCI DA UN CHILO, E I PESCI DA CINQUE CHILI.")
  (220 :offscreen "PESCATORE" "SE TI LASCI SCAPPARE 20 CHILI DI PESCE BUONO, MI RIPRENDO LA RETE!")
  (432)
  (438 :offscreen "PESCATORE" "IN QUESTO FIUME CI SONO ANGUILLE VELENOSE.")
  (542)
  (545 :offscreen "PESCATORE" "PRENDI ANCHE SOLO UNA DI QUELLE DISGRAZIATE, E TI AVVELENERÀ TUTTI I PESCI CHE HAI GIÀ PRESO! AHAHAHAHAH!")
  )

("fisher-introduction"
  (0 "DAXTER" "SCUSA, COS'HAI NEL CESTINO?")
  (50 "PESCATORE" "OH BEH, C'È POCO DA DIRE.")
  (103)
  (106 "PESCATORE" "QUEI MOSTRI CHE GIRANO PER L'OCEANO MI HANNO STACCATO A MORSI UN PEZZO DI BARCA,")
  (226)
  (229 "PESCATORE" "E ORA SI INGOZZANO CON I MIEI PESCI!")
  (290)
  (293 "PESCATORE" "LE HO PROVATE TUTTE, MA IN QUESTO FIUME NON RIESCO A PIGLIARE NEANCHE UN PESCE!")
  (419)
  (425 "DAXTER" "OHH! NON SARÀ... COLPA DEL TUO ALITO?")
  (515)
  (521 "PESCATORE" "PENSI DI POTER FARE MEGLIO? PROVA TU A PESCARE IN UN FIUME CON UNA RETE PICCOLISSIMA!")
  (665)
  (671 "PESCATORE" "TI REGALERÒ UNA BATTERIA SE RIUSCIRAI A PRENDERE 200 CHILI DI PESCE!")
  (808)
  (814 "PESCATORE" "GUARDA, A TE E AL TUO AMICO PRESTERÒ LA MIA BARCA PIÙ VELOCE PER ANDARE ALL'ISOLA DELLA NEBBIA.")
  (955)
  (961 "PESCATORE" "ALLORA, TI INTERESSA LA SFIDA?")
  )

("fisher-reject"
  (2 "PESCATORE" "EHI TU, SE TI VIENE VOGLIA DI PROVARE A GUADAGNARTI LA BATTERIA, SAI DOVE POTRAI TROVARMI.")
  )

("fisher-reminder-1"
  (6 "PESCATORE" "ALLORA, PERCHÉ NON PROVI A BATTERE IL FIUME?")
  )

("fisher-resolution"
  (0 "PESCATORE" "CE L'AVETE FATTA! AVETE PRESO 200 CHILI DI PESCE!")
  (115)
  (120 "PESCATORE" "NIENTE MALE PER DUE NOVELLINI!")
  (185)
  (199 "PESCATORE" "ECCO LA BATTERIA CHE AVEVO PROMESSO, E POTETE USARE LA MIA BARCA QUANDO VOLETE!")
  (351 "PESCATORE" "È ANCORATA AL PORTO.")
  )

("sksp0011" :hint #x240
  (0 "DAXTER" "DOVREMMO CHIEDERE AL PESCATORE CHE SI TROVA VICINO AL FIUME CHE COSTEGGIA LA GIUNGLA")
  (136 "DAXTER" "SE CI PRESTA LA SUA BARCA PER VOLAAARE VERSO L'ISOLA DELLA NEBBIA!")
  )

("sksp0018" :hint #x25e
  (0 "DAXTER" "DOVREMMO DIRE A QUEL FANFARONE DEL SINDACO CHE È IN DEBITO CON NOI")
  (223 "DAXTER" "PER AVER RIATTIVATO I RAGGI ENERGETICI DEL VILLAGGIO!")
  )

("sksp0037" :hint #x25f
  (0 "DAXTER" "QUESTE TORRI SPARSE PER TUTTA LA GIUNGLA SERVONO A RIFLETTERE GLI ECO-RAGGI!")
  (214)
  (220 "DAXTER" "ANDIAMO A DIVERTIRCI UN PO'!")
  )

("sksp0038" :hint #x23c
  (0 "DAXTER" "MMH, SE L'ECO BLU PUÒ ESSERE USATO PER COSTRUIRE UN PONTE, SCOMMETTO CHE PUÒ ANCHE APRIRE UNA PORTA.")
  (275)
  (281 "DAXTER" "TORNIAMO INDIETRO PER RICARICARTI.")
  )

("sksp0039" :hint #x25b
  (0 "DAXTER" "EHI, CI SONO DEI PICCOLI SEGNI LUMINOSI SU QUEI CARTELLI,")
  (202 "DAXTER" "E C'È ANCHE UNA LUCE CHE ESCE DA QUEL CONDOTTO!")
  (391)
  (400 "DAXTER" "STAI PENSADO QUELLO CHE PENSO IO...?")
  )

("sksp0040" :hint #x23d
  (0 "DAXTER" "SALIAMO SU QUELLA MACCHINA E ROMPIAMO LO SPECCHIO CHE DEVIA IL RAGGIO PRECURSOR!")
  )

("sksp0041" :hint #x23e
  (0 "DAXTER" "DOBBIAMO RAGGIUNGERE LA CIMA DI QUELLA TORRE!")
  )

("sksp0049" :hint #x29c
  (0 "DAXTER" "ALLINEA IL RAGGIO INDIRIZZANDOLO VERSO LA TORRE SUCCESSIVA!")
  )

("sksp0050" :hint #x29d
  (0 "DAXTER" "ROMPI LO SPECCHIO, JAK!")
  )

("sksp0051" :hint #x29e
  (0 "DAXTER" "PRENDI GLI INSETTI, JAK! PRENDI GLI INSETTI!")
  )

("sksp0052" :hint #x29f
  (0 "DAXTER" "ANDIAMO ALLA PROSSIMA TORRE E RICOLLEGHIAMO IL RAGGIO!")
  )

("sksp0053" :hint #x2a0
  (0 "DAXTER" "MMH! POSSIAMO SEGUIRE IL RAGGIO PER TROVARE LA PROSSIMA TORRE.")
  )

("sksp0054" :hint #x2a1
  (0 "DAXTER" "TI DEVI CARICARE CON QUELLA COSA BLU PER RIUSCIRE AD APRIRLA!")
  )

("sksp0b42" :hint #x278
  (0 "DAXTER" "SMETTILA DI LASCIARTI SCAPPARE I PESCI GIALLI! PESANO 5 LIBBRE OGNUNO! NON SONO NIENTE MALE, JAK.")
  )

;; -----------------
;; misty
;; -----------------

("asstvb03" :hint #x28b
  (0 "KEIRA" "BENE! AVETE BLOCCATO TUTTE LE MINE!")
  (190 "KEIRA" "PER SETTIMANE SONO STATE UNA MINACCIA PER LE ACQUE INTORNO AL NOSTRO VILLAGGIO.")
  (391 "KEIRA" "RIPORTATE LO ZOOMER AL TRANS-PAD, COSÌ LO TELETRASPORTERÒ INDIETRO!")
  )

("sagevb02" :hint #x28a
  (6 "SAMOS" "DEVO AMMETTERLO: SONO IMPRESSIONATO. NON MI AVETE DELUSO!")
  (385)
  (400 "SAMOS" "ORA CHE I LURKER NON POSSONO APRIRE IL SILOS, NON POTRANNO NEMMENO INFESTARE IL MONDO CON L'ECO OSCURO")
  (710 "SAMOS" "E CAUSARNE LA DISTRUZIONE.")
  (863)
  (880 "SAMOS" "MA ORA TOGLITI QUEL GHIGNO DALLA FACCIA, DAXTER! VOI DUE AVETE MOLTE COSE DA FARE.")
  (1191 "SAMOS" "MUOVETEVI!")
  )

("sksp0031" :hint #x23a
  (0 "DAXTER" "UUH! USIAMO IL CANNONE PER FAR SALTARE TUTTO IN ARIA!")
  )

("sksp0056" :hint #x27b
  (0 "DAXTER" "UAO! VEDO LA MUSA DELLO SCULTORE!")
  )

("sksp0059" :hint #x26e
  (0 "DAXTER" "QUESTO POSTO MI SPAVENTA... STIAMO LONTANI DAL FANGO, OK?")
  )

("sksp0060" :hint #x26f
  (0 "DAXTER" "AGH, QUESTO POSTO MI FA VENIRE I BRIVIDI! E CREDIMI, È UN'ESPERIENZA NUOVA")
  (337 "DAXTER" "SE SEI RICOPERTO... DI PELO!")
  )

("sksp0062" :hint #x27e
  (0 "DAXTER" "COLPIAMO E DISTRUGGIAMO I PALLONI DEI LURKER!")
  )

("sksp0063" :hint #x27f
  (0 "DAXTER" "HO DETTO DI DISTRUGGERE I PALLONI, JAK, NON LE MINE!")
  (332)
  (344 "DAXTER" "REGOLA NUMERO UNO: EVITA SEMPRE LE MINE!")
  )

("sksp0064" :hint #x245
  (0 "DAXTER" "GUARDATI ALLE SPALLE! TI RICORDI COS'È SUCCESSO L'ULTIMA VOLTA CHE SIAMO STATI QUI?")
  )

("sksp0067" :hint #x249
  (0 "DAXTER" "NON CADERE NELLA NEBBIA!! ANCHE PERCHÉ NON PENSO CHE RIUSCIREMMO AD USCIRNE.")
  )

("sksp0069" :hint #x2a3
  (0 "DAXTER" "È UN'IMBOSCATA, JAK! È UN'IMBOSCATA!")
  )

("sksp0070" :hint #x2a4
  (0 "DAXTER" "TUFFATI IN SALTO SU QUELLA BOLLA INSTABILE.")
  )

("sksp0435" :hint #x2aa
  (0 "DAXTER" "COLPISCI QUELLE OSSA!")
  )

;; -----------------
;; firecanyon
;; -----------------

("assistant-firecanyon-resolution"
  (25 "KEIRA" "GREAT! YOU HAVE THE 20 CELLS NEEDED TO POWER MY HEAT SHIELD!")
  (140)
  (143 "KEIRA" "NOW BE CAREFUL, THE SHIELD WILL ONLY PROTECT YOUR ZOOMER TILL IT REACHES 500 DEGREES,")
  (295 "KEIRA" "SO TRY TO KEEP HER COOL.")
  (343)
  (346 :offscreen "KEIRA" "FLYING OVER OPEN LAVA WILL DEFINITELY HEAT YOU UP FAST.")
  (458)
  (462 "KEIRA" "HIT 500 DEGREES, AND IT'S OVER.")
  (546)
  (552 "DAXTER" "OVER?! LIKE BURNING MOLTEN METAL OVER?!")
  (636)
  (639 "KEIRA" "THE FIRE CANYON GETS PRETTY HOT, SO KEEP A LOOK OUT FOR JUMPS")
  (745 "KEIRA" "TO KEEP YOU OFF THE HOT GROUND.")
  (792)
  (795 :offscreen "KEIRA" "I'VE ALSO RELEASED SEVERAL BLUE COOLING BALLOONS YOU CAN USE TO DROP")
  (895 :offscreen "KEIRA" "THE SHIELD'S TEMPERATURE QUICKLY.")
  (956)
  (962 "KEIRA" "OH! AND WHEN YOU GET ACROSS, DON'T FORGET TO ACTIVATE")
  (1063 "KEIRA" "THE TELEPORT GATE IN THE BLUE SAMOS'S LAB.")
  (1140)
  (1146 "KEIRA" "THEN WE'LL BE ABLE TO TELEPORT OVER AND MEET YOU!")
  (1222)
  (1228 "KEIRA" "GOOD LUCK!")
  )

("asstvb09" :hint #x24f
  (0 "KEIRA" "NON AVETE ABBASTANZA BATTERIE PER ALIMENTARE IL MIO SCUDO TERMICO.")
  (216)
  (234 "KEIRA" "NON POTETE ATTRAVERSARE IL CANYON DEL FUOCO FINCHÉ NON TROVATE 20 BATTERIE.")
  )

("sksp0076" :hint #x501
  (0 "DAXTER" "AVANTI, JAK! IL TERRENO È DANNATAMENTE CALDO, SALTA!")
  )

("sksp0077" :hint #x502
  (0 "DAXTER" "PALLONI BUONI; MAGMA CALDO CATTIVO!")
  )

("sksp0078" :hint #x503
  (0 "DAXTER" "STAI SUL PONTE PRECURSOR PER NON ESSERE FERITO.")
  )

("sksp0079" :hint #x504
  (0 "DAXTER" "AAH! STO MORENDO! STO ARRIVANDO, NONNO!")
  (257)
  (270 "DAXTER" "DEVI PORTARE QUESTA COSA DALL'ALTRA PARTE PRIMA CHE SI SURRISCALDI!")
  )

("sksp0080" :hint #x505
  (0 "DAXTER" "PER STERZARE DI PIÙ, CURVA MENTRE VOLI!")
  )

("sksp0081" :hint #x506
  (0 "DAXTER" "GAAH! POTREI GUIDARE IO?!")
  )

("sksp0082" :hint #x507
  (0 "DAXTER" "STAI PROVANDO A EVITARE LE SCATOLE DI ECO OSCURO, VERO?")
  )

("sksp0083" :hint #x508
  (0 "DAXTER" "UHUH! VEDIAMO SE RIUSCIAMO A SALTARE SOPRA A QUEL LURKER!")
  )

("sksp0084" :hint #x509
  (0 "DAXTER" "TROPPO VICINO, TROPPO VICINO!!")
  )

("sksp0085" :hint #x50a
  (0 "DAXTER" "WOW! QUESTA BAMBOLA SI STA SURRISCALDANDO!")
  )

("sksp0086" :hint #x50b
  (0 "DAXTER" "ANCORA POCHI SECONDI E SAREMO UN FLUT FLUT FRITTO!")
  )

("sksp0087" :hint #x50d
  (0 "DAXTER" "COLPISCI QUEI PALLONI PER ABBASSARE LA TEMPERATURA!")
  )

("sksp0088" :hint #x50e
  (0 "DAXTER" "ARRIVA UN ALTRO PALLONE!")
  )

("sksp0089" :hint #x50f
  (0 "DAXTER" "AVREI DOVUTO RIMANERE A DORMIRE QUESTA MATTINA!")
  )

("sksp0090" :hint #x510
  (0 "DAXTER" "HAI MANCATO UN PALLONE! CERCA DI COLPIRLI, O FINIREMO FRITTI!")
  )

("sksp0091" :hint #x511
  (0 "DAXTER" "QUESTO COSO STA DIVENTANDO TROPPO CALDO!")
  )

("sksp0092" :hint #x512
  (0 "DAXTER" "SENTI PUZZA DI BRUCIATO?")
  )

("sksp0093" :hint #x513
  (0 "DAXTER" "LA MIA CODA È IN FIAMMEEE!")
  )

("sksp0094" :hint #x514
  (0 "DAXTER" "ESPLODERÀ!")
  )

("sksp0095" :hint #x515
  (0 "DAXTER" "YA-HAA! CI SIAMO RIUSCITI!")
  )

("sksp0096" :hint #x516
  (0 "DAXTER" "ANCHE QUI CI SONO DELLE MOSCHE SCOUT!")
  )

;; -----------------
;; swamp
;; -----------------

("billy-accept"
  (5 "BILLY" "GOOD! THOSE RATS WILL BE BACK ANYTIME.")
  (109 "BILLY" "SHOOT ALL THEM RATS, AND KEEP 'EM FROM EATING AT LEAST ONE OF THEM SNACKS.")
  )

("billy-introduction"
  (6 "BILLY" "HOWDY, FRIENDS! ENJOYIN' MY BEAUTIFUL SWAMP? I OWN THESE HERE PARTS. EVERYTHING THAT DOESN'T SINK INTO THE MUD, THAT IS! HA HA HA...")
  (349)
  (369 "DAXTER" "JUDGING BY THE SMELL, I'D WAGER YOUR BATHTUB SANK IN THE MUD LONG AGO.")
  (497)
  (519 "BILLY" "WHAT'S A BATHTUB? ANYWAY I GOT BIGGER PROBLEMS NOW...")
  (677)
  (691 "BILLY" "SEEMS SOME NASTY LURKER VARMINTS ARE GROUSIN' ABOUTS SNATCHIN' EVERYTHING THEY CAN GET THEIR GRUBBY LITTLE PAWS ON.")
  (910 "BILLY" "AND SCARED AWAY MY PET HIPHOG, FARTHY.")
  (1000 "BILLY" "HE'S BEEN MISSIN' FOR NIGH ON TO A COON'S AGE.")
  (1136 :offscreen "BILLY" "I'VE BEEN PUTTIN' OUT HIS FAVORITE SNACK, BUT THOSE ORNERY SWAMP RATS KEEP STEALIN' EM!")
  (1318 :offscreen "BILLY" "IF YOU COULD KEEP THOSE PESKY CRITTERS AWAY LONG ENOUGH, I JUST KNOW FARTHY WOULD SMELL THEM VITTLES AND COME BACK!")
  (1509)
  (1527 "BILLY" "WILL YA HELP ME OUT?")
  )

("billy-reject"
  (7 "BILLY" "WELL, IF YOU CHANGE YOUR MIND, YOU KNOW WHERE TO FIND ME! (LAUGHS)")
  )

("billy-reminder-1"
  (36 "BILLY" "AHH, Y'ALL BACK TO HELP STOP THEM RATS?")
  )

("billy-resolution"
  (1 "BILLY" "WELL FRY MY HIDE! YOU SURE KNOW HOW TO SHOOT! THANKS A HEAP FOR THE HELP.")
  )

;; -----------------
;; citadel
;; -----------------

("BLU-AM01" :hint #x0
  (0 "SAGGIO BLU" "UN PO' DI AIUTO SAREBBE UTILE!")
  )

("BLU-AM02" :hint #x0
  (0 "SAGGIO BLU" "AH, QUESTO È UN BEL GUAIO.")
  )

("BLU-AM03" :hint #x0
  (0 "SAGGIO BLU" "MMH, CI TROVIAMO DI FRONTE A UN BELL'ENIGMA.")
  )

("RED-AM01" :hint #x0
  (0 "SAGGIO ROSSO" "C'È NESSUNO?")
  )

("RED-AM02" :hint #x0
  (0 "SAGGIO ROSSO" "BENE...")
  )

("RED-AM03" :hint #x0
  (0 "SAGGIO ROSSO" "COSA VI HA TRATTENUTO?")
  )

("YEL-AM01" :hint #x0
  (0 "SAGGIO GIALLO" "IL TEMPO STA PER SCADERE!")
  )

("YEL-AM02" :hint #x0
  (0 "SAGGIO GIALLO" "EHI! PORTATEMI FUORI DI QUI!")
  )

("YEL-AM03" :hint #x0
  (0 "SAGGIO GIALLO" "QUANDO SARÒ FUORI DI QUI, INIZIERÀ UNA SPARATORIA!")
  )

("bluesage-resolution"
  (63 "SAGGIO BLU" "GRAN BEL LAVORO, RAGAZZI! SAMOS AVEVA RAGIONE SU DI VOI!")
  (162)
  (165 "SAGGIO BLU" "GIÀ, BELL'AMMASSO DI METALLO PRECURSOR!")
  (253 "SAGGIO BLU" "QUELLA PERICOLOSA CREATURA MECCANICA NON DOVRÀ MAI RIUSCIRE A SPRIGIONARE IL SUO TERRIBILE POTERE!")
  (420 "SAGGIO BLU" "QUINDI, PROVERÒ A METTERE IN FUNZIONE LO SCUDO, CREANDO UN CONDOTTO D'ENERGIA")
  (554 "SAGGIO BLU" "TRA ME E L'ENORME VARCO CHE SI TROVA AL DI SOTTO DI ESSA!")
  (677 "DAXTER" "AH... BRAVO. CE L'HAI FATTA. ALLORA NOI... ANDIAMO SUBITO A CERCARE AIUTO.")
  (873)
  (899 :offscreen "DAXTER" "MOLTO STRANO...")
  (980)
  )

("green-sagecage-introduction"
  (134 "SAMOS" "ERA ORA CHE VI FACESTE VIVI!")
  (216 "DAXTER" "ANCHE NOI SIAMO FELICI DI VEDERTI. TI HANNO MESSO A PULIRE PER TERRA ORA?")
  (350 "SAMOS" "NON È IL MOMENTO DI SCHERZARE, DAXTER. GOL E MAIA CI HANNO RAPITO")
  (477 "SAMOS" "PER ASSORBIRE LE NOSTRE ENERGIE E DARE POTENZA ALLA LORO TERRIBILE MACCHINA.")
  (574)
  (610 :offscreen "SAMOS" "SEMBRA CHE ABBIANO MONTATO CIÒ CHE RIMANEVA DI UN ROBOT PRECURSOR")
  (721 :offscreen "SAMOS" "CON ALCUNI MANUFATTI TROVATI SCAVANDO NELLA ZONA.")
  (800)
  (812 :offscreen "SAMOS" "E CHE QUINDI ABBIANO AGGIUNTO ALTRE DIAVOLERIE CREATE DA LORO,")
  (921 :offscreen "SAMOS" "DANDO VITA AD UN MOSTRO IN GRADO DI APRIRE I SILOS DELL'ECO OSCURO.")
  (1070 "SAMOS" "SE RIESCI A LIBERARCI TUTTI E QUATTRO, POTREMO UNIRE I NOSTRI POTERI")
  (1189 "SAMOS" "E DISTRUGGERE LO SCUDO ENERGETICO INTORNO AL ROBOT, PRIMA CHE POSSANO DISTRUGGERE IL MONDO.")
  )

("green-sagecage-outro-preboss"
  (75 "GOL" "SEI ARRIVATO TROPPO TARDI, SAMOS.")
  (173 "GOL" "QUANDO AVRÒ UNA QUANTITÀ ILLIMITATA DI ECO OSCURO, ANCHE LA CHIAVE DELLA CREAZIONE SARÀ MIA!")
  (335 "SAMOS" "MA QUESTA È UNA FOLLIA! LIBERARE COSÌ TANTO ECO OSCURO DISTRUGGERÀ TUTTO CIÒ CHE CONOSCIAMO!")
  (519 "SAMOS" "CONSIDERA BENE QUELLO CHE È SUCCESSO A TE!")
  (578)
  (583 "MAIA" "CI HA DATO UNA BELLEZZA SUPERIORE A TUTTO CIÒ CHE VOI POTETE CAPIRE.")
  (693)
  (704 "DAXTER" "BELLEZZA? VI SIETE GUARDATI BENE ALLO SPECCHIO DI RECENTE?!")
  (825)
  (834 "MAIA" "ASPETTA FINO A QUANDO NON AVREMO APERTO TUTTI I SILOS, PICCOLETTO! TU CHE NE DICI, TI VA BENE BASSO E PELOSO?")
  (1043 "GOL" "E PENSARE, CHE VOI DUE SIETE ARRIVATI FIN QUI PER CERCARE IL MIO AIUTO.")
  (1190 "GOL" "PAZZI! DIVERTITEVI CON UN POSTO IN PRIMA FILA NELLA NUOVA CREAZIONE DEL MONDO!")
  (1391)
  (1609 "SAMOS" "JAK! SALI SULL'ASCENSORE, PRESTO! E FERMA SUBITO QUEL ROBOT!")
  )

("green-sagecage-resolution"
  (45 "SAMOS" "BEL LAVORO, RAGAZZI! ORA SIETE DEI VERI EROI.")
  (172 "SAMOS" "UNIRÒ I POTERI DELL'ECO VERDE CON QUELLI DEGLI ALTRI TRE SAGGI")
  (283 "SAMOS" "PER APRIRE UN VARCO NELLA BARRIERA ENERGETICA INTORNO AL ROBOT PRECURSOR.")
  (415 "DAXTER" "SÌ SÌ MI SEMBRA UN BUON INIZIO.")
  (474 "DAXTER" "MA DOPO CHE AVRETE APERTO IL VARCO, CHE COSA PENSATE DI FARE AL ROBOT?")
  (584 "SAMOS" "NIENTE, DAXTER. NOI DOVREMO GIÀ TENERE LO SCUDO APERTO.")
  (720 "SAMOS" "ECCO... VI DOVRETE OCCUPARE VOI DI DISTRUGGERE IL ROBOT.")
  (836 "DAXTER" "OH, OTTIMO. DEVO AIUTARE IL TIPO CHE MI HA TRASFORMATO IN UNA PALLA DI PELO")
  (995 "DAXTER" "A DISTRUGGERE L'UNICA PERSONA IN GRADO DI FARMI TORNARE NORMALE!")
  (1111)
  (1172 "SAMOS" "PER PRIMA COSA SALVATE IL MONDO, POI CERCHEREMO DI CONVINCERE GOL AD AIUTARE DAXTER.")
  )

("redsage-resolution"
  (62 "SAGGIO ROSSO" "HEHEHEH, ALLA FINE SIETE ARRIVATI A SALVARMI.")
  (190 "SAGGIO ROSSO" "SAPETE DA QUANTO TEMPO SONO QUI? PERCHÉ CI AVETE IMPIEGATO TANTO? BENE... HEHEHEH")
  (378 "SAGGIO ROSSO" "DUNQUE, COME VI CHIAMATE?")
  (429)
  (443 "DAXTER" "IO SONO DAXTER. LUI È JAK. È CON ME.")
  (548 :offscreen "SAGGIO ROSSO" "BEL LAVORO, DAXTER. SEI UN VERO EROE!")
  (677)
  (711 "SAGGIO ROSSO" "ECCO, DEVI EVITARE CHE GOL LANCI IL SUO ROBOT.")
  (845 "SAGGIO ROSSO" "IO UTILIZZERÒ, VEDIAMO UN PO', IL MIO POTERE DELL'ECO PER APRIRE LO SCUDO.")
  )

("sksp0378" :hint #x813
  (0 "DAXTER" "LA PORTA È APERTA, ANDIAMO!")
  )

("sksp0381" :hint #x806
  (0 "DAXTER" "DISTRUGGI IL GENERATORE PER LIBERARE IL SAGGIO!")
  )

("sksp0382" :hint #x807
  (0 "DAXTER" "RIMANI ATTACCATO AL BORDO!")
  )

("sksp0383" :hint #x808
  (0 "DAXTER" "ABBIAMO COMPAGNIA, JAK. UN BEL PO' DI LURKERS!")
  )

("sksp0384" :hint #x809
  (0 "DAXTER" "DISTRUGGI QUEI GENERATORI!")
  )

("sksp0385" :hint #x80a
  (0 "DAXTER" "PREMI IL PULSANTE!")
  )

("sksp0386" :hint #x80b
  (0 "DAXTER" "QUEL ROBOT NON MI SPAVENTA!")
  )

("sksp0387" :hint #x80c
  (0 "DAXTER" "SALIAMO SU QUELLE PIATTAFORME!")
  )

("sksp0388" :hint #x80d
  (0 "DAXTER" "NON MANCARE IL PROSSIMO LANCIATORE!")
  )

("sksp0389" :hint #x80e
  (0 "DAXTER" "ATTENTO!")
  )

("sksp0390" :hint #x80f
  (0 "DAXTER" "DOBBIAMO LIBERARE TUTTI I SAGGI!")
  )

("sksp0391" :hint #x810
  (0 "DAXTER" "PENSI CHE GOL MI RITRASFORMERÀ LO STESSO?")
  )

("sksp0392" :hint #x811
  (0 "DAXTER" "ALLORA QUESTA È LA CITTADELLA DI GOL E MAIA. CARINA E GRADEVOLE.")
  )

("sksp0393" :hint #x812
  (0 "DAXTER" "ATTERRA SUL LANCIATORE SUCCESSIVO!")
  )

("yellowsage-resolution"
  (57 "SAGGIO GIALLO" "CHI POTEVA PENSARE CHE SAREI VISSUTO FINO A VEDERE")
  (152 "SAGGIO GIALLO" "IL GIORNO IN CUI SAREI STATO SALVATO DA UN RAGAZZO E DAL SUO TOPO MUSCHIATO!")
  (285 "SAGGIO GIALLO" "... MH, GLIELA FARÒ PAGARE A CARA A GOL E MAIA PER QUESTO MOMENTO A DIR POCO IMBARAZZANTE.")
  (471)
  (492 "SAGGIO GIALLO" "POI DECIDERÒ SE MANGIARE DEL BUON TOPO MUSCHIATO IN UMIDO...")
  (605)
  )

;; -----------------
;; finalboss
;; -----------------

("GOL-AM01" :hint #x0
  (0 "GOL" "MICA TI VORRAI ARRENDERE, VERO?")
  )

("GOL-AM02" :hint #x0
  (0 "GOL" "PRESTO, L'ECO OSCURO SARÀ NOSTRO!")
  )

("GOL-AM03" :hint #x0
  (0 "GOL" "FINISCILI!")
  )

("GOL-AM04" :hint #x0
  (0 "GOL" "FUOCO!")
  )

("GOL-AM05" :hint #x0
  (0 "GOL" "DISTRUGGILI!")
  )

("GOL-AM06" :hint #x0
  (0 "GOL" "COSA? ANCORA LORO!")
  )

("GOL-AM07" :hint #x0
  (0 "GOL" "È TROPPO TARDI!")
  )

("GOL-AM08" :hint #x0
  (0 "GOL" "SEI MIO!")
  )

("GOL-AM09" :hint #x0
  (0 "GOL" "ORA SEI MIO!")
  )

("GOL-AM10" :hint #x0
  (0 "GOL" "AH HA HA HA HA!")
  )

("GOL-AM11" :hint #x0
  (0 "GOL" "NESSUNA PIETÀ!")
  )

("GOL-AM12" :hint #x0
  (0 "GOL" "PRENDI QUESTO!")
  )

("GOL-AM13" :hint #x0
  (0 "GOL" "BEL TENTATIVO!")
  )

("GOL-AM14" :hint #x0
  (0 "GOL" "STAI FERMO!")
  )

("GOL-AM15" :hint #x0
  (0 "GOL" "SEI PATETICO!")
  )

("GOL-AM16" :hint #x0
  (0 "GOL" "NOOO!")
  )

("GOL-AM17" :hint #x0
  (0 "GOL" "AHHH!")
  )

("GOL-AM18" :hint #x0
  (0 "GOL" "APRIREMO IL SILOS, E VI FAREMO A PEZZI!")
  )

("GOL-AM19" :hint #x0
  (0 "GOL" "L'ECO LUMINOSO! MA ALLORA ESISTE!")
  )

("GOL-AM20" :hint #x0
  (0 "GOL" "NON RIUSCIREMO A PRENDERLO!")
  )

("MAI-AM01" :hint #x0
  (0 "MAIA" "FINISCILI, UNA VOLTA PER TUTTE!")
  )

("MAI-AM02" :hint #x0
  (0 "MAIA" "ELIMINALI!")
  )

("MAI-AM03" :hint #x0
  (0 "MAIA" "HA HA HA!")
  )

("MAI-AM04" :hint #x0
  (0 "MAIA" "L'ECO NON VI PROTEGGERÀ ORA!")
  )

("MAI-AM05" :hint #x0
  (0 "MAIA" "FA' QUALCOSA!")
  )

("MAI-AM06" :hint #x0
  (0 "MAIA" "AGH!")
  )

("MAI-AM07" :hint #x0
  (0 "MAIA" "NOOOOO!")
  )

("MAI-AM08" :hint #x0
  (0 "MAIA" "APRIREMO I SILOS E VI DISTRUGGEREMO ENTRAMBI!")
  )

("MAI-AM09" :hint #x0
  (0 "MAIA" "NON DEVONO RIUSCIRE A PRENDERLO!")
  )

("finalbosscam-white-eco"
  (163 :offscreen "GOL" "L'ECO LUMINOSO! MA ALLORA ESISTE!")
  (268 :offscreen "MAIA" "NON DEVONO RIUSCIRE A PRENDERLO!")
  )

("green-sagecage-daxter-sacrifice"
  (0 "DAXTER" "L'ECO LUMINOSO! POTREBBE SERVIRE A FARMI TORNARE NORMALE!")
  (114)
  (123 "DAXTER" "OH... OPPURE POTREBBE FERMARE IL ROBOT.")
  (235)
  (274 "DAXTER" "RESTARE PELOSO, O SALVARE IL MONDO... CHE SCELTA...")
  (404)
  (437 "DAXTER" "OK, VA BENE, SALVEREMO IL MONDO. MA VEDIAMO DI FARE IN FRETTA, PRIMA CHE IO CAMBI IDEA!")
  (634)
  )

("green-sagecage-outro-beat-boss-a"
  (165 :offscreen "MAIA" "FA' QUALCOSA!")
  (216)
  (596 :offscreen "GOL" "NOOO!")
  )

("green-sagecage-outro-beat-boss-b"
  (532 "SAMOS" "BEH, FORSE SONO STATO UN PO' TROPPO DURO CON VOI, RAGAZZI MIEI.")
  (653 "SAMOS" "VOI AVETE TUTTO QUELLO CHE SERVE PER DIVENTARE EROI!")
  (745)
  (759 "KEIRA" "MA ORA, DAXTER, NON TI POSSIAMO TRASFORMARE.")
  (845)
  (853 "DAXTER" "OH, NON PREOCCUPARTI PER ME BABY. SAI COME SI DICE DI SOLITO? IL VINO BUONO STA IN UNA BOTTE... PICCOLINA.")
  (1096)
  (1114 "SAGGIO BLU" "JAK, HAI DAVVERO UN INCREDIBILE TALENTO NEL CANALIZZARE L'ECO!")
  (1219)
  (1230 "SAGGIO BLU" "SAMOS, DOPOTUTTO POTRESTI ANCHE AVER RAGIONE SU DI LUI!")
  (1321)
  (1330 "SAGGIO ROSSO" "SAI KEIRA, SENZA IL TUO AIUTO E SENZA LA TUA INGENUITÀ, TUTTO CIÒ NON SAREBBE STATO POSSIBILE.")
  (1522 "SAGGIO ROSSO" "HAHAHAH. CHISSÀ, FORSE ABBIAMO TROVATO UN NUOVO SAGGIO ORA CHE GOL E MAIA NON CI SONO PIÙ...")
  (1728)
  (1742 "SAMOS" "GIÀ, GOL E MAIA... SÌ, L'ECO OSCURO PROBABILMENTE LI AVRÀ DISTRUTTI.")
  (1946 :offscreen "SAMOS" "GIÀ, PROBABILMENTE...")
  (1999)
  (2005 "DAXTER" "AH, CHE IMPORTA? CHE RITORNINO, POSSIAMO SCONFIGGERLI UN'ALTRA VOLTA, VERO JAK?")
  (2168)
  (2181 "DAXTER" "NON HO DETTO... BENE, JAK?")
  (2256)
  (2312 "DAXTER" "WOW! DATTI UNA CALMATA, RAGAZZO!")
  )

("green-sagecage-outro-beat-boss-enough-cells"
  (151 "SAMOS" "PER TUTTE LE YAKOW! CHE COSA PUÒ ESSERE QUELLO?")
  (247 "KEIRA" "WOW! SI TRATTA DI UN ANTICO PORTONE PRECURSOR!")
  (355 :offscreen "KEIRA" "E SEMBRA CHE PER APRIRLO DOVREMO RIEMPIRE TUTTE E 100 LE FESSURE CON DELLE BATTERIE.")
  (485 "DAXTER" "UHM, MA NOI SIAMO DEGLI EROI, RICORDI? ECCOCI QUA, CON LE 100 BATTERIE NECESSARIE.")
  )

("green-sagecage-outro-beat-boss-need-cells"
  (151 "SAMOS" "PER TUTTE LE YAKOW! CHE COSA PUÒ ESSERE QUELLO?")
  (247 "KEIRA" "WOW! SI TRATTA DI UN ANTICO PORTONE PRECURSOR!")
  (355 :offscreen "KEIRA" "E SEMBRA CHE PER APRIRLO DOVREMO RIEMPIRE TUTTE E 100 LE FESSURE CON DELLE BATTERIE.")
  (485 "DAXTER" "OH RAGAZZI... ECCOCI TORNARE ALLA CARICA!")
  )

("green-sagecage-outro-big-finish"
  (322 "DAXTER" "WOW! MA CHE COS'È, PER VOI?")
  (425)
  (428 "KEIRA" "A ME SEMBRA COSÌ BELLO...")
  (516)
  (519 "SAMOS" "PER TUTTI I PRECURSOR...")
  (602)
  )

;; -----------------
;; training
;; -----------------

("asstvb40" :hint #x900
  (0 "KEIRA" "QUESTO APPARECCHIO È UN COMUNICATORE. CON QUESTO MIO PADRE E IO")
  (181 "KEIRA" "POTREMO CONTATTARVI IN QUALSIASI MOMENTO DURANTE L'AVVENTURA!")
  )

("asstvb41" :hint #x901
  (0 "KEIRA" "QUELLE COSE FLUTTUANTI A FORMA DI UOVO SONO I GLOBI PRECURSOR.")
  (176)
  (180 "KEIRA" "RACCOGLIETENE ABBASTANZA E GLI ABITANTI DEL VILLAGGIO")
  (315 "KEIRA" "LI SCAMBIERANNO CON UNA BATTERIA!")
  )

("asstvb42" :hint #x902
  (0 "KEIRA" "ECCO UNA BATTERIA, IL MANUFATTO PRECURSOR PIÙ IMPORTANTE CHE SI POSSA TROVARE!")
  (270)
  (275 "KEIRA" "DOVETE RACCOGLIERE 20 BATTERIE SE VOLETE ENERGIA SUFFICIENTE AD ATTIVARE LO SCUDO DI CALORE")
  (507 "KEIRA" "DEL VOSTRO ZOOMER ANTIGRAVITÀ.")
  )

("asstvb44" :hint #x903
  (0 "KEIRA" "EHI! AVETE TROVATO UNA DELLE MIE MOSCHE SCOUT!")
  (160 "KEIRA" "NE HO MANDATE SETTE IN OGNI AREA ALLA RICERCA DI BATTERIE,")
  (343 "KEIRA" "MA I LURKER DEVONO AVERLE CATTURATE TUTTE...")
  )

("asstvb45" :hint #x904
  (0 "KEIRA" "WOW! L'ULTIMA MOSCA SCOUT HA TROVATO UNA BATTERIA!")
  (219 "KEIRA" "SCOMMETTO CHE SE TROVATE TUTTE LE SETTE MOSCHE SCOUT RIUSCIRETE A RACIMOLARE ANCHE ALTRE BATTERIE!")
  )

("asstvb46" :hint #x905
  (0 "KEIRA" "FATE ATTENZIONE NELL'OCEANO, QUELLE ACQUE SONO PIENI DI SQUALI LURKER")
  (225 "KEIRA" "E NON MAI VISTO NESSUNO FARNE FUORI UNO.")
  (360)
  (380 "KEIRA" "STATE LONTANI DA LORO SE VOLETE SALVARE LA PELLE.")
  )

("asstvb47" :hint #x906
  (0 "KEIRA" "RICORDATE, QUELLA E' UNA BATTERIA. DOVETE RACCOGLIERNE IL PIU' POSSSIBILE.")
  )

("asstvb48" :hint #x907
  (0 "KEIRA" "QUELLA È UNA FONTE DELL'ECO BLU! LÌ L'ECO È PIÙ CONCENTRATA CHE ALTROVE,")
  (253 "KEIRA" "E VI PERMETTE DI OTTENERE UNA CARICA COMPLETA,")
  (419 "KEIRA" "E SFRUTTARE IL POTERE DELL'ECO PER IL MASSIMO DEL TEMPO!")
  )

("sagevb21" :hint #x908
  (3 "SAMOS" "QUELLE PICCOLE SFERE VERDI SUL TERRENO SONO UNA VARIETÀ DI ECO.")
  (280 "SAMOS" "RACCOGLINE 50 PICCOLE, OPPURE UNA GRANDE PER INCREMENTARE LA TUA ENERGIA.")
  )

("sagevb22" :hint #x909
  (0 "SAMOS" "QUESTO È ECO BLU E CONTIENE L'ENERGIA DEL MOVIMENTO.")
  (291 "SAMOS" "L'ECO BLU TI PERMETTE DI CORRERE PIÙ VELOCEMENTE, DI INFRANGERE CASSE E DI ATTIVARE ALCUNI")
  (640 "SAMOS" "MANUFATTI PRECURSOR, AVVICINANDOTI A ESSI.")
  )

("sagevb23" :hint #x90a
  (0 "SAMOS" "OGNI ECO BLU CHE RACCOGLI INCREMENTA IL TEMPO IN CUI PUOI SFRUTTARNE I POTERI.")
  )

("sagevb24" :hint #x90b
  (3 "SAMOS" "QUESTA È UNA PORTA PRECURSOR. PUÒ ESSERE APERTA SOLO AVVICINANDOTI AD ESSA")
  (357 "SAMOS" "MENTRE NEL TUO CORPO SCORRE L'ECO BLU.")
  )

("sagevb25" :hint #x90c
  (3 "SAMOS" "OTTIMO LAVORO. L'ECO BLU TI HA PERMESSO DI APRIRE LA PORTA. GRAZIE ALL'ECO BLU POTRAI CONVOGLIARE")
  (365 "SAMOS" "ENERGIA IN TUTTI I MANUFATTI PRECURSOR CHE FINORA ERANO RIMASTI INATTIVI PER ANNI.")
  )

("sagevb26" :hint #x90d
  (0 "SAMOS" "USA IL VISORE PER VISUALIZZARE I TUOI PROGRESSI DURANTE L'AVVENTURA.")
  )

("sagevb27" :hint #x90e
  (1 "SAMOS" "PUOI SALTARE UNA VOLTA, QUINDI SPICCARE UN ALTRO SALTO MENTRE SEI IN VOLO PER RAGGIUNGERE PIATTAFORME MOLTO ALTE.")
  )

("sagevb28" :hint #x90f
  (0 "SAMOS" "QUANDO SEI CIRCONDATO DAI NEMICI, USA IL TUO CALCIO ROTANTE.")
  )

("sagevb29" :hint #x910
  (0 "SAMOS" "QUESTO NON E' UN CALCIO ROTANTE, PROVA DI NUOVO.")
  )

("sagevb30" :hint #x911
  (0 "SAMOS" "ANDIAMO JAK, ESEGUI UN CALCIO ROTANTE!")
  )

("sagevb31" :hint #x912
  (0 "SAMOS" "BEL LAVORO! USA IL CALCIO ROTANTE QUANDO HAI BISOGNO DI UN'ATTACCO AD AMPIO RAGGIO.")
  )

("sagevb32" :hint #x913
  (0 "SAMOS" "PER UN ATTACCO IN LINEA RETTA, SFERRA UN PUGNO!")
  )

("sagevb33" :hint #x914
  (0 "SAMOS" "QUELLO NON è UN PUGNO! UN BEL PUGNO, ANDIAMO!")
  )

("sagevb34" :hint #x915
  (0 "SAMOS" "JAK! SFERRA UN PUGNO!")
  )

("sagevb35" :hint #x916
  (0 "SAMOS" "OTTIMO LAVORO! USA IL PUGNO PER ATTACCARE GLI AVVERSARI A CORTA DISTANZA!")
  )

("sagevb36" :hint #x917
  (0 "SAMOS" "ALCUNE VOLTE POTRESTI  VOLER COLPIRE CON MAGGIOR FORZA.")
  (218 "SAMOS" "PER SPACCARE UNA DI QUESTE CASSE DEVI SALTARE IN ARIA,")
  (420 "SAMOS" "QUINDI TUFFARTI SU DI ESSA CON LE MANI DAVANTI.")
  )

("sagevb37" :hint #x918
  (0 "SAMOS" "QUANDO SARAI ABBASTANZA ABILE, PROVA AD USARE I TUOI ATTACCHI IN COMBINAZIONE.")
  )

("sagevb38" :hint #x919
  (0 "SAMOS" "NON PUOI TORNARE INDIETRO ATTRAVERSO IL TELETRASPORTO FINCHÉ NON AVRAI TROVATO")
  (168 "SAMOS" "LE QUATTRO BATTERIE SU QUEST'ISOLA.")
  )

("sagevb39" :hint #x91a
  (0 "SAMOS" "OTTIMO! HAI TROVATO TUTTE LE BATTERIE SPARSE SULL'ISOLA!")
  (237 "SAMOS" "TORNA AL TELETRASPORTO COSÌ CHE POSSA RIPORTARTI AL LABORATORIO. SBRIGATI!")
  )

;; -----------------
;; uncategorized
;; -----------------

