(language-id 4)

;; -----------------
;; intro
;; -----------------

("sage-intro-sequence-a"
  (24 :offscreen "SAGE" "I HAVE SPENT MY LIFE SEARCHING FOR THE ANSWERS THAT MY FATHER, AND MY FATHER'S FATHERS FAILED TO FIND.")
  (260 :offscreen "SAGE" "WHO WERE THE PRECURSORS? WHY DID THEY CREATE THE VAST MONOLITHS THAT LITHER OUR PLANET?")
  (454 :offscreen "SAGE" "HOW DID THEY HARNESS ECO, THE LIFE ENERGY OF THE WORLD?")
  (581 :offscreen "SAGE" "WHAT WAS THEIR PURPOSE? AND WHY DID THEY VANISH?")
  (708)
  (720 :offscreen "SAGE" "I HAVE ASKED THE PLANTS, BUT THEY DO NOT REMEMBER.")
  (818 :offscreen "SAGE" "THE PLANTS HAVE ASKED THE ROCKS, BUT THE ROCKS DO NOT RECALL.")
  (955 :offscreen "SAGE" "EVEN THE ROCKS DO NOT RECALL...")
  (1064)
  (1090 :offscreen "SAGE" "EVERY BONE IN MY BODY TELLS ME THAT THE ANSWERS REST ON THE SHOULDERS OF A YOUNG BOY")
  (1297 :offscreen "SAGE" "OBLIVIOUS TO HIS DESTINY, UNINTERESTED IN THE SEARCH FOR TRUTH, AND REJECTING OF MY GUIDANCE!")
  (1536)
  (1545 :offscreen "SAGE" "AND WHY WOULD HE WANT TO LISTEN TO OLD SAMOS THE SAGE ANYWAY?")
  (1680)
  (1686 :offscreen "SAGE" "I'M ONLY THE MASTER OF GREEN ECO, ONE OF THE WISEST MEN ON THE PLANET!")
  (1875)
  (1958 :offscreen "SAGE" "SO IT SEEMS THE ANSWER BEGINS NOT WITH CAREFUL RESEARCH, OR SENSIBLE THINKING.")
  (2141)
  (2145 :offscreen "SAGE" "NAY! AS WITH MANY OF FATE'S MYSTERIES")
  (2281 :offscreen "SAGE" "IT BEGINS WITH BUT A SMALL ACT OF DISOBEDIENCE.")
  (2440 "DAXTER" "HEY! UH, JAK? OL' GREEN STUFF TOLD US NOT TO COME HERE!")
  )

("sage-intro-sequence-d1"
  (137 "SAGE" "WHAT IN GREEN TARNATION DO YOU TWO WANT?")
  (220 "DAXTER" "WE- WE- WE WAS- THEY WAS- I'M- I WAS-")
  (283 "SAGE" "DON'T TELL ME! INSTEAD OF HEEDING MY WISDOM, THE TWO OF YOU WENT MUCKING AROUND")
  (440 "SAGE" "IN THE ONLY PLACE THAT I TOLD YOU NOT TO GO: MISTY ISLAND!")
  (550 "DAXTER" "THAT'S RIGHT! AND THEN-")
  (579 "SAGE" "AND, DAXTER, YOU FINALLY TOOK A MUCH-NEEDED BATH, BUT IN A BATHTUB FILLED WITH DARK ECO.")
  (793 "DAXTER" "LOOK, OLD MAN, ARE YOU GONNA KEEP YAPPIN', OR YOU GONNA HELP ME OUTTA THIS MESS!?")
  (920 "SAGE" "I'M GONNA KEEP YAPPIN'! BECAUSE IN MY PROFESSIONAL OPINION, THE CHANGE IS AN IMPROVEMENT.")
  (1079 "SAGE" "AND BESIDES... I COULDN'T HELP YOU IF I WANTED TO.")
  (1186 "DAXTER" "WHAT!?")
  (1220 "SAGE" "THERE'S ONLY ONE PERSON WHO HAS STUDIED DARK ECO LONG ENOUGH")
  (1329 "SAGE" "TO HAVE A CHANCE AT RETURNING YOU TO YOUR PREVIOUS FORM:")
  (1431 "SAGE" "GOL ACHERON, THE SAGE.")
  (1493)
  (1496 :offscreen "SAGE" "BUT HE LIVES FAR TO THE NORTH. FAR, FAR TO NORTH. NOBODY HAS SPOKEN TO HIM IN AGES.")
  (1718 "SAGE" "I WOULD TELEPORT YOU THERE, BUT I CAN'T DO THAT EITHER.")
  (1831 "SAGE" "NONE OF THE THREE SAGES THAT MAINTAIN THE OTHER TELEPORTER GATES")
  (1934 "SAGE" "HAVE SEEN FIT TO TURN THEIR ENDS ON FOR QUITE A WHILE!")
  )

("sage-intro-sequence-d2"
  (3 "SAGE" "THE ONLY OTHER WAY NORTH IS BY FOOT THROUGH THE FIRE CANYON")
  (114 :offscreen "SAGE" "BUT ITS VOLCANIC SOIL IS HOT ENOUGH TO MELT PRECURSOR METAL.")
  (224 "SAGE" "YOU CAN'T JUST WALK THROUGH IT.")
  (270 "KEIRA" "BUT YOU COULD FLY OVER IT, IF YOU HAD A ZOOMER EQUIPPED WITH A HEAT SHIELD.")
  (393)
  (396 "KEIRA" "I JUST HAPPEN TO BE WORKING ON SUCH A THING AT THIS VERY MOMENT.")
  (512)
  (515 "KEIRA" "ALL I WOULD NEED IS TWENTY POWER CELLS TO GIVE IT ENOUGH ENERGY")
  (605 "KEIRA" "TO WITHSTAND THE CANYON'S HEAT. ISN'T THAT RIGHT, DADDY?")
  (696)
  (699 "SAGE" "YES, KEIRA, THAT MIGHT WORK. BUT WHERE ARE A BOY")
  (826 :offscreen "SAGE" "AND A HALF!")
  (857 "SAGE" "GOING TO GET TWENTY POWER CELLS?")
  (910 "KEIRA" "FROM THE VILLAGERS! MOST OF THEM HAVE A POWER CELL OR TWO STASHED AWAY SOMEWHERE.")
  (1050 :offscreen "KEIRA" "AND EVEN IF THEY AREN'T WILLING TO JUST GIVE THEM AWAY")
  (1133 "KEIRA" "GREASING THEIR PALMS WITH A FEW PRECURSOR ORBS SHOULD DO THE TRICK.")
  (1243)
  (1246 :offscreen "KEIRA" "AND I BET THERE ARE EVEN MORE OF THEM OUT IN THE WILDS JUST WAITING FOR SOME")
  (1364 "KEIRA" "BRAVE ADVENTURER TO FIND.")
  (1435 "DAXTER" "WELL WE'VE GOT THE BRAVE ADVENTURER, AT LEAST.")
  (1529)
  (1532 "SAGE" "BRAVE ADVENTURER?")
  (1582 "SAGE" "YOU TWO COULDN'T FIND YOUR WAY OUT OF THE VILLAGE WITHOUT TRAINING!")
  (1685)
  (1689 "SAGE" "BEFORE YOU DO ANYTHING ELSE, YOU BETTER GO THROUGH THE WARP GATE AND GET")
  (1810 "SAGE" "SOME PRACTICE ON GEYSER ROCK.")
  (1872)
  (1878 "DAXTER" "UH, WE WON'T FIND ANY MORE OF THAT DARK GOOEY ECO STUFF, WILL WE?")
  (1993 "DAXTER" "'CAUSE I'D HATE TO FALL IN AGAIN AND TURN INTO YOU!")
  (2069)
  (2072 "SAGE" "GET IN THERE! BEFORE I TURN YOU BOTH INTO FERNS!")
  (2189)
  )

("sage-intro-sequence-e"
  (200 "SAGE" "GOOD TRAINING, BOYS, BUT THAT'S NOTHING COMPARED TO THE CHALLENGES THAT LIE AHEAD.")
  (359 "DAXTER" "AH, THEY'RE NO PROBLEM. WE GOT THE MOVES, EH JAK?")
  (496 "DAXTER" "WE'D LOVE TO STAY AND CHAT, BIG GREEN, BUT WE'RE UH... ITCHING TO GET ON WITH OUR ADVENTURES.")
  (660 "SAGE" "FINE, FINE, \"ADVENTURE\" AWAY THEN.")
  (787 "SAGE" "AND WHILE YOU'RE OUT \"ADVENTURING,\" WHY DON'T YOU MAKE YOURSELF USEFUL?")
  (940)
  (952 :offscreen "SAGE" "MY DARN GREEN ECO COLLECTORS ARE CLOGGED UP AGAIN.")
  (1043)
  (1046 :offscreen "SAGE" "HEAD OUT TO THE FAR SIDE OF THE BEACH AND CLEAR THEM OUT WHY DON'T YOU.")
  (1160)
  (1169 :offscreen "SAGE" "FOLLOW THE LAMPS, THEY'LL TAKE YOU RIGHT THERE.")
  (1310)
  (1313 :offscreen "SAGE" "NOW, ALL OF YOU...")
  (1415)
  (1439 :offscreen "SAGE" "GET OUT OF HERE!")
  )

("sidekick-human-intro-sequence-b"
  (547 "OLD MAN" "CONTINUE YOUR SEARCH FOR ARTIFACTS AND ECO.")
  (674 "OLD MAN" "IF THE LOCALS POSSESS PRECURSOR ITEMS, YOU KNOW WHAT TO DO.")
  (842 "WOMAN" "DEAL HARSHLY WITH ANYBODY WHO STRAYS FROM THE VILLAGE.")
  (937 "WOMAN" "WE WILL ATTACK IT IN DUE TIME.")
  (1027)
  )

("sidekick-human-intro-sequence-c"
  (12 "DAXTER" "WHAT ARE WE DOING HERE ANYWAY, JAK? THIS PLACE GIVES ME THE CREEPS!")
  (151)
  (369 "DAXTER" "HUH?")
  (404 "DAXTER" "(GROAN) STUPID PRECURSOR JUNK!")
  (496)
  (577 "DAXTER" "EEK! WHAT IS THAT DARK OOZE? IT SURE DON'T LOOK FRIENDLY.")
  (721)
  (777 "DAXTER" "THE SAGE YAPS ON ABOUT THE PRECURSORS THAT BUILT THIS PLACE ALL THE TIME.")
  (909 "DAXTER" "\"WHERE DID THEY GO? WHY DID THEY BUILD THIS CRAP?\"")
  (1014 "DAXTER" "NOW I LIKE PRECURSOR ORBS AND POWER CELLS AS MUCH AS THE NEXT GUY")
  (1124 "DAXTER" "BUT IF YOU ASK ME, THEY MUST HAVE BEEN REAL LOSERS.")
  (1212 "DAXTER" "WHOA! HOW DID YOU DO THAT?")
  (1271)
  (1331 "DAXTER" "JAK, I THINK WE'RE IN TROUBLE!")
  (1386)
  (1857 "DAXTER" "MAN, THAT STUNG.")
  (1913)
  (1941 "DAXTER" "I TOLD YOU WE SHOULDN'T HAVE COME HERE, AND YOU LISTENED?")
  (2028)
  (2057 "DAXTER" "WHAAAT?")
  (2101)
  (2189 "DAXTER" "WAAAAAAAAHHHHHHHH!!")
  (2307 "DAXTER" "OKAY, OKAY. I'M FINE, I'M FINE...")
  (2431)
  (2481 "DAXTER" "WAAAAAAAAHHHHHHHH!!")
  )

;; -----------------
;; sidekick
;; -----------------

("sksp0001" :hint #x280
  (0 "DAXTER" "HEY! THAT SWEET-LOOKING BABE KEIRA WAS RIGHT! THERE ARE TRANS-PADS OUT HERE.")
  )

("sksp0002" :hint #x281
  (0 "DAXTER" "TRUST ME, THOSE DARK ECO BOXES ARE BAD NEWS!")
  )

("sksp0003" :hint #x282
  (0 "DAXTER" "I BET IF WE FOUND ALL OF THOSE SICKLY CUTE SCOUT FLIES ON EACH LEVEL")
  (215 "DAXTER" "AT LEAST ONE WILL HAVE A POWER CELL!")
  )

("sksp0004" :hint #x283
  (0 "DAXTER" "ALL RIGHT, TREASURE!")
  )

("sksp0005" :hint #x284
  (0 "DAXTER" "THESE WOOD AND METAL BOXES DON'T LOOK THAT TOUGH!")
  (166 "DAXTER" "I'LL BET THEY'LL BREAK IF YOU JUMP DIVE ONTO THEM.")
  )

("sksp0006" :hint #x285
  (0 "DAXTER" "THOSE ALL-METAL BOXES ARE THICKER THAN A YAKOW SKULL!")
  (188 "DAXTER" "BUT THERE MUST BE SOMETHING THAT CAN BUST 'EM OPEN.")
  )

("sksp0007" :hint #x286
  (0 "DAXTER" "TWO WORDS: POWER CELLS. WE NEED TO FIND 'EM AND WE AREN'T LOOKIN' SO GOOD RIGHT NOW.")
  )

("sksp0008" :hint #x287
  (0 "DAXTER" "WE NEED ORBS. ORBS, JAK! HOW ARE EVER GONNA BUY POWER CELLS IF WE DON'T COLLECT ORBS!")
  )

("sksp0009" :hint #x251
  (0 "DAXTER" "WHAT A WEIRD-LOOKING THING! I'LL BET WE CAN GET THIS OPEN")
  (206 "DAXTER" "IF YOU'RE POWERED UP WITH THAT ZAPPY BLUE ECO STUFF.")
  )

("sksp0014" :hint #x233
  (0 "DAXTER" "WE SCROUNGED ENOUGH ORBS TO TRADE FOR A POWER CELL.")
  (215 "DAXTER" "LET'S GET BACK AND MAKE THE SWITCH ALREADY!")
  )

("sksp0035" :hint #x25c
  (0 "DAXTER" "YEAH, SO WE GOT A PRECURSOR LAUNCHER HERE")
  (117 "DAXTER" "BUT YOU AREN'T POWERED UP WITH THE BLUE STUFF. SO IT AIN'T GONNA HELP US!")
  )

("sksp0071" :hint #x2a5
  (0 "DAXTER" "GET THE RED ECO!")
  )

("sksp0072" :hint #x2a6
  (0 "DAXTER" "RED ECO MAKES YOUR ATTACKS STRONGER.")
  )

("sksp0073" :hint #x2a7
  (0 "DAXTER" "WE NEED BLUE ECO TO CHARGE THIS PLATFORM UP!")
  )

("sksp009a" :hint #x0
  (0 "DAXTER" "HA HA! WE SHOWED HIM A THING OR TWO.")
  )

("sksp009b" :hint #x28e
  (0 "DAXTER" "ALL RIGHT, MORE ORBS!")
  )

("sksp009c" :hint #x28f
  (0 "DAXTER" "DO ME A FAVOR AND KEEP AWAY FROM THOSE DARK ECO BOXES!")
  )

("sksp009d" :hint #x290
  (0 "DAXTER" "YEAH-HA-HA-HA!")
  )

("sksp009e" :hint #x291
  (0 "DAXTER" "WA-HOO!")
  )

("sksp009f" :hint #x292
  (0 "DAXTER" "GET SOME, GET SOME! HA HA HA!")
  )

("sksp009g" :hint #x293
  (0 "DAXTER" "RIGHT BEHIND YA, JAK!")
  )

("sksp009i" :hint #x294
  (0 "DAXTER" "DID WE FIND ALL THE SCOUT FLIES IN THIS AREA?")
  )

("sksp009j" :hint #x295
  (0 "DAXTER" "HEY! IT LOOKS LIKE SCOUT FLIES ARE ALWAYS IN RED BOXES.")
  )

("sksp009k" :hint #x296
  (0 "DAXTER" "ALRIGHT! YOU FOUND ALL THE SCOUT FLIES IN THIS AREA!")
  )

("sksp0145" :hint #x359
  (0 "DAXTER" "WOW! YOU CAN SHOOT FIRE BALLS WHEN YOU'RE POWERED UP WITH YELLOW ECO.")
  )

;; -----------------
;; village1
;; -----------------

("ASSTLP01" :hint #x0
  (0 "KEIRA" "HMM...")
  )

("ASSTLP02" :hint #x0
  (0 "KEIRA" "GOTTA GET THIS HEAT SHIELD WORKING...")
  )

("ASSTLP03" :hint #x0
  (0 "KEIRA" "WE NEED POWER CELLS TO FUEL THE HEAT SHIELD...")
  )

("ASSTLP04" :hint #x0
  (0 "KEIRA" "WHERE'S MY SPANNER?")
  )

("ASSTLP05" :hint #x0
  (0 "KEIRA" "FIRE CANYON IS SO HOT...")
  )

("EXP-AM01" :hint #x0
  (0 "JAK'S UNCLE" "I NEED TO SET OFF ON MY JOURNEY SOON. I NEED PRECURSOR ORBS!")
  )

("EXP-AM02" :hint #x0
  (0 "JAK'S UNCLE" "LET'S SEE, NOW WHERE SHALL I GO FIRST? EH...")
  )

("EXP-AM03" :hint #x0
  (0 "JAK'S UNCLE" "OH I DO MISS THE OPEN ROAD.")
  )

("EXP-AM04" :hint #x0
  (0 "JAK'S UNCLE" "SO MANY PLACES TO SEE, AND SO LITTLE TIME.")
  )

("EXP-AM05" :hint #x0
  (0 "JAK'S UNCLE" "WELL IN MY DAY, YOU COULD WALK THE LANDS WITHOUT BEING ASSAULTED BY MONSTERS!")
  )

("EXP-LO02" :hint #x0
  (0 "JAK'S UNCLE" "I NEED MORE PRECURSOR ORBS.")
  )

("FAR-AM01" :hint #x0
  (0 "FARMER" "(SNORES) HERE, BESSIE... HERE, BESSIE BESSIE... THAT'S A GOOD GIRL...")
  )

("FAR-AM02" :hint #x0
  (0 "FARMER" "GOTTA BRING IN THE CROPS 'FORE THE JUNE BUGS...")
  )

("FAR-AM2A" :hint #x0
  (0 "FARMER" "GOTTA BRING IN THE CROPS 'FORE THE JUNE BUGS GET...")
  )

("FAR-LO01" :hint #x0
  (0 "FARMER" "(SNORES)")
  )

("FAR-LO1A" :hint #x0
  (0 "FARMER" "(SNORES)")
  )

("SAGELP03" :hint #x0
  (0 "SAGE" "THESE TWO COULDN'T UNBLOCK THEIR EARS...")
  )

("SAGELP04" :hint #x0
  (0 "SAGE" "HE'LL JUST NEVER BE LIKE HIS UNCLE...")
  (221 "SAGE" "I DON'T CARE WHAT THE OTHERS SAY.")
  )

("SAGELP05" :hint #x0
  (0 "SAGE" "HELLO, BLUE SAGE? HELLO? WHERE IN THE BLUE BLAZES COULD HE BE...")
  )

("SAGELP06" :hint #x0
  (0 "SAGE" "MY, MY, MY...")
  )

("SAGELP11" :hint #x0
  (0 "SAGE" "ANYONE? ANYONE AT ALL? COME IN?")
  )

("assistant-introduction-blue-eco-switch"
  (23 "DAXTER" "HEY BABY. WHAT DO YOU SAY YOU AND I GO CRUISIN' ON THIS A-GRAV ZOOMER?")
  (175)
  (193 "KEIRA" "RULE NUMBER ONE: I DON'T DATE ANIMALS.")
  (308)
  (312 "DAXTER" "OH YOU DON'T KNOW WHAT YOU'RE MISSING, HE HEH.")
  (430)
  (505 "KEIRA" "LISTEN, IF YOU NEED SOMETHING TO KEEP YOU BUSY, MY FATHER ALWAYS TALKED")
  (635 "KEIRA" "ABOUT AN ANCIENT PRECURSOR PIPELINE HIDDEN DEEP UNDERGROUND.")
  (739)
  (742 :offscreen "KEIRA" "SOME OF THESE PIPES END IN VENTS FROM WHICH ECO FLOWS FREELY,")
  (842 :offscreen "KEIRA" "AND SOME HAVE BEEN CAPPED OFF SO THAT THE ECO IS SEALED BACK.")
  (945)
  (954 "KEIRA" "THERE MUST BE A WAY TO TURN THE CAPPED VENTS ON.")
  (1052 :offscreen "KEIRA" "I TRACED PART OF THE PIPELINE BACK TO THE FORBIDDEN TEMPLE.")
  (1138 "KEIRA" "MAYBE YOU SHOULD LOOK THERE FOR SOME TYPE OF SWITCH.")
  (1246)
  )

("assistant-introduction-race-bike"
  (9 "DAXTER" "HEY BABY, WHAT'CHA WORKIN' ON?")
  (63 "KEIRA" "BE CAREFUL WITH THAT! I'M TRYING TO FIGURE HOW TO TRANSPORT THE ZOOMER")
  (200 "KEIRA" "USING THE TRANS-PADS THE PRECURSORS LEFT ALL OVER THE WORLD.")
  (308)
  (312 :offscreen "KEIRA" "IF YOU COME ACROSS ONE OF THESE PADS I CAN LOCK ON TO YOUR COMMUNICATOR'S LOCATION")
  (453 :offscreen "KEIRA" "AND SEND YOU THE ZOOMER!")
  (508 "KEIRA" "KEEP AN EYE OUT FOR A TRANS-PAD WHEN YOU EXPLORE MISTY ISLAND, AND WHEREVER ELSE YOU GO!")
  (665)
  )

("assistant-reminder-1-blue-eco-switch"
  (23 "KEIRA" "I'M SURE IF YOU LOOKED INSIDE THE PRECURSOR FORBIDDEN TEMPLE")
  (143 "KEIRA" "YOU'LL FIND A WAY TO TURN ON THAT CAPPED BLUE ECO VENT ON SENTINEL BEACH.")
  (295)
  )

("assistant-reminder-1-generic"
  (25 "KEIRA" "HEY GUYS! KEEP COLLECTING POWER CELLS, THEY'RE THE KEY TO CONTINUING OUR JOURNEY NORTH.")
  )

("assistant-reminder-1-race-bike"
  (19 "KEIRA" "I'VE DEFINITELY FIGURED OUT HOW TO USE THE TRANS-PADS.")
  (106 "KEIRA" "NOW GO TO MISTY ISLAND AND I'LL SEND THE ZOOMER OVER TO YOU.")
  (229)
  )

("asstvb04" :hint #x2b1
  (0 "KEIRA" "GOOD, YOU'VE COLLECTED ENOUGH POWER CELLS TO FUEL MY HEAT SHIELD!")
  (233 "KEIRA" "MEET ME BY THE ENTRANCE TO THE FIRE CANYON BY CLIMBING THE CLIFF BEHIND THE FARMER'S HOUSE.")
  (559 "KEIRA" "BRING THE POWER CELLS, AND HURRY! MY FATHER SAYS HE'S SEEN MORE LURKERS AROUND!")
  )

("asstvb08" :hint #x2b2
  (0 "KEIRA" "HURRY UP WITH THOSE POWER CELLS. I'M WAITING AT THE HEAD OF FIRE CANYON")
  (260 "KEIRA" "AT THE TOP OF THE CLIFF BEHIND THE FARMER'S HOUSE!")
  )

("explorer-introduction"
  (23 "JAK'S UNCLE" "WELL, HELLO THERE MY DEAR BOY. YOU'VE CAUGHT AT A MOST INOPPORTUNE MOMENT.")
  (197 "JAK'S UNCLE" "I WAS TO SET OFF ON MY JOURNEYS YESTERDAY")
  (288 "JAK'S UNCLE" "BUT I SEEM TO BE A SPOT SHORT ON THE OLD PRECURSOR ORBS.")
  (426)
  (430 "JAK'S UNCLE" "I WOULD'VE PLEDGED MY WORD THAT I HAD 90 OF THEM,")
  (538 "JAK'S UNCLE" "BUT I GATHER THAT YOUR YOUNG FRIEND, YOU KNOW, THE LITTLE ANNOYING MISERABLY UGLY ONE")
  (716 "JAK'S UNCLE" "MIGHT HAVE JUST PILFERED THEM AS A SORT OF A SPOT OF FUN.")
  (829)
  (865 "JAK'S UNCLE" "ANYWAY, WOULD YOU BE KIND ENOUGH TO LOAN YOUR DEAR OLD UNCLE 90 PRECURSOR ORBS")
  (1043 "JAK'S UNCLE" "SO HE CAN GET UNDERWAY? I WOULD OFFER YOU A POWER CELL IN RETURN.")
  )

("explorer-reminder-1"
  (25 "JAK'S UNCLE" "WHAT? YOU DON'T HAVE THE FULL STASH? HARUMPH!")
  (148 "JAK'S UNCLE" "WELL, ANY LESS THAN 90 PRECURSOR ORBS")
  (251 "JAK'S UNCLE" "AND I SHAN'T HAVE A CHANCE TO GET UNDERWAY, DEAR BOY.")
  (387)
  )

("explorer-reminder-2"
  (33 "JAK'S UNCLE" "OH SEE HERE, THE DEAL IS FOR 90 PRECURSOR ORBS FOR A POWER CELL.")
  (187 "JAK'S UNCLE" "A DOWNRIGHT EVEN TRADE.")
  )

("explorer-resolution"
  (28 "JAK'S UNCLE" "I SEE YOU TWO ARE BACK TO MAKE THE TRADE. GOOD, GOOD, JOLLY GOOD!")
  (179 "JAK'S UNCLE" "EH, YOU HAVE THE UH, PRECURSOR ORBS THAT WE AGREED ON?")
  (310)
  (324 "JAK'S UNCLE" "I HOPE YOU PUT THIS HARD-EARNED POWER CELL TO GOOD USE. CHEERIO, TA TA, BYE BYE!")
  )

("farmer-introduction"
  (1 "FARMER" "GOTTA MILK THOSE YAKOWS, GOTTA MILK THOSE YAKOWS...")
  (113 "FARMER" "OH! IT'S YOU... JUST RESTIN' MY TRIED BONES. I'VE BEEN TRYING TO GET THOSE ORNERY YAKOWS")
  (317 "FARMER" "BACK INTO THE PEN ALL DAY! SOME STRANGE CREATURES TRIED TO STEAL 'EM EARLIER.")
  (454)
  (456 "FARMER" "YOU THINK YOU CAN HELP AN OLD MAN TRY TO GET 'EM BACK INTO THE CORRAL?")
  )

("farmer-reminder-1"
  (0 "FARMER" "HEY! MY YAKOWS ARE STILL ON THE LOOSE! EH, COULD YOU BRING 'EM BACK FOR ME ALREADY?")
  )

("farmer-reminder-2"
  (0 "FARMER" "THOSE DARN YAKOWS ARE STILL ROAMIN' FREE.")
  (85 "FARMER" "AIN'T YOU GONNA CHASE 'EM INTO THE CORRAL ALREADY?")
  )

("farmer-resolution"
  (0 "FARMER" "AH, WELL DONE MY BOY. YOU ACTUALLY GOT THOSE FLEABAGS PACK INTO THE PEN.")
  (134 "FARMER" "NOW I CAN SLEEP IN PEACE. TAKE THIS POWER CELL FOR YOUR TROUBLE.")
  (340)
  )

("sage-introduction-misty-cannon"
  (24 "SAGE" "OH, IT'S THE CONQUERING HEROES.")
  (136 "SAGE" "GOOD, I WANTED TO TALK WITH YOU TWO ABOUT SOMETHING SERIOUS.")
  (258)
  (261 :offscreen "SAGE" "THERE APPEARS TO BE QUITE A BIT OF LURKER ACTIVITY ON MISTY ISLAND.")
  (387)
  (393 :offscreen "SAGE" "I CAN SEE THEM BOMBARDING THE PRECURSOR SILO FROM MY LOOKOUT TOWER.")
  (525)
  (528 "SAGE" "IF THE LURKERS OPEN IT UP AND RELEASE THE DARK ECO, WE COULD ALL END UP")
  (663 "SAGE" "RUNNING AROUND LOOKING AS RIDICULOUS AS THIS ANNOYING LITTLE SPECIMEN.")
  (788)
  (807 "SAGE" "JAK, IT'S TIME FOR YOU TO PROVE YOUR WORTH.")
  (906 "SAGE" "GET THE FISHERMAN TO LET YOU TAKE HIS BOAT BACK TO MISTY ISLAND")
  (1018 "SAGE" "GET TO THE TOP OF THE PRECURSOR SILO AND TAKE OUT THAT CANNON.")
  (1171)
  (1177 "DAXTER" "AND... WHAT ABOUT ME?")
  (1232)
  (1235 "SAGE" "YOU? WHY DON'T YOU MOP MY FLOORS? THEY SEEM TO HAVE LOST THEIR SHINE LATELY.")
  )

("sage-reminder-1-ecorocks"
  (28 "SAGE" "SOME \"BRAVE ADVENTURERS\" YOU TWO ARE.")
  (132 "SAGE" "BACK ALREADY AND WITHOUT CLEARING MY BLOCKED ECO HARVESTERS!")
  (244)
  (252 :offscreen "SAGE" "THEY'RE ON THE FAR SIDE OF THE BEACH, BOYS.")
  (365)
  (366 :offscreen "SAGE" "NOW...")
  (412 :offscreen "SAGE" "GET MOVING!")
  )

("sage-reminder-1-generic"
  (54 "SAGE" "WHAT ARE YOU TWO DOING HERE? YOU HAVE POWER CELLS TO COLLECT!")
  (178)
  (181 "SAGE" "LEAVE ME ALONE... UNTIL YOU HAVE THEM!")
  )

("sage-reminder-1-misty-cannon"
  (24 "SAGE" "THE BOMBARDMENT IS GETTING WORSE!")
  (86 :offscreen "SAGE" "FIND THE FISHERMAN IN THE JUNGLE, GET PERMISSION TO USE HIS BOAT")
  (215 :offscreen "SAGE" "AND GET OVER TO MISTY ISLAND TO STOP THE CANNON.")
  (317)
  (320 "SAGE" "AND YOU DAXTER, YOU NEED TO GET MOPPING. THIS PLACE IS A MESS!")
  )

("sage-reminder-2-generic"
  (27 "SAGE" "YOU TWO JUST DON'T UNDERSTAND THE GRAVITY OF THE SITUATION.")
  (137 "SAGE" "THIS IS ABOUT MORE THAN A SINGLE BOY GONE FUZZY. THIS IS ABOUT LIFE AS WE KNOW IT.")
  (320)
  (323 "SAGE" "NOW, GET OUT THERE AND FULFILL YOUR DESTINY.")
  (455)
  )

("sksp0010" :hint #x231
  (0 "DAXTER" "HEY! LET'S GO CHECK OUT OL' FISH BREATH'S SPEED-BOAT AT THE DOCK!")
  )

("sksp0013" :hint #x232
  (0 "DAXTER" "DID YOU SEE THE SIZE OF THE BITE THAT LURKER SHARK TOOK OUT OF THE FISHERMAN'S BOAT?")
  (315)
  (337 "DAXTER" "WE BEST STAY WAY CLEAR OF THEM! I DON'T THINK WE CAN TACKLE A CREATURE THAT DAG NASTY.")
  )

("sksp0015" :hint #x234
  (0 "DAXTER" "THIS MUST BE A PRECURSOR ORACLE LIKE THE SAGE ALWAYS GOES ON ABOUT.")
  (228 "DAXTER" "I HOPE THEY WEREN'T AS UGLY IN PERSON!")
  )

("sksp0017" :hint #x235
  (0 "DAXTER" "WHOA! CHECK OUT THAT FUNKY SCULPTURE SITTIN' ON THE ROCKS OVER THERE!")
  )

("sksp0043" :hint #x24e
  (0 "DAXTER" "MAYBE WE SHOULD GO ROOT OUT THE FISHERMAN.")
  (106 "DAXTER" "I HEARD HE WAS IN THE JUNGLE FISHING BY THE LOWER RIVER!")
  )

("sksp018a" :hint #x297
  (0 "DAXTER" "THAT LAZY FARMER OWES US A POWER CELL!")
  (156 "DAXTER" "LET'S GO TALK TO HIM!")
  )

;; -----------------
;; oracle
;; -----------------

("oracle-intro-1"
  (0 "ORACLE" "WHO AWAKENS THE ORACLE?")
  (75)
  (81 "ORACLE" "WAIT, ONE OF YOU HAS THE LIGHT WITHIN.")
  (198)
  (206 "ORACLE" "FROM BEFORE TIME, I HAVE WATCHED AND WAITED FOR THE TRUE HERO TO RETURN.")
  (390)
  (395 "ORACLE" "PRESENT TO ME 120 PRECURSOR ORBS FOR EACH POWER CELL I CONTAIN.")
  )

("oracle-left-eye-1"
  (0 "ORACLE" "YOU HAVE PROVEN YOURSELF WORTHY. HERE IS A POWER CELL.")
  )

("oracle-left-eye-2"
  (0 "ORACLE" "FOR YOUR SACRIFICE, I OFFER YOU A POWER CELL.")
  )

("oracle-left-eye-3"
  (0 "ORACLE" "FOR YOUR EFFORT, A POWER CELL IS THE REWARD.")
  )

("oracle-reminder-1"
  (0 "ORACLE" "BRING TO ME 120 PRECURSOR ORBS AND I WILL AWARD YOU A POWER CELL.")
  )

("oracle-right-eye-1"
  (0 "ORACLE" "FOR YOUR GIFT, ANOTHER POWER CELL IS YOURS.")
  )

("oracle-right-eye-2"
  (0 "ORACLE" "HERE IS ANOTHER POWER CELL FOR YOUR QUEST.")
  )

("oracle-right-eye-3"
  (0 "ORACLE" "YOU HAVE OBTAINED ANOTHER POWER CELL.")
  )

;; -----------------
;; beach
;; -----------------

("BIR-AM01" :hint #x0
  (0 "BIRDWATCHER" "ARE YOU NEAR THE EGG YET?")
  )

("BIR-AM02" :hint #x0
  (0 "BIRDWATCHER" "THAT'S IT, JUST A LITTLE FURTHER!")
  )

("BIR-AM03" :hint #x0
  (0 "BIRDWATCHER" "OH, GOOD, NOW PUSH IT. OH, GENTLY NOW!")
  )

("BIR-AM04" :hint #x0
  (0 "BIRDWATCHER" "OH, MY, THAT WASN'T GENTLE!")
  )

("BIR-AM05" :hint #x0
  (0 "BIRDWATCHER" "COME ON, PUSH THE EGG OFF THE CLIFF!")
  )

("BIR-AM06" :hint #x0
  (0 "BIRDWATCHER" "OHH!")
  )

("BIR-AM07" :hint #x0
  (0 "BIRDWATCHER" "OH, HERE, BIRDIE BIRDIE. HERE, BIRDIE BIRDIE.")
  )

("BIR-AM08" :hint #x0
  (0 "BIRDWATCHER" "HERE, BIRDIE BIRDIE.")
  )

("BIR-AM09" :hint #x0
  (0 "BIRDWATCHER" "BE CAREFUL, IT DOESN'T LOOK SAFE UP THERE!")
  )

("BIR-AM10" :hint #x0
  (0 "BIRDWATCHER" "CAREFUL, EASY DOES IT!")
  )

("BIR-AM11" :hint #x0
  (0 "BIRDWATCHER" "GOOD JOB! NOW MEET ME DOWN HERE BY THE EGG.")
  )

("BIR-AM12" :hint #x0
  (0 "BIRDWATCHER" "YOU MUST BE A TRUE ANIMAL LOVER!")
  )

("BIR-AM13" :hint #x0
  (0 "BIRDWATCHER" "DO YOU SEE ANY OTHER BIRDS UP THERE?")
  )

("BIR-LO01" :hint #x0
  (0 "BIRDWATCHER" "(KISS) (WHISTLE)")
  )

("BIR-LO02" :hint #x0
  (0 "BIRDWATCHER" "OH MY, THAT'S A PRETTY ONE.")
  )

("BIR-LO03" :hint #x0
  (0 "BIRDWATCHER" "OH LOOK, A MUCKY-MUCK.")
  )

("CHI-AM01" :hint #x0
  (0 "MAYOR" "THIS IS A CATASTROPHE. A CATASTROPHE I SAY!")
  )

("CHI-AM02" :hint #x0
  (0 "MAYOR" "THEY WANT ME TO GO INTO THE JUNGLE - ME! HO HO OH...")
  (214)
  (219 "MAYOR" "I'D SOONER WRESTLE AN ENRAGED FLUT FLUT.")
  )

("CHI-AM03" :hint #x0
  (0 "MAYOR" "...FIRST THE FISHERMAN'S BOAT, (STUTTERS) IT'S ATTACKED BY A MONSTER...")
  (352)
  (395 "MAYOR" "AND NOW, NOW THIS... WHAT ELSE COULD GO WRONG?")
  )

("CHI-AM04" :hint #x0
  (0 "MAYOR" "I DON'T... I'D, I'D... OOH, MAYBE I SHOULD RAISE TAXES (STUTTERS) TO PAY FOR THIS MESS.")
  )

("CHI-AM05" :hint #x0
  (0 "MAYOR" "PROBLEMS... PROBLEMS... PROBLEMS!")
  )

("CHI-AM06" :hint #x0
  (0 "MAYOR" "(SOBS) I'LL NEVER GET RE-ELECTED NOW...")
  )

("CHI-AM07" :hint #x0
  (0 "MAYOR" "(MOANS) WHAT'S HAPPENED TO THE VILLAGE'S ENERGY BEAM?")
  )

("CHI-AM08" :hint #x0
  (0 "MAYOR" "I... THEY, I DON'T... (MUTTERS)")
  )

("CHI-LO01" :hint #x0
  (0 "MAYOR" "...WINDMILL, MONSTERS, POWER, RE-ELECTION...")
  )

("CHI-LO02" :hint #x0
  (0 "MAYOR" "...THE POLLS, I... MONSTERS, HM... RE-ELECTION, OH...")
  )

("SCU-AM01" :hint #x0
  (0 "SCULPTOR" "AW... I JUST CAN'T DO IT ANYMORE.")
  )

("SCU-AM02" :hint #x0
  (0 "SCULPTOR" "AW, I WISH I HAD SOME INSPIRATION.")
  )

("SCU-AM03" :hint #x0
  (0 "SCULPTOR" "I'M AS INSPIRED AS... THIS ROCK.")
  )

("SCU-AM04" :hint #x0
  (0 "SCULPTOR" "AW... WHERE IS MY MUSE?")
  )

("SCU-AM05" :hint #x0
  (0 "SCULPTOR" "I CAN'T WORK LIKE THIS!")
  )

("SCU-AM06" :hint #x0
  (0 "SCULPTOR" "AW MAN... WILL SHE EVER COME BACK TO ME?")
  )

("SCU-LO01" :hint #x0
  (0 "SCULPTOR" "AW MAN...")
  )

("bird-lady-beach-resolution"
  (30 "BIRDWATCHER" "OH MY, I HOPE THE POOR DEAR'S OKAY. HERE'S A POWER CELL FOR YOUR VALOR.")
  (243)
  (306 "FLUT FLUT" "MAMA!")
  (354)
  (406 "FLUT FLUT" "MAMA!")
  (430 "DAXTER" "OH NO! NO, NO, NO, NO!")
  (533)
  (535 "BIRDWATCHER" "LOOK... ISN'T THAT CUTE? IT THINKS YOU'RE ITS MAMA.")
  (696)
  (699 "DAXTER" "EH? I'M NOT YOUR MOM! YOU SEE ANY FEATHERS HERE?")
  (803)
  (807 "BIRDWATCHER" "OH, LOVE AT FIRST SIGHT! AH...")
  (936)
  (939 "BIRDWATCHER" "LISTEN, BOYS, I'LL TAKE THIS LITTLE CHICK BACK TO THE VILLAGE WITH ME")
  (1054 "BIRDWATCHER" "AND WORK WITH THE SAGE TO TAKE CARE OF HER.")
  )

("bird-lady-introduction"
  (125 "BIRDWATCHER" "OH MY, WHAT A HORRIBLY SICK LITTLE BIRD.")
  (245)
  (251 "DAXTER" "HUH! YOU DON'T LOOK SO GOOD YOURSELF, LADY!")
  (326)
  (331 "BIRDWATCHER" "OH, SORRY. I THOUGHT YOU WERE A SPOTTED ORANGE-BELLIED RAIN FRAY.")
  (454)
  (457 "BIRDWATCHER" "YOU KNOW, YESTERDAY I SAW SOME TERRIBLY VICIOUS CREATURES")
  (578 "BIRDWATCHER" "CAPTURE A MOTHER FLUT FLUT NEAR THE BEACH.")
  (648)
  (654 :offscreen "BIRDWATCHER" "NOW THERE'S THIS POOR LITTLE ORPHAN EGG SITTING IN A NEST AT THE TOP OF THE CLIFF")
  (796 :offscreen "BIRDWATCHER" "AND I CAN'T GET TO IT. IF YOU COULD CLIMB UP THERE AND PUSH IT OFF, I'VE PILED")
  (951 :offscreen "BIRDWATCHER" "SOME HAY DOWN AT THE BASE TO CATCH IT SAFELY.")
  (1041)
  (1044 "BIRDWATCHER" "DO AN OLD LADY A FAVOR, AND I'LL GIVE YOU A POWER CELL.")
  (1198)
  )

("bird-lady-reminder-1"
  (56 "BIRDWATCHER" "OH, HELLO AGAIN. DID YOU BOYS FIND THAT BLUE EGG ON THE CLIFF?")
  (208)
  (211 "BIRDWATCHER" "PUSH IT OFF THE EDGE AND I'LL GIVE YOU A POWER CELL!")
  (348)
  )

("bird-lady-reminder-2"
  (58 "BIRDWATCHER" "ARE YOU BOYS STILL PICKING AROUND HERE? HO HO HO.")
  (170)
  (174 "BIRDWATCHER" "I'LL BET THAT POOR LITTLE BLUE EGG ON THE CLIFF IS GETTING AWFULLY COLD BY NOW.")
  (313)
  (316 "BIRDWATCHER" "GO SAVE IT BY PUSHING IT OFF THE EDGE OF THE CLIFF, AND I'LL GIVE YOU A POWER CELL.")
  )

("mayor-introduction"
  (31 "MAYOR" "NO... (MUTTERS) DON'T TELL ME THAT YOU TWO HAVE PROBLEMS AS WELL!")
  (171)
  (174 "MAYOR" "FIRST I HEAR OF MONSTER SIGHTINGS NEAR THE VILLAGE, AND NOW THIS.")
  (313)
  (320 "MAYOR" "SEE THOSE GEARS UP THERE, BOYS? SEE THEM? SEE HOW THEY'RE NOT MOVING?")
  (479 "MAYOR" "THAT MEANS OUR VILLAGE HAS NO POWER!")
  (569)
  (578 "MAYOR" "THE ECO BEAM COMING FROM THE JUNGLE TEMPLE HAS BEEN INTERRUPTED!")
  (685)
  (689 "MAYOR" "AND BOYS, EVERYONE'S TOO FRIGHTENED TO GO OUT AND FIND OUT WHAT'S HAPPENED.")
  (850)
  (864 "DAXTER" "DID YOU PAY THE BILL?")
  (915)
  (917 "MAYOR" "YEAH-HMM? OH-HUH-OH, YOU'RE FUNNY.")
  (1071)
  (1074 "MAYOR" "NOW LOOK, IF YOU TWO FIX THE ECO BEAM, I'LL GIVE YOU A POWER CELL.")
  (1262 "MAYOR" "OH OOH OOH AND-AND ANOTHER THING, UH...")
  (1346 "MAYOR" "IF BY ANY CHANCE YOU'RE INTERESTED IN MAKING A CONTRIBUTION TO MY RE-ELECTION CAMPAIGN,")
  (1551 "MAYOR" "I-I MIGHT BE WILLING TO PART WITH YET ANOTHER POWER CELL!")
  (1668)
  (1671 "MAYOR" "THE MINIMUM CONTRIBUTION IS, OH, A VERY MODEST...")
  (1797 "MAYOR" "90 PRECURSOR ORBS.")
  )

("mayor-reminder-beams"
  (25 "MAYOR" "BACK ALREADY? AND WITHOUT FIXING THE ECO BEAMS?")
  (157 "MAYOR" "(SOBS) YOUR VILLAGE NEEDS YOU, BOYS!")
  )

("mayor-reminder-donation"
  (26 "MAYOR" "AH, HERE TO MAKE A DONATION TO MY CAMPAIGN, OH HO HO HO.")
  (159 "MAYOR" "90 PRECURSOR ORBS BUYS YOU A POWER CELL, THANK YOU.")
  )

("mayor-resolution-beams"
  (28 "MAYOR" "OH HO HO, WHAT A WONDERFUL SIGHT! I THANK YOU!")
  (205 "MAYOR" "AND THE ENTIRE VILLAGE WILL THANK ME -")
  (269 "MAYOR" "UH, BOYS, YOU HAVE RESTORED POWER TO THE VILLAGE AND GUARANTEED MY RE-ELECTION!")
  (472)
  (475 "MAYOR" "AND FOR THAT, MY BOY, YOU'VE EARNED A POWER CELL.")
  )

("mayor-resolution-donation"
  (28 "MAYOR" "SO EH, YOU UH, WANNA MAKE A CONTRIBUTION? GOOD... A-A-A SIZABLE ONE I HOPE.")
  (219)
  (224 "MAYOR" "YOOH! EH HE HE, IT'S A, OH, THIS IS A SIZABLE CONTRIBUTION!")
  (365 "MAYOR" "I, WH-WH-WH-WHY I JUST HOPE THIS POWER CELL ADEQUATELY REPRESENTS MY GRATITUDE.")
  )

("sagevb01" :hint #x288
  (0 "SAGE" "WELL, I SEE THAT YOU TWO HAVE FINALLY DECIDED TO UNBLOCK MY COLLECTORS.")
  (347)
  (352 "SAGE" "I WOULD OFFER MY CONGRATULATIONS, BUT YOU HAVE SO MUCH TO DO I WON'T WASTE YOUR TIME.")
  (705)
  (712 "SAGE" "BY THE WAY, IF THINGS DON'T WORK OUT,")
  (884 "SAGE" "DAXTER COULD ALWAYS GET A JOB CONTROLLING THE VILLAGE RAT PROBLEM.")
  (1116 "SAGE" "NYEH HA HA HA HA.")
  )

("sculptor-introduction"
  (30 "SCULPTOR" "HEY... LITTLE FURRY DUDE!")
  (154)
  (161 "SCULPTOR" "AWW... I THOUGHT FOR A MOMENT YOU WERE MY MUSE.")
  (282)
  (285 "DAXTER" "YOUR WHAT?")
  (334)
  (343 "SCULPTOR" "HAVEN'T YOU EVER SEEN A MUSE BEFORE?")
  (430)
  (434 "SCULPTOR" "IT'S A LITTLE GLOWIN' SQUIRREL ABOUT YOUR SIZE, FULL OF SPUNK, AND CRAZY AS A LARK!")
  (622)
  (632 "DAXTER" "OH, I GET IT! LIKE A SIDEKICK.")
  (757)
  (763 "SCULPTOR" "AS A MATTER OF FACT, WITHOUT MY MUSE, I JUST CAN'T SCULPT.")
  (920)
  (923 "SCULPTOR" "BUT WITH HER AROUND... I SEE BEAUTY IN EVERYTHING, YOU KNOW?")
  (1087)
  (1091 "SCULPTOR" "RIGHT NOW I COULDN'T CHISEL MY WAY OUT OF A BOX.")
  (1182)
  (1191 :offscreen "SCULPTOR" "I THINK SHE RAN AWAY TO THAT MISTY ISLAND.")
  (1278)
  (1281 "SCULPTOR" "AWW, I JUST HOPE SHE'S ALL RIGHT.")
  (1370)
  (1376 "SCULPTOR" "IT'S WORTH A POWER CELL IF YOU BRING HER BACK TO ME!")
  (1441)
  (1467 "DAXTER" "WAIT A MINUTE! WE ARE NOT GOING BACK TO MISTY ISLAND!")
  (1646)
  (1649 "DAXTER" "ARE WE?")
  )

("sculptor-reminder-1"
  (27 "SCULPTOR" "AW HEY DUDES! DID YOU FIND MY MUSE YET?")
  (169)
  )

("sculptor-resolution"
  (87 "SCULPTOR" "OH, MY MUSE! YOU SAVED HER! AW, YOU REALLY ARE THE BEST!")
  (230 "SCULPTOR" "HERE, TAKE THIS POWER CELL. I WON'T NEED IT NOW THAT I HAVE MY INSPIRATION BACK!")
  )

("sksp0019" :hint #x236
  (0 "DAXTER" "HEY, SEAGULLS! LET'S BUZZ 'EM FOR KICKS.")
  )

("sksp0020" :hint #x268
  (0 "DAXTER" "YEAH HA HA! LET'S DO THAT AGAIN!")
  )

("sksp0022" :hint #x26a
  (0 "DAXTER" "YEAH HA HA HA HA HA!! WOO HO HO HO!")
  )

("sksp0023" :hint #x26b
  (0 "DAXTER" "WOOHOO!")
  )

("sksp0024" :hint #x26c
  (0 "DAXTER" "YEAH HA HA! YEAH!")
  )

("sksp0025" :hint #x273
  (0 "DAXTER" "WHOA! THEY CAUSED AN AVALANCHE! LET'S CHECK IT OUT.")
  )

("sksp0026" :hint #x237
  (0 "DAXTER" "HEY! THAT PELICAN JUST SNAGGED A POWER CELL!")
  (197)
  (200 "DAXTER" "LET'S GO KICK SOME BIG BIRD BUTT!")
  )

("sksp0027" :hint #x274
  (0 "DAXTER" "QUICK! WE HAVE TO GET TO THE POWER CELL BEFORE THE PELICAN SCOOPS IT UP AGAIN.")
  )

("sksp0029" :hint #x275
  (0 "DAXTER" "EH, WE MIGHT WANNA TALK TO THE BIRDWATCHER")
  (125 "DAXTER" "AND SEE IF WE SCRAMBLED THAT FLUT FLUT EGG.")
  )

("sksp0030" :hint #x239
  (0 "DAXTER" "HEY, TRY PUNCHING THE ROCKS TO GET 'EM OUT OF THE WAY!")
  )

("sksp0034" :hint #x23b
  (0 "DAXTER" "AWOOGA! AWOOGA! DIVE FOR THOSE ORBS, JAK, DIVE!")
  )

("sksp0443" :hint #x2af
  (0 "DAXTER" "PUNCH THOSE POLES UP FROM BELOW!")
  )

;; -----------------
;; jungle
;; -----------------

("FIS-AM01" :hint #x0
  (0 "FISHERMAN" "GRR, THESE DARN FISH... I NEVER CATCH ME A SINGLE ONE.")
  )

("FIS-AM02" :hint #x0
  (0 "FISHERMAN" "THEM MONSTERS THAT DONE BIT ME SHIP WILL DRIVE ME BROKE.")
  )

("FIS-AM03" :hint #x0
  (0 "FISHERMAN" "DRAT, THESE BLIGHTERS!")
  (135 "FISHERMAN" "IN ME BASKET, DARN FISHIES, COME ON YEAH...")
  (419)
  (425 "FISHERMAN" "HEH HE HE HE HE...")
  )

("FIS-AM04" :hint #x0
  (0 "FISHERMAN" "OH I LOVE THE SMELL OF FISH IN THE MORNIN'.")
  )

("FIS-AM05" :hint #x0
  (0 "FISHERMAN" "OOH I COULD USE ME A SALTED FISH LIPS ON RYE.")
  )

("FIS-AM06" :hint #x0
  (0 "FISHERMAN" "I 'MEMBER THE BIG ONE THAT GOT AWAY...")
  )

("FIS-LO01" :hint #x0
  (0 "FISHERMAN" "GRR!")
  )

("FIS-LO03" :hint #x0
  (0 "FISHERMAN" "HA HA HA HA HA HAH!")
  )

("FIS-LO04" :hint #x0
  (0 "FISHERMAN" "DARN FISH... THEY NEVER GET IN ME NET!")
  )

("FIS-LO05" :hint #x0
  (0 "FISHERMAN" "HA HA HA AH HA HA HA HAH!")
  )

("FIS-TA01" :hint #x0
  (0 "FISHERMAN" "TO THE LEFT!")
  )

("FIS-TA02" :hint #x0
  (0 "FISHERMAN" "RIGHT WITH YA!")
  )

("FIS-TA03" :hint #x0
  (0 "FISHERMAN" "HERE COMES A BIG ONE!")
  )

("FIS-TA04" :hint #x0
  (0 "FISHERMAN" "YE MISSED A JUMBO, LADDIE!")
  )

("FIS-TA05" :hint #x0
  (0 "FISHERMAN" "DON'T MISS ONE LIKE THAT AGAIN!")
  )

("FIS-TA06" :hint #x0
  (0 "FISHERMAN" "STEADY BOY.")
  )

("FIS-TA07" :hint #x0
  (0 "FISHERMAN" "YOUR SAILS ARE SAGGING IN THE WIND, BOY.")
  )

("FIS-TA08" :hint #x0
  (0 "FISHERMAN" "MISSED.")
  )

("FIS-TA09" :hint #x0
  (0 "FISHERMAN" "LOOKS LIKE YOU COULD USE A BIGGER NET...")
  )

("FIS-TA10" :hint #x0
  (0 "FISHERMAN" "MISSED AGAIN!")
  )

("FIS-TA11" :hint #x0
  (0 "FISHERMAN" "HOLD STEADY! YOU'RE ALMOST THERE...")
  )

("FIS-TA1A" :hint #x0
  (0 "FISHERMAN" "LEFT!")
  )

("FIS-TA2A" :hint #x0
  (0 "FISHERMAN" "RIGHT!")
  )

("asstvb02" :hint #x289
  (0 "KEIRA" "WOW, DID YOU SEE THAT? BLUE ECO VENTS HAVE BEEN ACTIVATED ALL OVER THE WORLD!")
  (305)
  (315 "KEIRA" "I KNEW THERE WAS A WAY TO TURN THEM ON.")
  (435)
  (442 "KEIRA" "THERE MUST BE PLACES TO TURN ON THE OTHER ECO VENTS AS WELL.")
  )

("fisher-accept"
  (0 :offscreen "FISHERMAN" "THERE ARE TWO TYPES OF GOOD FISH TO CATCH: ONE-POUND FISHIES, AND FIVE-POUND FISHIES.")
  (220 :offscreen "FISHERMAN" "HEH. IF YOU MISS 20 POUNDS OF GOOD FISH, THEN I'M GONNA TAKE ME NET BACK FROM YA!")
  (432)
  (438 :offscreen "FISHERMAN" "THERE ARE POISONOUS EELS IN THIS RIVER.")
  (542)
  (545 :offscreen "FISHERMAN" "CATCH EVEN ONE OF THEM BOOGERS, AND YOU'LL POISON THE WHOLE DARN CATCH!")
  )

("fisher-introduction"
  (0 "DAXTER" "WHAT DO YOU HAVE IN THE BASKET?")
  (50 "FISHERMAN" "NOTHING TO TALK ABOUT.")
  (103)
  (106 "FISHERMAN" "THEM MONSTERS PATROLIN' THE OCEAN TOOK A BITE OUT OF ME FISHIN' RIG.")
  (226)
  (229 "FISHERMAN" "AND NOW THEY'RE GOBLIN' UP ME CATCH!")
  (290)
  (293 "FISHERMAN" "NO MATTER WHAT I TRY, I CAN'T SEEM TO CATCH A SINGLE FISH IN THIS RIVER.")
  (419)
  (425 "DAXTER" "WHOO! MAYBE... IT'S YOUR BREATH.")
  (515)
  (521 "FISHERMAN" "YOU THINK YOU CAN DO BETTER? TRY SCOOPIN' UP RIVER FISH WITH A TINY NET!")
  (665)
  (671 "FISHERMAN" "I'LL GIVE YOU A POWER CELL IF YOU CAN CATCH 200 POUNDS OF THEM CRITTERS!")
  (808)
  (814 "FISHERMAN" "AND I'LL LET YOU AND SHRIMP HERE USE MY SPEEDBOAT TO GET TO MISTY ISLAND.")
  (955)
  (961 "FISHERMAN" "YOU'S WANT TO TRY THE CHALLENGE?")
  )

("fisher-reject"
  (2 "FISHERMAN" "WELL, IF YOU WANT TO TRY FOR THE POWER CELL SOMETIME, YOU KNOW WHERE TO FIND ME.")
  )

("fisher-reminder-1"
  (6 "FISHERMAN" "WANT TO TRY AND BEAT THE RIVER, DO YA?")
  )

("fisher-resolution"
  (0 "FISHERMAN" "YOU DID IT! YOU CAUGHT 200 POUNDS OF FISH!")
  (115)
  (120 "FISHERMAN" "NOT BAD FOR A COUPLE OF LAND LUBBERS!")
  (185)
  (199 "FISHERMAN" "HERE'S THE POWER CELL I PROMISED, AND YOU CAN USE MY BOAT IN THE VILLAGE DOCK")
  (351 "FISHERMAN" "WHENEVER YOU LIKE!")
  )

("sksp0011" :hint #x240
  (0 "DAXTER" "WE SHOULD ASK THE FISHERMAN DOWN BY THE JUNGLE RIVER")
  (136 "DAXTER" "IF WE CAN BORROW HIS SPEEDBOAT TO ZOOM ON OVER TO MISTY ISLAND!")
  )

("sksp0018" :hint #x25e
  (0 "DAXTER" "WE SHOULD GO TELL THAT WINDBAG OF A MAYOR THAT HE OWES US BIG TIME")
  (223 "DAXTER" "FOR CONNECTING THE VILLAGE ENERGY BEAM!")
  )

("sksp0037" :hint #x25f
  (0 "DAXTER" "THOSE TOWER DOOHICKEYS SCATTERED ALL OVER THE JUNGLE MUST REDIRECT THE ECO BEAM.")
  (214)
  (220 "DAXTER" "LET'S GO FIDDLE WITH THEM!")
  )

("sksp0038" :hint #x23c
  (0 "DAXTER" "HMM, IF BLUE ECO CAN BUILD A BRIDGE, THEN I BET IT'LL OPEN A DOOR!")
  (275)
  (281 "DAXTER" "LET'S GO BACK AND GET YOU JUICED UP AGAIN.")
  )

("sksp0039" :hint #x25b
  (0 "DAXTER" "HEY, THERE'S LITTLE LIGHTNING MARKS ON THOSE POSTS")
  (202 "DAXTER" "AND THERE'S LIGHTNING COMING OUT OF THAT VENT OVER THERE.")
  (391)
  (400 "DAXTER" "ARE YOU THINKING WHAT I'M THINKING?")
  )

("sksp0040" :hint #x23d
  (0 "DAXTER" "LET'S GET UP ON THAT MACHINE AND BREAK THE MIRROR DIVERTING THE PRECURSOR BEAM!")
  )

("sksp0041" :hint #x23e
  (0 "DAXTER" "WE NEED TO GET TO THE TOP OF THAT TOWER!")
  )

("sksp0049" :hint #x29c
  (0 "DAXTER" "LINE UP THE BEAM BY POINTING IT AT THE NEXT TOWER!")
  )

("sksp0050" :hint #x29d
  (0 "DAXTER" "BREAK THE MIRROR, JAK!")
  )

("sksp0051" :hint #x29e
  (0 "DAXTER" "GET THE BUGS, JAK! GET THE BUGS!")
  )

("sksp0052" :hint #x29f
  (0 "DAXTER" "LET'S GO TO THE NEXT TOWER AND RECONNECT THE BEAM THERE!")
  )

("sksp0053" :hint #x2a0
  (0 "DAXTER" "HEY! WE CAN FOLLOW THE BEAM TO FIND THE NEXT TOWER.")
  )

("sksp0054" :hint #x2a1
  (0 "DAXTER" "WE NEED TO CHARGE YOU UP WITH THAT BLUE STUFF TO GET THIS OPEN!")
  )

("sksp0b42" :hint #x278
  (0 "DAXTER" "STOP MISSING THE YELLOW FISH, THEY WEIGH FIVE POUNDS EACH! AND THAT'S A LOTTA FISH, JAK.")
  )

;; -----------------
;; misty
;; -----------------

("asstvb03" :hint #x28b
  (0 "KEIRA" "GOOD! YOU STOPPED ALL THE MINE-DROPPING LURKERS!")
  (190 "KEIRA" "THEY'VE BEEN THREATENING THE WATERS AROUND OUR VILLAGE FOR WEEKS.")
  (391 "KEIRA" "BRING YOUR ZOOMER BACK TO THE TRANS-PAD AND I'LL TELEPORT IT BACK.")
  )

("sagevb02" :hint #x28a
  (6 "SAGE" "I HAVE TO ADMIT, I'M IMPRESSED. YOU TWO DIDN'T SCREW UP!")
  (385)
  (400 "SAGE" "NOW THAT THE LURKERS CAN'T OPEN THAT SILO, THEY CAN'T FLOOD THE WORLD WITH DARK ECO")
  (710 "SAGE" "AND CAUSE UNTOLD DESTRUCTION.")
  (863)
  (880 "SAGE" "WIPE THAT RIDICULOUS GRIN OFF YOUR FACE, DAXTER! THE TWO OF YOU HAVE PLENTY TO DO.")
  (1191 "SAGE" "GET ON WITH IT!")
  )

("sksp0031" :hint #x23a
  (0 "DAXTER" "OOH! LET'S USE THE CANNON TO BLOW THINGS UP!")
  )

("sksp0056" :hint #x27b
  (0 "DAXTER" "HEY! I SEE THE SCULPTOR'S MUSE!")
  )

("sksp0059" :hint #x26e
  (0 "DAXTER" "THIS PLACE GIVES ME THE WILLIES! LET'S KEEP YOU OUT OF THE OOZE, OKAY?")
  )

("sksp0060" :hint #x26f
  (0 "DAXTER" "(WHIMPERS) THIS PLACE GIVES ME THE CREEPS! AND TRUST ME, IT'S A WHOLE NEW EXPERIENCE")
  (337 "DAXTER" "WHEN YOU'RE COVERED IN FUZZ!")
  )

("sksp0062" :hint #x27e
  (0 "DAXTER" "LET'S PLOW INTO THOSE BALLOON LURKERS AND SHRED 'EM!")
  )

("sksp0063" :hint #x27f
  (0 "DAXTER" "I SAID \"SHRED THE LURKERS,\" JAK. NOT THE MINES!")
  (332)
  (344 "DAXTER" "RULE NUMBER ONE: ALWAYS AVOID THE MINES!")
  )

("sksp0064" :hint #x245
  (0 "DAXTER" "WATCH YOUR BACK! YOU REMEMBER WHAT HAPPENED THE LAST TIME WE WERE HERE.")
  )

("sksp0067" :hint #x249
  (0 "DAXTER" "DON'T FALL INTO THE MIST BELOW US! 'CAUSE I DON'T THINK WE'LL MAKE IT BACK.")
  )

("sksp0069" :hint #x2a3
  (0 "DAXTER" "IT'S AN AMBUSH, JAK! IT'S AN AMBUSH!")
  )

("sksp0070" :hint #x2a4
  (0 "DAXTER" "JUMP, THEN DIVE ONTO THE TEETER-TOTTER.")
  )

("sksp0435" :hint #x2aa
  (0 "DAXTER" "KNOCK OVER THOSE BONES!")
  )

;; -----------------
;; firecanyon
;; -----------------

("assistant-firecanyon-resolution"
  (25 "KEIRA" "GREAT! YOU HAVE THE 20 CELLS NEEDED TO POWER MY HEAT SHIELD!")
  (140)
  (143 "KEIRA" "NOW BE CAREFUL, THE SHIELD WILL ONLY PROTECT YOUR ZOOMER TILL IT REACHES 500 DEGREES,")
  (295 "KEIRA" "SO TRY TO KEEP HER COOL.")
  (343)
  (346 :offscreen "KEIRA" "FLYING OVER OPEN LAVA WILL DEFINITELY HEAT YOU UP FAST.")
  (458)
  (462 "KEIRA" "HIT 500 DEGREES, AND IT'S OVER.")
  (546)
  (552 "DAXTER" "OVER?! LIKE BURNING MOLTEN METAL OVER?!")
  (636)
  (639 "KEIRA" "THE FIRE CANYON GETS PRETTY HOT, SO KEEP A LOOK OUT FOR JUMPS")
  (745 "KEIRA" "TO KEEP YOU OFF THE HOT GROUND.")
  (792)
  (795 :offscreen "KEIRA" "I'VE ALSO RELEASED SEVERAL BLUE COOLING BALLOONS YOU CAN USE TO DROP")
  (895 :offscreen "KEIRA" "THE SHIELD'S TEMPERATURE QUICKLY.")
  (956)
  (962 "KEIRA" "OH! AND WHEN YOU GET ACROSS, DON'T FORGET TO ACTIVATE")
  (1063 "KEIRA" "THE TELEPORT GATE IN THE BLUE SAGE'S LAB.")
  (1140)
  (1146 "KEIRA" "THEN WE'LL BE ABLE TO TELEPORT OVER AND MEET YOU!")
  (1222)
  (1228 "KEIRA" "GOOD LUCK!")
  )

("asstvb09" :hint #x24f
  (0 "KEIRA" "YOU DON'T HAVE ENOUGH POWER CELLS TO FUEL MY HEAT SHIELD.")
  (216)
  (234 "KEIRA" "YOU CAN'T CROSS FIRE CANYON UNTIL YOU COLLECT ENOUGH POWER CELLS.")
  )

("sksp0076" :hint #x501
  (0 "DAXTER" "JAK, HIT SOME JUMPS TO KEEP US OFF THE HOT GROUND!")
  )

("sksp0077" :hint #x502
  (0 "DAXTER" "BALLOONS GOOD, BURNING HOT MAGMA BAD!")
  )

("sksp0078" :hint #x503
  (0 "DAXTER" "RIDE ON THE RAISED PRECURSOR STUFF TO KEEP US COOL.")
  )

("sksp0079" :hint #x504
  (0 "DAXTER" "AHH! I'M GONNA DIE! I'M A COMING, GRANDPAP!")
  (257)
  (270 "DAXTER" "YOU HAVE TO GET THIS THING TO THE OTHER SIDE BEFORE IT OVERHEATS!")
  )

("sksp0080" :hint #x505
  (0 "DAXTER" "USE THE HOP-TURN TO STEER HARDER!")
  )

("sksp0081" :hint #x506
  (0 "DAXTER" "AHH! MAYBE I SHOULD DRIVE!")
  )

("sksp0082" :hint #x507
  (0 "DAXTER" "YOU ARE TRYING TO AVOID THOSE DARK ECO BOXES, RIGHT?")
  )

("sksp0083" :hint #x508
  (0 "DAXTER" "OOH! SEE IF WE CAN CATCH AIR OFF THOSE LURKERS!")
  )

("sksp0084" :hint #x509
  (0 "DAXTER" "TOO CLOSE, TOO CLOSE!")
  )

("sksp0085" :hint #x50a
  (0 "DAXTER" "WHOA! THIS BABY'S GETTING WAY TOO HOT!")
  )

("sksp0086" :hint #x50b
  (0 "DAXTER" "A FEW MORE SECONDS AND WE'RE FRIED FLUT FLUT!")
  )

("sksp0087" :hint #x50d
  (0 "DAXTER" "HIT THOSE BALLOONS TO COOL OFF!")
  )

("sksp0088" :hint #x50e
  (0 "DAXTER" "HERE COMES ANOTHER BALLOON!")
  )

("sksp0089" :hint #x50f
  (0 "DAXTER" "I WISH I SLEPT IN THIS MORNING!")
  )

("sksp0090" :hint #x510
  (0 "DAXTER" "YOU MISSED A BALLOON! WE NEED THOSE OR WE'RE COOKED!")
  )

("sksp0091" :hint #x511
  (0 "DAXTER" "THIS PUPPY'S GETTING TOO HOT!")
  )

("sksp0092" :hint #x512
  (0 "DAXTER" "DO YOU SMELL SOMETHING BURNING?!")
  )

("sksp0093" :hint #x513
  (0 "DAXTER" "I THINK MY TAIL'S ON FIRE!")
  )

("sksp0094" :hint #x514
  (0 "DAXTER" "SHE'S GONNA BLOW!")
  )

("sksp0095" :hint #x515
  (0 "DAXTER" "WAHOO! WE MADE IT!")
  )

("sksp0096" :hint #x516
  (0 "DAXTER" "THERE'S SCOUT FLIES OUT HERE, TOO!")
  )

;; -----------------
;; swamp
;; -----------------

("billy-accept"
  (5 "BILLY" "GOOD! THOSE RATS WILL BE BACK ANYTIME.")
  (109 "BILLY" "SHOOT ALL THEM RATS, AND KEEP 'EM FROM EATING AT LEAST ONE OF THEM SNACKS.")
  )

("billy-introduction"
  (6 "BILLY" "HOWDY, FRIENDS! ENJOYIN' MY BEAUTIFUL SWAMP? I OWN THESE HERE PARTS. EVERYTHING THAT DOESN'T SINK INTO THE MUD, THAT IS! HA HA HA...")
  (349)
  (369 "DAXTER" "JUDGING BY THE SMELL, I'D WAGER YOUR BATHTUB SANK IN THE MUD LONG AGO.")
  (497)
  (519 "BILLY" "WHAT'S A BATHTUB? ANYWAY I GOT BIGGER PROBLEMS NOW...")
  (677)
  (691 "BILLY" "SEEMS SOME NASTY LURKER VARMINTS ARE GROUSIN' ABOUTS SNATCHIN' EVERYTHING THEY CAN GET THEIR GRUBBY LITTLE PAWS ON.")
  (910 "BILLY" "AND SCARED AWAY MY PET HIPHOG, FARTHY.")
  (1000 "BILLY" "HE'S BEEN MISSIN' FOR NIGH ON TO A COON'S AGE.")
  (1136 :offscreen "BILLY" "I'VE BEEN PUTTIN' OUT HIS FAVORITE SNACK, BUT THOSE ORNERY SWAMP RATS KEEP STEALIN' EM!")
  (1318 :offscreen "BILLY" "IF YOU COULD KEEP THOSE PESKY CRITTERS AWAY LONG ENOUGH, I JUST KNOW FARTHY WOULD SMELL THEM VITTLES AND COME BACK!")
  (1509)
  (1527 "BILLY" "WILL YA HELP ME OUT?")
  )

("billy-reject"
  (7 "BILLY" "WELL, IF YOU CHANGE YOUR MIND, YOU KNOW WHERE TO FIND ME! (LAUGHS)")
  )

("billy-reminder-1"
  (36 "BILLY" "AHH, Y'ALL BACK TO HELP STOP THEM RATS?")
  )

("billy-resolution"
  (1 "BILLY" "WELL FRY MY HIDE! YOU SURE KNOW HOW TO SHOOT! THANKS A HEAP FOR THE HELP.")
  )

;; -----------------
;; citadel
;; -----------------

("BLU-AM01" :hint #x0
  (0 "SAGGIO BLU" "UN PO' DI AIUTO SAREBBE UTILE!")
  )

("BLU-AM02" :hint #x0
  (0 "SAGGIO BLU" "AH, QUESTO È UN BEL GUAIO.")
  )

("BLU-AM03" :hint #x0
  (0 "SAGGIO BLU" "HMM, CI TROVIAMO DI FRONTE A UN BELL'ENIGMA.")
  )

("RED-AM01" :hint #x0
  (0 "SAGGIO ROSSO" "C'È NESSUNO?")
  )

("RED-AM02" :hint #x0
  (0 "SAGGIO ROSSO" "BENE...")
  )

("RED-AM03" :hint #x0
  (0 "SAGGIO ROSSO" "COSA VI HA TRATTENUTO?")
  )

("YEL-AM01" :hint #x0
  (0 "SAGGIO GIALLO" "IL TEMPO STA PER SCADERE!")
  )

("YEL-AM02" :hint #x0
  (0 "SAGGIO GIALLO" "HEY! PORTATEMI FUORI DI QUI!")
  )

("YEL-AM03" :hint #x0
  (0 "SAGGIO GIALLO" "QUANDO SARÒ FUORI DI QUI, INIZIERÀ UNA SPARATORIA!")
  )

("bluesage-resolution"
  (63 "SAGGIO BLU" "GRAN BEL LAVORO, RAGAZZI! SAMOS AVEVA RAGIONE SU DI VOI!")
  (162)
  (165 "SAGGIO BLU" "GIÀ, BELL'AMMASSO DI METALLO PRECURSOR!")
  (253 "SAGGIO BLU" "QUELLA PERICOLOSA CREATURA MECCANICA NON DOVRÀ MAI RIUSCIRE A SPRIGIONARE IL SUO TERRIBILE POTERE!")
  (420 "SAGGIO BLU" "QUINDI, PROVERÒ A METTERE IN FUNZIONE LO SCUDO, CREANDO UN CONDOTTO D'ENERGIA")
  (554 "SAGGIO BLU" "TRA ME E L'ENORME VARCO CHE SI TROVA AL DI SOTTO DI ESSA!")
  (677 "DAXTER" "AH... BRAVO. CE L'HAI FATTA. ALLORA NOI... ANDIAMO SUBITO A CERCARE AIUTO.")
  (873)
  (899 :offscreen "DAXTER" "MOLTO STRANO...")
  (980)
  )

("green-sagecage-introduction"
  (134 "SAMOS" "ERA ORA CHE VI FACESTE VIVI!")
  (216 "DAXTER" "ANCHE NOI SIAMO FELICI DI VEDERTI. TI HANNO MESSO A PULIRE PER TERRA ORA?")
  (350 "SAMOS" "NON È IL MOMENTO DI SCHERZARE, DAXTER. GOL E MAIA CI HANNO RAPITO")
  (477 "SAMOS" "PER ASSORBIRE LE NOSTRE ENERGIE E DARE POTENZA ALLA LORO TERRIBILE MACCHINA.")
  (574)
  (610 :offscreen "SAMOS" "SEMBRA CHE ABBIANO MONTATO CIÒ CHE RIMANEVA DI UN ROBOT PRECURSOR")
  (721 :offscreen "SAMOS" "CON ALCUNI MANUFATTI TROVATI SCAVANDO NELLA ZONA.")
  (800)
  (812 :offscreen "SAMOS" "E CHE QUINDI ABBIANO AGGIUNTO ALTRE DIAVOLERIE CREATE DA LORO,")
  (921 :offscreen "SAMOS" "DANDO VITA AD UN MOSTRO IN GRADO DI APRIRE I SILOS DELL'ECO OSCURO.")
  (1070 "SAMOS" "SE RIESCI A LIBERARCI TUTTI E QUATTRO, POTREMO UNIRE I NOSTRI POTERI")
  (1189 "SAMOS" "E DISTRUGGERE LO SCUDO ENERGETICO INTORNO AL ROBOT, PRIMA CHE POSSANO DISTRUGGERE IL MONDO.")
  )

("green-sagecage-outro-preboss"
  (75 "GOL" "SEI ARRIVATO TROPPO TARDI, SAMOS.")
  (173 "GOL" "QUANDO AVRÒ UNA QUANTITÀ ILLIMITATA DI ECO OSCURO, ANCHE LA CHIAVE DELLA CREAZIONE SARÀ MIA!")
  (335 "SAMOS" "MA QUESTA È UNA FOLLIA! LIBERARE COSÌ TANTO ECO OSCURO DISTRUGGERÀ TUTTO CIÒ CHE CONOSCIAMO!")
  (519 "SAMOS" "CONSIDERA BENE QUELLO CHE È SUCCESSO A TE!")
  (578)
  (583 "MAIA" "CI HA DATO UNA BELLEZZA SUPERIORE A TUTTO CIÒ CHE VOI POTETE CAPIRE.")
  (693)
  (704 "DAXTER" "BELLEZZA? VI SIETE GUARDATI BENE ALLO SPECCHIO DI RECENTE?!")
  (825)
  (834 "MAIA" "ASPETTA FINO A QUANDO NON AVREMO APERTO TUTTI I SILOS, PICCOLETTO! TU CHE NE DICI, TI VA BENE BASSO E PELOSO?")
  (1043 "GOL" "E PENSARE, CHE VOI DUE SIETE ARRIVATI FIN QUI PER CERCARE IL MIO AIUTO.")
  (1190 "GOL" "PAZZI! DIVERTITEVI CON UN POSTO IN PRIMA FILA NELLA NUOVA CREAZIONE DEL MONDO!")
  (1391)
  (1609 "SAMOS" "JAK! SALI SULL'ASCENSORE, PRESTO! E FERMA SUBITO QUEL ROBOT!")
  )

("green-sagecage-resolution"
  (45 "SAMOS" "BEL LAVORO, RAGAZZI! ORA SIETE DEI VERI EROI.")
  (172 "SAMOS" "UNIRÒ I POTERI DELL'ECO VERDE CON QUELLI DEGLI ALTRI TRE SAGGI")
  (283 "SAMOS" "PER APRIRE UN VARCO NELLA BARRIERA ENERGETICA INTORNO AL ROBOT PRECURSOR.")
  (415 "DAXTER" "SÌ SÌ MI SEMBRA UN BUON INIZIO.")
  (474 "DAXTER" "MA DOPO CHE AVRETE APERTO IL VARCO, CHE COSA PENSATE DI FARE AL ROBOT?")
  (584 "SAMOS" "NIENTE, DAXTER. NOI DOVREMO GIÀ TENERE LO SCUDO APERTO.")
  (720 "SAMOS" "ECCO... VI DOVRETE OCCUPARE VOI DI DISTRUGGERE IL ROBOT.")
  (836 "DAXTER" "OH, OTTIMO. DEVO AIUTARE IL TIPO CHE MI HA TRASFORMATO IN UNA PALLA DI PELO")
  (995 "DAXTER" "A DISTRUGGERE L'UNICA PERSONA IN GRADO DI FARMI TORNARE NORMALE!")
  (1111)
  (1172 "SAMOS" "PER PRIMA COSA SALVATE IL MONDO, POI CERCHEREMO DI CONVINCERE GOL AD AIUTARE DAXTER.")
  )

("redsage-resolution"
  (62 "SAGGIO ROSSO" "HEHEHEH, ALLA FINE SIETE ARRIVATI A SALVARMI.")
  (190 "SAGGIO ROSSO" "SAPETE DA QUANTO TEMPO SONO QUI? PERCHÉ CI AVETE IMPIEGATO TANTO? BENE... HEHEHEH")
  (378 "SAGGIO ROSSO" "DUNQUE, COME VI CHIAMATE?")
  (429)
  (443 "DAXTER" "IO SONO DAXTER. LUI È JAK, È CON ME.")
  (548 :offscreen "SAGGIO ROSSO" "BEL LAVORO, DAXTER. SEI UN VERO EROE!")
  (677)
  (711 "SAGGIO ROSSO" "ECCO, DEVI EVITARE CHE GOL LANCI IL SUO ROBOT.")
  (845 "SAGGIO ROSSO" "IO UTILIZZERÒ, VEDIAMO UN PO', IL MIO POTERE DELL'ECO PER APRIRE LO SCUDO.")
  )

("sksp0378" :hint #x813
  (0 "DAXTER" "LA PORTA È APERTA, ANDIAMO!")
  )

("sksp0381" :hint #x806
  (0 "DAXTER" "DISTRUGGI IL GENERATORE PER LIBERARE IL SAGGIO!")
  )

("sksp0382" :hint #x807
  (0 "DAXTER" "RIMANI ATTACCATO AL BORDO!")
  )

("sksp0383" :hint #x808
  (0 "DAXTER" "ABBIAMO COMPAGNIA, JAK. UN BEL PO' DI LURKERS!")
  )

("sksp0384" :hint #x809
  (0 "DAXTER" "DISTRUGGI QUEI GENERATORI!")
  )

("sksp0385" :hint #x80a
  (0 "DAXTER" "PREMI IL PULSANTE!")
  )

("sksp0386" :hint #x80b
  (0 "DAXTER" "QUEL ROBOT NON MI SPAVENTA!")
  )

("sksp0387" :hint #x80c
  (0 "DAXTER" "SALIAMO SU QUELLE PIATTAFORME!")
  )

("sksp0388" :hint #x80d
  (0 "DAXTER" "NON MANCARE IL PROSSIMO LANCIATORE!")
  )

("sksp0389" :hint #x80e
  (0 "DAXTER" "ATTENTO!")
  )

("sksp0390" :hint #x80f
  (0 "DAXTER" "DOBBIAMO LIBERARE TUTTI I SAGGI!")
  )

("sksp0391" :hint #x810
  (0 "DAXTER" "PENSI CHE GOL MI RITRASFORMERÀ LO STESSO?")
  )

("sksp0392" :hint #x811
  (0 "DAXTER" "ALLORA QUESTA È LA CITTADELLA DI GOL E MAIA. CARINA E GRADEVOLE.")
  )

("sksp0393" :hint #x812
  (0 "DAXTER" "ATTERRA SUL LANCIATORE SUCCESSIVO!")
  )

("yellowsage-resolution"
  (57 "SAGGIO GIALLO" "CHI POTEVA PENSARE CHE SAREI VISSUTO FINO A VEDERE")
  (152 "SAGGIO GIALLO" "IL GIORNO IN CUI SAREI STATO SALVATO DA UN RAGAZZO E DAL SUO TOPO MUSCHIATO!")
  (285 "SAGGIO GIALLO" "EH... GLIELA FARÒ PAGARE A CARA A GOL E MAIA PER QUESTO MOMENTO A DIR POCO IMBARAZZANTE.")
  (471)
  (492 "SAGGIO GIALLO" "POI DECIDERÒ SE MANGIARE DEL BUON TOPO MUSCHIATO IN UMIDO...")
  (605)
  )

;; -----------------
;; finalboss
;; -----------------

("GOL-AM01" :hint #x0
  (0 "GOL" "MICA TI VORRAI ARRENDERE, VERO?")
  )

("GOL-AM02" :hint #x0
  (0 "GOL" "PRESTO, L'ECO OSCURO SARÀ NOSTRO!")
  )

("GOL-AM03" :hint #x0
  (0 "GOL" "FINISCILI!")
  )

("GOL-AM04" :hint #x0
  (0 "GOL" "FUOCO!")
  )

("GOL-AM05" :hint #x0
  (0 "GOL" "DISTRUGGILI!")
  )

("GOL-AM06" :hint #x0
  (0 "GOL" "COSA? ANCORA LORO!")
  )

("GOL-AM07" :hint #x0
  (0 "GOL" "È TROPPO TARDI!")
  )

("GOL-AM08" :hint #x0
  (0 "GOL" "SEI MIO!")
  )

("GOL-AM09" :hint #x0
  (0 "GOL" "ORA SEI MIO!")
  )

("GOL-AM10" :hint #x0
  (0 "GOL" "AH HA HA HA HA!")
  )

("GOL-AM11" :hint #x0
  (0 "GOL" "NESSUNA PIETÀ!")
  )

("GOL-AM12" :hint #x0
  (0 "GOL" "PRENDI QUESTO!")
  )

("GOL-AM13" :hint #x0
  (0 "GOL" "BEL TENTATIVO!")
  )

("GOL-AM14" :hint #x0
  (0 "GOL" "STAI FERMO!")
  )

("GOL-AM15" :hint #x0
  (0 "GOL" "SEI PATETICO!")
  )

("GOL-AM16" :hint #x0
  (0 "GOL" "NOOO!")
  )

("GOL-AM17" :hint #x0
  (0 "GOL" "AHHH!")
  )

("GOL-AM18" :hint #x0
  (0 "GOL" "APRIREMO IL SILOS, E VI FAREMO A PEZZI!")
  )

("GOL-AM19" :hint #x0
  (0 "GOL" "L'ECO LUMINOSO! MA ALLORA ESISTE!")
  )

("GOL-AM20" :hint #x0
  (0 "GOL" "NON RIUSCIREMO A PRENDERLO!")
  )

("MAI-AM01" :hint #x0
  (0 "MAIA" "FINISCILI, UNA VOLTA PER TUTTE!")
  )

("MAI-AM02" :hint #x0
  (0 "MAIA" "ELIMINALI!")
  )

("MAI-AM03" :hint #x0
  (0 "MAIA" "HA HA HA!")
  )

("MAI-AM04" :hint #x0
  (0 "MAIA" "L'ECO NON VI PROTEGGERÀ ORA!")
  )

("MAI-AM05" :hint #x0
  (0 "MAIA" "FA QUALCOSA!")
  )

("MAI-AM06" :hint #x0
  (0 "MAIA" "AGH!")
  )

("MAI-AM07" :hint #x0
  (0 "MAIA" "NOOOOO!")
  )

("MAI-AM08" :hint #x0
  (0 "MAIA" "APRIREMO I SILOS E VI DISTRUGGEREMO ENTRAMBI!")
  )

("MAI-AM09" :hint #x0
  (0 "MAIA" "NON DEVONO RIUSCIRE A PRENDERLO!")
  )

("finalbosscam-white-eco"
  (163 :offscreen "GOL" "L'ECO LUMINOSO! MA ALLORA ESISTE!")
  (268 :offscreen "MAIA" "NON DEVONO RIUSCIRE A PRENDERLO!")
  )

("green-sagecage-daxter-sacrifice"
  (0 "DAXTER" "L'ECO LUMINOSO! POTREBBE SERVIRE A FARMI TORNARE NORMALE!")
  (114)
  (123 "DAXTER" "OH... OPPURE POTREBBE FERMARE IL ROBOT.")
  (235)
  (274 "DAXTER" "RESTARE PELOSO, O SALVARE IL MONDO... CHE SCELTA...")
  (404)
  (437 "DAXTER" "OKAY, VA BENE, SALVEREMO IL MONDO. MA VEDIAMO DI FARE IN FRETTA, PRIMA CHE IO CAMBI IDEA!")
  (634)
  )

("green-sagecage-outro-beat-boss-a"
  (165 :offscreen "MAIA" "FA QUALCOSA!")
  (216)
  (596 :offscreen "GOL" "NOOO!")
  )

("green-sagecage-outro-beat-boss-b"
  (532 "SAMOS" "BEH, FORSE SONO STATO UN PO' TROPPO DURO CON VOI, RAGAZZI MIEI.")
  (653 "SAMOS" "VOI AVETE TUTTO QUELLO CHE SERVE PER DIVENTARE EROI!")
  (745)
  (759 "KEIRA" "MA ORA, DAXTER, NON TI POSSIAMO TRASFORMARE.")
  (845)
  (853 "DAXTER" "OH, NON PREOCCUPARTI PER ME BABY. SAI COME SI DICE DI SOLITO? IL VINO BUONO STA IN UNA BOTTE... PICCOLINA.")
  (1096)
  (1114 "SAGGIO BLU" "JAK, HAI DAVVERO UN INCREDIBILE TALENTO NEL CANALIZZARE L'ECO!")
  (1219)
  (1230 "SAGGIO BLU" "SAMOS, DOPOTUTTO POTRESTI ANCHE AVER RAGIONE SU DI LUI!")
  (1321)
  (1330 "SAGGIO ROSSO" "SAI KEIRA, SENZA IL TUO AIUTO E SENZA LA TUA INGENUITÀ, TUTTO CIÒ NON SAREBBE STATO POSSIBILE.")
  (1522 "SAGGIO ROSSO" "HAHAHAH. CHISSÀ, FORSE ABBIAMO TROVATO UN NUOVO SAGGIO ORA CHE GOL E MAIA NON CI SONO PIÙ...")
  (1728)
  (1742 "SAMOS" "GIÀ, GOL E MAIA... SÌ, L'ECO OSCURO PROBABILMENTE LI AVRÀ DISTRUTTI.")
  (1946 :offscreen "SAMOS" "GIÀ, PROBABILMENTE...")
  (1999)
  (2005 "DAXTER" "AH, CHE IMPORTA? CHE RITORNINO, POSSIAMO SCONFIGGERLI UN'ALTRA VOLTA, VERO JAK?")
  (2168)
  (2181 "DAXTER" "NON HO DETTO... BENE, JAK?")
  (2256)
  (2312 "DAXTER" "WOW! DATTI UNA CALMATA, RAGAZZO!")
  )

("green-sagecage-outro-beat-boss-enough-cells"
  (151 "SAMOS" "PER TUTTE LE YAKOW! CHE COSA PUÒ ESSERE QUELLO?")
  (247 "KEIRA" "WOW! SI TRATTA DI UN ANTICO PORTONE PRECURSOR!")
  (355 :offscreen "KEIRA" "E SEMBRA CHE PER APRIRLO DOVREMO RIEMPIRE TUTTE E 100 LE FESSURE CON DELLE BATTERIE.")
  (485 "DAXTER" "UHM, MA NOI SIAMO DEGLI EROI, RICORDI? ECCOCI QUA, CON LE 100 BATTERIE NECESSARIE.")
  )

("green-sagecage-outro-beat-boss-need-cells"
  (151 "SAMOS" "PER TUTTE LE YAKOW! CHE COSA PUÒ ESSERE QUELLO?")
  (247 "KEIRA" "WOW! SI TRATTA DI UN ANTICO PORTONE PRECURSOR!")
  (355 :offscreen "KEIRA" "E SEMBRA CHE PER APRIRLO DOVREMO RIEMPIRE TUTTE E 100 LE FESSURE CON DELLE BATTERIE.")
  (485 "DAXTER" "OH RAGAZZI... ECCOCI TORNARE ALLA CARICA!")
  )

("green-sagecage-outro-big-finish"
  (322 "DAXTER" "WOW! MA CHE COS'È, PER VOI?")
  (425)
  (428 "KEIRA" "A ME SEMBRA COSÌ BELLO...")
  (516)
  (519 "SAMOS" "PER TUTTI I PRECURSOR...")
  (602)
  )

;; -----------------
;; training
;; -----------------

("asstvb40" :hint #x900
  (0 "KEIRA" "THIS DEVICE IS A COMMUNICATOR. WITH IT, MY FATHER AND I")
  (181 "KEIRA" "CAN GIVE YOU ADVICE AT ANY TIME DURING YOUR QUEST.")
  )

("asstvb41" :hint #x901
  (0 "KEIRA" "THESE FLOATING EGG-SHAPED THINGS ARE PRECURSOR ORBS.")
  (176)
  (180 "KEIRA" "COLLECT ENOUGH OF THEM, AND SOME OF THE VILLAGERS WILL GIVE YOU")
  (315 "KEIRA" "A POWER CELL IN EXCHANGE.")
  )

("asstvb42" :hint #x902
  (0 "KEIRA" "THIS IS A POWER CELL, THE MOST IMPORTANT PRECURSOR ARTIFACT YOU CAN FIND!")
  (327)
  (333 "KEIRA" "YOU NEED TO COLLECT 20 OF THESE SO I CAN POWER THE HEAT SHIELD")
  (507 "KEIRA" "FOR YOUR A-GRAV ZOOMER.")
  )

("asstvb44" :hint #x903
  (0 "KEIRA" "HEY, YOU FOUND ONE OF MY SCOUT FLIES!")
  (160 "KEIRA" "I SENT 7 OF THEM TO EACH AREA TO LOOK FOR POWER CELLS")
  (343 "KEIRA" "BUT THE LURKERS MUST HAVE CAPTURED THEM ALL!")
  )

("asstvb45" :hint #x904
  (0 "KEIRA" "WOW! THAT LAST SCOUT FLY HAD A POWER CELL!")
  (219 "KEIRA" "I'LL BET IF YOU COLLECT ALL 7 IN EACH AREA YOU CAN FIND EVEN MORE POWER CELLS.")
  )

("asstvb46" :hint #x905
  (0 "KEIRA" "BE CAREFUL IN THE OCEAN, THE WATERS ARE CHOCK-FULL OF LURKER SHARKS")
  (258 "KEIRA" "AND I'VE NEVER SEEN ANYONE DEFEAT ONE.")
  (419)
  (426 "KEIRA" "STAY CLEAR OF THEM IF YOU KNOW WHAT'S GOOD FOR YOU!")
  )

("asstvb47" :hint #x906
  (0 "KEIRA" "REMEMBER, THAT'S A POWER CELL. YOU NEED TO COLLECT AS MANY OF THOSE AS YOU CAN.")
  )

("asstvb48" :hint #x907
  (0 "KEIRA" "THAT'S A BLUE ECO VENT! MORE CONCENTRATED THAN THE FLOATING CLUSTERS,")
  (253 "KEIRA" "THIS VENT WILL GIVE YOU A FULL CHARGE OF BLUE ECO,")
  (419 "KEIRA" "LETTING YOU USE IT FOR THE MAXIMUM TIME.")
  )

("sagevb21" :hint #x908
  (3 "SAGE" "THOSE LITTLE GREEN BALLS OF ENERGY ON THE GROUND ARE A TYPE OF ECO.")
  (280 "SAGE" "PICK UP 50 SMALL GREEN ECOES, OR ONE BIG GREEN ONE TO INCREASE YOUR HEALTH.")
  )

("sagevb22" :hint #x909
  (0 "SAGE" "THAT'S BLUE ECO, WHICH CONTAINS THE ENERGY OF MOTION.")
  (291 "SAGE" "BLUE ECO ALLOWS YOU TO RUN FAST, BREAK BOXES, AND EVEN ACTIVATE SOME PRECURSOR")
  (640 "SAGE" "ARTIFACTS WHEN YOU GET NEAR THEM.")
  )

("sagevb23" :hint #x90a
  (0 "SAGE" "NOTICE HOW EACH BLUE ECO CLUSTER YOU PICK UP INCREASES THE TIME YOU CAN USE ITS POWER.")
  )

("sagevb24" :hint #x90b
  (3 "SAGE" "THIS IS A PRECURSOR DOOR. IT CAN ONLY BE OPENED BY APPROACHING THE DOOR")
  (357 "SAGE" "WHILE CHANNELING BLUE ECO THROUGH YOUR BODY.")
  )

("sagevb25" :hint #x90c
  (3 "SAGE" "GOOD WORK, THE BLUE ECO CAUSED THE DOOR TO OPEN. WITH BLUE ECO, YOU CAN BREATHE")
  (365 "SAGE" "ENERGY INTO ALL KINDS OF PRECURSOR ARTIFACTS THAT HAVE LAIN DORMANT FOR YEARS.")
  )

("sagevb26" :hint #x90d
  (0 "SAGE" "USE YOUR GOGGLES TO VIEW YOUR PROGRESS DURING THE ADVENTURE.")
  )

("sagevb27" :hint #x90e
  (1 "SAGE" "YOU CAN JUMP ONCE, THEN JUMP AGAIN IN THE AIR TO REACH EVEN HIGHER LEDGES.")
  )

("sagevb28" :hint #x90f
  (0 "SAGE" "WHEN YOU'RE SURROUNDED BY ENEMIES, USE YOUR SPIN KICK.")
  )

("sagevb29" :hint #x910
  (0 "SAGE" "THAT'S NOT A SPIN KICK! TRY AGAIN.")
  )

("sagevb30" :hint #x911
  (0 "SAGE" "COME ON, JAK! DO A SPIN KICK.")
  )

("sagevb31" :hint #x912
  (0 "SAGE" "GOOD WORK. USE THE SPIN KICK WHEN YOU WANT A GOOD ALL-ROUND ATTACK.")
  )

("sagevb32" :hint #x913
  (0 "SAGE" "FOR A STRAIGHT LINE, MOVING ATTACK, USE YOUR FIST TO PUNCH.")
  )

("sagevb33" :hint #x914
  (0 "SAGE" "THAT'S NOT A PUNCH ATTACK! LET'S SEE YOU PUNCH ALREADY.")
  )

("sagevb34" :hint #x915
  (0 "SAGE" "JAK! USE A PUNCH.")
  )

("sagevb35" :hint #x916
  (0 "SAGE" "GREAT JOB. USE THE PUNCH TO CLOSE DISTANCE QUICKLY IN A TOUGH SPOT.")
  )

("sagevb36" :hint #x917
  (0 "SAGE" "SOMETIMES YOU'LL WANT TO HIT THINGS WITH A GREATER FORCE.")
  (218 "SAGE" "TO BREAK ONE OF THESE BOXES, YOU SHOULD JUMP IN THE AIR")
  (420 "SAGE" "AND THEN DIVE DOWN ONTO IT, HANDS FIRST.")
  )

("sagevb37" :hint #x918
  (0 "SAGE" "WHEN YOU GET SOME CONFIDENCE, TRY USING SOME OF YOUR MOVES IN COMBINATIONS.")
  )

("sagevb38" :hint #x919
  (0 "SAGE" "YOU CAN'T COME BACK THROUGH THE WARP GATE UNTIL YOU FIND")
  (168 "SAGE" "ALL 4 POWER CELLS ON THIS ISLAND.")
  )

("sagevb39" :hint #x91a
  (0 "SAGE" "GREAT! YOU FOUND ALL OF THE POWER CELLS ON THE ISLAND.")
  (269 "SAGE" "COME BACK TO THE WARP GATE SO I CAN BRING YOU BACK TO THE LAB. HURRY UP!")
  )

;; -----------------
;; uncategorized
;; -----------------

