(language-id 6)
(text-version jak1-v2)

;; -----------------
;; intro
;; -----------------

("sidekick-human-intro-sequence-b"
  (547 "OLD MAN" "CONTINUE YOUR SEARCH FOR ARTEFACTS AND ECO.")
  (664)
  (674 "OLD MAN" "IF THE LOCALS POSSESS PRECURSOR ITEMS, YOU KNOW WHAT TO DO.")
  (819)
  (839 "WOMAN" "DEAL HARSHLY WITH ANYBODY WHO STRAYS FROM THE VILLAGE.")
  (937 "WOMAN" "WE WILL ATTACK IT IN DUE TIME.")
  (1027)
  )

;; -----------------
;; sidekick
;; -----------------

;; -----------------
;; oracle
;; -----------------

;; -----------------
;; training
;; -----------------

("asstvb42" :hint #x902
  (0 "KEIRA" "THIS IS A POWER CELL, THE MOST IMPORTANT PRECURSOR ARTEFACT YOU CAN FIND!")
  (327)
  (333 "KEIRA" "YOU NEED TO COLLECT 20 OF THESE SO I CAN POWER THE HEAT SHIELD")
  (507 "KEIRA" "FOR YOUR A-GRAV ZOOMER.")
  )

("sagevb22" :hint #x909
  (0 "SAGE" "THAT'S BLUE ECO, WHICH CONTAINS THE ENERGY OF MOTION.")
  (291 "SAGE" "BLUE ECO ALLOWS YOU TO RUN FAST, BREAK BOXES, AND EVEN ACTIVATE SOME PRECURSOR")
  (640 "SAGE" "ARTEFACTS WHEN YOU GET NEAR THEM.")
  )

("sagevb25" :hint #x90c
  (3 "SAGE" "GOOD WORK, THE BLUE ECO CAUSED THE DOOR TO OPEN. WITH BLUE ECO, YOU CAN BREATHE")
  (365 "SAGE" "ENERGY INTO ALL KINDS OF PRECURSOR ARTEFACTS THAT HAVE LAIN DORMANT FOR YEARS.")
  )

;; -----------------
;; village1
;; -----------------

;; -----------------
;; beach
;; -----------------

;; -----------------
;; jungle
;; -----------------

;; -----------------
;; misty
;; -----------------

;; -----------------
;; firecanyon
;; -----------------

;; -----------------
;; village2
;; -----------------

("sage-bluehut-introduction-prec-arm"
  (0 "SAGE" "WELL, I HOPE YOU'VE PACKED A LUNCH.'CAUSE WE'RE JUST GETTING STARTED.")
  (130)
  (140 "SAGE" "ACCORDING TO THE BLUE SAGE'S NOTES,")
  (208 "SAGE" "LURKERS HAVE INFESTED THE SWAMP ACROSS THE BAY.")
  (300)
  (304 :offscreen "SAGE" "APPARENTLY, THEY'RE PLANNING TO USE A DIRIGIBLE")
  (417 :offscreen "SAGE" "TO LIFT AN IMPORTANT PRECURSOR ARTEFACT FROM THE MUCK.")
  (531)
  (549 :offscreen "SAGE" "YOU'RE GOING TO HAVE TO GET OVER THERE TO DISLODGE THEIR TETHERS.")
  (675)
  (685 "SAGE" "WHO KNOWS WHAT THEY MIGHT WANT WITH THE ARTEFACT,")
  (764 "SAGE" "BUT LIKE ORANGE STUFF HERE'S BREATH, IT JUST CAN'T BE GOOD.")
  )

;; -----------------
;; swamp
;; -----------------

("sksp0153" :hint #x361
  (0 "DAXTER" "HEY, THAT MUST BE THE PRECURSOR ARTEFACT THE LURKERS ARE AFTER!")
  (175 "DAXTER" "IT LOOKS LIKE A GIANT ROBOT ARM!")
  )

;; -----------------
;; rolling
;; -----------------

;; -----------------
;; sunken
;; -----------------

("sksp0135" :hint #x34f (0 "DAXTER" "THAT WATER LOOKS DANGEROUS WHEN IT CHANGES COLOUR!"))
("sksp0136" :hint #x350 (0 "DAXTER" "YOU GOTTA GET OUT OF THE WATER BEFORE IT CHANGES COLOUR!"))

;; -----------------
;; ogre
;; -----------------

;; -----------------
;; village3
;; -----------------

("minershort-introduction-gnawers"
  (5 "GORDY" "WHY DON'T YOU TWO MAKE YOURSELVES USEFUL?")
  (89 "GORDY" "LURKERS HAVE BEEN EXCAVATIN' THE DARK CAVES OVER THERE.")
  (191 :offscreen "GORDY" "SEEMS THEY'RE LOOKIN' FOR PRECURSOR ARTEFACTS.")
  (265)
  (271 :offscreen "GORDY" "THEY CAN HAVE THE ARTEFACTS, FOR ALL I CARE.")
  (357)
  (360 :offscreen "WILLARD" "FOR ALL WE CARE!")
  (441)
  (444 "GORDY" "WILLARD, FEED YOUR BIRD.")
  (490)
  (496 "GORDY" "ALL I CARE ABOUT ARE GEMS!")
  (566 "GORDY" "BUT I AIN'T GONNA BE ABLE TO GET THE CAVE'S GEMS")
  (625 "GORDY" "BECAUSE WHEN THEY'RE THROUGH, THEY'RE GONNA COLLAPSE THE PLACE!")
  (715)
  (721 "GORDY" "IF YOU TAKE OUT THE LURKERS CHEWIN' AT THE SUPPORT BEAMS,")
  (827 "GORDY" "YOU COULD SAVE THE CAVE FOR ME.")
  (875)
  (884 "GORDY" "NOW BEAT IT!")
  )

("sage-village3-introduction"
  (6 "SAGE" "OW! I ALWAYS WONDER IF I'M LOSING BODY PARTS IN THOSE THINGS!")
  (153)
  (183 "SAGE" "HOLY YAKOW! THE RED SAGE'S LAB LOOKS WORSE THAN THE BLUE'S!")
  (321)
  (321 "KEIRA" "WELL, IT DEFINITELY LOOKS AS THOUGH THERE'S BEEN A STRUGGLE HERE.")
  (418)
  (441 "OLD MAN" "HA HA HA HA HA!")
  (500)
  (528 "OLD MAN" "I'D HARDLY CALL IT \"STRUGGLE.\" WOULD YOU, DEAR SISTER?")
  (672 "WOMAN" "CERTAINLY NOT. THE RED SAGE GAVE UP WITH SO LITTLE EFFORT.")
  (799)
  (806 "WOMAN" "NO FUN AT ALL.")
  (860)
  (884 "SAGE" "GOL? IS THAT YOU?")
  (965)
  (969 "SAGE" "YOU'VE FINALLY GONE OFF THE DEEP END, EH?")
  (1060 "SAGE" "AND, MAIA! I TOLD YOU THE DARK ECO WOULD AFFECT YOU BOTH!")
  (1180 "SAGE" "HNG, NOBODY EVER LISTENS TO OLD SAMOS...")
  (1265)
  (1282 "SAGE" "WHAT HAVE YOU TWO DONE WITH THE BLUE AND RED SAGES?")
  (1372 "GOL" "DON'T WORRY ABOUT YOUR COLOURFUL FRIENDS, YOU OLD FOOL.")
  (1516 "GOL" "THEY'RE PERFECTLY SAFE IN OUR CITADEL. OUR SPECIAL GUESTS.")
  (1680 "MAIA" "THEY HAVE GRACIOUSLY AGREED TO HELP US ON A LITTLE PROJECT.")
  (1813)
  (1828 "GOL" "YOU WERE WRONG, SAMOS. DARK ECO CAN BE CONTROLLED!")
  (1990)
  (1996 "GOL" "WE'VE LEARNED ITS SECRETS, AND NOW WE CAN RESHAPE THE WORLD TO OUR LIKING.")
  (2212)
  (2223 "SAGE" "YOU CAN'T CONTROL DARK ECO BY ITSELF! EVEN THE PRECURSORS COULDN'T-")
  (2357 "MAIA" "UNTIL NOW, WE'VE HAD TO SCRAPE BY WITH WHAT LITTLE DARK ECO WE COULD FIND NEAR THE SURFACE.")
  (2508)
  (2520 "MAIA" "BUT SOON, WE WILL HAVE ACCESS TO THE VAST STORES")
  (2611 "MAIA" "OF DARK ECO HIDDEN DEEP UNDERGROUND.")
  (2715 "SAGE" "NOT THE SILOS!")
  (2758)
  (2768 "GOL" "YES, THE SILOS!")
  (2841 "GOL" "THEY WILL BE OPENED, AND ALL THE DARK ECO IN THE WORLD WILL BE OURS!")
  (3028)
  (3034 "SAGE" "BUT THAT'S IMPOSSIBLE! ONLY A PRECURSOR ROBOT-")
  (3128 "MAIA" "OH, DON'T LOOK SO UPSET, SAMOS. WE'VE GOT BIG PLANS FOR YOU.")
  (3300)
  (3303 :offscreen "MAIA" "AH HA HA HA HA HA HA! AH...")
  (3460)
  (3495 "DAXTER" "WAIT A MINUTE!")
  (3538)
  (3541 "DAXTER" "THAT WAS GOL?")
  (3586)
  (3595 "DAXTER" "THE SAME GOL WHO'S SUPPOSED TO CHANGE ME BACK?")
  (3690 "DAXTER" "GOL IS THE GUY TRYING TO KILL US?!")
  (3772)
  (3785 "DAXTER" "I'M DOOMED.")
  (3822)
  (3828 "SAGE" "WE MAY ALL BE DOOMED.")
  (3897)
  (3903 "SAGE" "IF THEY OPEN THE SILOS, THE DARK ECO WILL TWIST AND DESTROY EVERYTHING IT TOUCHES!")
  (4080 "SAGE" "WE SIMPLY MUST GET TO THEIR CITADEL, TO STOP THEM!")
  (4189)
  (4192 "KEIRA" "THE FASTEST WAY THERE IS THROUGH THE LAVA TUBE AT THE BOTTOM OF THIS CRATER.")
  (4316)
  (4324 "KEIRA" "A FEW MORE POWER CELLS, AND YOUR ZOOMER'S HEAT SHIELD")
  (4400 "KEIRA" "SHOULD GET YOU ACROSS THE LAVA SAFELY.")
  (4460)
  (4464 "SAGE" "ALL RIGHT, MY BOY. YOU KNOW WHAT TO DO.")
  (4545 "SAGE" "TAKE THE FLEABAG AND GO ROUND UP MORE POWER CELLS.")
  (4664)
  )

("asstv103" :hint #x452
  (0 "KEIRA" "DON'T FORGET TO TURN ON THE TELEPORT GATE TO LET US THROUGH.")
  (160 "KEIRA" "YOU'VE GOT TO GO INTO THE RED SAGE'S LAB")
  (280 "KEIRA" "IN THE CENTRE OF THE VOLCANIC CRATER TO TURN IT ON.")
  (450 "KEIRA" "WE CAN'T COME THROUGH UNTIL IT'S BACK ONLINE.")
  )

;; -----------------
;; snowy
;; -----------------

;; -----------------
;; spidercave
;; -----------------

;; -----------------
;; lavatube
;; -----------------

;; -----------------
;; citadel
;; -----------------

("green-sagecage-introduction"
  (130 "SAGE" "IT'S ABOUT TIME YOU TWO DECIDED TO SHOW UP!")
  (207 "DAXTER" "NICE TO SEE YOU TOO! DO THEY HAVE YOU MOPPING THE FLOORS NOW?")
  (343 "SAGE" "THERE'S NO TIME FOR JOKES, DAXTER. GOL AND MAIA KIDNAPPED US")
  (477 "SAGE" "TO SAP OUR ENERGIES TO POWER THEIR ABOMINABLE MACHINE.")
  (574)
  (584 :offscreen "SAGE" "IT APPEARS THEY HAVE COMBINED THE FUNCTIONAL REMAINS OF A PRECURSOR ROBOT")
  (710 :offscreen "SAGE" "WITH SCAVENGED ARTEFACTS FROM ACROSS THE LAND.")
  (800)
  (816 :offscreen "SAGE" "THEN THEY ADDED A FEW DIABOLICAL ADDITIONS OF THEIR OWN,")
  (926 :offscreen "SAGE" "CREATING THE ONE THING CAPABLE OF OPENING THE DARK ECO SILOS.")
  (1060 "SAGE" "IF YOU CAN FREE THE FOUR OF US, WE CAN USE OUR COMBINED POWERS")
  (1180 "SAGE" "TO BREAK THE FORCE SHIELD SURROUNDING THE ROBOT, BEFORE THEY USE IT TO DESTROY THE WORLD.")
  )

;; -----------------
;; finalboss
;; -----------------

;; -----------------
;; title
;; -----------------

;; -----------------
;; uncategorized
;; -----------------

