(language-id 2)
(text-version jak1-v2)

;; -----------------
;; intro
;; -----------------

;; -----------------
;; sidekick
;; -----------------

("sksp0001" :hint #x280
  (0 "DAXTER" "HEY! DIE SÜSSE KEIRA-MAUS HATTE RECHT! HIER GIBT'S WIRKLICH TRANS-PADS!")
  )

("sksp0002" :hint #x281
  (0 "DAXTER" "GLAUB' MIR, DIESE DUNKLEN ECO-BOXEN SIND ÜBERHAUPT NICHTS GUTES!")
  )

("sksp0003" :hint #x282
  (0 "DAXTER" "ICH WETTE, WENN WIR ALLE VON DIESEN NIEDLICHEN SPÄHFLIEGEN IN EINEM LEVEL FINDEN,")
  (215 "DAXTER" "IST BESTIMMT EINE DABEI MIT EINER ENERGIEZELLE!")
  )

("sksp0004" :hint #x283
  (0 "DAXTER" "JAWOLL, EIN SCHATZ!")
  )

("sksp0005" :hint #x284
  (0 "DAXTER" "SO HART SEHEN DIESE HOLZ- UND METALLKISTEN NUN AUCH NICHT AUS!")
  (200 "DAXTER" "ICH WETTE, MIT EINEM TAUCHSPRUNG KRIEGT MAN SIE AUF!")
  )

("sksp0006" :hint #x285
  (0 "DAXTER" "DIESE METALLKISTEN SIND JA DICKER ALS DER SCHÄDEL EINER YAKOW!")
  (188 "DAXTER" "ABER ES MUSS DOCH WAS GEBEN, WOMIT MAN SIE AUFKRIEGT!")
  )

("sksp0007" :hint #x286
  (0 "DAXTER" "NUR EIN WORT: ENERGIEZELLEN. DIE MÜSSEN WIR FINDEN UND IM MOMENT SIND WIR DARIN GAR NICHT GUT!")
  )

("sksp0008" :hint #x287
  (0 "DAXTER" "WIR BRAUCHEN ORBS. ORBS, JAK! WIE SOLLEN WIR DENN JEMALS ENERGIEZELLEN KAUFEN, WENN WIR KEINE ORBS SAMMELN?!")
  )

("sksp0009" :hint #x251
  (0 "DAXTER" "WAS FÜR EIN SELTSAMES DING! ICH WETTE, WIR KRIEGEN DAS AUF,")
  (188 "DAXTER" "WENN DU DICH MIT DIESEM BLUBBERNDEN BLAUEN ECO-ZEUGS AUFLÄDST.")
  )

("sksp0014" :hint #x233
  (0 "DAXTER" "WIR HABEN GENUG ORBS FÜR EINE ENERGIEZELLE ZUSAMMENGESCHNORRT.")
  (215 "DAXTER" "KOMM, WIR GEHEN ZURÜCK UND TAUSCHEN SIE ENDLICH EIN!")
  )

("sksp0035" :hint #x25c
  (0 "DAXTER" "SUPER, JETZT HABEN WIR HIER EINEN PRECURSOR-STARTER,")
  (117 "DAXTER" "ABER DEINE ENERGIE IST NICHT VOLL AUFGELADEN MIT DIESEM BLAUEN ZEUG, ALSO BRINGT UNS DAS ÜBERHAUPT NICHTS!")
  )

("sksp0071" :hint #x2a5
  (0 "DAXTER" "HOL DAS ROTE ECO!")
  )

("sksp0072" :hint #x2a6
  (0 "DAXTER" "ROTES ECO VERSTÄRKT DEINE ANGRIFFE!")
  )

("sksp0073" :hint #x2a7
  (0 "DAXTER" "WIR BRAUCHEN BLAUES ECO, UM DAS HIER AUFZULADEN!")
  )

("sksp009a" :hint #x0
  (0 "DAXTER" "HAHA, DEM HABEN WIR'S GEZEIGT, WAS?")
  )

("sksp009b" :hint #x28e
  (0 "DAXTER" "JAWOLL, NOCH MEHR ORBS!")
  )

("sksp009c" :hint #x28f
  (0 "DAXTER" "TU MIR DEN GEFALLEN UND HALT DICH VON DIESEN DUNKLEN ECO-KISTEN FERN!")
  )

("sksp009d" :hint #x290
  (0 "DAXTER" "JA, HA, HA, HA, HA, HA!")
  )

("sksp009e" :hint #x291
  (0 "DAXTER" "WA-HOO!")
  )

("sksp009f" :hint #x292
  (0 "DAXTER" "SCHNAPP DIR WELCHE, SCHNAPP DIR WELCHE! HA, HA, HA!")
  )

("sksp009g" :hint #x293
  (0 "DAXTER" "DIREKT HINTER DIR, JAK!")
  )

("sksp009i" :hint #x294
  (0 "DAXTER" "HABEN WIR JETZT ALLE SPÄHFLIEGEN IN DIESEM GEBIET GEFUNDEN?")
  )

("sksp009j" :hint #x295
  (0 "DAXTER" "HEY! SIEHT GANZ SO AUS, ALS BEFINDEN SICH DIE SPÄHFLIEGEN IMMER IN ROTEN KISTEN!")
  )

("sksp009k" :hint #x296
  (0 "DAXTER" "JAWOLL! DU HAST ALLE SPÄHFLIEGEN IN DIESEM GEBIET GEFUNDEN!")
  )

("sksp0110" :hint #x336
  (0 "DAXTER" "ICH HAB'S DIR EINMAL GESAGT UND ICH SAG'S DIR NOCHMAL...")
  (164 "DAXTER" "HALT DICH VON DEN DUNKLEN ECO-KISTEN FERN!")
  )

("sksp0145" :hint #x359
  (0 "DAXTER" "WOW! DU KANNST FEUERBÄLLE ABSCHIESSEN, WENN DU MIT GELBEM ECO AUFGELADEN BIST!")
  )

("sksp0328" :hint #x433
  (0 "DAXTER" "VIELLEICHT KANNST DU BESSER SCHIESSEN, WENN DU DURCH DEINE SCHUTZBRILLE ZIELST!")
  )

;; -----------------
;; training
;; -----------------

("asstvb40" :hint #x900
  (0 "KEIRA" "DIESES GERÄT IST EIN KOMMUNIKATOR, DAMIT KÖNNEN MEIN VATER UND ICH")
  (219 "KEIRA" "EUCH JEDERZEIT BEI EURER SUCHE RATSCHLÄGE GEBEN.")
  )

("asstvb41" :hint #x901
  (0 "KEIRA" "DIESE SCHWEBENDEN EIFÖRMIGEN DINGER SIND PRECURSOR-ORBS.")
  (182)
  (185 "KEIRA" "WENN IHR GENUG DAVON SAMMELT, GEBEN EUCH EIN PAAR DER DORFBEWOHNER")
  (376 "KEIRA" "EINE ENERGIEZELLE DAFÜR.")
  )

("asstvb42" :hint #x902
  (0 "KEIRA" "DAS IST EINE ENERGIEZELLE, DAS WICHTIGSTE PRECURSOR-ARTEFAKT, DAS IHR FINDEN KÖNNT.")
  (272)
  (275 "KEIRA" "IHR MÜSST 20 DAVON SAMMELN, DAMIT ICH DEN HITZESCHILD")
  (453 "KEIRA" "FÜR EUREN A-GRAV-ZOOMER AKTIVIEREN KANN.")
  )

("asstvb44" :hint #x903
  (0 "KEIRA" "HEY, IHR HABT EINE MEINER SPÄHFLIEGEN GEFUNDEN!")
  (160 "KEIRA" "ICH HABE SIEBEN DAVON IN JEDES GEBIET ENTSANDT, UM NACH ENERGIEZELLEN ZU SUCHEN,")
  (428 "KEIRA" "ABER DIE LURKER MÜSSEN SIE ALLE EINGEFANGEN HABEN.")
  )

("asstvb45" :hint #x904
  (0 "KEIRA" "WOW! DIESE LETZTE SPÄHFLIEGE HATTE EINE ENERGIEZELLE!")
  (219 "KEIRA" "ICH WETTE, WENN IHR ALLE SIEEBEN IN EINEM GEBIET FINDET, BEKOMMT IHR BESTIMMT NOCH MEHR ENERGIEZELLEN.")
  )

("asstvb46" :hint #x905
  (0 "KEIRA" "SEID VORSICHTIG IM OZEAN, DIE GEWÄSSER WIMMELN NUR SO VOR LURKER-HAIEN")
  (255 "KEIRA" "UND ICH HABE NOCH NIE ERLEBT, DASS JEMAND EINEN DAVON BESIEGT HAT.")
  (419)
  (426 "KEIRA" "HALTET EUCH VON IHNEN FERN, WENN EUCH EUER LEBEN LIEB IST!")
  )

("asstvb47" :hint #x906
  (0 "KEIRA" "DENK DRAN, DAS IST EINE ENERGIEZELLE. IHR MÜSST SO VIELE SAMMELN WIE NUR MÖGLICH!")
  )

("asstvb48" :hint #x907
  (0 "KEIRA" "DAS IST EINE BLAUE ECO-ÖFFNUNG! HIER IST DAS BLAUE ECO VIEL KONZENTRIERTER ALS BEI DEN SCHWEBENDEN HAUFEN,")
  (344 "KEIRA" "DESHALB BEKOMMST DU HIER EINE VOLLE LADUNG DAVON,")
  (492 "KEIRA" "DIE DU FÜR DIE MAXIMALE ZEITDAUER NUTZEN KANNST.")
  )

("sagevb21" :hint #x908
  (3 "SAMOS" "DIESE KLEINEN GRÜNEN ENERGIEBÄLLE AUF DEM BODEN SIND EINE ECO-ART.")
  (280 "SAMOS" "HEBE 50 KLEINE ODER EINEN GROSSEN GRÜNEN ECO AUF, DANN WIRD DEINE GESUNDHEIT VERBESSERT.")
  )

("sagevb22" :hint #x909
  (0 "SAMOS" "DAS HIER IST BLAUES ECO, ES ENTHÄLT DIE BEWEGUNGSENERGIE.")
  (275 "SAMOS" "MIT BLAUEM ECO KANNST DU SCHNELL RENNEN, KISTEN AUFBRECHEN UND SOGAR EINIGE PRECURSOR-ARTEFAKTE AKTIVIEREN,")
  (660 "SAMOS" "WENN DU IN IHRE NÄHE KOMMST.")
  )

("sagevb23" :hint #x90a
  (0 "SAMOS" "SCHAU, WIE SICH MIT JEDEM AUFGEHOBENEN BLAUEN ECO-HAUFEN DIE ZEIT VERLÄNGERT, IN DER DU ES BENUTZEN KANNST.")
  )

("sagevb24" :hint #x90b
  (3 "SAMOS" "DAS IST EINE PRECURSOR-TÜR. SIE LÄSST SICH NUR ÖFFNEN,")
  (194 "SAMOS" "WENN DU BLAUES ECO DURCH DEINEN KÖRPER LAUFEN LÄSST.")
  )

("sagevb25" :hint #x90c
  (3 "SAMOS" "GUT GEMACHT, DAS BLAUE ECO HAT DIE TÜR GEÖFFNET. MIT BLAUEM ECO KANNST DU SELBST DEN PRECURSOR-ARTEFAKTEN,")
  (456 "SAMOS" "DIE SCHON SEIT JAHREN NICHT MEHR AKTIVIERT WORDEN SIND, ENERGIE EINHAUCHEN.")
  )

("sagevb26" :hint #x90d
  (0 "SAMOS" "DURCH DEINE SCHUTZBRILLE KANNST DU DEINE FORTSCHRITTE IM SPIEL ANSEHEN.")
  )

("sagevb27" :hint #x90e
  (1 "SAMOS" "WENN DU SPRINGST UND DANN IN DER LUFT GLEICH NOCHMAL SPRINGST, KANNST DU AUF EINEN HÖHER GELEGENEN VORSPRUNG GELANGEN.")
  )

("sagevb28" :hint #x90f
  (0 "SAMOS" "WENN DU VON FEINDEN UMZINGELT BIST, BENUTZE DIE ROTIER-TRET-METHODE.")
  )

("sagevb29" :hint #x910
  (0 "SAMOS" "THAT'S NOT A SPIN KICK! TRY AGAIN.")
  )

("sagevb30" :hint #x911
  (0 "SAMOS" "NA LOS, JAK! ROTIERE UND TRETE.")
  )

("sagevb31" :hint #x912
  (0 "SAMOS" "BENUTZE DIE ROTIER-TRET-METHODE FÜR EINEN RUNDUMSCHLAG.")
  )

("sagevb32" :hint #x913
  (0 "SAMOS" "BENUTZE BEI EINEM FRONTALANGRIFF EINEN BOXHIEB.")
  )

("sagevb33" :hint #x914
  (0 "SAMOS" "DAS IST DOCH KEIN BOXHIEB! JETZT ZEIG' UNS MAL, WIE DU RICHTIG BOXT!")
  )

("sagevb34" :hint #x915
  (0 "SAMOS" "JAK! VERSUCH'S MIT EINEM BOXHIEB.")
  )

("sagevb35" :hint #x916
  (0 "SAMOS" "TOLL! MIT DEM BOXHIEB KANNST DU DICH SCHNELL DURCHKÄMPFEN, WENN'S BRENZLIG WIRD.")
  )

("sagevb36" :hint #x917
  (0 "SAMOS" "MANCHMAL MUSST DU MIT GRÖSSERER KRAFT ZUSCHLAGEN.")
  (154 "SAMOS" "UM EINE DIESER KISTEN ZU ÖFFNEN, MUSST DU HOCHSPRINGEN")
  (309 "SAMOS" "UND DANN MIT DEN HÄNDEN VORAN ABTAUCHEN.")
  )

("sagevb37" :hint #x918
  (0 "SAMOS" "MIT EIN BISSCHEN ÜBUNG KANNST DU AUCH VERSUCHEN, EINIGE DIESER BEWEGUNGEN ZU VERBINDEN.")
  )

("sagevb38" :hint #x919
  (0 "SAMOS" "DU KANNST NICHT ZURÜCK DURCH'S SPRUNGTOR,")
  (120 "SAMOS" "BIS DU ALLE VIER ENERGIEZELLEN AUF DIESER INSEL GEFUNDEN HAST.")
  )

("sagevb39" :hint #x91a
  (0 "SAMOS" "SUPER! DU HAST ALLE ENERGIEZELLEN AUF DER INSEL GEFUNDEN.")
  (210 "SAMOS" "KOMM ZURÜCK ZUM SPRUNGTOR, DAMIT ICH DICH ZURÜCK INS LABOR BEFÖRDERN KANN! BEEIL DICH!")
  )

;; -----------------
;; village1
;; -----------------

("ASSTLP01" :hint #x0
  (0 "KEIRA" "HMM...")
  )

("ASSTLP02" :hint #x0
  (0 "KEIRA" "HMM, ICH MUSS DEN HITZESCHILD HIER IN GANG KRIEGEN...")
  )

("ASSTLP03" :hint #x0
  (0 "KEIRA" "WIR BRAUCHEN ENERGIEZELLEN, UM DEN HITZESCHILD ZU AKTIVIEREN...")
  )

("ASSTLP04" :hint #x0
  (0 "KEIRA" "WHERE'S MY SPANNER?")
  )

("ASSTLP05" :hint #x0
  (0 "KEIRA" "FIRE CANYON IS SO HOT...")
  )

("EXP-AM01" :hint #x0
  (0 "JAKS ONKEL" "ICH MUSS BALD ZU MEINER REISE AUFBRECHEN, ICH BRAUCHE PRECURSOR-ORBS!")
  )

("EXP-AM02" :hint #x0
  (0 "JAKS ONKEL" "HM, MAL SEHEN, WO SOLL ICH ZUERST HIN?")
  )

("EXP-AM03" :hint #x0
  (0 "JAKS ONKEL" "AH, ICH VERMISSE DIE LANDSTRASSE.")
  )

("EXP-AM04" :hint #x0
  (0 "JAKS ONKEL" "ES GIBT SO VIEL ZU SEHEN UND SO WENIG ZEIT DAFÜR.")
  )

("EXP-AM05" :hint #x0
  (0 "JAKS ONKEL" "HMPF, ZU MEINER ZEIT KONNTE MAN NOCH REISEN, OHNE VON MONSTERN ANGEGRIFFEN ZU WERDEN!")
  )

("EXP-LO02" :hint #x0
  (0 "JAKS ONKEL" "ICH BRAUCHE MEHR PRECURSOR-ORBS.")
  )

("EXP-LO1A" :hint #x0
  (0 "JAKS ONKEL" "(MURMELT)")
  )

("FAR-AM01" :hint #x0
  (0 "FARMER" "(SCHNARCHT) HIER, BESSIE... HIER, BESSIE BESSIE... MEIN MÄDCHEN...")
  )

("FAR-AM02" :hint #x0
  (0 "FARMER" "MUSS DIE ERNTE EINBRINGEN, BEVOR DIE JUNEKÄFER SIE HOLEN...")
  )

("FAR-AM2A" :hint #x0
  (0 "FARMER" "MUSS DIE ERNTE EINBRINGEN, BEVOR DIE JUNEKÄFER SIE HOLEN...")
  )

("FAR-LO01" :hint #x0
  (0 "FARMER" "(SCHNARCHT)")
  )

("FAR-LO1A" :hint #x0
  (0 "FARMER" "(SCHNARCHT)")
  )

("SAGELP03" :hint #x0
  (0 "SAMOS" "DIESE BEIDEN KÖNNTEN NOCH NICHT EINMAL IHRE EIGENEN OHREN FREIBEKOMMEN...")
  )

("SAGELP04" :hint #x0
  (0 "SAMOS" "ER WIRD SEINEM ONKEL NIE DAS WASSER REICHEN KÖNNEN,")
  (200 "SAMOS" "GANZ GLEICH, WAS DIE ANDEREN BEHAUPTEN.")
  )

("SAGELP05" :hint #x0
  (0 "SAMOS" "HALLO, BLAUER WEISER? HALLO? WO ZUM TEUFEL KANN ER NUR SEIN?!")
  )

("SAGELP06" :hint #x0
  (0 "SAMOS" "ACH, DU MEINE GÜTE...")
  )

("SAGELP11" :hint #x0
  (0 "SAMOS" "HALLO? IRGENDJEMAND, BITTE MELDEN!")
  )

("assistant-introduction-blue-eco-switch"
  (23 "DAXTER" "HEY, BABY. WOLLEN WIR NICHT ZUSAMMEN EIN PAAR RUNDEN AUF DIESEM A-GRAV ZOOMER DREHEN?")
  (175)
  (200 "KEIRA" "REGEL NUMMER EINS: ICH VERABREDE MICH NICHT MIT TIEREN.")
  (308)
  (312 "DAXTER" "ACH, DU WEISST JA GAR NICHT, WAS DIR ENTGEHT, EH HEH HEH...")
  (430)
  (505 "KEIRA" "HÖR ZU, WENN IHR BESCHÄFTIGUNG BRAUCHT, MEIN VATER HAT VON EINEM")
  (635 "KEIRA" "ALTEN PRECURSOR-ROHRSYSTEM TIEF UNTER DER ERDE ERZÄHLT.")
  (739)
  (742 :offscreen "KEIRA" "AM ENDE VON EINIGEN ROHREN SIND ÖFFNUNGEN, AUS DENEN DAS ECO HERAUSSTRÖMT,")
  (855 :offscreen "KEIRA" "ANDERE SIND VERRIEGELT, SODASS DAS ECO EINGESCHLOSSEN IST.")
  (945)
  (954 "KEIRA" "ES MUSS MÖGLICH SEIN, DIE VERRIEGELTEN ÖFFNUNGEN AUFZUMACHEN.")
  (1052 :offscreen "KEIRA" "ICH HAB RAUSGEFUNDEN, DASS EIN TEIL DER ROHRE UNTER DEM VERBOTENEN TEMPEL LIEGT.")
  (1165 "KEIRA" "SUCHT DORT MAL NACH EINEM SCHALTER.")
  (1246)
  )

("assistant-introduction-race-bike"
  (9 "DAXTER" "HEY BABY, WAS IST'N DAS HIER?")
  (78 "KEIRA" "SEI VORSICHTIG! ICH VERSUCHE, HERAUSZUFINDEN, WIE MAN DEN ZOOMER MITHILFE DER")
  (205 "KEIRA" "PRECURSOR-TRANS-PADS TRANSPORTIEREN KANN.")
  (308)
  (312 :offscreen "KEIRA" "WENN IHR AN EINES DIESER PADS KOMMT, KANN ICH DIE POSITION EURES KOMMUNIKATORS ERMITTELN")
  (453 :offscreen "KEIRA" "UND EUCH DEN ZOOMER SCHICKEN!")
  (508 "KEIRA" "HALTET AUF DER NEBELINSEL AUSSCHAU NACH SOLCHEN TRANS-PADS, ODER SONSTWO!")
  (665)
  )

("assistant-reminder-1-blue-eco-switch"
  (23 "KEIRA" "WENN IHR IM VERBOTENEN PRECURSOR-TEMPEL SUCHT, SCHAFFT IHR ES BESTIMMT,")
  (160 "KEIRA" "DIE VERSCHLOSSENE BLAUE ECO-ÖFFNUNG AM WÄCHTERSTRAND AUFZUMACHEN.")
  (295)
  )

("assistant-reminder-1-generic"
  (25 "KEIRA" "HEY, JUNGS! SAMMELT WEITER ENERGIEZELLEN, IHR BRAUCHT SIE, UM WEITER NACH NORDEN ZU REISEN.")
  )

("assistant-reminder-1-race-bike"
  (25 "KEIRA" "ICH WEISS JETZT, WIE MAN DIE TRANS-PADS BENUTZT.")
  (106 "KEIRA" "GEHT ZUR NEBELINSEL UND ICH SCHICKE EUCH DEN ZOOMER RÜBER.")
  (229)
  )

("asstvb04" :hint #x2b1
  (0 "KEIRA" "GUT, IHR HABT GENUG ENERGIEZELLEN GESAMMELT, UM MEINEN HITZESCHILD ZU AKTIVIEREN!")
  (288 "KEIRA" "KLETTERT DIE KLIPPE HINTER DEM HAUS DES FARMERS HOCH UND TREFFT MICH AM EINGANG ZUM FEUER-CANYON!")
  (636 "KEIRA" "BRINGT DIE ENERGIEZELLEN MIT UND BEEILT EUCH! MEIN VATER MEINT, ER HABE HIER WIEDER MEHR LURKER GESEHEN.")
  )

("asstvb08" :hint #x2b2
  (0 "KEIRA" "BEEILT EUCH MIT DEN ENERGIEZELLEN, ICH WARTE AM ANFANG DES FEUER-CANYONS,")
  (216 "KEIRA" "OBEN AUF DER KLIPPE, HINTER DEM HAUS DES FARMERS!")
  )

("explorer-introduction"
  (23 "JAK'S ONKEL" "OH, HALLO, MEIN LIEBER JUNGE. DU KOMMST MIR JETZT ABER GERADE EIN WENIG UNGELEGEN.")
  (197 "JAKS ONKEL" "WEISST DU, ICH WOLLTE SCHON GESTERN ZU MEINER REISE AUFBRECHEN,")
  (300 "JAKS ONKEL" "ABER ICH HABE SCHEINBAR ZU WENIG PRECURSOR-ORBS.")
  (426)
  (430 "JAKS ONKEL" "ICH HÄTTE SCHWÖREN KÖNNEN, DASS ICH 90 STÜCK HATTE.")
  (538 "JAKS ONKEL" "ABER ICH VERMUTE, DEIN JUNGER FREUND, DIESER LÄSTIGE, FURCHTBAR HÄSSLICHE KLEINE KERL HIER,")
  (716 "JAKS ONKEL" "HAT MIR AUS JUX GERADE EIN PAAR ENTWENDET.")
  (829)
  (865 "JAKS ONKEL" "NUN DENN, WÜRDEST DU DEINEM LIEBEN ALTEN ONKEL FREUNDLICHERWEISE 90 PRECURSOR-ORBS LEIHEN,")
  (1043 "JAKS ONKEL" "DAMIT ER AUFBRECHEN KANN? ICH BIETE DIR EINE ENERGIEZELLE DAFÜR.")
  )

("explorer-reminder-1"
  (25 "JAKS ONKEL" "WAS? SO VIELE HAST DU NICHT? HARUMPH!")
  (148 "JAKS ONKEL" "TJA, MIT WENIGER ALS 90 PRECURSOR-ORBS KANN ICH NICHT AUFBRECHEN, MEIN JUNGE.")
  (370)
  )

("explorer-reminder-2"
  (33 "JAKS ONKEL" "NUN JA, 90 PRECURSOR-OBS FÜR EINE ENERGIEZELLE SIND EIN AUSGESPROCHEN FAIRES GESCHÄFT.")
  )

("explorer-resolution"
  (28 "JAKS ONKEL" "AH, IHR WOLLT DAS GESCHÄFT ALSO DOCH MACHEN? PRÄCHTIG, AUSGESPROCHEN PRÄCHTIG!")
  (179 "JAKS ONKEL" "HEY, HABT IHR DIE VEREINBARTEN PRECURSOR-ORBS?")
  (310)
  (324 "JAKS ONKEL" "HM, HOFFENTLICH VERGEUDET IHR DIESE SCHWER VERDIENTE ENERGIEZELLE NICHT. MACHTS GUT, CIAO CIAO, BYE BYE!")
  )

("farmer-introduction"
  (1 "FARMER" "MUSS DIE YAKOWS MELKEN, MUSS DIE YAKOWS MELKEN...")
  (113 "FARMER" "OH! IHR SEID'S... ICH RUH MICH NUR EIN BISSCHEN AUS. HAB DEN GANZEN TAG VERSUCHT, DIESE STREITLUSTIGEN KÜHE")
  (317 "FARMER" "ZURÜCK IN DEN PFERCH ZU KRIEGEN! EIN PAAR SELTSAME TYPEN WOLLTEN SIE SCHON STEHLEN.")
  (454)
  (456 "FARMER" "KÖNNTET IHR WOHL EINEM ALTEN MANN HELFEN UND SIE IN DEN PFERCH BRINGEN?")
  )

("farmer-reminder-1"
  (0 "FARMER" "HEY! MEINE YAKOWS SIND JA IMMER NOCH DRAUSSEN! SEID BITTE SO NETT UND HOLT SIE JETZT REIN.")
  )

("farmer-reminder-2"
  (0 "FARMER" "DIESE BLÖDEN YAKOWS STROLLEN IMMER NOCH RUM!")
  (85 "FARMER" "JETZT BRINGT SIE DOCH ENDLICH MAL IN DEN PFERCH!")
  )

("farmer-resolution"
  (0 "FARMER" "AH, GUT GEMACHT, MEIN JUNGE. DIE VERLAUSTEN VIECHER SIND JETZT IM PFERCH.")
  (134 "FARMER" "NUN KANN ICH BERUHIGT SCHLAFEN. HIER IST EINE ENERGIEZELLE FÜR DEINE MÜHE.")
  (340)
  )

("sage-introduction-misty-cannon"
  (50 "SAMOS" "OH, IHR SEID'S, DIE GROSSEN BEZWINGER.")
  (136 "SAMOS" "GUT, ICH HABE DA ETWAS ERNSTES MIT EUCH ZU BESPRECHEN.")
  (258)
  (261 :offscreen "SAMOS" "ES SCHEINT, ALS SEIEN DIE LURKER AUF DER NEBELINSEL ENORM AKTIV.")
  (375)
  (380 :offscreen "SAMOS" "VON MEINEM BEOBACHTUNGSTURM AUS KANN ICH ERKENNEN, WIE SIE DIE PRECURSOR-ECO-STATION BOMBARDIEREN.")
  (525)
  (528 "SAMOS" "FALLS SIE SIE ÖFFNEN UND DAS DUNKLE ECO FREISETZEN, WERDEN WIR AM ENDE")
  (663 "SAMOS" "NOCH SO HERUMLAUFEN WIE DIESE HÄSSLICHE KLEINE FLOHQUASTE HIER.")
  (788)
  (807 "SAMOS" "JAK, WIR MÜSSEN DEINE... TAUGLICHKEIT PRÜFEN.")
  (920 "SAMOS" "BRING DEN FISCHER DAZU, DIR SEIN BOOT ZU LEIHEN UND FAHR ZUR NEBELINSEL.")
  (1018 "SAMOS" "DU MUSST AUF DIE SPITZE DER PRECURSOR-ECO-STATION UND DIE VERMALEDEITE KANONE AUSSER GEFECHT SETZEN.")
  (1171)
  (1177 "DAXTER" "UND WAS... IST MIT MIR?")
  (1232)
  (1235 "SAMOS" "DU? DU KANNST MEINE FUSSBÖDEN WISCHEN, IN LETZTER ZEIT GLÄNZEN SIE NICHT MEHR SO SCHÖN.")
  )

("sage-reminder-1-ecorocks"
  (45 "SAMOS" "NA, IHR SEID MIR JA ZWEI TOLLE ABENTEURER!")
  (132 "SAMOS" "SCHON ZURÜCK UND HABT NOCH NICHT EINMAL MEINE BLOCKIERTEN ECO-ERNTER IN ORDNUNG GEBRACHT!")
  (244)
  (270 :offscreen "SAMOS" "SIE SIND AM ANDEREN ENDE DES STRANDES, JUNGS.")
  (365)
  (370 :offscreen "SAMOS" "JETZT...")
  (400 :offscreen "SAMOS" "MACHT ENDLICH!")
  )

("sage-reminder-1-generic"
  (54 "SAMOS" "WAS MACHT IHR DENN HIER? IHR SOLLT ENERGIEZELLEN SAMMELN!")
  (178)
  (181 "SAMOS" "LASST MICH IN FRIEDEN, BIS IHR GENUG HABT!")
  )

("sage-reminder-1-misty-cannon"
  (24 "SAMOS" "DAS BOMBARDMENT WIRD SCHLIMMER!")
  (86 :offscreen "SAMOS" "SUCH DEN FISCHER IM DSCHUNGEL, HOL DIR DIE ERLAUBNIS, SEIN BOOT ZU BENUTZEN")
  (200 :offscreen "SAMOS" "UND FAHR ZUR NEBELINSEL, UM ENDLICH DIE KANONE ZU STOPPEN.")
  (317)
  (320 "SAMOS" "UND DU, DAXTER. FANG AN, AUFZUWISCHEN. SIEHT JA SCHLIMM AUS HIER!")
  )

("sage-reminder-2-generic"
  (27 "SAMOS" "IHR ZWEI VERSTEHT DEN ERNST DER LAGE WOHL IMMER NOCH NICHT.")
  (137 "SAMOS" "HIER GEHT ES UM MEHR ALS NUR EINEN DUMMEN JUNGENSTREICH. HIER GEHT UM DAS LEBEN, SO, WIE WIR ES KENNEN.")
  (320)
  (323 "SAMOS" "JETZT MACHT EUCH ENDLICH AUF UND STELLT EUCH EUREM SCHICKSAL.")
  (455)
  )

("sksp0010" :hint #x231
  (0 "DAXTER" "HEY! KOMM, WIR SEHEN UNS MAL DAS SPEEDBOOT VON DEM ALTEN FISCHKOPP AM DOCK AN!")
  )

("sksp0013" :hint #x232
  (0 "DAXTER" "HAST DU GESEHEN, WAS FÜR EIN RIESENSTÜCK DIESER LURKER-HAI AUS DEM BOOT DES FISCHERS GEBISSEN HAT?")
  (305 "DAXTER" "AM BESTEN, WIR HALTEN VIEL ABSTAND ZU DIESEN VIECHERN, ICH GLAUBE NICHT, DASS WIR ES MIT SO EINEM HÖLLENTIER AUFNEHMEN KÖNNEN!")
  )

("sksp0015" :hint #x234
  (0 "DAXTER" "DAS MUSS EINS VON DEN PRECURSOR-ORAKELN SEIN, VON DENEN DER WEISE DAUERND ERZÄHLT!")
  (238 "DAXTER" "HOFFENTLICH SIND DIE NICHT GENAU SO HÄSSLICH WIE ER!")
  )

("sksp0017" :hint #x235
  (0 "DAXTER" "WOW, GUCK DIR BLOSS MAL DIESE IRRE SKULPTUR AUF DEN FELSEN DA DRÜBEN AN!")
  )

("sksp0043" :hint #x24e
  (0 "DAXTER" "VIELLEICHT SOLLTEN WIR MAL DEN FISCHER AUSFINDIG MACHEN.")
  (136 "DAXTER" "SOVIEL ICH WEISS, SOLL ER AM UNTEREN FLUSS IM DSCHUNGEL FISCHEN!")
  )

("sksp018a" :hint #x297
  (0 "DAXTER" "DIESER FAULE FARMER SCHULDET UNS EINE ENERGIEZELLE!")
  (130 "DAXTER" "MIT DEM WERDEN WIR JETZT MAL REDEN!")
  )

;; -----------------
;; beach
;; -----------------

("bird-lady-beach-resolution"
  (30 "VOGEL-BEOBACHTERIN" "OH, JE, HOFFENTLICH GEHTS DEM ARMEN KLEINEN GUT. HIER, EINE ENERGIEZELLE FÜR EUREN MUT.")
  (243)
  (306 "FLUT FLUT" "MAMA!")
  (354)
  (406 "FLUT FLUT" "MAMA!")
  (430 "DAXTER" "OH, NEIN! NEIN! NEIN! NEIN! NEIN!")
  (533)
  (535 "VOGEL-BEOBACHTERIN" "SCHAUT MAL, IST DAS NICHT SÜSS? ES GLAUBT, DU WÄRST SEINE MAMA.")
  (696)
  (699 "DAXTER" "HÄ? ICH BIN NICHT DEINE MAMA! HAB ICH ETWA FEDERN?")
  (803)
  (807 "VOGEL-BEOBACHTERIN" "AH, LIEBE AUF DEN ERSTEN BLICK! OH...")
  (936)
  (939 "VOGEL-BEOBACHTERIN" "HÖRT MAL, JUNGS, ICH NEHME DAS KLEINE KÜKEN MIT INS DORF UND KÜMMERE MICH ZUSAMMEN MIT DEM WEISEN DARUM.")
  )

("bird-lady-introduction"
  (125 "VOGEL-BEOBACHTERIN" "ACH, HERRJE, SO EIN FURCHTBAR KRANKES VÖGELCHEN.")
  (245)
  (251 "DAXTER" "HAH! SIEHST AUCH NICHT GERADE GESUND AUS, LADY!")
  (326)
  (331 "VOGEL-BEOBACHTERIN" "OH, ENTSCHULDIGUNG. ICH DACHTE, DU WÄRST EIN ORANGEGEFLECKTER BAUCHRINGFRING.")
  (454)
  (457 "VOGEL-BEOBACHTERIN" "WISST IHR, GESTERN HABEN EIN PAAR SCHRECKLICH BÖSE WESEN HIER AM STRAND EINE FLUT-FLUT-MUTTER GEFANGEN.")
  (648)
  (654 :offscreen "VOGEL-BEOBACHTERIN" "JETZT LIEGT DIESES ARME KLEINE WAISENEI IM NEST OBEN AUF DER KLIPPE UND ICH KOMME NICHT DRAN.")
  (855 :offscreen "VOGEL-BEOBACHTERIN" "KÖNNT IHR DA DRAUFKLETTERN UND ES RUNTERSCHUBSEN? ICH HABE UNTEN ETWAS HEU HINGELEGT, UM ES AUFZUFANGEN.")
  (1041)
  (1044 "VOGEL-BEOBACHTERIN" "TUT EINER ALTEN FRAU EINEN GEFALLEN UND IHR BEKOMMT EINE ENERGIEZELLE DAFÜR.")
  (1198)
  )

("bird-lady-reminder-1"
  (56 "VOGEL-BEOBACHTERIN" "OH, HALLO NOCHMAL. HABT IHR JUNGS DAS BLAUE EI AUF DER KLIPPE GEFUNDEN?")
  (208)
  (211 "VOGEL-BEOBACHTERIN" "SCHUBST ES RUNTER UND IHR BEKOMMT EINE ENERGIEZELLE!")
  (348)
  )

("bird-lady-reminder-2"
  (58 "VOGEL-BEOBACHTERIN" "SEID IHR JUNGS ETWA IMMER NOCH HIER? HA, HA, HA!")
  (170)
  (174 "VOGEL-BEOBACHTERIN" "DEM ARMEN KEINEN BLAUEN EI AUF DEM ABHANG IST BESTIMMT SCHRECKLICH KALT.")
  (313)
  (316 "VOGEL-BEOBACHTERIN" "SCHUBST ES VON DER KLIPPE RUNTER UND RETTET ES, DAFÜR BEKOMMT IHR EINE ENERGIEZELLE!")
  )

("mayor-introduction"
  (44 "BÜRGERMEISTER" "OH... (MURMELT) JETZT SAGT MIR BLOSS NICHT, DASS IHR ZWEI AUCH EIN PROBLEM HABT!")
  (206)
  (209 "BÜRGERMEISTER" "ERST WERDEN IN DER NÄHE DES DORFES MONSTER GESICHTET UND JETZT DAS!")
  (352)
  (355 "BÜRGERMEISTER" "SEHT IHR DIE WINDMÜHLENFLÜGEL? DA OBEN, JUNGS, JA? DIE STEHEN STILL,")
  (497 "BÜRGERMEISTER" "DAS BEDEUTET, IM DORF GIBTS KEINEN STROM!")
  (569)
  (586 "BÜRGERMEISTER" "DER ECO-STRAHL AUS DEM DSCHUNGEL-TEMPEL IST UNTERBROCHEN WORDEN, JUNGS")
  (737)
  (740 "BÜRGERMEISTER" "UND NIEMAND TRAUT SICH, NACHZUSEHEN, WAS PASSIERT IST!")
  (861)
  (864 "DAXTER" "IST DIE RECHNUNG BEZAHLT?")
  (936)
  (939 "BÜRGERMEISTER" "JA? HMM, OH, DU BIST JA WITZIG.")
  (1089)
  (1092 "BÜRGERMEISTER" "WÜRDET IHR ZWEI DEN ECO-STRAHL REPARIEREN? FÜR EINE ENERGIEZELLE?")
  (1288 "BÜRGERMEISTER" "OH, NOCH ETWAS...")
  (1370 "BÜRGERMEISTER" "IHR ZWEI WOLLT NICHT ZUFÄLLIG EINE KLEINIGKEIT FÜR MEINE KAMPAGNE ZU MEINER WIEDERWAHL SPENDEN?")
  (1580 "BÜRGERMEISTER" "DAS WÄRE MIR GLATT NOCH EINE ENERGIEZELLE WERT!")
  (1687)
  (1690 "BÜRGERMEISTER" "DAS MINIMUM FÜR EINE SPENDE BETRÄGT, ÄHM, JA, BESCHEIDENE 90 PRECURSOR-ORBS!")
  )

("mayor-reminder-beams"
  (25 "BÜRGERMEISTER" "SCHON ZURÜCK? UND OHNE DIE ECO-STRAHLEN ZU REPARIEREN?")
  (157 "BÜRGERMEISTER" "(SCHLUCHZT) EUER DORF BRAUCHT EUCH, JUNGS!")
  )

("mayor-reminder-donation"
  (26 "BÜRGERMEISTER" "AH, HERE TO MAKE A DONATION TO MY CAMPAIGN, OH HO HO HO.")
  (159 "BÜRGERMEISTER" "90 PRECURSOR ORBS BUYS YOU A POWER CELL, THANK YOU.")
  )

("mayor-resolution-beams"
  (28 "BÜRGERMEISTER" "OH HO HO, WAS FÜR EIN WUNDERVOLLER ANBLICK! ICH DANKE EUCH!")
  (190 "BÜRGERMEISTER" "UND DAS GANZE DORF WIRD MIR DANKEN -")
  (280 "BÜRGERMEISTER" "OH, JUNGS, DANK EUCH HABEN WIR WIEDER STROM UND MEINE WIEDERWAHL IST GESICHERT!")
  (472)
  (475 "BÜRGERMEISTER" "UND DAFÜR, MEIN JUNGE, HAST DU DIR EINE ENERGIEZELLE VERDIENT!")
  )

("mayor-resolution-donation"
  (28 "BÜRGERMEISTER" "IHR WOLLT ALSO ETWAS SPENDEN? GUT... HOFFENTLICH EIN SCHÖNES SÜMMCHEN!")
  (219)
  (220 "BÜRGERMEISTER" "JUHU! OHHH, DAS IST EINE GROSSZÜGIGE SPENDE!")
  (350 "BÜRGERMEISTER" "ICH-ICH-ICH HOFFE NUR, D-D-DA-DASS DIESE ENERGIEZELLE EUREN EINSATZ GEBÜHREND BELOHNT!")
  )

("sculptor-introduction"
  (30 "BILDHAUER" "HEY... DU HAARIGER KLEINER KUMPEL!")
  (154)
  (161 "BILDHAUER" "OH... ICH DACHTE, DU WÄRST MEINE MUSE.")
  (282)
  (285 "DAXTER" "DEINE WAS?")
  (334)
  (343 "BILDHAUER" "HAST DU NOCH NIE EINE MUSE GESEHEN?")
  (430)
  (434 "BILDHAUER" "DAS IST EINE KLEINES LEUCHTENDES EICHHÖRNCHEN, SO GROSS WIE DU, SEHR MUTIG UND IMMER GUT DRAUF!")
  (622)
  (632 "DAXTER" "OH, JETZT KAPIER ICH! WIE EIN KUMPELCHEN, HÄ?")
  (757)
  (763 "BILDHAUER" "ALSO, ES IST SO: OHNE MEINE MUSE KANN ICH NICHT BILDHAUERN.")
  (920)
  (923 "BILDHAUER" "ABER WENN SIE DA IST, SEHE ICH NUR SCHÖNHEIT IN ALLEN DINGEN, WISST IHR?")
  (1087)
  (1091 "BILDHAUER" "IM MOMENT KÖNNTE ICH MICH NICHT MAL AUS 'NER KISTE RAUSMEISSELN.")
  (1182)
  (1191 :offscreen "BILDHAUER" "ICH GLAUBE, SIE IST ZUR NEBELINSEL GELAUFEN.")
  (1278)
  (1281 "BILDHAUER" "ACH, ICH HOFFE BLOSS, IHR GEHTS GUT.")
  (1370)
  (1376 "BILDHAUER" "EINE ENERGIEZELLE, WENN IHR SIE ZURÜCKBRINGT!")
  (1441)
  (1467 "DAXTER" "MOMENT MAL! WIR WERDEN AUF KEINEN FALL ZURÜCK ZUR NEBELINSEL GEHEN!")
  (1646)
  (1649 "DAXTER" "ODER DOCH?")
  )

("sculptor-reminder-1"
  (27 "BILDHAUER" "OH, HEY, LEUTE! HABT IHR MEINE MUSE SCHON GEFUNDEN?")
  (169)
  )

("sculptor-resolution"
  (90 "BILDHAUER" "OH, MEINE MUSE! IHR HABT SIE GERETTET! OH, MANN, IHR SEID DIE GRÖSSTEN!")
  (230 "BILDHAUER" "HIER, NEHMT DIESE ENERGIEZELLE, ICH BRAUCHE SIE NICHT MEHR, MEINE INSPIRATION IST WIEDER DA!")
  )

;; -----------------
;; jungle
;; -----------------

("fisher-accept"
  (0 :offscreen "FISCHER" "MUSST DREI SACHEN WISSEN, WENN DU FISCHST. ERSTENS: KANNST ZWEI ARTEN VON FISCHEN FANGEN, EINPFÜNDER UND FÜNFPFÜNDER.")
  (275 :offscreen "FISCHER" "ZWEITENS: LÄSSTE 20 PFUND VON DEN GUTEN FISCHEN ENTWISCHEN, DU, DANN NEHM ICH DIR DAS NETZ WEG.")
  (470 :offscreen "FISCHER" "DRITTENS GIBTS GIFTIGE AALE IM FLUSS, AUCH WENN DU NUR EINEN VON DEN BURSCHEN ERWISCHST, VERGIFTET ER DEN GANZEN FANG!")
  )

("fisher-introduction"
  (0 "DAXTER" "WAS HAST'N DA IM KORB?")
  (50 "FISCHER" "ACH, NICHT DER REDE WERT.")
  (107)
  (110 "FISCHER" "DIE MONSTER DA AM OZEAN HABEN EIN STÜCK AUS MEINEM BOOT RAUSGEBISSEN")
  (210)
  (212 "FISCHER" "UND NUN VERLEIBEN SIE SICH MEINEN FANG EIN!")
  (290)
  (293 "FISCHER" "EGAL, WAS ICH MACHE, ICH FANG HIER IM FLUSS EINFACH KEINEN FISCH MEHR.")
  (419)
  (425 "DAXTER" "UUH, VIELLEICHT IST'S DEIN MUNDGERUCH.")
  (515)
  (525 "FISCHER" "MEINST, DU KANNST DAS BESSER? VERSUCH MAL, MIT 'NEM WINZIGEN NETZ FLUSSFISCHE ZU FANGEN!")
  (665)
  (671 "FISCHER" "KRIEGST 'NE ENERGIEZELLE VON MIR, WENN DU 200 PFUND VON DEN VIECHERN FÄNGST!")
  (808)
  (814 "FISCHER" "UND ICH LASS DICH UND DEN KNIRPS HIER MEIN SCHNELLBOOT BENUTZEN, UM ZUR NEBELINSEL ZU KOMMEN.")
  (955)
  (964 "FISCHER" "NA, WOLLT IHR ES VERSUCHEN?")
  )

("fisher-reject"
  (2 "FISCHER" "NAJA, NUN, WENN IHR ES EUCH ANDERS ÜBERLEGEN TUT, DANN WISST IHR JA, WO IHR MICH FINDET.")
  )

("fisher-reminder-1"
  (6 "FISCHER" "WOLLT'S WOHL MIT DEM FLUSS AUFNEHMEN, WAS?")
  )

("fisher-resolution"
  (0 "FISCHER" "IHR HABT'S GESCHAFFT! HABT 200 PFUND FISCH GEFANGEN!")
  (115)
  (120 "FISCHER" "NICHT SCHLECHT FÜR EIN PAAR LANDRATTEN!")
  (185)
  (199 "FISCHER" "HIER, DIE ENERGIEZELLE. UND IHR KÖNNT EUCH MEIN BOOT VOM DOCK IM DORF HOLEN, WENN IHR ES BRAUCHT!")
  )

;; -----------------
;; misty
;; -----------------

;; -----------------
;; firecanyon
;; -----------------

("assistant-firecanyon-resolution"
  (25 "KEIRA" "SUPER! IHR HABT DIE 20 ENERGIEZELLEN, UM MEINEN HITZESCHILD ZU AKTIVIEREN!")
  (147)
  (150 "KEIRA" "SEID ABER VORSICHTIG, DER SCHILD SCHÜTZT DEN ZOOMER NUR BIS ZU EINER TEMPERATUR VON 500 GRAD.")
  (310 "KEIRA" "ALSO LASST IHN NICHT ZU HEISS LAUFEN.")
  (352)
  (355 :offscreen "KEIRA" "WENN IHR ÜBER GLÜHENDE LAVA FLIEGT, HEIZT IHN DAS GANZ SCHÖN SCHNELL AUF.")
  (462)
  (466 "KEIRA" "WENN IHR 500 GRAD ERREICHT, IST ES AUS!")
  (554)
  (559 "DAXTER" "AUS?! DU MEINST WIE IN \"AUS UND VORBEI\"?!")
  (636)
  (639 "KEIRA" "DER FEUER-CANYON IST SEHR HEISS, ACHTET AUF SPRUNGMÖGLICHKEITEN, UM DEN ABSTAND ZUR LAVA ZU VERGRÖSSERN.")
  (797)
  (800 :offscreen "KEIRA" "ICH HABE AUCH MEHRERE BLAUE KÜHLBALLONS STEIGEN LASSEN, MIT DENEN IHR DIE TEMPERATUR DES SCHILDES SCHNELL SENKEN KÖNNT.")
  (956)
  (962 "KEIRA" "ACH, JA, WENN IHR DURCH DEN CANYON SEID, VERGESST JA NICHT, DAS TELEPORTTOR")
  (1063 "KEIRA" "IM LABOR DES BLAUEN WEISEN ZU AKTIVIEREN. DANN KÖNNEN WIR UNS ZU EUCH HINÜBERTELEPORTIEREN!")
  (1222 "KEIRA" "VIEL GLÜCK!")
  )

;; -----------------
;; snowy
;; -----------------

("sksp0345" :hint #x443
  (0 "DAXTER" "WIE KOMMEN WIR IN DIESES FORT REIN?")
  )

("sksp0346" :hint #x444
  (0 "DAXTER" "VIELLEICHT KANN ROTES ECO DIESEN KERL BESIEGEN!")
  )

("sksp0350" :hint #x448
  (0 "DAXTER" "SCHNAPP IHN DIR, WENN SEINE STACHELN DRIN SIND!")
  )

("sksp0360" :hint #x44c
  (0 "DAXTER" "JAWOLL! WIR HABEN DIE VERSIEGELTEN GELBEN ECO-ÖFFNUNGEN AUFGEMACHT!")
  )

;; -----------------
;; spidercave
;; -----------------

("sksp0327" :hint #x432
  (0 "DAXTER" "ICH GLAUBE, DAS WAR DER LETZTE DUNKLE ECO-KRISTALL!")
  )

("sksp0332" :hint #x437
  (0 "DAXTER" "PASS AUF, DASS DAS LICHT NICHT AUSGEHT!")
  )

("sksp0333" :hint #x438
  (0 "DAXTER" "STOSS AN EINEN KRISTALL, DANN BEKOMMST DU LICHT!")
  )

("sksp0334" :hint #x439
  (0 "DAXTER" "HAU AB! DIESER KRISTALL EXPLODIERT GLEICH!")
  )

("sksp0341" :hint #x440
  (0 "DAXTER" "ICH GLAUBE, WIR SIND HIER IN EINEM SPINNENNEST!")
  )

;; -----------------
;; lavatube
;; -----------------

("asstva74" :hint #x428
  (0 "KEIRA" "IHR HABT NICHT GENUG ENERGIEZELLEN, UM DURCH DIE LAVA ZU KOMMEN!")
  (182 "KEIRA" "IHR KÖNNT NICHT ZU GOL UND MAIAS ZITADELLE GELANGEN, BIS IHR 72 ENERGIEZELLEN GESAMMELT HABT!")
;; -----------------
;; firecanyon
;; -----------------

("assistant-firecanyon-resolution"
  (25 "KEIRA" "SUPER! IHR HABT DIE 20 ENERGIEZELLEN, UM MEINEN HITZESCHILD ZU AKTIVIEREN!")
  (147)
  (150 "KEIRA" "SEID ABER VORSICHTIG, DER SCHILD SCHÜTZT DEN ZOOMER NUR BIS ZU EINER TEMPERATUR VON 500 GRAD.")
  (310 "KEIRA" "ALSO LASST IHN NICHT ZU HEISS LAUFEN.")
  (352)
  (355 :offscreen "KEIRA" "WENN IHR ÜBER GLÜHENDE LAVA FLIEGT, HEIZT IHN DAS GANZ SCHÖN SCHNELL AUF.")
  (462)
  (466 "KEIRA" "WENN IHR 500 GRAD ERREICHT, IST ES AUS!")
  (554)
  (559 "DAXTER" "AUS?! DU MEINST WIE IN \"AUS UND VORBEI\"?!")
  (636)
  (639 "KEIRA" "DER FEUER-CANYON IST SEHR HEISS, ACHTET AUF SPRUNGMÖGLICHKEITEN, UM DEN ABSTAND ZUR LAVA ZU VERGRÖSSERN.")
  (797)
  (800 :offscreen "KEIRA" "ICH HABE AUCH MEHRERE BLAUE KÜHLBALLONS STEIGEN LASSEN, MIT DENEN IHR DIE TEMPERATUR DES SCHILDES SCHNELL SENKEN KÖNNT.")
  (956)
  (962 "KEIRA" "ACH, JA, WENN IHR DURCH DEN CANYON SEID, VERGESST JA NICHT, DAS TELEPORTTOR")
  (1063 "KEIRA" "IM LABOR DES BLAUEN WEISEN ZU AKTIVIEREN. DANN KÖNNEN WIR UNS ZU EUCH HINÜBERTELEPORTIEREN!")
  (1222 "KEIRA" "VIEL GLÜCK!")
  )

("asstvb09" :hint #x24f
  (0 "KEIRA" "IHR HABT KEINE 20 ENERGIEZELLEN, UM MEINEN HITZESCHILD ZU AKTIVIEREN!")
  (216)
  (234 "KEIRA" "YOU CAN'T CROSS FIRE CANYON UNTIL YOU COLLECT ENOUGH POWER CELLS.")
  )

("sksp0076" :hint #x501
  (0 "DAXTER" "JAK, WIR MÜSSEN EIN PAAR SPRUNGPLATTFORMEN BENUTZEN, UM NICHT AUF DEN HEISSEN BODEN ZU KOMMEN!")
  )

("sksp0077" :hint #x502
  (0 "DAXTER" "BALLONS GUT, GLÜHENDES HEISSES MAGMA SCHLECHT!")
  )

("sksp0078" :hint #x503
  (0 "DAXTER" "FLIEG ÜBER DAS PRECURSOR-ZEUG, UM UNS ABZUKÜHLEN!")
  )

("sksp0079" :hint #x504
  (0 "DAXTER" "AHH! ICH WERDEN STERBEN! ICH KOMME, GROSSVATER!")
  (238)
  (241 "DAXTER" "DU MUSST DIESES DING AUF DIE ANDERE SEITE BRINGEN, BEVOR ES ÜBERHITZT!")
  )

("sksp0080" :hint #x505
  (0 "DAXTER" "MIT DEM HÜPFDREHER KANNST DU ENGERE KURVEN FLIEGEN!")
  )

("sksp0081" :hint #x506
  (0 "DAXTER" "AH! VIELLEICHT SOLLTE ICH LIEBER FLIEGEN!")
  )

("sksp0082" :hint #x507
  (0 "DAXTER" "DU GIBST DIR MÜHE, DICH VON DIESEN DUNKLEN ECO-KISTEN FERNZUHALTEN, ODER?")
  )

("sksp0083" :hint #x508
  (0 "DAXTER" "HUCH! MAL SEHEN, OB WIR DURCH DIESE LURKER AN HÖHE GEWINNEN!")
  )

("sksp0084" :hint #x509
  (0 "DAXTER" "ZU NAHE, ZU NAHE!")
  )

("sksp0085" :hint #x50a
  (0 "DAXTER" "WOW! DIESES BABY WIRD VIEL ZU HEISS!")
  )

("sksp0086" :hint #x50b
  (0 "DAXTER" "IN EIN PAAR SEKUNDEN SIND WIR GEGRILLTES FLUT FLUT!")
  )

("sksp0087" :hint #x50d
  (0 "DAXTER" "TRIFF DIE BALLONS, UM UNS ABZUKÜHLEN!")
  )

("sksp0088" :hint #x50e
  (0 "DAXTER" "DA KOMMT WIEDER EIN BALLON!")
  )

("sksp0089" :hint #x50f
  (0 "DAXTER" "HÄTTE ICH DOCH HEUTE BLOSS VERSCHLAFEN!")
  )

("sksp0090" :hint #x510
  (0 "DAXTER" "DU HAST EINEN BALLON VERPASST! WIR BRAUCHEN DIESE BALLONS, SONST WERDEN WIR GEBRATEN!")
  )

("sksp0091" :hint #x511
  (0 "DAXTER" "DIESES BABY WIRD ZU HEISS!")
  )

("sksp0092" :hint #x512
  (0 "DAXTER" "RIECHT'S HIER ETWA ANGEBRANNT?!")
  )

("sksp0093" :hint #x513
  (0 "DAXTER" "ICH GLAUBE, MEIN SCHWANZ BRENNT!")
  )

("sksp0094" :hint #x514
  (0 "DAXTER" "GLEICH EXPLODIERT ER!")
  )

("sksp0095" :hint #x515
  (0 "DAXTER" "JUHUU! WIR HABEN'S GESCHAFFT!")
  )

("sksp0096" :hint #x516
  (0 "DAXTER" "HIER GIBT'S AUCH SPÄHFLIEGEN!")
  )

  )

("sksp0375" :hint #x70d
  (0 "DAXTER" "SCHIESS AUF DEN ENERGIEBEREICH, UM DIE TÜR ZU ÖFFNEN!")
  )

;; -----------------
;; citadel
;; -----------------

("bluesage-resolution"
  (63 "BLAUER WEISE" "GUT GEMACHT, JUNGS! DER ALTE SAMOS HATTE RECHT MIT EUCH!")
  (162)
  (180 "BLAUER WEISE" "ACH, DU HEILIGES PRECURSOR-METALL!")
  (259 "BLAUER WEISE" "WIR DÜRFEN NICHT ZULASSEN, DASS DIESE HEIMTÜCKISCHE MASCHINE ALLES ZERSTÖRT!")
  (420 "BLAUER WEISE" "ICH WERDE VERSUCHEN, DIE SCHUTZSCHILDTÜR IN BEWEGUNG ZU SETZEN, INDEM ICH EINEN ENERGIESTRAHL")
  (570 "BLAUER WEISE" "ZWISCHEN MIR UND DEM GROSSEN PORTAL DARUNTER ERZEUGE!")
  (666 "DAXTER" "ÄH... JA. MACH DAS MAL. WIR, ÄH... WERDEN NOCH MEHR HILFE HOLEN.")
  (873)
  (891 :offscreen "DAXTER" "VOLLKOMMEN IRRE!")
  (980)
  )

("green-sagecage-introduction"
  (130 "SAMOS" "WIRD AUCH LANGSAM ZEIT, DASS IHR ZWEI HIER AUFTAUCHT!")
  (213 "DAXTER" "SCHÖNEN GUTEN TAG, AUCH! LÄSST MAN DICH JETZT DIE BÖDEN HIER WISCHEN?")
  (343 "SAMOS" "WIR HABEN KEINE ZEIT ZUM SCHERZEN, DAXTER. GOL UND MAIA HABEN UNS ENTFÜHRT, UM MIT UNSERER ENERGIE")
  (515 "SAMOS" "IHRE SCHEUSSLICHE MASCHINE ANZUTREIBEN.")
  (574)
  (600 :offscreen "SAMOS" "WIE ES SCHEINT, HABEN SIE DIE FUNKTIONIERENDEN TEILE EINES PRECURSOR-ROBOTERS")
  (710 :offscreen "SAMOS" "MIT DEN AUS DEM GANZEN LAND ZUSAMMENGETRAGENEN ARTEFAKTEN VERBUNDEN,")
  (800)
  (803 :offscreen "SAMOS" "EIGENE TEUFLISCHE VERÄNDERUNGEN VORGENOMMEN UND EINE KREATUR ERSCHAFFEN,")
  (930 "SAMOS" "DIE ALS EINZIGE DIE DUNKLEN PRECURSOR-ECO-STATIONEN ÖFFNEN KANN.")
  (1060 "SAMOS" "WENN DU UNS VIER BEFREIEN KANNST, KÖNNEN WIR ALLE MIT VEREINTEN KRÄFTEN DAS SCHUTZSCHILD UM DEN ROBOTER ZERSTÖREN,")
  (1276 "SAMOS" "BEVOR SIE MIT IHM DIE GANZE WELT VERNICHTEN.")
  )

("green-sagecage-outro-preboss"
  (56 "GOL" "DU KOMMST ZU SPÄT, SAMOS.")
  (144 "GOL" "SOBALD ICH UNBEGRENZT DUNKLES ECO BESITZE, WERDE ICH DEN SCHLÜSSEL ZUR SCHÖPFUNG HABEN!")
  (335 "SAMOS" "DAS IST WAHNSINN! WENN DU SO VIEL DUNKLES ECO FREISETZT, WIRD ALLES ZERSTÖRT! ALLES!")
  (525 "SAMOS" "SIEH DOCH, WAS ES AUS EUCH GEMACHT HAT!")
  (578)
  (581 "MAIA" "ES HAT UNS EINE ART SCHÖNHEIT GESCHENKT, DIE DU NIE VERSTEHEN WÜRDEST.")
  (693)
  (696 "DAXTER" "SCHÖNHEIT? HABT IHR BEIDEN IN LETZTER ZEIT MAL IN DEN SPIEGEL GESCHAUT?")
  (825)
  (828 "MAIA" "WENN DU DENKST, EIN HAARIGER WINZLING ZU SEIN, WÄRE SCHLIMM, WARTE NUR, BIS WIR DIE ECO-STATION GEÖFFNET HABEN!")
  (1065 "GOL" "UND IHR ZWEI SEID NUR WEGEN MEINER HILFE SO WEIT GEREIST.")
  (1180 "GOL" "NARREN! LEHNT EUCH ZURÜCK UND GENIESST DIE NEUERSCHAFFUNG DER WELT!")
  (1391)
  (1605 "SAMOS" "JAK! NIMM DEN AUFZUG UND HALTE DIESEN ROBOTER AUF!")
  )

("green-sagecage-resolution"
  (35 "SAMOS" "TOLL GEMACHT, JUNGS! JETZT SEID IHR WAHRE HELDEN!")
  (158 "SAMOS" "ICH VEREINE JETZT MEINE GRÜNE ECO-KRAFT MIT DEN ANDEREN DREI WEISEN")
  (280 "SAMOS" "UND ZUSAMMEN ÖFFNEN WIR DIE TÜR DES SCHUTZSCHILDES, DAS DEN PRECURSOR-ROBOTER UMGIBT.")
  (405 "DAXTER" "JA, JA, FÜR DEN ANFANG SCHON GANZ GUT.")
  (457 "DAXTER" "UND WENN IHR DIESEN SCHILD GEÖFFNET HABT, WAS MACHT IHR DANN MIT DEM ROBOTER?")
  (586 "SAMOS" "GAR NICHTS, DAXTER. WIR MÜSSEN NUR DAS SCHUTZSCHILD OFFEN HALTEN.")
  (715 "SAMOS" "DANN LIEGT ES AN EUCH BEIDEN, DEN ROBOTER ZU ZERSTÖREN.")
  (823 "DAXTER" "OH, KLASSE. JETZT KANN ICH DEM KERL HELFEN, DER MICH IN EINER RATTE VERWANDELT HAT")
  (983 "DAXTER" "UND DIE EINZIGE PERSON VERNICHTEN, DIE MICH ZURÜCKVERWANDELN KANN!")
  (1111)
  (1171 "SAMOS" "RETTET ZUERST EINMAL DIE WELT, DANN VERSUCHEN WIR, GOL DAZU ZU BRINGEN, DAXTER ZU HELFEN.")
  )

("redsage-resolution"
  (58 "ROTER WEISE" "(LACHT) ENDLICH KOMMT IHR MICH RETTEN.")
  (206 "ROTER WEISE" "WISST IHR, WIE LANGE ICH SCHON HIER BIN? WIESO HABT IHR SO LANGE GEBRAUCHT? (LACHT) ")
  (389 "ROTER WEISE" "UND WIE HEISST IHR?")
  (429)
  (450 "DAXTER" "ICH BIN DAXTER! DAS IST JAK, GEHÖRT ZU MIR.")
  (540 :offscreen "ROTER WEISE" "GUT GEMACHT, DAXTER. DU BIST EIN WAHRER HELD.")
  (677)
  (716 "ROTER WEISE" "IHR MÜSST GOL DARAN HINDERN, DEN ROBOTER ZU STARTEN.")
  (848 "ROTER WEISE" "MIT MEINER ECO-KRAFT HELFE ICH EUCH, DIE SCHUTZSCHILDTÜR ZU ÖFFNEN.")
  )

("yellowsage-resolution"
  (57 "GELBER WEISE" "WER HÄTTE GEDACHT, DASS ICH MICH EINES TAGES")
  (137 "GELBER WEISE" "VON EINEM JUNGEN UND SEINER RATTE RETTEN LASSEN MÜSSTE!")
  (271 "GELBER WEISE" "AHHH, DIESE PEINLICHKEIT WERDE ICH GOL UND MAIA GANZ SICHER HEIMZAHLEN!")
  (471)
  (495 "GELBER WEISE" "DANACH KÖNNEN WIR UNS JA UM DEN RATTENEINTOPF KÜMMERN...")
  (605)
  )

;; -----------------
;; finalboss
;; -----------------

("GOL-AM01" :hint #x0
  (0 "GOL" "IHR GEBT EINFACH NICHT AUF, WAS?")
  )

("GOL-AM02" :hint #x0
  (0 "GOL" "BALD GEHÖRT DAS DUNKLE ECO UNS!")
  )

("GOL-AM03" :hint #x0
  (0 "GOL" "ERLEDIGT SIE!")
  )

("GOL-AM04" :hint #x0
  (0 "GOL" "FEUER FREI!")
  )

("GOL-AM05" :hint #x0
  (0 "GOL" "JAGT SIE IN DIE LUFT!")
  )

("GOL-AM06" :hint #x0
  (0 "GOL" "WAS? DIE SCHON WIEDER?!")
  )

("GOL-AM07" :hint #x0
  (0 "GOL" "ES IST ZU SPÄT!")
  )

("GOL-AM08" :hint #x0
  (0 "GOL" "IHR GEHÖRT MIR!")
  )

("GOL-AM09" :hint #x0
  (0 "GOL" "JETZT HABE ICH EUCH!")
  )

("GOL-AM10" :hint #x0
  (0 "GOL" "HA, HA, HA, HA, HA!")
  )

("GOL-AM11" :hint #x0
  (0 "GOL" "KEINE GNADE!")
  )

("GOL-AM12" :hint #x0
  (0 "GOL" "NIMM DAS!")
  )

("GOL-AM13" :hint #x0
  (0 "GOL" "NETTER VERSUCH!")
  )

("GOL-AM14" :hint #x0
  (0 "GOL" "HALT STILL!")
  )

("GOL-AM15" :hint #x0
  (0 "GOL" "ERBÄRMLICH!")
  )

("GOL-AM16" :hint #x0
  (0 "GOL" "NEEEIN!")
  )

("GOL-AM17" :hint #x0
  (0 "GOL" "AHHH!")
  )

("GOL-AM18" :hint #x0
  (0 "GOL" "WIR WERDEN DIE ECO-STATION GANZ ÖFFNEN UND EUCH ZWEI VERNICHTEN!")
  )

("GOL-AM19" :hint #x0
  (0 "GOL" "HELLES ECO! ES EXISTIERT ALSO WIRKLICH!")
  )

("GOL-AM20" :hint #x0
  (0 "GOL" "DAS LASSEN WIR UNS NICHT GEFALLEN!")
  )

("MAI-AM01" :hint #x0
  (0 "MAIA" "ERLEDIGE SIE BEIDE, EIN FÜR ALLE MAL!")
  )

("MAI-AM02" :hint #x0
  (0 "MAIA" "MACH SIE FERTIG!")
  )

("MAI-AM03" :hint #x0
  (0 "MAIA" "HA, HA, HA!")
  )

("MAI-AM04" :hint #x0
  (0 "MAIA" "ECO HILFT EUCH JETZT NICHT MEHR!")
  )

("MAI-AM05" :hint #x0
  (0 "MAIA" "TU DOCH WAS!")
  )

("MAI-AM06" :hint #x0
  (0 "MAIA" "AAAAH!")
  )

("MAI-AM07" :hint #x0
  (0 "MAIA" "NEEEEEIN!")
  )

("MAI-AM08" :hint #x0
  (0 "MAIA" "WIR WERDEN DIE ECO-STATION GANZ ÖFFNEN UND EUCH ZWEI VERNICHTEN!")
  )

("MAI-AM09" :hint #x0
  (0 "MAIA" "SIE DÜRFEN ES NICHT BEKOMMEN!")
  )

("finalbosscam-white-eco"
  (143 :offscreen "GOL" "HELLES ECO?! ES EXISTIERT ALSO WIRKLICH!")
  (268 :offscreen "MAIA" "SIE DÜRFEN ES NICHT BEKOMMEN!")
  )

("green-sagecage-daxter-sacrifice"
  (0 "DAXTER" "HELLES ECO! DAS KÖNNTE MICH ZURÜCKVERWANDELN, HAH!")
  (114)
  (123 "DAXTER" "ODER... ES KÖNNTE DEN ROBOTER AUFHALTEN.")
  (235)
  (274 "DAXTER" "HMM... WUSCHELIG BLEIBEN ODER DIE WELT RETTEN? MAL NACHDENKEN...")
  (404)
  (437 "DAXTER" "OKAY, NA GUT, DANN RETTEN WIR EBEN DIE WELT, ABER MACHT SCHNELL, BEVOR ICH'S MIR ANDERS ÜBERLEGE!")
  (634)
  )

("green-sagecage-outro-beat-boss-a"
  (165 :offscreen "MAIA" "TU DOCH WAS!")
  (216)
  (596 :offscreen "GOL" "NEEEEIN!")
  )

("green-sagecage-outro-beat-boss-b"
  (522 "SAMOS" "NUN JA, ES SCHEINT, ALS HÄTTE ICH EUCH JUNGS FALSCH EINGESCHÄTZT,")
  (640 "SAMOS" "IHR HABT DOCH DAS ZEUG ZU HELDEN!")
  (745)
  (751 "KEIRA" "OH, DAXTER, JETZT MUSST DU IMMER SO BLEIBEN.")
  (845)
  (847 "DAXTER" "MACH DIR KEINE SORGEN UM MICH, SÜSSE. DU WEISST DOCH, ES HEISST: \"KLEINER KERL, ABER GROSS WAS DAHINTER.\"")
  (1096)
  (1100 "BLAUER WEISE" "JAK, DU BESITZT EIN UNGLAUBLICHES TALENT, ECO ZU KANALISIEREN!")
  (1219)
  (1222 "BLAUER WEISE" "SAMOS, VIELLEICHT HATTEST DU DOCH RECHT MIT DEM BURSCHEN!")
  (1321)
  (1323 "ROTER WEISE" "UND KEIRA, OHNE DEINE HILFE UND DEINEN EINFALLSREICHTUM WÄRE NICHTS DAVON MÖGLICH GEWESEN.")
  (1515 "ROTER WEISE" "HA, HA, HA. VIELLEICHT HABEN WIR JA EINEN NEUEN WEISEN GEFUNDEN, JETZT, WO GOL UND MAIA FORT SIND.")
  (1728)
  (1731 "SAMOS" "JA, GOL UND MAIA... DAS DUNKLE ECO HAT SIE MÖGLICHERWEISE GETÖTET.")
  (1916 :offscreen "SAGE" "MÖGLICHERWEISE...")
  (1999)
  (2003 "DAXTER" "ACH, WEN JUCKT'S? HOLT SIE HER, WIR MACHEN SIE NOCHMAL FERTIG! ODER, JAK?")
  (2168)
  (2172 "DAXTER" "ICH SAGTE, \"ODER, JAK?\"")
  (2256)
  (2302 "DAXTER" "WOW! NIMM MAL 'NE KALTE DUSCHE, DU HELD!")
  )

("green-sagecage-outro-beat-boss-enough-cells"
  (151 "SAMOS" "HEILIGE YAKOW! WAS IST DAS DENN?")
  (270 "KEIRA" "WOW, DAS IST EINE ALTE PRECURSOR-TÜR!")
  (342 :offscreen "KEIRA" "ES SCHEINT, ALS LIESSE SIE SICH ÖFFNEN, WENN WIR ALLE 100 LÖCHER MIT ENERGIEZELLEN FÜLLEN!")
  (485 "DAXTER" "ÄHM, WIR SIND HELDEN, WISST IHR NOCH? WIR HABEN 100 ENERGIEZELLEN!")
  )

("green-sagecage-outro-beat-boss-need-cells"
  (151 "SAMOS" "HEILIGE YAKOW! WAS IST DAS DENN?")
  (266 "KEIRA" "WOW, DAS IST EINE ALTE PRECURSOR-TÜR!")
  (342 :offscreen "KEIRA" "ES SCHEINT, ALS LIESSE SIE SICH ÖFFNEN, WENN WIR ALLE 100 LÖCHER MIT ENERGIEZELLEN FÜLLEN!")
  (485 "DAXTER" "OH, MANN, JETZT GEHT DAS SCHON WIEDER LOS!")
  )

("green-sagecage-outro-big-finish"
  (322 "DAXTER" "WOW! WAS... IST DAS?")
  (425)
  (428 "KEIRA" "OH, ES IST WUNDERSCHÖN...")
  (516)
  (519 "SAMOS" "BEI ALLEN PRECURSORN...")
  (602)
  )

;; -----------------
;; uncategorized
;; -----------------

