(language-id 3)

;; -----------------
;; intro
;; -----------------

("sage-intro-sequence-a"
  (24 :offscreen "SAMOS" "ME HE PASADO LA VIDA BUSCANDO RESPUESTAS QUE MI PADRE Y SUS ANTEPASADOS NO PUDIERON ENCONTRAR.")
  (260 :offscreen "SAMOS" "¿QUIÉNES ERAN LOS PRECURSOR? ¿POR QUÉ CREARON LOS ENORMES MONOLITOS QUE ENSUCIAN NUESTRO PLANETA?")
  (454 :offscreen "SAMOS" "¿CÓMO PUDIERON DOMINAR EL ECO? LA ENERGÍA VITAL DEL MUNDO.")
  (581 :offscreen "SAMOS" "¿Y POR QUÉ SE DESVANECIERON?")
  (708)
  (720 :offscreen "SAMOS" "HE PREGUNTADO A LAS PLANTAS PERO ELLAS NO LO RECUERDAN.")
  (818 :offscreen "SAMOS" "LAS PLANTAS SE LO HAN PREGUNTADO A LAS PIEDRAS, PERO ELLAS TAMPOCO SE ACUERDAN.")
  (955 :offscreen "SAMOS" "NI SIQUIERA LAS PIEDRAS SE ACUERDAN...")
  (1064)
  (1090 :offscreen "SAMOS" "CADA HUESO DE MI CUERPO ME DICE QUE LAS RESPUESTAN DESCANSAN EN LOS HOMBROS DE UN JOVEN.")
  (1297 :offscreen "SAMOS" "INCONSCIENTE DE SU DESTINO, A QUIEN NO LE INTERESA AVERIGUAR LA VERDAD, Y QUE RECHAZA MI GUÍA!")
  (1536)
  (1545 :offscreen "SAMOS" "¿Y POR QUÉ IBA ÉL A ESCUCHAR AL VIEJO SAMOS EL SABIO DE TODAS FORMAS?")
  (1680)
  (1686 :offscreen "SAMOS" "TAN SOLO SOY EL MAESTRO DEL ECO VERDE, UNO DE LOS HOMBRES MÁS SABIOS DEL PLANETA.")
  (1875)
  (1958 :offscreen "SAMOS" "ASÍ QUE PARECE QUE LA RESPUESTA NO ESTRIBA EN UNA CUIDADOSA INVESTIGACIÓN NI EN SENSATAS DELIBERACIONES, NO.")
  (2141)
  (2145 :offscreen "SAMOS" "COMO EN MUCHOS MISTERIOS DEL DESTINO")
  (2281 :offscreen "SAMOS" "COMIENZA CON UN PEQUEÑO ACTO DE DESOBEDIENCIA.")
  (2440 "DAXTER" "¡EH, JAK! EL AMIGUETE VERDE NOS DIJO QUE NO VINIÉSEMOS POR AQUÍ.")
  )

("sage-intro-sequence-d1"
  (137 "SAMOS" "¿PERO QUÉ DEMONIOS QUERÉIS VOSOTROS DOS?")
  (220 "DAXTER" "E- E- E- E- EEEESTÁBAMOS- MMMM- MMMM-")
  (283 "SAMOS" "¡NO SIGAS! EN LUGAR DE SEGUIR MI CONSEJO, FUISTEIS A TRASTEAR AL ÚNICO SITIO")
  (440 "SAMOS" "EN EL QUE OS DIJE QUE NO ENTRARAIS: ¡LA ISLA DE MISTY!")
  (550 "DAXTER" "¡BUENO SÍ! Y-")
  (579 "SAMOS" "Y TÚ, DAXTER, AL FINAL TE DISTE UN BAÑO, QUE TE HACÍA FALTA, PERO EN UNA BAÑERA REBOSANTE DE ECO OSCURO.")
  (793 "DAXTER" "MIRA ABUELETE, ¿VAS A SEGUIR REZONGANDO, O ME VAS A AYUDAR A SALIR DE ESTE LÍO?")
  (920 "SAMOS" "¡VOY A SEGUIR REZONGANDO! PORQUE EN MI DOCTA OPINIÓN, ESTE CAMBIO ES MÁS BIEN UNA MEJORA.")
  (1130 "SAMOS" "AUNQUE QUISIERA NO PODRÍA AYUDARTE.")
  (1186 "DAXTER" "¿¡QUÉ!?")
  (1220 "SAMOS" "SOLO HAY UNA PERSONA QUE HA ESTUDIADO EL TEMA DEL ECO OSCURO EL TIEMPO NECESARIO")
  (1329 "SAMOS" "COMO PARA PODER DEVOLVERTE A TU ESTADO ANTERIOR:")
  (1431 "SAMOS" "GOL ACHERON, EL SABIO.")
  (1493)
  (1496 :offscreen "SAMOS" "PERO VIVE LEJOS EN EL NORTE. MUY LEJOS EN EL NORTE. HACE AÑOS QUE NADIE HA HABLADO CON ÉL.")
  (1718 "SAMOS" "OS TELETRANSPORTARÍA ALLÍ, PERO TAMPOCO PUEDO HACERLO.")
  (1831 "SAMOS" "NINGUNO DE LOS TRES SABIOS QUE GUARDAN LAS OTRAS PUERTAS")
  (1934 "SAMOS" "HA VISTO ADECUADO ACTIVAR SU LADO DESDE HACE TIEMPO.")
  )

("sage-intro-sequence-d2"
  (3 "SAMOS" "LA OTRA ÚNICA MANERA DE IR AL NORTE ES ATRAVESANDO EL DESFILADERO DEL FUEGO")
  (114 :offscreen "SAMOS" "PERO SU SUELO VOLCÁNICO ES TAN CALIENTE QUE FUNDE EL METAL.")
  (224 "SAMOS" "NO PODÉIS CAMINAR ENCIMA.")
  (270 "KEIRA" "PERO PODRÍAIS VOLAR ENCIMA, SI TUVIESEIS UN ZOOMER CON ESCUDO TÉRMICO.")
  (393)
  (396 "KEIRA" "DA LA CASUALIDAD DE QUE ESTOY TRABAJANDO EN ESO AHORA MISMO.")
  (512)
  (515 "KEIRA" "SOLO NECESITO VEINTE BATERÍAS QUE LE DEN LA ENERGÍA")
  (605 "KEIRA" "PARA RESISTIR EL CALOR DEL DESFILADERO. ¿VERDAD, PAPÁ?")
  (696)
  (699 "SAMOS" "SÍ, KEIRA, PODRÍA FUNCIONAR. ¿PERO DE DÓNDE VAN A SACAR UN CHICO")
  (826 :offscreen "SAMOS" "Y UN BICHO")
  (857 "SAMOS" "VEINTE BATERÍAS?")
  (910 "KEIRA" "DE LOS ALDEANOS. LA MAYORÍA TIENE UNA BATERÍA O DOS GUARDADAS EN ALGUNA PARTE.")
  (1050 :offscreen "KEIRA" "Y SI NO QUIEREN DÁROSLAS POR LAS BUENAS")
  (1133 "KEIRA" "SOBORNADLES CON UNAS CUANTAS ESFERAS DE PRECURSOR. Y YA VERÉIS CÓMO OS LAS DAN.")
  (1243)
  (1246 :offscreen "KEIRA" "Y ESTOY SEGURA DE QUE HABRÁ MÁS POR ESAS TIERRAS SALVAJES")
  (1364 "KEIRA" "ESPERANDO A QUE LAS ENCUENTRE UN BRAVO AVENTURERO.")
  (1435 "DAXTER" "POR LO MENOS TENEMOS AL BRAVO AVENTURERO.")
  (1529)
  (1532 "SAMOS" "¿BRAVO AVENTURERO?")
  (1582 "SAMOS" "¡VOSOTROS DOS NO PODRÍAIS ENCONTRAR LA SALIDA DE LA ALDEA SIN ENTRENAMIENTO!")
  (1685)
  (1689 "SAMOS" "ANTES DE NADA, ATRAVESAD LA PUERTA TRANSPORTADORA")
  (1810 "SAMOS" "Y PRACTICAD UN POCO EN LA ROCA DE GEYSER.")
  (1872)
  (1878 "DAXTER" "AAAMMMM, ¿NO IREMOS A ENCONTRAR MÁS ECO OSCURO DE ESE, VERDAD?")
  (1993 "DAXTER" "PORQUE NO ME GUSTARÍA CAERME DE NUEVO DENTRO Y ¡CONVERTIRME EN TÍ!")
  (2069)
  (2072 "SAMOS" "¡METEOS AHÍ ANTES DE QUE OS CONVIERTA EN ALFALFA!")
  (2189)
  )

("sage-intro-sequence-e"
  (200 "SAMOS" "BUEN ENTRENAMIENTO, CHICOS, PERO ESO NO ES NADA COMPARADO CON LOS DESAFÍOS QUE OS AGUARDAN.")
  (359 "DAXTER" "BUEEENO, NO HAY PROBLEEEMA. SABEMOS MOVERNOS, ¿EH, JAK?")
  (496 "DAXTER" "NOS ENCANTARÍA QUEDARNOS A CHARLAR, PERO, ARDEMOS EN DESEOS DE EMPRENDER AVENTURAS.")
  (660 "SAMOS" "BIEN, BIEN. PUES A LA \"AVENTURA\" ENTONCES..")
  (787 "SAMOS" "Y DURANTE ESAS \"AVENTURAS,\" PODRÍAIS HACER ALGO ÚTIL.")
  (940)
  (952 :offscreen "SAMOS" "MIS MALDITOS RECOLECTORES DE ECO VERDE ESTÁN ATASCADOS DE NUEVO.")
  (1043)
  (1105 :offscreen "SAMOS" "ID AL EXTREMO DE LA PLAYA Y DESBLOQUEADLOS, ¿DE ACUERDO?")
  (1160)
  (1169 :offscreen "SAMOS" "SEGUID LAS LUCES. OS LLEVARÁN ALLÍ.")
  (1310)
  (1330 :offscreen "SAMOS" "AHORA, LOS DOS...")
  (1415)
  (1439 :offscreen "SAMOS" "FUEEEEERA DE AQUÍ!")
  )

("sidekick-human-intro-sequence-b"
  (547 "ANCIANO" "SEGUID BUSCANDO ARTEFACTOS Y ECO.")
  (674 "ANCIANO" "SI LA GENTE DEL LUGAR TIENE OBJETOS DE PRECURSOR, YA SABÉIS QUÉ HACER.")
  (842 "MUJER" "OCUPAOS BIEN DE AQUELLOS QUE SE DESPISTEN FUERA DE LA ALDEA.")
  (937 "MUJER" "ATACAREMOS EN SU MOMENTO.")
  (1027)
  )

("sidekick-human-intro-sequence-c"
  (12 "DAXTER" "PERO ¿QUÉ HACEMOS AQUÍ, JAK? ¡ESTE SITIO ME ASUSTA!")
  (151)
  (369 "DAXTER" "EEH?")
  (404 "DAXTER" "OH...¡MALDITA PORQUERÍA PRECURSOR!")
  (496)
  (577 "DAXTER" "¡AAY! ¿QUÉ ES ESO OSCURO QUE REZUMA? NO PARECE MUY AMISTOSO.")
  (721)
  (777 "DAXTER" "EL SABIO SE PASA EL DÍA REFUNFUÑANDO SOBRE LOS PRECURSOR QUE CONSTRUYERON ESTE SITIO.")
  (909 "DAXTER" "\"¿A DÓNDE SE FUERON? ¿POR QUÉ CONSTRUYERON ESTA PORQUERÍA?\"")
  (1014 "DAXTER" "ME GUSTAN LAS ESFERAS DE PRECURSOR Y LAS BATERÍAS TANTO COMO A CUALQUIERA")
  (1124 "DAXTER" "PERO, SI TE DIGO LA VERDAD, DEBIERON DE SER UNOS PRINGAOS.")
  (1212 "DAXTER" "¡VAAYA! ¿CÓMO HAS HECHO ESO?")
  (1271)
  (1331 "DAXTER" "JAK, CREO QUE TENEMOS PROBLEMAS.")
  (1386)
  (1622 "DAXTER" "¡SOCORROOOO!")
  (1660)
  (1857 "DAXTER" "¡CHICO, ESO HA DOLIDO!.")
  (1913)
  (1941 "DAXTER" "TE DIJE QUE NO TENÍAMOS QUE HABER VENIDO, ¿HABÍAS OÍDO...")
  (2028)
  (2057 "DAXTER" "¿¿QUÉ??")
  (2101)
  (2189 "DAXTER" "AAAAAAAAHHHHHHHH!!")
  (2307 "DAXTER" "¡VAALE!, VALE. ESTOY BIEN, ¿ESTOY BIEN?")
  (2431)
  (2481 "DAXTER" "AAAAAAAAAAAAAAAAAAAHHHHHHHH!!")
  )

;; -----------------
;; sidekick
;; -----------------

("sksp0001" :hint #x280
  (0 "DAXTER" "¡EH! ESE BOMBÓN DE KEIRA TENÍA RAZÓN. ¡AQUÍ HAY TRANS-PADS!")
  )

("sksp0002" :hint #x281
  (0 "DAXTER" "¡CRÉEME, ESAS CAJAS DE ECO OSCURO TIENEN MUUUUUUY MALA PINTA!")
  )

("sksp0003" :hint #x282
  (0 "DAXTER" "SEGURO QUE SI ENCONTRAMOS A TODAS ESAS CONDENADAS MOSCAS EXPLORADORAS DE CADA NIVEL")
  (215 "DAXTER" "AL MENOS UNO TENDRÁ UNA BATERÍA!")
  )

("sksp0004" :hint #x283
  (0 "DAXTER" "¡SÍ SEÑOR, UN TESORO!")
  )

("sksp0005" :hint #x284
  (0 "DAXTER" "¡SEGURO QUE CAJAS DE MADERA Y METAL NO SON TAN RESISTENTES!")
  (166 "DAXTER" "VERÁS COMO SE ROMPEN SI SALTAS EN PICADO ENCIMA.")
  )

("sksp0006" :hint #x285
  (0 "DAXTER" "ESAS CAJAS DE METAL SON MÁS GRUESAS QUE EL CRANEO DE UNA YAKOW.")
  (188 "DAXTER" "PERO DEBE DE HABER UNA FORMA DE ABRIRLAS.")
  )

("sksp0007" :hint #x286
  (0 "DAXTER" "DOS PALABRAS: LAS BATERÍAS. HAY QUE ENCONTRARLAS. Y PARA ESO HAY QUE BUSCARLAS BIEN DE UNA VEZ.")
  )

("sksp0008" :hint #x287
  (0 "DAXTER" "NECESITAMOS ESFERAS, ¡EEEESFERAS, JAK! ¡¿CÓMO VAMOS A COMPRAR BATERÍAS SI NO REUNIMOS ESFERAS?!")
  )

("sksp0009" :hint #x251
  (0 "DAXTER" "¡QUÉ ASPECTO MÁS EXTRAÑO TIENE! SEGURO QUE LO PODEMOS ABRIR")
  (206 "DAXTER" "SI LE APLICAS UN POCO...DEL ECO AZUL ESE.")
  )

("sksp0014" :hint #x233
  (0 "DAXTER" "HEMOS REUNIDO LAS ESFERAS SUFICIENTES PARA UNA BATERÍA.")
  (215 "DAXTER" "¡VAYAMOS A HACER EL TRUEQUE!")
  )

("sksp0035" :hint #x25c
  (0 "DAXTER" "VALE, TENEMOS UN LANZADOR DE PRECURSOR AQUÍ.")
  (117 "DAXTER" "PERO COMO NO LE HAS APLICADO ENERGÍA AZUL, ¡NO NOS SERVIRÁ DE NADA!")
  )

("sksp0071" :hint #x2a5
  (0 "DAXTER" "¡CONSIGUE EL ECO ROJO!")
  )

("sksp0072" :hint #x2a6
  (0 "DAXTER" "EL ECO ROJO FORTALECE TUS ATAQUES.")
  )

("sksp0073" :hint #x2a7
  (0 "DAXTER" "NECESITAMOS ECO AZUL PARA RECARGAR ESTO.")
  )

("sksp009a" :hint #x0
  (0 "DAXTER" "¡JAJAJAJA! ¡LE HEMOS DADO UNA BUENA LECCIÓN!")
  )

("sksp009b" :hint #x28e
  (0 "DAXTER" "¡MUY BIEN, MÁS ESFERAS!")
  )

("sksp009c" :hint #x28f
  (0 "DAXTER" "¡HAZME UN FAVOR Y ALÉJATE DE ESAS CAJAS DE ECO OSCURO!")
  )

("sksp009d" :hint #x290
  (0 "DAXTER" "YUUUUUUJUJUJUJUJUUYY!")
  )

("sksp009e" :hint #x291
  (0 "DAXTER" "WUUUUUUUUU!")
  )

("sksp009f" :hint #x292
  (0 "DAXTER" "¡TOMA!, ¡TOMA! JAJAJAJA!")
  )

("sksp009g" :hint #x293
  (0 "DAXTER" "¡DETRÁS DE TÍ, JAK!")
  )

("sksp009i" :hint #x294
  (0 "DAXTER" "¿HEMOS ENCONTRADO TODAS LAS MOSCAS EXPLORADORAS DE ESTA ZONA?")
  )

("sksp009j" :hint #x295
  (0 "DAXTER" "¡EH! PARECE SER QUE LAS MOSCAS EXPLORADORAS SIEMPRE ESTÁN EN CAJAS ROJAS.")
  )

("sksp009k" :hint #x296
  (0 "DAXTER" "¡MUY BIEN! ¡HAS ENCONTRADO TODAS LAS MOSCAS EXPLORADORAS DE ESTA ZONA!")
  )

("sksp0145" :hint #x359
  (0 "DAXTER" "¡GUAAU! ¡CUANDO TIENES ECO AMARILLO PUEDES DISPARAR BOLAS DE FUEGO!")
  )

;; -----------------
;; village1
;; -----------------

("ASSTLP01" :hint #x0
  (0 "KEIRA" "HMM...")
  )

("ASSTLP02" :hint #x0
  (0 "KEIRA" "TENGO QUE ARREGLAR ESTE ESCUDO TÉRMICO...")
  )

("ASSTLP03" :hint #x0
  (0 "KEIRA" "NECESITAMOS BATERÍAS PARA ALIMENTAR EL ESCUDO TÉRMICO...")
  )

("ASSTLP04" :hint #x0
  (0 "KEIRA" "¿DÓNDE ESTÁ MI LLAVE?")
  )

("ASSTLP05" :hint #x0
  (0 "KEIRA" "EL DESFILADERO DEL FUEGO ESTÁ TAN CALIENTE...")
  )

("EXP-AM01" :hint #x0
  (0 "EXPLORADOR" "TENGO QUE IRME DE VIAJE PRONTO. NECESITO ESFERAS DE LOS PRECURSORES.")
  )

("EXP-AM02" :hint #x0
  (0 "EXPLORADOR" "VEAMOS...¿A DÓNDE VOY PRIMERO? MMM...")
  )

("EXP-AM03" :hint #x0
  (0 "EXPLORADOR" "OH...¡CÓMO ECHO DE MENOS VIAJAR!")
  )

("EXP-AM04" :hint #x0
  (0 "EXPLORADOR" "TANTOS LUGARES POR VER Y TAN POCO TIEMPO.")
  )

("EXP-AM05" :hint #x0
  (0 "EXPLORADOR" "EN MIS TIEMPOS, UNO PODÍA RECORRER EL MUNDO SIN QUE LE ASALTASEN MONSTRUOS.")
  )

("EXP-LO02" :hint #x0
  (0 "EXPLORADOR" "NECESITO MÁS ESFERAS DE LOS PRECURSORES.")
  )

("FAR-AM01" :hint #x0
  (0 "GRANJERO" "(RONQUIDOS)")
  )

("FAR-AM02" :hint #x0
  (0 "GRANJERO" "(RONQUIDOS)(BALBUCEO)")
  )

("FAR-AM2A" :hint #x0
  (0 "GRANJERO" "(BALBUCEO)...TENGO QUE RECOGER LA COSECHA ANTES DE QUE SE LA COMAN LOS BICHOS DE JUNE...(RONQUIDOS)")
  )

("FAR-LO01" :hint #x0
  (0 "GRANJERO" "(RONQUIDOS)")
  )

("FAR-LO1A" :hint #x0
  (0 "GRANJERO" "(RONQUIDOS)")
  )

("SAGELP03" :hint #x0
  (0 "SAMOS" "ESTOS DOS NO SON CAPACES NI DE DESBLOQUEARSE LA NARIZ...")
  )

("SAGELP04" :hint #x0
  (0 "SAMOS" "NUNCA SERÁ COMO SU TÍO...")
  (221 "SAMOS" "NO ME IMPORTA LO QUE DIGAN LOS DEMÁS.")
  )

("SAGELP05" :hint #x0
  (0 "SAMOS" "HOLA, ¿SABIO AZUL? ¡HOLA! ¿DÓNDE DIANTRE ESTARÁ...?")
  )

("SAGELP06" :hint #x0
  (0 "SAMOS" "VAYA, VAYA, VAYA...")
  )

("SAGELP11" :hint #x0
  (0 "SAMOS" "¿HAY ALGUIEN? ¡QUIEN SEA! ¡RESPONDED!")
  )

("assistant-introduction-blue-eco-switch"
  (23 "DAXTER" "¡EEH, NENA! ¿QUÉ TE PARECE SI TE DOY UNA VUELTA EN ESTE ZOOMER ANTIGRAVITATORIO?")
  (175)
  (193 "KEIRA" "REGLA NÚMERO UNO: NO SALGO CON ANIMALES.")
  (308)
  (312 "DAXTER" "VAAAYA, PUES NO SABES LO QUE TE PIERDES, JIJIJIJI.")
  (430)
  (505 "KEIRA" "ESCUCHAD, SI QUIERES ESTAR OCUPADO CON ALGO, MI PADRE SIEMPRE HABLABA")
  (635 "KEIRA" "DE UNA ANTIGUA TUBERÍA DE PRECURSOR ESCONDIDA PROFUNDAMENTE BAJO TIERRA.")
  (739)
  (742 :offscreen "KEIRA" "ALGUNAS DE ESTAS TUBERÍAS ACABAN EN RESPIRADEROS POR LOS QUE SALE ECO,")
  (842 :offscreen "KEIRA" "Y ALGUNAS HAN SIDO SELLADAS PARA QUE EL ECO QUEDE ENCERRADO.")
  (945)
  (954 "KEIRA" "DEBE DE HABER UNA MANERA DE ABRIR LOS RESPIRADEROS SELLADOS.")
  (1052 :offscreen "KEIRA" "HE SEGUIDO EL RASTRO DE LA TUBERÍA HASTA EL TEMPLO PROHIBIDO.")
  (1138 "KEIRA" "TAL VEZ DEBERÍAIS BUSCAR ALLÍ ALGÚN INTERRUPTOR.")
  (1246)
  )

("assistant-introduction-race-bike"
  (9 "DAXTER" "¡EH, NENA!, ¿EN QUÉ TRABAJAS?")
  (63 "KEIRA" "¡CUIDADO CON ESO! ESTOY INTENTANDO AVERIGUAR CÓMO TRANSPORTAR EL ZOOMER")
  (200 "KEIRA" "CON LOS TRANS-PAD QUE LOS PRECURSORS HAN DEJADO POR TODO EL MUNDO.")
  (308)
  (312 :offscreen "KEIRA" "SI OS ENCONTRÁIS CON UNO DE ESOS TRANS-PAD, PODRÉ DEJAR LA UBICACIÓN DE VUESTRO COMUNICADOR")
  (453 :offscreen "KEIRA" "Y ENVIAROS EL ZOOMER.")
  (508 "KEIRA" "ESTAD ATENTOS POR SI ENCONTRÁIS UN TRANS-PAD AL EXPLORAR MISTY ISLAND Y EN CUALQUIER OTRO SITIO.")
  (665)
  )

("assistant-reminder-1-blue-eco-switch"
  (23 "KEIRA" "ESTOY SEGURA DE QUE SI MIRÁIS DENTRO DEL TEMPLO PRECURSOR PROHIBIDO")
  (143 "KEIRA" "ENCONTRARÉIS LA MANERA DE ACTIVAR EL RESPIRADERO DE ECO AZUL DE LA PLAYA DEL CENTINELA.")
  (295)
  )

("assistant-reminder-1-generic"
  (25 "KEIRA" "¡EH, CHICOS! SEGUID REUNIENDO BATERÍAS. SON FUNDAMENTALES PARA SEGUIR NUESTRA TRAVESÍA HACIA EL NORTE.")
  )

("assistant-reminder-1-race-bike"
  (19 "KEIRA" "HE AVERIGUADO CÓMO USAR LOS TRANS-PAD.")
  (106 "KEIRA" "AHORA ID A MISTY ISLAND Y ENVIARÉ ALLÍ EL ZOOMER.")
  (229)
  )

("asstvb04" :hint #x2b1
  (0 "KEIRA" "BIEN, ¡HABÉIS REUNIDO LAS SUFICIENTES BATERÍAS PARA ACTIVAR MI ESCUDO TÉRMICO!")
  (233 "KEIRA" "ESCALAD EL ACANTILADO TRAS LA CASA DEL GRANJERO PARA REUNIROS CONMIGO EN LA ENTRADA DEL DESFILADERO DEL FUEGO.")
  (559 "KEIRA" "TRAED LAS BATERÍAS, ¡Y DAOS PRISA! ¡MI PADRE DICE QUE HA VISTO A MÁS LURKERS RONDANDO!")
  )

("asstvb08" :hint #x2b2
  (0 "KEIRA" "DAOS PRISA CON LAS BATERÍAS. OS ESPERO AL PRINCIPIO DEL DESFILADERO DEL FUEGO")
  (260 "KEIRA" "SUBIENDO EL ACANTILADO QUE HAY TRAS LA CASA DEL GRANJERO.")
  )

("explorer-introduction"
  (23 "EXPLORADOR" "VAYA, ¡HOLA, CHAVAL! ME HAS PILLADO EN EL MOMENTO MÁS INOPORTUNO.")
  (197 "EXPLORADOR" "IBA A MARCHARME DE VIAJE AYER,")
  (288 "EXPLORADOR" "PERO ME HE QUEDADO ALGO ESCASO DE ESFERAS DE LOS PRECURSORES.")
  (426)
  (430 "EXPLORADOR" "JURARÍA QUE TENÍA 90 ESFERAS,")
  (538 "EXPLORADOR" "PERO ME DA QUE TU AMIGUETE...YA SABES, LA SABANDIJA ESA...")
  (716 "EXPLORADOR" "ME LAS DEBE DE HABER QUITADO SOLO PARA DIVERTIRSE.")
  (829)
  (865 "EXPLORADOR" "EN CUALQUIER CASO, ¿SERÍAS TAN AMABLE DE PRESTARLE A TU QUERIDO TÍO 90 ESFERAS DE LOS PRECURSORES")
  (1043 "EXPLORADOR" "PARA QUE PUEDA PONERSE EN CAMINO? A CAMBIO, TE DARÍA UNA BATERÍA.")
  )

("explorer-reminder-1"
  (25 "EXPLORADOR" "¿QUÉ? ¿NO LAS TIENES TODAS?")
  (148 "EXPLORADOR" "PUES CON MENOS DE 90 ESFERAS DE LOS PRECURSORES,")
  (251 "EXPLORADOR" "NO PODRÉ IR A NINGÚN LADO, CHAVALÍN.")
  (387)
  )

("explorer-reminder-2"
  (33 "EXPLORADOR" "¡BUENO, VEAMOS! EL TRATO SON 90 ESFERAS DE LOS PRECURSORES POR UNA BATERÍA.")
  (187 "EXPLORADOR" "ME PARECE BASTANTE JUSTO.")
  )

("explorer-resolution"
  (28 "EXPLORADOR" "VEO QUE LOS DOS HABÉIS VUELTO PARA HACER NEGOCIOS. ¡MUY BIEN!, ¡MUY BIEN!")
  (179 "EXPLORADOR" "EH...¿TENÉIS LA CANTIDAD DE ESFERAS DE LOS PRECURSORES ACORDADA?")
  (310)
  (324 "EXPLORADOR" "ME HA COSTADO MUCHO CONSEGUIR ESTA BATERÍA. ¡USADLA BIEN! ¡HASTA LUEGO, CHAO, BYE BYE!")
  )

("farmer-introduction"
  (1 "GRANJERO" "TENGO QUE ORDEÑAR A LAS YAKOUS, TENGO QUE ORDENAR A LAS YAKOUS...")
  (113 "GRANJERO" "¡EH, ERES TÚ! AH...ESTABA DESCANSANDO UN POQUITO. LLEVO TODO EL DÍA INTENTANDO ENCERRAR A ESAS IRASCIBLES YAKOUS.")
  (370 "GRANJERO" "UNAS EXTRAÑAS CRIATURAS INTENTARON ROBARLAS ANTES.")
  (470 "GRANJERO" "¿CREÉIS QUE PODRÉIS AYUDAR A ESTE VIEJO A METERLAS EN EL CORRAL?")
  )

("farmer-reminder-1"
  (0 "GRANJERO" "¡EH, EHH! ¡MIS YAKOUS ESTÁN TODAVÍA SUELTAS! ¿ME...LAS PODRÍAIS TRAER PRONTO?")
  )

("farmer-reminder-2"
  (0 "GRANJERO" "¡ESAS MALDITAS YAKOUS SIGUEN DEAMBULANDO LIBRES!")
  (85 "GRANJERO" "¿VAIS A METERLAS EN EL CORRAL DE UNA VEZ?")
  )

("farmer-resolution"
  (0 "GRANJERO" "¡EH!, ¡BIEN HECHO, CHAVAL! HAS CONSEGUIDO METER A ESAS PESADAS EN EL CORRAL.")
  (134 "GRANJERO" "¡YA PUEDO DORMIR TRANQUILO! TOMA ESTA BATERÍA POR MOLESTARTE.")
  (340)
  )

("sage-introduction-misty-cannon"
  (24 "SAMOS" "OH, SON LOS CONQUISTADORES.")
  (136 "SAMOS" "BIEN, QUERÍA HABLAR CON VOSOTROS DOS DE COSAS SERIAS.")
  (258)
  (261 :offscreen "SAMOS" "PARECE SER QUE HAY CIERTA ACTIVIDAD LURKER EN MISTY ISLAND.")
  (387)
  (393 :offscreen "SAMOS" "PUEDO VER CÓMO BOMBARDEAN EL SILO PRECURSOR DESDE MI OBSERVATORIO.")
  (525)
  (528 "SAMOS" "SI LOS LURKERS LO ABREN Y LIBERAN EL ECO OSCURO, PODRÍAMOS ACABAR TODOS")
  (663 "SAMOS" "CON EL ASPECTO RIDÍCULO DE ESTE MOLESTO ESPÉCIMEN.")
  (788)
  (807 "SAMOS" "JAK, ES EL MOMENTO DE QUE DEMUESTRES LO QUE VALES.")
  (906 "SAMOS" "CONSIGUE QUE EL PESCADOR TE DEJE SU BARCO PARA IR A MISTY ISLAND")
  (1018 "SAMOS" "SUBE A LA CIMA DEL SILO DE PRECURSOR Y ACABA CON ESE CAÑÓN.")
  (1171)
  (1177 "DAXTER" "Y...¿QUÉ HAY DE MÍ?")
  (1232)
  (1235 "SAMOS" "¿TÚ? ¿POR QUÉ NO FRIEGAS EL SUELO? PARECE HABER PERDIDO BRILLO ÚLTIMAMENTE.")
  )

("sage-reminder-1-ecorocks"
  (28 "SAMOS" "MENUDOS \"AVENTUREROS VALIENTES\" QUE SOIS.")
  (132 "SAMOS" "YA HABÉIS VUELTO Y NO HABÉIS DESBLOQUEADO MIS COSECHADORES DE ECO.")
  (244)
  (252 :offscreen "SAMOS" "ESTÁN EN EL EXTREMO DE LA PLAYA, CHICOS.")
  (365)
  (366 :offscreen "SAMOS" "AHORA...")
  (412 :offscreen "SAMOS" "¡EN MARCHA!")
  )

("sage-reminder-1-generic"
  (54 "SAMOS" "¿QUÉ HACÉIS LOS DOS AQUÍ? ¡TENÉIS QUE IR A CONSEGUIR BATERÍAS!")
  (178)
  (181 "SAMOS" "HASTA QUE LAS CONSIGÁIS...¡DEJAZME EN PAZ!")
  )

("sage-reminder-1-misty-cannon"
  (28 "SAMOS" "MENUDOS \"AVENTUREROS VALIENTES\" QUE SOIS.")
  (132 "SAMOS" "YA HABÉIS VUELTO Y NO HABÉIS DESBLOQUEADO MIS COSECHADORES DE ECO.")
  (244)
  (252 :offscreen "SAMOS" "ESTÁN EN EL EXTREMO DE LA PLAYA, CHICOS.")
  (365)
  (366 :offscreen "SAMOS" "AHORA...")
  (412 :offscreen "SAMOS" "¡EN MARCHA!")
  )

("sage-reminder-2-generic"
  (27 "SAMOS" "NO ACABÁIS DE ENTENDER LA GRAVEDAD DE LA SITUACIÓN.")
  (137 "SAMOS" "LA COSA NO SE QUEDA EN LA TRANSFORMACIÓN DE UN CHAVAL EN BICHO PELUDO. ESTO CONCIERNE A LA VIDA TAL Y COMO LA CONOCEMOS.")
  (320)
  (323 "SAMOS" "AHORA MARCHÁOS Y COMPLETAD VUESTRA TAREA.")
  (455)
  )

("sksp0010" :hint #x231
  (0 "DAXTER" "¡EH! VAMOS A ECHAR UN VISTAZO A LA SUPER LANCHA DEL LOBO DE MAR EN EL PUERTO.")
  )

("sksp0013" :hint #x232
  (0 "DAXTER" "¿HAS VISTO EL PEDAZO DE BOCADO QUE LE PEGÓ UN TIBURÓN LURKER AL BARCO DEL PESCADOR?")
  (315)
  (337 "DAXTER" "¡MÁS NOS VALE ESTAR BIEN LEJITOS DE ELLOS! NO CREO QUE NOS PODAMOS ENFRENTAR A ALGO TAN TREMENDO.")
  )

("sksp0015" :hint #x234
  (0 "DAXTER" "ESTO DEBE DE SER EL ORÁCULO DE PRECURSOR DEL QUE SIEMPRE HABLA EL SABIO.")
  (228 "DAXTER" "¡ESPERABA QUE NO FUESE TAN FEO EN PERSONA!")
  )

("sksp0017" :hint #x235
  (0 "DAXTER" "¡GUAU! ¡ECHA UN VISTAZO A LA ESCULTURA TAN HORTERA QUE HAY EN AQUELLAS ROCAS!")
  )

("sksp0043" :hint #x24e
  (0 "DAXTER" "TAL VEZ DEBERÍAMOS IR A VER AL PESCADOR.")
  (106 "DAXTER" "HE OÍDO QUE SUELE PESCAR EN EL RÍO DE LA SELVA.")
  )

("sksp018a" :hint #x297
  (0 "DAXTER" "¡EL GANDUL DEL GRANJERO NOS DEBE UNA BATERÍA!")
  (156 "DAXTER" "¡HABLEMOS CON ÉL!")
  )

;; -----------------
;; oracle
;; -----------------

("oracle-intro-1"
  (0 "ORÁCULO" "¿QUIÉN DESPIERTA AL ORÁCULO?")
  (75)
  (81 "ORÁCULO" "¡ESPERA!, UNO DE LOS DOS LLEVA LA LUZ DENTRO.")
  (198)
  (206 "ORÁCULO" "HE ESTADO AGUARDANDO EL RETORNO DEL HÉROE VERDADERO DESDE HACE MILENIOS.")
  (390)
  (395 "ORÁCULO" "TREAEDME 120 ESFERAS DE PRECURSOR, POR CADA BATERÍA QUE ALBERGO.")
  )

("oracle-left-eye-1"
  (0 "ORÁCULO" "HABÉIS DEMOSTRADO SER HONESTOS. HE AQUÍ UNA BATERÍA.")
  )

("oracle-right-eye-1"
  (0 "ORÁCULO" "TOMAD UNA BATERÍA A CAMBIO DE VUESTRO REGALO.")
  )

("oracle-reminder-1"
  (0 "ORÁCULO" "TRAEDME 120 ESFERAS DE PRECURSOR, Y OS DARÉ UNA BATERÍA.")
  )

("oracle-left-eye-2"
  (0 "ORÁCULO" "POR VUESTRO SACRIFICIO, UNA BATERÍA OS DOY.")
  )

("oracle-right-eye-2"
  (0 "ORÁCULO" "HE AQUÍ OTRA BATERÍA POR VUESTROS ESFUERZOS.")
  )

("oracle-left-eye-3"
  (0 "ORÁCULO" "A CAMBIO DE VUESTRO DENUEDO, HE AQUÍ UNA BATERÍA.")
  )

("oracle-right-eye-3"
  (0 "ORÁCULO" "HABÉIS CONSEGUIDO OTRA BATERÍA.")
  )

;; -----------------
;; beach
;; -----------------

("BIR-AM01" :hint #x0
  (0 "MUJER PÁJARO" "¿ESTÁIS YA CERCA DEL HUEVO?")
  )

("BIR-AM02" :hint #x0
  (0 "MUJER PÁJARO" "¡ESO ES, UN POCO MÁS!")
  )

("BIR-AM03" :hint #x0
  (0 "MUJER PÁJARO" "ESTUPENDO. AHORA EMPUJADLO SUAVEMENTE")
  )

("BIR-AM04" :hint #x0
  (0 "MUJER PÁJARO" "¡DIOS MÍO! ¡HE DICHO SUAVEMENTE!")
  )

("BIR-AM05" :hint #x0
  (0 "MUJER PÁJARO" "¡VAMOS, EMPUJAD EL HUEVO POR EL BARRANCO!")
  )

("BIR-AM06" :hint #x0
  (0 "MUJER PÁJARO" "OOOOHH!")
  )

("BIR-AM07" :hint #x0
  (0 "MUJER PÁJARO" "¡AQUÍ, PAJARITO! ¡AQUÍ, PAJARITO! ¡PÍO, PÍO!")
  )

("BIR-AM08" :hint #x0
  (0 "MUJER PÁJARO" "AQUÍ, PAJARITO.")
  )

("BIR-AM09" :hint #x0
  (0 "MUJER PÁJARO" "¡CUIDADO! ¡AHÍ ARRIBA PARECE PELIGROSO!")
  )

("BIR-AM10" :hint #x0
  (0 "MUJER PÁJARO" "¡CUIDADO! ¡POCO A POCO!" )
  )

("BIR-AM11" :hint #x0
  (0 "MUJER PÁJARO" "¡BUEN TRABAJO! AHORA VENID AQUÍ, AL LADO DEL HUEVO.")
  )

("BIR-AM12" :hint #x0
  (0 "MUJER PÁJARO" "DEBES DE SER TODO UN AMANTE DE LOS ANIMALES.")
  )

("BIR-AM13" :hint #x0
  (0 "MUJER PÁJARO" "¿HAY MÁS PÁJAROS POR AHÍ ARRIBA?")
  )

("BIR-LO01" :hint #x0
  (0 "MUJER PÁJARO" "(SILBIDO)")
  )

("BIR-LO02" :hint #x0
  (0 "MUJER PÁJARO" "¡OH, MIRA!, ESE ES PRECIOSO.")
  )

("BIR-LO03" :hint #x0
  (0 "MUJER PÁJARO" "¡OH, MIRA! UN MUCKY-MUCK.")
  )

("CHI-AM01" :hint #x0
  (0 "MAYOR" "OH...¡ESTO ES UNA CATÁSTROFE! ¡UN ABSOLUTO DESASTRE!")
  )

("CHI-AM02" :hint #x0
  (0 "MAYOR" "QUIEREN QUE VAYA A LA SELVA...¡¡YO!!")
  (214)
  (219 "MAYOR" "¡ANTES DESPLUMARÍA A UN FLUT FLUT RABIOSO!")
  )

("CHI-AM03" :hint #x0
  (0 "ALCALDE" "¡...PRIMERO UN MONSTRUO ATACA EL BARCO DEL PESCADOR!")
  (352)
  (395 "ALCALDE" "...Y...Y...Y...AHORA....¡AHORA ESTO! ¡¿QUÉ MÁS PUEDE IR MAL?!")
  )

("CHI-AM04" :hint #x0
  (0 "ALCALDE" "OHHH...TAL VEZ...DEBA...EHHH...TAL VEZ DEBERÍA SUBIR LOS IMPUESTOS...PARA EHHH...¡COSTEAR ESTE DESASTRE!")
  )

("CHI-AM05" :hint #x0
  (0 "ALCALDE" "PROBLEMAS, ¡TODO SON...PROBLEMAS! ¡OOHHH...PROBLEMAS!")
  )

("CHI-AM06" :hint #x0
  (0 "ALCALDE" "(LLANTO) ¡AHORA VA A SER IMPOSIBLE QUE ME REELIJAN!")
  )

("CHI-AM07" :hint #x0
  (0 "ALCALDE" "(LLANTO) ¿QUÉ HA PASADO CON EL RAYO ENERGÉTICO DE LA ALDEA?")
  )

("CHI-AM08" :hint #x0
  (0 "ALCALDE" "(LLANTO) OHH...¿¿POR QUÉ?? OOOAAHHH ¿¿¿POR QUÉ???(LLANTO)")
  )

("CHI-LO01" :hint #x0
  (0 "ALCALDE" "(LLANTO)...MOLINO, MONSTRUOS, ELECTRICIDAD, REELECCIÓN...")
  )

("CHI-LO02" :hint #x0
  (0 "ALCALDE" "(LLANTO)...CUESTAS, MONSTRUOS, REELECCIÓN...")
  )

("SCU-AM01" :hint #x0
  (0 "ESCULTOR" "OH...YA NO ME SALE NADA.")
  )

("SCU-AM02" :hint #x0
  (0 "ESCULTOR" "OH...OJALÁ ESTUVIESE INSPIRADO.")
  )

("SCU-AM03" :hint #x0
  (0 "ESCULTOR" "ESTOY TAN INSPIRADO COMO...ESTA PIEDRA.")
  )

("SCU-AM04" :hint #x0
  (0 "ESCULTOR" "OH...¿DÓNDE ESTARÁ MI MUSA?")
  )

("SCU-AM05" :hint #x0
  (0 "ESCULTOR" "¡ASÍ NO PUEDO TRABAJAR!")
  )

("SCU-AM06" :hint #x0
  (0 "ESCULTOR" "OH DIOS MÍO...¿CUÁNDO VOLVERÁ CONMIGO?")
  )

("SCU-LO01" :hint #x0
  (0 "ESCULTOR" "OH...NO...")
  )

("bird-lady-beach-resolution"
  (30 "MUJER PÁJARO" "¡OH, CIELOS! ESPERO QUE EL POBRECITO ESTÉ BIEN. TOMAD UNA BATERÍA POR VUESTRO VALOR.")
  (243)
  (306 "FLUT FLUT" "¡MAMA!")
  (354)
  (406 "FLUT FLUT" "¡MAMA!")
  (430 "DAXTER" "¡OH, NO! ¡¡NO, NO, NO, NO, NOOO!!")
  (533)
  (535 "MUJER PÁJARO" "MIRAD, ¿A QUE ES MONO? CREO QUE PIENSA QUE ERES SU MAMÁ.")
  (696)
  (699 "DAXTER" "¿¿MAMÁ?? ¡NO SOY TU MADRE! ¿VES PLUMAS POR ALGÚN LADO? ¿MMM?")
  (803)
  (807 "MUJER PÁJARO" "OH, ¡AMOR A PRIMERA VISTA! BUENO...")
  (936)
  (939 "MUJER PÁJARO" "ESCUCHAD, CHICOS, ME LLEVARÉ AL PUEBLO AL POLLUELO")
  (1054 "MUJER PÁJARO" "Y TRATARÉ DE QUE EL SABIO SE OCUPE DE ÉL.")
  )

("bird-lady-introduction"
  (125 "MUJER PÁJARO" "¡CIELO SANTO! ¡QUÉ PAJARITO MÁS ENFERMO!")
  (245)
  (251 "DAXTER" "USTED TAMPOCO TIENE MUY BUENA PINTA, SEÑORA.")
  (326)
  (331 "MUJER PÁJARO" "OH, LO SIENTO. PENSÉ QUE ERAS UN RAIN FRAY DE VIENTRE NARANJA.")
  (454)
  (457 "MUJER PÁJARO" "¿SABES? AYER VI COMO UNAS MALVADAS CRIATURAS")
  (578 "MUJER PÁJARO" "CAPTURABAN A UNA MADRE FLUT FLUT CERCA DE LA PLAYA.")
  (648)
  (654 :offscreen "MUJER PÁJARO" "Y EN SU NIDO, EN LO ALTO DEL BARRANCO, SE HA QUEDADO UN POBRE HUEVO HUÉRFANO")
  (796 :offscreen "MUJER PÁJARO" " AL QUE NO PUEDO LLEGAR. ¿PODRÍAIS SUBIR Y EMPUJARLO PARA QUE CAIGA")
  (951 :offscreen "MUJER PÁJARO" "EN EL MONTÓN DE HENO QUE HE PUESTO DEBAJO?")
  (1041)
  (1044 "MUJER PÁJARO" "SI ME HACÉIS ESTE FAVOR, OS RECOMPENSARÉ CON UNA BATERÍA.")
  (1198)
  )

("bird-lady-reminder-1"
  (56 "MUJER PÁJARO" "OH, ¡HOLA DE NUEVO! ¿HABÉIS ENCONTRADO EL HUEVO AZUL QUE HAY EN EL BARRANCO?")
  (208)
  (211 "MUJER PÁJARO" "¡EMPUJADLO POR EL BORDE Y OS DARÉ UNA BATERÍA!")
  (348)
  )

("bird-lady-reminder-2"
  (58 "MUJER PÁJARO" "¿TODAVÍA REVOLOTEANDO POR AQUÍ? JAJAJAJA")
  (170)
  (174 "MUJER PÁJARO" "¡SEGURO QUE ESE POBRE HUEVO DEL BARRANCO ESTÁ PASANDO UN FRÍO TERRIBLE!")
  (313)
  (316 "MUJER PÁJARO" "¡ID A SALVARLO! EMPUJÁNDOLO POR EL BORDE...Y OS DARÉ UNA BATERÍA.")
  )

("mayor-introduction"
  (31 "ALCALDE" "¡¡NO!! (MURMURA) ¡NO ME DIGAS QUE VOSOTROS DOS TAMBIÉN TENÉIS PROBLEMAS!")
  (171)
  (174 "ALCALDE" "PRIMERO LAS APARICIONES DE MONSTRUOS CERCA DE LA ALDEA, ¡Y AHORA ESTO!")
  (313)
  (320 "ALCALDE" "¿VEIS ESOS ENGRANAJES AHÍ ARRIBA, CHICOS? ¿LOS VEIS? ¿VEIS LO PARADOS QUE ESTÁN?")
  (479 "ALCALDE" "¡ESO SIGNIFICA QUE NUESTRA ALDEA NO TIENE ELECTRICIDAD!")
  (569)
  (578 "ALCALDE" "¡EL RAYO ECO QUE PROVIENE DEL TEMPLO DE LA SELVA SE HA INTERRUMPIDO!")
  (685)
  (689 "ALCALDE" "Y LA VERDAD, A TODO EL MUNDO LE DA MIEDO. ID A VER QUÉ ES LO QUE HA PASADO.")
  (850)
  (864 "DAXTER" "¿HAS PAGADO LA FACTURA?")
  (915)
  (917 "ALCALDE" "¡AJÁ! JOOOJOOJAJAAAA, QUÉ GRACIOSO...")
  (1071)
  (1074 "ALCALDE" "MIRAD, SI ARREGLÁIS EL RAYO ECO, OS DARÉ...UNA BATERÍA.")
  (1262 "ALCALDE" "¡AH, AHH, AHH, OTRA COSA!")
  (1346 "ALCALDE" "SI POR CASUALIDAD OS INTERESA HACER UNA CONTRIBUCIÓN A MI CAMPAÑA DE REELECCIÓN,")
  (1551 "ALCALDE" "TAL VEZ CONSIDERE EL DAROS OTRA BATERÍA.")
  (1668)
  (1671 "ALCALDE" "LA CONTRIBUCIÓN MÍNIMA ES DE UNAS...MODESTAS...")
  (1797 "ALCALDE" "90 ESFERAS.")
  )

("mayor-reminder-beams"
  (25 "ALCALDE" "¿YA HABÉIS VUELTO? ¡¿Y SIN ARREGLAR EL RAYO ECO?!")
  (157 "ALCALDE" "(LLANTO) ¡VUESTRA ALDEA OS NECESITA, CHICOS!")
  )

("mayor-reminder-donation"
  (26 "ALCALDE"  "¿HABÉIS VENIDO A HACER UNA DONACIÓN A MI CAMPAÑA...?")
  (159 "ALCALDE" "CON 90 ESFERAS DE LOS PRECURSORES OS LLEVÁIS UNA BATERÍA, CHICOS.")
  )

("mayor-resolution-beams"
  (28 "ALCALDE" "JAAAAJAJAJAJA, ¡QUÉ VISTA TAN MARAVILLOSA! OS LO AGRADEZCO,")
  (205 "ALCALDE" "Y TODA LA ALDEA ME LO AGRADECERÁ A MÍ.")
  (269 "ALCALDE" "¡EH, CHICOS! ¡HABÉIS DEVUELTO LA ELECTRICIDAD A LA ALDEA Y GARANTIZADO MI REELECCIÓN!")
  (472)
  (475 "ALCALDE" "Y POR ELLO, AMIGOS MÍOS, OS DOY...¡UNA BATERÍA!")
  )

("mayor-resolution-donation"
  (28 "MAYOR" "ASÍ QUE...QUERÉIS REALIZAR UNA CONTRIBUCIÓN, ¡BIEN! SERÁ DE BUEN TAMAÑO, ESPERO.")
  (219)
  (224 "MAYOR" "¡GUAAAAAAU, SIII...! AAMM...ES UNA CONTRIBUCIÓN HERMOSA.")
  (365 "MAYOR" "BUENO, EMMM...ESPERO QUE ESTA BATERÍA SEA UNA BUENA MUESTRA DE MI GRATITUD.")
  )

("sagevb01" :hint #x288
  (0 "SAMOS" "BIEN, VEO QUE OS HABÉIS DECIDIDO FINALMENTE A DEBLOQUEAR MIS COSECHADORES.")
  (347)
  (352 "SAMOS" "OS FELICITARÍA, PERO TENÉIS TANTO POR HACER, QUE NOS HARÉ PERDER EL TIEMPO.")
  (705)
  (712 "SAMOS" "POR CIERTO, SI LAS COSAS NO FUNCIONAN,")
  (884 "SAMOS" "DAXTER SIEMPRE PODRÍA CONSEGUIR UN TRABAJO CONTROLANDO LA POBLACIÓN DE RATAS DE LA ALDEA.")
  (1190 "SAMOS" "JAJAJAJAJAJAJA.")
  )

("sculptor-introduction"
  (30 "ESCULTOR" "EH...¡PEQUEÑÍN PELUDO!")
  (154)
  (161 "ESCULTOR" "OHH...POR UN MOMENTO, PENSÉ QUE ERAS MI MUSA.")
  (282)
  (285 "DAXTER" "¿¿TU QUÉ??")
  (334)
  (343 "ESCULTOR" "¿NUNCA HABÍAIS VISTO A UNA MUSA?")
  (430)
  (434 "ESCULTOR" "ES UNA PEQUEÑA ARDILLA RESPLANDECIENTE DE TU TAMAÑO, LLENA DE VITALIDAD, ¡Y LOCA COMO UNA REGADERA!")
  (622)
  (632 "DAXTER" "AAAH, ¡LO PILLO! COMO UN...¡COMPAÑERO DE AVENTURAS!")
  (757)
  (763 "ESCULTOR" "EN REALIDAD...SIN MI MUSA...NO PUEDO ESCULPIR.")
  (920)
  (923 "ESCULTOR" "CON ELLA CERCA...VEO LA BELLEZA DE TODO, ¿SABÉIS?")
  (1087)
  (1091 "ESCULTOR" "AHORA MISMO NO PODRÍA HACER NI UN AGUJERO CON EL CINCEL...")
  (1182)
  (1191 :offscreen "ESCULTOR" "CREO QUE ELLA HA HUÍDO A ISLA DE MISTY.")
  (1278)
  (1281 "ESCULTOR" "OHH...ESPERO QUE ESTÉ BIEN.")
  (1370)
  (1376 "ESCULTOR" "¡OS DARÉ UNA BATERÍA SI ME LA TRAÉIS!")
  (1441)
  (1467 "DAXTER" "¡ESPERA UN SEGUNDO! NO...VAMOS A...¡¡VOLVER A LA ISLA DE NIEBLA!!")
  (1646)
  (1649 "DAXTER" "¿VERDAD...?")
  )

("sculptor-reminder-1"
  (27 "ESCULTOR" "OHH...¡EH, AMIGOS! ¿HABÉIS ENCONTRADO A MI MUSA?")
  (169)
  )

("sculptor-resolution"
  (87 "ESCULTOR" "¡¡OH, MI MUSA!! ¡¡LA HABÉIS SALVADO!! ¡OH, SOIS LOS MEJORES!")
  (230 "ESCULTOR" "BIEN, TOMAD ESTA BATERÍA. YA NO LA NECESITO, AHORA QUE ME HA VUELTO LA INSPIRACIÓN.")
  )

("sksp0019" :hint #x236
  (0 "DAXTER" "¡EH, GAVIOTAS! VAMOS A ESPANTARLAS PARA DIVERTIRNOS.")
  )

("sksp0020" :hint #x268
  (0 "DAXTER" "¡YUUJUJUUUUY! ¡VENGA, OTRA VEZ!")
  )

("sksp0022" :hint #x26a
  (0 "DAXTER" "¡YUUUUUJUUUU JAJAJAJAAA YUUJUJUJUYY!")
  )

("sksp0023" :hint #x26b
  (0 "DAXTER" "¡WUUUUU!")
  )

("sksp0024" :hint #x26c
  (0 "DAXTER" "¡YAAAAHJAAAJAJAA, ¡¡SÍ!!")
  )

("sksp0025" :hint #x273
  (0 "DAXTER" "¡GUAU! ¡HAN CAUSADO UNA AVALANCHA! ¡VAMOS A VERLA!")
  )

("sksp0026" :hint #x237
  (0 "DAXTER" "¡EH, ESE PELÍCANO NOS HA BIRLADO UNA BATERÍA!")
  (197)
  (200 "DAXTER" "VAMOS A DARLE SU MERECIDO.")
  )

("sksp0027" :hint #x274
  (0 "DAXTER" "¡DEPRISA! ¡TENEMOS QUE LLEGAR A LA BATERÍA ANTES DE QUE EL PELÍCANO SE LA LLEVE DE NUEVO!")
  )

("sksp0029" :hint #x275
  (0 "DAXTER" "EMMM, DEBERÍAMOS HABLAR CON LA ORNITÓLOGA")
  (125 "DAXTER" "Y VER SI EL HUEVO DE FLUT FLUT HA ACABADO REVUELTO.")
  )

("sksp0030" :hint #x239
  (0 "DAXTER" "¡EH, PRUEBA A GOLPEAR LAS PIEDRAS PARA VER SI LAS QUITAS DE EN MEDIO!")
  )

("sksp0034" :hint #x23b
  (0 "DAXTER" "¡AUUUUUUU, AH AH AH AAAAAAAH! ¡BUCEA Y COGE LOS HUEVOS, JAK, BUCEA!")
  )

("sksp0443" :hint #x2af
  (0 "DAXTER" "¡GOLPEA ESAS PÉRTIGAS DESDE ABAJO!")
  )

;; -----------------
;; jungle
;; -----------------

("FIS-AM01" :hint #x0
  (0 "PESCADOR" "GRRRRRR...MALDITOS PECES...¡NUNCA ATRAPARÉ A NINGUNO!")
  )

("FIS-AM02" :hint #x0
  (0 "PESCADOR" "ESOS MONSTRUOS QUE ATACARON...¡ME VAN A ARRUINAR!")
  )

("FIS-AM03" :hint #x0
  (0 "PESCADOR" "¡¡MALDITOS SINVERGÜENZAS!!")
  (135 "PESCADOR" "VENGA, PECES DEL DEMONIO, A MI CESTA...")
  (419)
  (425 "PESCADOR" "JE JE JE JE JE...")
  )

("FIS-AM04" :hint #x0
  (0 "PESCADOR" "AAAH...ME ENCANTA EL OLOR DEL PESCADO POR LA MAÑANA.")
  )

("FIS-AM05" :hint #x0
  (0 "PESCADOR" "MMMMM...ME APETECEN UNOS RICOS PESCADITOS FRITOS...")
  )

("FIS-AM06" :hint #x0
  (0 "PESCADOR" "AAAAH...ME ACUERDO DEL GRANDOTE QUE SE ME ESCAPÓ...")
  )

("FIS-LO01" :hint #x0
  (0 "PESCADOR" "¡GRRRRRR!")
  )

("FIS-LO03" :hint #x0
  (0 "PESCADOR" "¡¡JAJAJAJAJAJAJAJAJAJAJA!!")
  )

("FIS-LO04" :hint #x0
  (0 "PESCADOR" "MALDITOS PECES...¡NUNCA SE DEJAN ATRAPAR!")
  )

("FIS-LO05" :hint #x0
  (0 "PESCADOR" "¡JAJAJAJAJAJAJAJAJA! ¡JAJAJAAAA!")
  )

("FIS-TA01" :hint #x0
  (0 "PESCADOR" "¡A LA IZQUIERDA!")
  )

("FIS-TA02" :hint #x0
  (0 "PESCADOR" "¡A LA DERECHA!")
  )

("FIS-TA03" :hint #x0
  (0 "PESCADOR" "¡AQUÍ LLEGA UNO GRANDOTE!")
  )

("FIS-TA04" :hint #x0
  (0 "PESCADOR" "¡SE OS HA ESCAPADO UNO ENORME!")
  )

("FIS-TA05" :hint #x0
  (0 "PESCADOR" "¡QUE NO SE OS ESCAPE OTRO!")
  )

("FIS-TA06" :hint #x0
  (0 "PESCADOR" "¡FIRME, CHAVAL!")
  )

("FIS-TA07" :hint #x0
  (0 "PESCADOR" "¡TUS VELAS SE DOBLAN POR EL VIENTO, CHAVAL!")
  )

("FIS-TA08" :hint #x0
  (0 "PESCADOR" "¡GRRRR...SE ESCAPÓ!")
  )

("FIS-TA09" :hint #x0
  (0 "PESCADOR" "NO OS VENDRÍA MAL UNA RED MÁS GRANDE...")
  )

("FIS-TA10" :hint #x0
  (0 "PESCADOR" "¡SE ESCAPÓ DE NUEVO!")
  )

("FIS-TA11" :hint #x0
  (0 "PESCADOR" "¡MANTENTE AHÍ! CASI LO HAS CONSEGUIDO...")
  )

("FIS-TA1A" :hint #x0
  (0 "PESCADOR" "¡IZQUIERDA!")
  )

("FIS-TA2A" :hint #x0
  (0 "PESCADOR" "¡DERECHA!")
  )

("asstvb02" :hint #x289
  (0 "KEIRA" "¡GUAU!, ¿HABÉIS VISTO ESO? ¡LOS RESPIRADEROS DE ECO AZUL DEBEN DE HABERSE ACTIVADO EN TODO EL MUNDO!")
  (305)
  (315 "KEIRA" "SABÍA QUE HABÍA ALGUNA MANERA DE HACERLO.")
  (435)
  (442 "KEIRA" "DEBE DE HABER OTROS SITIOS EN LOS QUE ACTIVAR LOS DEMÁS RESPIRADEROS DE ECO.")
  )

("fisher-accept"
  (0 :offscreen "PESCADOR" "QUE LOS BUENOS PECES SON DE DOS TIPOS: LOS DE 1 KILO Y LOS DE 5.")
  (220 :offscreen "PESCADOR" "QUE SI DEJÁIS ESCAPAR 20 KILOS DE PESCADO, ¡OS QUITARÉ LA RED!")
  (432)
  (438 :offscreen "PESCADOR" "¡EN ESTE RÍO HAY ANGUILAS VENENOSAS!")
  (542)
  (545 :offscreen "PESCADOR" "SI COGÉIS UNA, LA MUY DESGRACIADA CONTAMINARÁ A TODA LA CAPTURA...JEJEJEJEJE...")
  )

("fisher-introduction"
  (0 "DAXTER" "¿QUÉ TIENES EN LA CESTA?")
  (50 "PESCADOR" "PUES...NADA.")
  (103)
  (106 "PESCADOR" "¡ESOS MONSTRUOS QUE PATRULLAN EL OCÉANO ME HAN ROTO LAS REDES!")
  (226)
  (229 "PESCADOR" "¡¡Y SE ESTÁN COMIENDO MIS CAPTURAS!!")
  (290)
  (293 "PESCADOR" "INTENTE LO QUE INTENTE...NO HAY MANERA DE PESCAR UN SOLO PEZ EN ESTE RÍO.")
  (419)
  (425 "DAXTER" "¡UUUFFF! ¿NO SERÁ...TU ALIENTO?")
  (515)
  (521 "PESCADOR" "¿CREÉIS QUE PODÉIS HACERLO MEJOR? ¡PUES INTENTAD COGER PECES CON UNA REDECITA!")
  (665)
  (671 "PESCADOR" "OS DARÉ UNA BATERÍA SI CONSEGUÍS PESCAR 200 KILOS DE PESCADO.")
  (808)
  (814 "PESCADOR" "Y LUEGO OS DEJARÉ A TÍ Y AL BOQUERÓN ESTE, USAR MI LANCHA PARA LLEGAR A ISLA DE MISTY.")
  (955)
  (961 "PESCADOR" "¿ACEPTÁIS EL RETO?")
  )

("fisher-reject"
  (2 "PESCADOR" "BIEN, SI ALGUNA VEZ QUERÉIS CONSEGUIR LA BATERÍA...YA SABÉIS DÓNDE ESTOY.")
  )

("fisher-reminder-1"
  (6 "PESCADOR" "QUERÉIS ENFRENTAROS AL RÍO, ¿VERDAD?")
  )

("fisher-resolution"
  (0 "PESCADOR" "¡LO CONSEGUISTEIS! ¡HABÉIS CONSEGUIDO 200 KILOS DE PESCADO!")
  (115)
  (120 "PESCADOR" "¡NO ESTÁ MAL PARA UN PAR DE HARAGANES!")
  (185)
  (199 "PESCADOR" "AQUÍ ESTÁ LA BATERÍA QUE OS PROMETÍ. ADEMÁS PODÉIS USAR LA LANCHA AMARRADA EN EL PUERTO DE LA ALDEA")
  (351 "PESCADOR" "CUANDO QUERÁIS.")
  )

("sksp0011" :hint #x240
  (0 "DAXTER" "DEBERÍAMOS PEDIRLE PRESTADA SU LANCHA AL PESCADOR DEL RÍO DE LA SELVA")
  (136 "DAXTER" "PARA IR A TODA PRISA A LA ISLA DE MISTY!")
  )

("sksp0018" :hint #x25e
  (0 "DAXTER" "¡DEBERÍAMOS DECIRLE AL CHARLATÁN DEL ALCALDE QUE NOS DEBE UNA")
  (223 "DAXTER" "POR CONECTARLE EL RAYO ENERGÉTICO DE LA ALDEA!")
  )

("sksp0037" :hint #x25f
  (0 "DAXTER" "ESA ESPECIE DE TORRES QUE HAY POR TODA LA SELVA DEBEN DE...REDIRIGIR EL RAYO ECO.")
  (214)
  (230 "DAXTER" "¡VAMOS A TRASTEAR CON ELLAS!")
  )

("sksp0038" :hint #x23c
  (0 "DAXTER" "MMMM, SI EL ECO AZUL PUEDE CONSTRUIR UN PUENTE, ¡SEGURO QUE TAMBIÉN ABRE PUERTAS!")
  (275)
  (281 "DAXTER" "¡VOLVAMOS PARA QUE PUEDAS REPOSTAR!")
  )

("sksp0039" :hint #x25b
  (0 "DAXTER" "¡EH!, HAY SEÑALES CON RELÁMPAGOS EN ESTOS POSTES.")
  (202 "DAXTER" "Y DE ESE RESPIRADERO SALE UN RELAMPAGUEO.")
  (391)
  (400 "DAXTER" "¿PIENSAS LO MISMO QUE YO?")
  )

("sksp0040" :hint #x23d
  (0 "DAXTER" "¡SUBÁMONOS A ESA MÁQUINA PARA ROMPER EL ESPEJO QUE DESVÍA EL RAYO DE PRECURSOR!")
  )

("sksp0041" :hint #x23e
  (0 "DAXTER" "¡TENEMOS QUE SUBIR A LA CIMA DE ESA TORRE!")
  )

("sksp0049" :hint #x29c
  (0 "DAXTER" "¡ALINEA EL RAYO APUNTÁNDOLE A LA TORRE SIGUIENTE!")
  )

("sksp0050" :hint #x29d
  (0 "DAXTER" "¡ROMPE EL ESPEJO, JAK!")
  )

("sksp0051" :hint #x29e
  (0 "DAXTER" "¡ATRAPA A LOS BICHOS, JAK! ¡ATRÁPALOS!")
  )

("sksp0052" :hint #x29f
  (0 "DAXTER" "¡VAYAMOS A LA SIGUIENTE TORRE A RECONECTAR EL RAYO!")
  )

("sksp0053" :hint #x2a0
  (0 "DAXTER" "¡EH! PARA ENCONTRAR LA SIGUIENTE TORRE PODEMOS SEGUIR EL RAYO.")
  )

("sksp0054" :hint #x2a1
  (0 "DAXTER" "TENEMOS QUE RECARGARTE DE COSA AZUL PARA QUE PUEDAS ABRIR ESTO.")
  )

("sksp0b42" :hint #x278
  (0 "DAXTER" "QUE NO SE TE ESCAPEN MÁS PECES AMARILLOS. ¡CADA UNO DE ELLOS PESA 5 KILOS! Y ESO ES UN MONTÓN, JAK.")
  )

;; -----------------
;; misty
;; -----------------

("asstvb03" :hint #x28b
  (0 "KEIRA" "¡BIEN! ¡HABÉIS DETENIDO A LOS LURKERS MINADORES!")
  (190 "KEIRA" "DURANTE SEMANAS HAN SIDO UNA PESADILLA EN LAS AGUAS QUE RODEAN A NUESTRA ALDEA.")
  (391 "KEIRA" "TRAED EL ZOOMER DE VUELTA AL TRANS-PAD Y OS TELETRANSPORTARÉ DE VUELTA.")
  )

("sagevb02" :hint #x28a
  (6 "SAMOS" "TENGO QUE ADMITIRLO, ¡ESTOY IMPRESIONADO! ¡NO LA HABÉIS PICIADO!")
  (385)
  (400 "SAMOS" "AHORA QUE LOS LURKERS NO PUEDEN ABRIR EL SILO, TAMPOCO PUEDEN INUNDAR EL MUNDO DE ECO OSCURO")
  (710 "SAMOS" "Y CAUSAR UN CAOS INCALCULABLE.")
  (863)
  (880 "SAMOS" "¡BORRA ESA RIDÍCULA SONRISA DE TU CARA, DAXTER! ¡LOS DOS TENÉIS MUCHO QUE HACER!")
  (1191 "SAMOS" "¡MANOS A LA OBRA!")
  )

("sksp0031" :hint #x23a
  (0 "DAXTER" "¡OOH, VAMOS A USAR EL CAÑÓN PARA VOLAR COSAS POR LOS AIRES!")
  )

("sksp0056" :hint #x27b
  (0 "DAXTER" "¡EEH, VEO A LA MUSA DEL ESCULTOR!")
  )

("sksp0059" :hint #x26e
  (0 "DAXTER" "¡ESTE SITIO ME DA ESCALOFRÍOS! ¡NO TE ACERQUES A ESO QUE REZUMA! ¿VALE?")
  )

("sksp0060" :hint #x26f
  (0 "DAXTER" "¡UUUUY! ¡ESTE SITIO ME DA ESCALOFRÍOS! Y CRÉEME, ES TODA UNA EXPERIENCIA")
  (337 "DAXTER" "CUANDO ESTÁS RECUBIERTO DE PELO.")
  )

("sksp0062" :hint #x27e
  (0 "DAXTER" "¡VAMOS A ACABAR CON ESOS LURKERS GLOBO! ¡NO DEJEMOS NI UNO!")
  )

("sksp0063" :hint #x27f
  (0 "DAXTER" "HE DICHO QUE ATAQUEMOS A LOS LURKERS, JAK. ¡NO LAS MINAS!")
  (332)
  (344 "DAXTER" "REGLA NÚMERO UNO: ¡EVITA SIEMPRE LAS MINAS!")
  )

("sksp0064" :hint #x245
  (0 "DAXTER" "¡VIGILA TU ESPALDA! QUE NO SE NOS OLVIDE LO QUE PASÓ AQUÍ LA ÚLTIMA VEZ.")
  )

("sksp0067" :hint #x249
  (0 "DAXTER" "¡NO TE CAIGAS EN LA NEBLINA QUE HAY DEBAJO! NO CREO QUE PODAMOS SALIR DE ELLA.")
  )

("sksp0069" :hint #x2a3
  (0 "DAXTER" "ES UNA EMBOSCADA, JAK ¡ES UNA EMBOSCADA!")
  )

("sksp0070" :hint #x2a4
  (0 "DAXTER" "SALTA, Y LUEGO CAE EN PICADO SOBRE EL BALANCÍN.")
  )

("sksp0435" :hint #x2aa
  (0 "DAXTER" "DERRIBA ESOS HUESOS.")
  )

;; -----------------
;; firecanyon
;; -----------------

("assistant-firecanyon-resolution"
  (25 "KEIRA" "¡ESTUPENDO! ¡TENÉIS LAS 20 BATERÍAS NECESARIAS PARA ACTIVAR MI ESCUDO TÉRMICO!")
  (140)
  (143 "KEIRA" "AHORA, ¡CUIDADO!, EL ESCUDO SOLO PROTEGERA EL ZOOMER HASTA LOS 500 GRADOS,")
  (295 "KEIRA" "ASÍ QUE MANTENEDLO FRESQUITO.")
  (343)
  (346 :offscreen "KEIRA" "SI VOLÁIS SOBRE LAVA, SEGURO QUE SE CALIENTA RÁPIDAMENTE.")
  (458)
  (462 "KEIRA" "SI LLEGÁIS A 500 GRADOS, SE ACABÓ.")
  (546)
  (552 "DAXTER" "¡¿SE ACABÓ?! ¡¿IGUAL QUE ACABA UN CHUBASCO?!")
  (636)
  (639 "KEIRA" "EL DESFILADERO DEL FUEGO SE CALIENTA MUCHO, ASÍ QUE BUSCAD LA MANERA DE SALTAR")
  (767 "KEIRA" " PARA EVITAR EL SUELO.")
  (792)
  (795 :offscreen "KEIRA" "TAMBIÉN HE SOLTADO MUCHOS GLOBOS REFRIGERANTES PARA QUE PODÁIS BAJAR")
  (895 :offscreen "KEIRA" "RÁPIDAMENTE LA TEMPERATURA DEL ESCUDO.")
  (956)
  (962 "KEIRA" "¡AAH! CUANDO LO ATRAVESÉIS, ¡NO OS OLVIDÉIS ACTIVAR")
  (1063 "KEIRA" "LA PUERTA TELETRANSPORTADORA EN EL LABORATORIO DEL SABIO AZUL.")
  (1140)
  (1146 "KEIRA" "¡ASÍ PODREMOS TELETRANSPORTARNOS Y REUNIRNOS CON VOSOTROS.")
  (1222)
  (1228 "KEIRA" "¡BUENA SUERTE!")
  )

("asstvb09" :hint #x24f
  (0 "KEIRA" "NO TENÉIS LAS 20 BATERÍAS NECESARIAS PARA ACTIVAR MI ESCUDO TÉRMICO.")
  (216)
  (234 "KEIRA" "NO PODÉIS CRUZAR EL DESFILADERO DEL FUEGO HASTA QUE NO TENGÁIS LAS QUE HACEN FALTA.")
  )

("sksp0076" :hint #x501
  (0 "DAXTER" "¡JAK, SALTA PARA MANTENERNOS LEJOS DE LA LAVA!")
  )

("sksp0077" :hint #x502
  (0 "DAXTER" "LOS GLOBOS SON BUENOS, ¡LA LAVA ARDIENTE ES MALA!")
  )

("sksp0078" :hint #x503
  (0 "DAXTER" "SÚBETE AL CHISME PRECURSOR PARA QUE SIGAMOS FRESQUITOS.")
  )

("sksp0079" :hint #x504
  (0 "DAXTER" "¡AAAAYYY, ME VOY A MORIIIIIR! ¡SOY UN BICHEJO FIAMBREE!")
  (257)
  (270 "DAXTER" "¡TIENES QUE LLEGAR AL OTRO LADO ANTES DE QUE ESTE CHISME SE CALIENTE DEMASIADO!")
  )

("sksp0080" :hint #x505
  (0 "DAXTER" "¡TIRA BRINCANDO, PARA DAR CURVAS MÁS CERRADAS!")
  )

("sksp0081" :hint #x506
  (0 "DAXTER" "¡AAAAAAYY! ¡DEBERÍA CONDUCIR YO!")
  )

("sksp0082" :hint #x507
  (0 "DAXTER" "¿TÁS INTENTANDO ESQUIVAR LAS CAJAS DE ECO OSCURO, VERDAD?")
  )

("sksp0083" :hint #x508
  (0 "DAXTER" "¡OOH, A VER SI PODEMOS PONER DISTANCIA ENTRE ESOS LURKERS Y NOSOTROS!")
  )

("sksp0084" :hint #x509
  (0 "DAXTER" "¡MUY CERCA! ¡MUUUUUUUY CERCA!")
  )

("sksp0085" :hint #x50a
  (0 "DAXTER" "¡GUAU! ¡ESTE CHISME SE ESTÁ CALENTANDO DEMASIADO!")
  )

("sksp0086" :hint #x50b
  (0 "DAXTER" "¡UNOS SEGUNDOS MÁS Y ESTAREMOS MÁS FRITOS QUE UN HUEVO DE FLUT FLUT!")
  )

("sksp0087" :hint #x50d
  (0 "DAXTER" "¡CHOCA CONTRA LOS GLOBOS, PARA REFRIGERARNOS!")
  )

("sksp0088" :hint #x50e
  (0 "DAXTER" "¡AHÍ VIENE OTRO GLOBO!")
  )

("sksp0089" :hint #x50f
  (0 "DAXTER" "¡OJALÁ NO HUBIESE SONADO EL DESPERTADOR ESTA MAÑANA!")
  )

("sksp0090" :hint #x510
  (0 "DAXTER" "¡SE TE HA ESCAPADO UN GLOBO! ¡LOS NECESITAMOS PARA NO ACABAR ESTOFADOS!")
  )

("sksp0091" :hint #x511
  (0 "DAXTER" "¡ESTE BÓLIDO SE ESTÁ CALENTANDO DEMASIADO!")
  )

("sksp0092" :hint #x512
  (0 "DAXTER" "¿NO HUELES A QUEMADO?")
  )

("sksp0093" :hint #x513
  (0 "DAXTER" "¡CREO QUE TENGO LA COLA ARDIENDOO!")
  )

("sksp0094" :hint #x514
  (0 "DAXTER" "¡ESTO VA A ESTALLAR!")
  )

("sksp0095" :hint #x515
  (0 "DAXTER" "¡YUUUJUUUUU! ¡LO CONSEGUIMOS!")
  )

("sksp0096" :hint #x516
  (0 "DAXTER" "¡AQUÍ TAMBIÉN HAY MOSCAS EXPLORADORAS!")
  )

;; -----------------
;; swamp
;; -----------------

("billy-accept"
  (5 "BILLY" "¡¡BIEEN!! ESAS RATAS VOLVERÁN EN CUALQUIER MOMENTO.")
  (109 "BILLY" "DISPARAD A TODAS, QUE NO SE COMAN NI UN SOLO APERITIVO.")
  )

("billy-introduction"
  (6 "BILLY" "¡HOLA, AMIGOS! ¿DISFRUTANDO DE MI PRECIOSO PANTANO? SOY EL DUEÑO DE ESTAS TIERRAS. ¡DE TODO LO QUE NO SE HUNDA EN EL BARRO, CLARO! JAAJIIJIJIJII")
  (349)
  (369 "DAXTER" "A JUZGAR POR EL OLOR, JURARÍA QUE TU BAÑERA ESTÁ HUNDIDA EN EL BARRO DESDE HACE MUCHO.")
  (497)
  (519 "BILLY" "¿QUÉ ES UNA BAÑERA? DA IGUAL...TENGO PROBLEMAS MÁS SERIOS...")
  (677)
  (691 "BILLY" "PARECE QUE UNAS ALIMAÑAS LURKER ESTÁN MERODEANDO POR AHÍ, ¡AGARRANDO LO QUE PUEDEN CON SUS MUGRIENTAS GARRAS!")
  (910 "BILLY" "Y ASUSTANDO A MI HIPHOG, FARTHY.")
  (1000 "BILLY" "LLEVA DESAPARECIDO NI SE SABE CUÁNTO.")
  (1136 :offscreen "BILLY" "HE ESTADO PONIENDO FUERA SU APERITIVO FAVORITO, ¡PERO ESAS RATAS DE PANTANO NO DEJAN DE ROBARLO!")
  (1318 :offscreen "BILLY" "SI PUDIÉSEIS MANTENER LEJOS A ESAS MOLESTAS CRIATURAS LO SUFICIENTE, ¡SÉ QUE FARTHY OLERÍA EL PAPEO Y VOLVERÍA!")
  (1509)
  (1527 "BILLY" "¿ME AYUDARÉIS?")
  )

("billy-reject"
  (7 "BILLY" "BIEEN...SI CAMBIÁIS DE IDEA, ¡YA SABÉIS DONDE ENCONTRARME! (RISAS)")
  )

("billy-reminder-1"
  (36 "BILLY" "¡VAAAAYA! ¿HABÉIS VUELTO PARA ACABAR CON LAS RATAS?")
  )

("billy-resolution"
  (1 "BILLY" "¡NO ESTÁ NADA MAL! ¡TIENES BUENA PUNTERÍA! GRACIAS MIL POR LA AYUDA.")
  )

;; -----------------
;; citadel
;; -----------------

("BLU-AM01" :hint #x0
  (0 "SABIO AZUL" "¡NO ME VENDRÍA MAL UN POCO DE AYUDA!")
  )

("BLU-AM02" :hint #x0
  (0 "SABIO AZUL" "MENUDO DESASTRE TENEMOS AQUÍ.")
  )

("BLU-AM03" :hint #x0
  (0 "SABIO AZUL" "VAYA, ESTO ES TODO UN ENIGMA.")
  )

("RED-AM01" :hint #x0
  (0 "SABIO ROJO" "¿HAY ALGUIEN AHÍ?")
  )

("RED-AM02" :hint #x0
  (0 "SABIO ROJO" "BIEN...")
  )

("RED-AM03" :hint #x0
  (0 "SABIO ROJO" "¿POR QUÉ HABÉIS TARDADO?")
  )

("YEL-AM01" :hint #x0
  (0 "SABIO AMARILLO" "¡EL TIEMPO SE AGOTA!")
  )

("YEL-AM02" :hint #x0
  (0 "SABIO AMARILLO" "¡EEH! ¡¡SACADME DE AQUÍ!!")
  )

("YEL-AM03" :hint #x0
  (0 "SABIO AMARILLO" "CUANDO SALGA DE AQUÍ ¡¡ALGUIEN SE VA A ENTERAR!!")
  )

("bluesage-resolution"
  (63 "SABIO AZUL" "¡BUEN TRABAJO, CHICOS! ¡SAMOS TENÍA RAZÓN SOBRE VOSOTROS!")
  (162)
  (165 "SABIO AZUL" "¡POR TODOS LOS PRECURSOR!")
  (253 "SABIO AZUL" "¡NO DEBEMOS PERMITIR QUE ESA ABERRACIÓN MECÁNICA DESATE EL CAOS!")
  (420 "SABIO AZUL" "INTENTARÉ ACTIVAR EL ESCUDO CREANDO UN CONDUCTO ENERGÉTICO")
  (563 "SABIO AZUL" "ENTRE MÍ...Y EL ENORME PORTAL QUE HAY ABAJO.")
  (666 "DAXTER" "AAAMM...SÍ. HAZLO. NOSOTROS...EMMMM...IREMOS A BUSCAR MÁS AYUDA...")
  (873)
  (891 :offscreen "DAXTER" "¡¡TÍO RARO!!")
  (980)
  )

("green-sagecage-introduction"
  (130 "SAMOS" "¡YA ERA HORA DE QUE DIÉRAIS SEÑALES DE VIDA!")
  (207 "DAXTER" "TAMBIÉN ESTAMOS ENCANTADOS DE VERTE. ¿AHORA...TE DEDICAS A FREGAR SUELOS?")
  (343 "SAMOS" "NO HAY TIEMPO PARA BROMITAS, DAXTER. GOL Y MAIA NOS RAPTARON.")
  (477 "SAMOS" "PARA ARREBATARNOS NUESTRAS FUERZAS Y ALIMENTAR A SU TERRORÍFICA MÁQUINA.")
  (574)
  (577 :offscreen "SAMOS" "PARECE SER QUE HAN COMBINADO LOS RESTOS ÚTILES DE UN ROBOT PRECURSOR")
  (710 :offscreen "SAMOS" "CON ARTEFACTOS RECOGIDOS POR AQUÍ Y ALLÁ.")
  (800)
  (803 :offscreen "SAMOS" "Y HAN AÑADIDO UNOS CUANTOS TOQUES DIABÓLICOS DE SU COSECHA,")
  (921 :offscreen "SAMOS" "CREANDO LA ÚNICA COSA CAPAZ DE ABRIR LOS SILOS DE ECO OSCURO.")
  (1060 "SAMOS" "SI LOGRÁIS LIBERARNOS A LOS CUATRO, USAREMOS NUESTROS PODERES COMBINADOS")
  (1180 "SAMOS" "PARA ROMPER EL ESCUDO DE FUERZA QUE RODEA AL ROBOT, ANTES DE QUE LO USEN PARA DESTRUIR EL MUNDO.")
  )

("green-sagecage-outro-preboss"
  (56 "GOL" "HAS LLEGADO DEMASIADO TARDE, SAMOS.")
  (125 "GOL" "CUANDO POSEA INFINITO ECO OSCURO, TENDRÉ LA LLAVE DE LA CREACIÓN.")
  (335 "SAMOS" "¡¡ES UNA LOCURA!! ¡AL LIBERAR TODO ESE ECO OSCURO DESTRUIRÉIS ABSOLUTAMENTE TODO!")
  (504 "SAMOS" "¡FIJAOS EN LO QUE OS HA HECHO A VOSOTROS!")
  (578)
  (581 "MAIA" "NOS HA DADO UNA BELLEZA QUE TU INTELECTO NO LLEGA A COMPRENDER.")
  (693)
  (696 "DAXTER" "¿BELLEZA...? ¿OS...HABÉIS MIRADO AL ESPEJO ÚLTIMAMENTE?")
  (825)
  (828 "MAIA" "ESPERA A QUE ABRAMOS LOS SILOS, CHIQUITÍN. AÑORARÁS EL ASPECTO QUE TIENES AHORA.")
  (1030 "GOL" "Y PENSAR QUE HABÉIS LLEGADO HASTA AQUÍ BUSCANDO MI AYUDA...")
  (1180 "GOL" "¡¡TONTOS!! ¡¡DISFRUTAD DE LA REMODELACIÓN DEL MUNDO EN PRIMERA FILA!!")
  (1391)
  (1605 "SAMOS" "¡JAK! ¡SUBE EN EL ASCENSOR Y DETÉN A ESE ROBOT!")
  )

("green-sagecage-resolution"
  (35 "SAMOS" "¡BUEN TRABAJO, MUCHACHOS! AHORA SÍ QUE SOIS UNOS HÉROES.")
  (158 "SAMOS" "COMBINARÉ MI PODER DE ECO VERDE CON LOS DE LOS OTROS TRES SABIOS")
  (280 "SAMOS" "Y JUNTOS ABRIREMOS EL ESCUDO QUE RODEA AL ROBOT PRECURSOR.")
  (405 "DAXTER" "¡SÍ, SÍ! PARECE UN BUEN COMIENZO.")
  (457 "DAXTER" "Y...¿QUÉ VAIS A HACER CON EL ROBOT, DESPUÉS DE HABER ABIERTO EL ESCUDO?")
  (576 "SAMOS" "NADA, DAXTER. NOSOTROS TENEMOS QUE MANTENER EL ESCUDO ABIERTO.")
  (705 "SAMOS" "TENDRÉIS QUE AVERIGUAR LA FORMA DE DESTRUIR AL ROBOT.")
  (823 "DAXTER" "OHH...GENIAL...ME TOCA AYUDAR AL TIPO QUE ME CONVIRTIÓ EN UNA BOLA DE PELOS")
  (983 "DAXTER" "¡A DESTRUIR A LA ÚNICA PERSONA QUE PUEDE DEVOLVERME MI FORMA!")
  (1111)
  (1161 "SAMOS" "¡PRIMERO, SALVAD EL MUNDO! LUEGO TRATAREMOS DE CONVENCER A GOL PARA QUE AYUDE A DAXTER.")
  )

("redsage-resolution"
  (58 "SABIO ROJO" "(RISAS) POR FIN VENÍS A RESCATARME.")
  (190 "SABIO ROJO" "¿SABÉIS CUÁNTO TIEMPO LLEVO AQUÍ? ¿POR QUÉ HABÉIS TARDADO TANTO? (RISAS)")
  (378 "SABIO ROJO" "¿CÓMO OS LLAMÁIS?")
  (429)
  (432 "DAXTER" "¡SOY DAXTER! ÉL ES JAK, VIENE CONMIGO.")
  (540 :offscreen "SABIO ROJO" "BUEN TRABAJO, DAXTER. ERES TOOODO UN HÉROE.")
  (677)
  (703 "SABIO ROJO" "TENÉIS QUE EVITAR QUE GOL ACTIVE EL ROBOT.")
  (837 "SABIO ROJO" "OS AYUDARÉ A ABRIR EL ESCUDO CON MI PODER DE ECO.")
  )

("sksp0378" :hint #x813
  (0 "DAXTER" "LA PUERTA ESTÁ ABIERTA, ¡VÁMONOS!")
  )

("sksp0381" :hint #x806
  (0 "DAXTER" "¡ROMPE EL GENERADOR PARA LIBERAR AL SABIO!")
  )

("sksp0382" :hint #x807
  (0 "DAXTER" "¡AGUANTA EN EL BORDE!")
  )

("sksp0383" :hint #x808
  (0 "DAXTER" "TENEMOS COMPAÑÍA, JAK. ¡MONTONES DE LURKERS!")
  )

("sksp0384" :hint #x809
  (0 "DAXTER" "¡DESTRUYE LOS GENERADORES!")
  )

("sksp0385" :hint #x80a
  (0 "DAXTER" "¡PULSA EL BOTÓN!")
  )

("sksp0386" :hint #x80b
  (0 "DAXTER" "¡ESE ROBOT NO ME DA MIEDO!")
  )

("sksp0387" :hint #x80c
  (0 "DAXTER" "¡SUBAMOS A ESAS PLATAFORMAS!")
  )

("sksp0388" :hint #x80d
  (0 "DAXTER" "¡QUE NO SE TE ESCAPE EL PRÓXIMO LANZADOOOOOR!")
  )

("sksp0389" :hint #x80e
  (0 "DAXTER" "¡CUIDADO!")
  )

("sksp0390" :hint #x80f
  (0 "DAXTER" "TENEMOS QUE RESCATAR A TODOS LOS SABIOS.")
  )

("sksp0391" :hint #x810
  (0 "DAXTER" "¿TÚ CREES QUE GOL ME DEVOLVERÁ MI ASPECTO?")
  )

("sksp0392" :hint #x811
  (0 "DAXTER" "ASÍ QUE ESTA ES LA CIUDADELA DE GOL Y MAIA. ¡QUÉ MOOONA!")
  )

("sksp0393" :hint #x812
  (0 "DAXTER" "¡ATERRIZA EN EL PRÓXIMO LANZADOR!")
  )

("yellowsage-resolution"
  (57 "SABIO AMARILLO" "¿QUIÉN HABRÍA DICHO QUE VIVIRÍA PARA VER")
  (137 "SABIO AMARILLO" "CÓMO ME RESCATAN UN CHICO Y SU COMADREJA?")
  (271 "SABIO AMARILLO" "MMMMM...VOY A DAR A GOL Y A MAIA SU MERECIDO POR PASAR ESTE BOCHORNO.")
  (471)
  (480 "SABIO AMARILLO" "Y DESPUÉS, VEREMOS SI...COCINAMOS UN ESTOFADO DE...COMADREJA.")
  (605)
  )

;; -----------------
;; finalboss
;; -----------------

("GOL-AM01" :hint #x0
  (0 "GOL" "NO PENSÁIS RENDIROS, ¿VERDAD?")
  )

("GOL-AM02" :hint #x0
  (0 "GOL" "¡EL ECO OSCURO PRONTO SERÁ NUESTRO!")
  )

("GOL-AM03" :hint #x0
  (0 "GOL" "¡ACABAD CON ELLOS!")
  )

("GOL-AM04" :hint #x0
  (0 "GOL" "¡FUEEEGOO!")
  )

("GOL-AM05" :hint #x0
  (0 "GOL" "¡PULVERIZADLOOS!")
  )

("GOL-AM06" :hint #x0
  (0 "GOL" "¿QUÉ...? ¡¿OTRA VEZ ELLOS!?")
  )

("GOL-AM07" :hint #x0
  (0 "GOL" "¡ES DEMASIADO TARDE!")
  )

("GOL-AM08" :hint #x0
  (0 "GOL" "¡SOIS MÍOS!")
  )

("GOL-AM09" :hint #x0
  (0 "GOL" "¡YA OS TENGO!")
  )

("GOL-AM10" :hint #x0
  (0 "GOL" "(RISAS)")
  )

("GOL-AM11" :hint #x0
  (0 "GOL" "¡SIN PIEDAD!")
  )

("GOL-AM12" :hint #x0
  (0 "GOL" "¡TOMA YA!")
  )

("GOL-AM13" :hint #x0
  (0 "GOL" "¡BUEN INTENTO!")
  )

("GOL-AM14" :hint #x0
  (0 "GOL" "¡QUIETECIITOOS!")
  )

("GOL-AM15" :hint #x0
  (0 "GOL" "¡QUÉ PATÉTICO!")
  )

("GOL-AM16" :hint #x0
  (0 "GOL" "¡NOOOOOOO!")
  )

("GOL-AM17" :hint #x0
  (0 "GOL" "¡AAAHHH!")
  )

("GOL-AM18" :hint #x0
  (0 "GOL" "¡ABRIREMOS EL SILO DEL TODO Y OS DESTRUIREMOS A LOS DOS!")
  )

("GOL-AM19" :hint #x0
  (0 "GOL" "¡ECO LUMINOSO! ¡¡EXISTE!!")
  )

("GOL-AM20" :hint #x0
  (0 "GOL" "¡NO VAMOS A ACEPTARLO!")
  )

("MAI-AM01" :hint #x0
  (0 "MAIA" "¡ACABAD CON ELLOS DE UNA VEZ!")
  )

("MAI-AM02" :hint #x0
  (0 "MAIA" "¡LIQUIDADLOS!")
  )

("MAI-AM03" :hint #x0
  (0 "MAIA" "(RISAS)")
  )

("MAI-AM04" :hint #x0
  (0 "MAIA" "¡EL ECO YA NO OS PROTEGERÁ!")
  )

("MAI-AM05" :hint #x0
  (0 "MAIA" "¡HACED ALGO!")
  )

("MAI-AM06" :hint #x0
  (0 "MAIA" "¡AAAHHH!")
  )

("MAI-AM07" :hint #x0
  (0 "MAIA" "¡NOOOOOOOOOOOOOO!")
  )

("MAI-AM08" :hint #x0
  (0 "MAIA" "¡ABRIREMOS EL SILO DEL TODO Y OS DESTRUIREMOS A LOS DOS!")
  )

("MAI-AM09" :hint #x0
  (0 "MAIA" "¡¡NO DEJÉIS QUE LO COJAN!!")
  )

("finalbosscam-white-eco"
  (163 :offscreen "GOL" "¡ECO LUMINOSO! ¡¡EXISTE!!")
  (268 :offscreen "MAIA" "¡¡NO DEJÉIS QUE LO COJAN!!")
  )

("green-sagecage-daxter-sacrifice"
  (0 "DAXTER" "¡¡SANTO ECO!! ¡¡ESO ME PODRÍA DEVOLVER MI ASPECTO!!")
  (114)
  (123 "DAXTER" "MMMMM...Y TAMBIÉN...DETENER AL ROBOT.")
  (235)
  (274 "DAXTER" "MMMMM...VAYA...¿SEGUIR PELUDO...? ¡SALVAR EL MUNDO...!")
  (404)
  (437 "DAXTER" "VEAAAMOS, VAAALE ¡MUY BIEN! ¡SALVAREMOS EL MUNDO! ¡PERO RAPIDITO! ANTES DE QUE CAMBIE DE IDEA ¿EH? (RISAS)")
  (634)
  )

("green-sagecage-outro-beat-boss-a"
  (165 :offscreen "MAIA" "¡¡HAZ ALGO!!")
  (216)
  (596 :offscreen "GOL" "¡¡NOOOOOOOO!!")
  )

("green-sagecage-outro-beat-boss-b"
  (522 "SAMOS" "BIEN, PARECE QUE HE SIDO DEMASIADO DURO CON VOSOTROS.")
  (640 "SAMOS" "¡SÍ QUE TENÉIS MADERA DE HÉROES!")
  (745)
  (751 "KEIRA" "PERO DAXTER...¡AHORA NO PODEMOS CAMBIARTE!")
  (845)
  (847 "DAXTER" "NO TE PREOCUPES POR MÍ, NENA. YA SABES QUE...LAS GRANDES ESENCIAS...VIENEN EN FRASCOS PEQUEÑOS.")
  (1096)
  (1100 "SABIO AZUL" "JAK, ¡TIENES UN DON INCREÍBLE PARA CANALIZAR EL ECO!")
  (1219)
  (1222 "SABIO AZUL" "SAMOS, ¡NO TE HABÍAS EQUIVOCADO SOBRE ÉL DESPUÉS DE TODO!")
  (1321)
  (1323 "SABIO ROJO" "Y KEIRA, SIN TU AYUDA E INGENIO, NADA DE ESTO HABRÍA SIDO POSIBLE.")
  (1515 "SABIO ROJO" "(RISAS) TAL VEZ TENGAMOS ENTRE NOSOTROS A OTRO SABIO, AHORA QUE GOL Y MAIA NO ESTÁN...")
  (1728)
  (1731 "SAMOS" "SÍ, GOL Y MAIA...ES PROBABLE QUE EL ECO OSCURO LOS HAYA DESTRUÍDO.")
  (1916 :offscreen "SAMOS" "ES PROBABLE...")
  (1999)
  (2003 "DAXTER" "¡BAAH! ¿QUÉ MÁS DA? ¡QUE VENGAN Y LOS DERROTAREMOS DE NUEVO! ¿VERDAD, JAK?")
  (2168)
  (2172 "DAXTER" "EEMMMMM...¿JAK?")
  (2256)
  (2302 "DAXTER" "¡GUAAAU! ¡UN POCO DE HIELO PARA ESTE!")
  )

("green-sagecage-outro-beat-boss-enough-cells"
  (151 "SAMOS" "¡SANTO ECO! ¿QUÉ SERÁ ESO?")
  (247 "KEIRA" "¡GUAAU! ¡ES UNA ANTIGUA PUERTA PRECURSOR!")
  (342 :offscreen "KEIRA" "PARECE QUE SOLO SE ABRE LLENANDO LOS 100 AGUJEROS...DE BATERÍAS.")
  (485 "DAXTER" "¡EJEEEM! SOMOS HÉROES, ¿RECUERDAS? ¡YA TENEMOS 100 BATERÍAS!")
  )

("green-sagecage-outro-beat-boss-need-cells"
  (151 "SAMOS" "¡SANTO ECO! ¿QUÉ SERÁ ESO?")
  (247 "KEIRA" "¡GUAAU! ¡ES UNA ANTIGUA PUERTA PRECURSOR!")
  (342 :offscreen "KEIRA" "PARECE QUE SOLO SE ABRE LLENANDO LOS 100 AGUJEROS...DE BATERÍAS.")
  (485 "DAXTER" "¡VAAAYA! ¡ALLÁ VAAMOS OTRA VEEEEZ!")
  )

("green-sagecage-outro-big-finish"
  (322 "DAXTER" "¡GUAAAU! ¿QUÉ ES?")
  (425)
  (428 "KEIRA" "ES...TAN BONITO...")
  (516)
  (519 "SAMOS" "¡POR TODOS LOS PRECURSOR!")
  (602)
  )

;; -----------------
;; training
;; -----------------

("asstvb40" :hint #x900
  (0 "KEIRA" "ESTE APARATO ES UN COMUNICADOR. CON ÉL, MI PADRE Y YO")
  (181 "KEIRA" "PODREMOS ACONSEJAROS EN CUALQUIER MOMENTO DURANTE VUESTRA AVENTURA.")
  )

("asstvb41" :hint #x901
  (0 "KEIRA" "ESTAS COSAS CON FORMA DE HUEVO QUE FLOTAN SON ESFERAS DE PRECURSOR.")
  (176)
  (180 "KEIRA" "SI RECOGÉIS LAS SUFICIENTES, ALGUNOS DE LOS ALDEANOS OS DARÁN")
  (405 "KEIRA" "A CAMBIO UNA BATERÍA.")
  )

("asstvb42" :hint #x902
  (0 "KEIRA" "ESTO ES UNA BATERÍA, EL ARTEFACTO PRECURSOR MÁS IMPORTANTE QUE PODÉIS ENCONTRAR.")
  (327)
  (333 "KEIRA" "TENÉIS QUE RECOGER 20 COMO ESTAS, Y ASÍ PODRÉ HACER QUE FUNCIONE EL ESCUDO TÉRMICO")
  (507 "KEIRA" "DE VUESTRO ZOOMER ANTI-GRAVITATORIO.")
  )

("asstvb44" :hint #x903
  (0 "KEIRA" "¡EHH! ¡HABÉIS ENCONTRADO UNA DE MIS MOSCAS EXPLORADORAS!")
  (160 "KEIRA" "ENVÍE 7 A CADA ZONA PARA QUE BUSCARAN BATERÍAS,")
  (343 "KEIRA" "PERO LOS LURKERS DEBEN DE HABERLAS CAPTURADO A TODAS-")
  )

("asstvb45" :hint #x904
  (0 "KEIRA" "¡VAYA! ¡ESA ÚLTIMA MOSCA EXPLORADORA TENÍA UNA BATERÍA!")
  (219 "KEIRA" "SEGURO QUE SI REUNÍS LAS 7 DE CADA ZONA PODRÉIS ENCONTRAR MÁS BATERÍAS TODAVÍA.")
  )

("asstvb46" :hint #x905
  (0 "KEIRA" "¡TENED CUIDADO EN EL OCÉANO! ¡LAS AGUAS ESTÁN ATESTADAS DE TIBURONES LURKER!")
  (258 "KEIRA" "¡Y JAMÁS HE VISTO A NADIE QUE LOGRE DERROTAR A UNO!")
  (419)
  (426 "KEIRA" "¡MANTENÉOS ALEJADOS DE ELLOS SI SABÉIS LO QUE OS CONVIENE!")
  )

("asstvb47" :hint #x906
  (0 "KEIRA" "RECORDAD, ESO ES UNA BATERÍA. TENÉIS QUE RECOGER EL MAYOR NÚMERO DE ELLAS POSIBLE.")
  )

("asstvb48" :hint #x907
  (0 "KEIRA" "ESO ES UN RESPIRADERO DE ECO AZUL. AL ESTAR MÁS CONCENTRADO QUE EN LOS RACIMOS FLOTANTES,")
  (253 "KEIRA" "ESTE RESPIRADERO OS PROPORCIONARÁ UNA CARGA COMPLETA DE ECO AZUL,")
  (419 "KEIRA" "QUE PODRÉIS UTILIZAR DURANTE EL MÁXIMO DE TIEMPO.")
  )

("sagevb21" :hint #x908
  (3 "SAMOS" "ESAS BOLITAS VERDES DE ENERGÍA DEL SUELO SON UNA CLASE DE ECO.")
  (280 "SAMOS" "RECOGE 50 BOLITAS VERDES DE ECO O UNA GRANDE Y VERDE Y AUMENTARÁS TU NIVEL DE SALUD.")
  )

("sagevb22" :hint #x909
  (0 "SAMOS" "ESO ES ECO AZUL, QUE CONTIENE LA ENERGÍA DEL MOVIMIENTO.")
  (291 "SAMOS" "EL ECO AZUL TE PERMITIRÁ CORRER MÁS RÁPIDO, ROMPER CAJAS, E INCLUSO ACTIVAR ALGUNOS ARTEFACTOS")
  (640 "SAMOS" "PRECURSOR CUANDO TE ACERQUES.")
  )

("sagevb23" :hint #x90a
  (0 "SAMOS" "FÍJATE COMO CADA RACIMO DE ECO AZUL QUE RECOGES, HACE QUE AUMENTE EL TIEMPO DURANTE EL QUE PUEDES UTILIZAR SU PODER.")
  )

("sagevb24" :hint #x90b
  (3 "SAMOS" "ESTA ES UNA PUERTA PRECURSOR. SOLO PODRÁS ABRIRLA SI TE APROXIMAS A ELLA")
  (357 "SAMOS" "MIENTRAS EMITES CON TU CUERPO ECO AZUL.")
  )

("sagevb25" :hint #x90c
  (3 "SAMOS" "¡BUEN TRABAJO! EL ECO AZUL HA HECHO QUE LA PUERTA SE ABRA. CON EL ECO AZUL, PODRÁS INSUFLAR")
  (365 "SAMOS" "ENERGÍA EN TODO TIPO DE ARTEFACTOS PRECURSOR, QUE HAN ESTADO INACTIVOS DURANTE AÑOS.")
  )

("sagevb26" :hint #x90d
  (0 "SAMOS" "UTILIZA LAS GAFAS PARA VER TUS AVANCES A LO LARGO DE LA AVENTURA.")
  )

("sagevb27" :hint #x90e
  (1 "SAMOS" "PUEDES SALTAR UNA VEZ, Y CUANDO ESTÉS EN EL AIRE, HACERLO DE NUEVO PARA LLEGAR A LOS SALIENTES QUE ESTÉN MÁS ALTOS.")
  )

("sagevb28" :hint #x90f
  (0 "SAMOS" "CUANDO ESTÉS RODEADO DE ENEMIGOS, USA LA PATADA GIRATORIA.")
  )

("sagevb29" :hint #x910
  (0 "SAMOS" "¡ESO NO ES UNA PATADA GIRATORIA! ¡OTRA VEZ!")
  )

("sagevb30" :hint #x911
  (0 "SAMOS" "¡VAMOS, JAK! ¡DA UNA PATADA GIRATORIA!")
  )

("sagevb31" :hint #x912
  (0 "SAMOS" "¡BUEN TRABAJO! USA LA PATADA GIRATORIA CUANDO QUIERAS ATACAR A TODO LO QUE TE RODEA.")
  )

("sagevb32" :hint #x913
  (0 "SAMOS" "PARA LLEVAR A CABO UN ATAQUE EN MOVIMIENTO EN LÍNEA RECTA, USA EL PUÑO PARA DAR UN PUÑETAZO.")
  )

("sagevb33" :hint #x914
  (0 "SAMOS" "¡ESO NO ES UN PUÑETAZO! ¡DA AHORA UN PUÑETAZO DE VERDAD!")
  )

("sagevb34" :hint #x915
  (0 "SAMOS" "¡JAK! ¡DA UN PUÑETAZO!")
  )

("sagevb35" :hint #x916
  (0 "SAMOS" "¡BIEN HECHO! UTILIZA EL PUÑETAZO PARA REDUCIR RÁPIDAMENTE LA DISTANCIA EN UNA SITUACIÓN DIFÍCIL.")
  )

("sagevb36" :hint #x917
  (0 "SAMOS" "A VECES QUERRÁS GOLPEAR LAS COSAS CON MÁS FUERZA.")
  (218 "SAMOS" "PARA ROMPER UNA DE ESAS CAJAS TENDRÁS QUE SALTAR EN EL AIRE")
  (420 "SAMOS" "Y CAER EN PICADO SOBRE ELLA, ¡PERO CON LAS MANOS POR DELANTE!")
  )

("sagevb37" :hint #x918
  (0 "SAMOS" "CUANDO COJAS MÁS CONFIANZA EN TÍ MISMO, TRATA DE PONER EN PRÁCTICA ALGUNOS DE TUS MOVIMIENTOS COMBINADOS.")
  )

("sagevb38" :hint #x919
  (0 "SAMOS" "NO PODRÉIS REGRESAR A TRAVÉS DE LA PUERTA TRANSPORTADORA,")
  (212 "SAMOS" "HASTA QUE NO HAYÁIS ENCONTRADO LAS 4 BATERÍAS DE ESTA ISLA.")
  )

("sagevb39" :hint #x91a
  (0 "SAMOS" "¡ESTUPENDO! ¡HABÉIS ENCONTRADO TODAS LAS BATERÍAS DE LA ISLA!")
  (269 "SAMOS" "REGRESAD POR LA PUERTA TRANSPORTADORA, Y ASÍ PODRÉ LLEVAROS DE VUELTA AL LABORATORIO. ¡RÁPIDO!")
  )

;; -----------------
;; uncategorized
;; -----------------
