(language-id 6)
(text-version jak1-v2)

;; -----------------
;; intro
;; -----------------

("sidekick-human-intro-sequence-b"
  (547 "OLD MAN" "CONTINUE YOUR SEARCH FOR ARTEFACTS AND ECO.")
  (664)
  (674 "OLD MAN" "IF THE LOCALS POSSESS PRECURSOR ITEMS, YOU KNOW WHAT TO DO.")
  (819)
  (839 "WOMAN" "DEAL HARSHLY WITH ANYBODY WHO STRAYS FROM THE VILLAGE.")
  (937 "WOMAN" "WE WILL ATTACK IT IN DUE TIME.")
  (1027)
  )

;; -----------------
;; sidekick
;; -----------------

("sksp009c" :hint #x28f (0 "DAXTER" "DO ME A FAVOUR AND KEEP AWAY FROM THOSE DARK ECO BOXES!"))

;; -----------------
;; oracle
;; -----------------

;; -----------------
;; training
;; -----------------

("asstvb42" :hint #x902
  (0 "KEIRA" "THIS IS A POWER CELL, THE MOST IMPORTANT PRECURSOR ARTEFACT YOU CAN FIND!")
  (327)
  (333 "KEIRA" "YOU NEED TO COLLECT 20 OF THESE SO I CAN POWER THE HEAT SHIELD")
  (507 "KEIRA" "FOR YOUR A-GRAV ZOOMER.")
  )

("sagevb22" :hint #x909
  (0 "SAGE" "THAT'S BLUE ECO, WHICH CONTAINS THE ENERGY OF MOTION.")
  (291 "SAGE" "BLUE ECO ALLOWS YOU TO RUN FAST, BREAK BOXES, AND EVEN ACTIVATE SOME PRECURSOR")
  (640 "SAGE" "ARTEFACTS WHEN YOU GET NEAR THEM.")
  )

("sagevb25" :hint #x90c
  (3 "SAGE" "GOOD WORK, THE BLUE ECO CAUSED THE DOOR TO OPEN.")
  (250 "SAGE" "WITH BLUE ECO, YOU CAN BREATHE ENERGY INTO ALL KINDS")
  (476 "SAGE" "OF PRECURSOR ARTEFACTS THAT HAVE LAIN DORMANT FOR YEARS.")
  )

;; -----------------
;; village1
;; -----------------

;; -----------------
;; beach
;; -----------------

("bird-lady-beach-resolution"
  (30 "BIRDWATCHER" "OH MY, I HOPE THE POOR DEAR'S OKAY.")
  (148)
  (157 "BIRDWATCHER" "HERE'S A POWER CELL FOR YOUR VALOUR.")
  (237)
  (306 "FLUT FLUT" "MAMA!")
  (351)
  (406 "FLUT FLUT" "MAMA!")
  (430 "DAXTER" "OH NO! NO, NO, NO, NO!")
  (533)
  (535 "BIRDWATCHER" "LOOK... ISN'T THAT CUTE? IT THINKS YOU'RE ITS MAMA.")
  (696)
  (699 "DAXTER" "EH? I'M NOT YOUR MOM! YOU SEE ANY FEATHERS HERE?")
  (803)
  (807 "BIRDWATCHER" "OH, LOVE AT FIRST SIGHT! AH...")
  (936)
  (939 "BIRDWATCHER" "LISTEN, BOYS, I'LL TAKE THIS LITTLE CHICK BACK TO THE VILLAGE WITH ME")
  (1054 "BIRDWATCHER" "AND WORK WITH THE SAGE TO TAKE CARE OF HER.")
  )

("bird-lady-introduction"
  (125 "BIRDWATCHER" "OH MY, WHAT A HORRIBLY SICK LITTLE BIRD.")
  (245)
  (251 "DAXTER" "HUH! YOU DON'T LOOK SO GOOD YOURSELF, LADY!")
  (328)
  (331 "BIRDWATCHER" "OH, SORRY. I THOUGHT YOU WERE A SPOTTED")
  (408 "BIRDWATCHER" "ORANGE-BELLIED RAIN FRAY.")
  (454)
  (457 "BIRDWATCHER" "YOU KNOW, YESTERDAY I SAW SOME")
  (536 "BIRDWATCHER" "TERRIBLY VICIOUS CREATURES CAPTURE")
  (590 "BIRDWATCHER" "A MOTHER FLUT FLUT NEAR THE BEACH.")
  (648)
  (654 :offscreen "BIRDWATCHER" "NOW THERE'S THIS POOR LITTLE ORPHAN EGG")
  (730 :offscreen "BIRDWATCHER" "SITTING IN A NEST AT THE TOP OF THE CLIFF")
  (794 :offscreen "BIRDWATCHER" "AND I CAN'T GET TO IT.")
  (854 :offscreen "BIRDWATCHER" "IF YOU COULD CLIMB UP THERE AND PUSH IT OFF, I'VE PILED")
  (946 :offscreen "BIRDWATCHER" "SOME HAY DOWN AT THE BASE TO CATCH IT SAFELY.")
  (1041)
  (1044 "BIRDWATCHER" "DO AN OLD LADY A FAVOUR, AND I'LL GIVE YOU A POWER CELL.")
  (1198)
  )

;; -----------------
;; jungle
;; -----------------

;; -----------------
;; misty
;; -----------------

;; -----------------
;; firecanyon
;; -----------------

;; -----------------
;; village2
;; -----------------

("sage-bluehut-introduction-prec-arm"
  (0 "SAGE" "WELL, I HOPE YOU'VE PACKED A LUNCH. 'CAUSE WE'RE JUST GETTING STARTED.")
  (130)
  (140 "SAGE" "ACCORDING TO THE BLUE SAGE'S NOTES,")
  (208 "SAGE" "LURKERS HAVE INFESTED THE SWAMP ACROSS THE BAY.")
  (300)
  (304 :offscreen "SAGE" "APPARENTLY, THEY'RE PLANNING TO USE A DIRIGIBLE")
  (417 :offscreen "SAGE" "TO LIFT AN IMPORTANT PRECURSOR ARTEFACT FROM THE MUCK.")
  (531)
  (549 :offscreen "SAGE" "YOU'RE GOING TO HAVE TO GET OVER THERE TO DISLODGE THEIR TETHERS.")
  (675)
  (685 "SAGE" "WHO KNOWS WHAT THEY MIGHT WANT WITH THE ARTEFACT,")
  (764 "SAGE" "BUT LIKE ORANGE STUFF HERE'S BREATH, IT JUST CAN'T BE GOOD.")
  )

("warrior-introduction"
  (24 "WARRIOR" "OHH... MY ACHING HEAD.")
  (128)
  (137 "DAXTER" "I DOUBT THAT'S ONE OF YOUR VITAL ORGANS!")
  (212 "DAXTER" "WALK IT OFF, TOUGH GUY!")
  (264 "WARRIOR" "OH, SURE, I WAS TOUGH ONCE.")
  (337 "WARRIOR" "MAYBE EVEN THE TOUGHEST OF THEM ALL.")
  (402 "WARRIOR" "I SINGLE-HANDEDLY DEFENDED THIS VILLAGE FROM THOSE HORRID CREATURES FOR ALMOST A YEAR!")
  (594 :offscreen "WARRIOR" "THEN THAT HORRIBLE MONSTER ARRIVED AND COMMENCED THE BOULDER BOMBARDMENT.")
  (760 :offscreen "WARRIOR" "SO, FULL OF VALOUR, ARMOR SHINING IN THE SUN...")
  (928 "WARRIOR" "I CLIMBED THE HILL TO TAKE HIM ON...!")
  (1033)
  (1044 "WARRIOR" "BUT HE POUNDED ME LIKE ONE TENDERIZES A YAKOW STEAK.")
  (1172)
  (1178 "DAXTER" "HAVE YOU TRIED ATTACKING HIM WITH YOUR MELODRAMA?")
  (1255 "DAXTER" "'CAUSE IT'S KILLIN' ME!")
  (1303)
  (1310 :offscreen "WARRIOR" "AFTER MY LAST STUNNING FAILURE,")
  (1395 :offscreen "WARRIOR" "HE SEALED THE PASSAGEWAY TO HIS ROOST WITH A 30-TON BOULDER,")
  (1515 :offscreen "WARRIOR" "LEAVING NO WAY FOR ANYONE TO CHALLENGE HIM AGAIN.")
  (1640)
  (1669 "WARRIOR" "SO, OUR SAGE, A MASTER OF BLUE ECO AND A MECHANICAL GENIUS, DEVISED A MACHINE")
  (1905 "WARRIOR" "CAPABLE OF LIFTING THE BOULDER OUT OF THE WAY...!")
  (2030)
  (2040 "WARRIOR" "BUT ALAS, HE DISAPPEARED BEFORE WE HAD A CHANCE TO TURN IT ON.")
  (2200)
  (2222 "WARRIOR" "AND HE TOOK ALL OF HIS POWER CELLS WITH HIM.")
  (2330)
  (2360 :offscreen "WARRIOR" "AT LEAST I WAS ABLE TO PULL ENOUGH PONTOONS OUT OF OUR BRIDGE TO PREVENT")
  (2465 :offscreen "WARRIOR" "THAT MONSTER FROM COMING DOWN HERE TO DO ME HARM.")
  (2561)
  (2566 "DAXTER" "YEAH, GOOD, GOOD JOB, TOUGH GUY. BUT, UM...")
  (2659 "DAXTER" "WE'RE GONNA NEED YOU TO, UH... PUT 'EM BACK, AND STUFF.")
  (2766)
  (2770 "WARRIOR" "OH, SURE! AND SEAL MY DOOM?")
  (2880 "WARRIOR" "(SIGHS)")
  (2943)
  (2949 "WARRIOR" "ALRIGHT. FINE.")
  (3036 "WARRIOR" "BRING ME 90 PRECURSOR ORBS AND I'LL LET THE PONTOONS LOOSE.")
  (3173)
  (3197 "WARRIOR" "BUT I'M NOT GOING TO FIGHT THAT MONSTER AGAIN!")
  )

;; -----------------
;; swamp
;; -----------------

("billy-introduction"
  (6 "BILLY" "HOWDY, FRIENDS! ENJOYIN' MY BEAUTIFUL SWAMP?")
  (123 "BILLY" "I OWN THESE HERE PARTS. EVERYTHING THAT DOESN'T SINK INTO THE MUD, THAT IS! HA HA HA...")
  (349)
  (369 "DAXTER" "JUDGING BY THE SMELL, I'D WAGER YOUR BATHTUB SANK IN THE MUD LONG AGO.")
  (497)
  (519 "BILLY" "WHAT'S A BATHTUB? ANYWAY I GOT BIGGER PROBLEMS NOW...")
  (680)
  (691 "BILLY" "SEEMS SOME NASTY LURKER VARMINTS ARE GROUSIN' ABOUTS,")
  (798 "BILLY" "SNATCHIN' EVERYTHING THEY CAN GET THEIR GRUBBY LITTLE PAWS ON.")
  (910 "BILLY" "AND SCARIN' AWAY MY PET HIPHOG, FARTHY.")
  (1017)
  (1021 "BILLY" "HE'S BEEN MISSIN' FOR NIGH ON TO A COON'S AGE.")
  (1133)
  (1136 :offscreen "BILLY" "I'VE BEEN PUTTIN' OUT HIS FAVOURITE SNACK, BUT THOSE ORNERY SWAMP RATS KEEP STEALIN' EM!")
  (1318 :offscreen "BILLY" "IF YOU COULD KEEP THOSE PESKY CRITTERS AWAY LONG ENOUGH,")
  (1408 :offscreen "BILLY" "I JUST KNOW FARTHY WOULD SMELL THEM VITTLES AND COME BACK!")
  (1519)
  (1530 "BILLY" "WILL YA HELP ME OUT?")
  )

("sksp0153" :hint #x361
  (0 "DAXTER" "HEY, THAT MUST BE THE PRECURSOR ARTEFACT THE LURKERS ARE AFTER!")
  (175 "DAXTER" "IT LOOKS LIKE A GIANT ROBOT ARM!")
  )

;; -----------------
;; rolling
;; -----------------

;; -----------------
;; sunken
;; -----------------

("sksp0135" :hint #x34f (0 "DAXTER" "THAT WATER LOOKS DANGEROUS WHEN IT CHANGES COLOUR!"))
("sksp0136" :hint #x350 (0 "DAXTER" "YOU GOTTA GET OUT OF THE WATER BEFORE IT CHANGES COLOUR!"))

;; -----------------
;; ogre
;; -----------------

;; -----------------
;; village3
;; -----------------

("minershort-introduction-gnawers"
  (5 "GORDY" "WHY DON'T YOU TWO MAKE YOURSELVES USEFUL?")
  (89 "GORDY" "LURKERS HAVE BEEN EXCAVATIN' THE DARK CAVES OVER THERE.")
  (191 :offscreen "GORDY" "SEEMS THEY'RE LOOKIN' FOR PRECURSOR ARTEFACTS.")
  (265)
  (271 :offscreen "GORDY" "THEY CAN HAVE THE ARTEFACTS, FOR ALL I CARE.")
  (357)
  (360 :offscreen "WILLARD" "FOR ALL WE CARE!")
  (441)
  (444 "GORDY" "WILLARD, FEED YOUR BIRD.")
  (490)
  (496 "GORDY" "ALL I CARE ABOUT ARE GEMS!")
  (566 "GORDY" "BUT I AIN'T GONNA BE ABLE TO GET THE CAVE'S GEMS")
  (625 "GORDY" "BECAUSE WHEN THEY'RE THROUGH, THEY'RE GONNA COLLAPSE THE PLACE!")
  (715)
  (721 "GORDY" "IF YOU TAKE OUT THE LURKERS CHEWIN' AT THE SUPPORT BEAMS,")
  (827 "GORDY" "YOU COULD SAVE THE CAVE FOR ME.")
  (875)
  (884 "GORDY" "NOW BEAT IT!")
  )

("sage-village3-introduction"
  (6 "SAGE" "OW! I ALWAYS WONDER IF I'M LOSING BODY PARTS IN THOSE THINGS!")
  (153)
  (183 "SAGE" "HOLY YAKOW! THE RED SAGE'S LAB LOOKS WORSE THAN THE BLUE'S!")
  (321)
  (321 "KEIRA" "WELL, IT DEFINITELY LOOKS AS THOUGH THERE'S BEEN A STRUGGLE HERE.")
  (418)
  (441 "OLD MAN" "HA HA HA HA HA!")
  (500)
  (528 "OLD MAN" "I'D HARDLY CALL IT \"STRUGGLE.\"")
  (618 "OLD MAN" "WOULD YOU, DEAR SISTER?")
  (672 "WOMAN" "CERTAINLY NOT. THE RED SAGE GAVE UP WITH SO LITTLE EFFORT.")
  (800)
  (805 "WOMAN" "NO FUN AT ALL.")
  (860)
  (884 "SAGE" "GOL? IS THAT YOU?")
  (965)
  (969 "SAGE" "YOU'VE FINALLY GONE OFF THE DEEP END, EH?")
  (1060 "SAGE" "AND, MAIA! I TOLD YOU THE DARK ECO WOULD AFFECT YOU BOTH!")
  (1180 "SAGE" "HNG, NOBODY EVER LISTENS TO OLD SAMOS...")
  (1265)
  (1282 "SAGE" "WHAT HAVE YOU TWO DONE WITH THE BLUE AND RED SAGES?")
  (1372 "GOL" "DON'T WORRY ABOUT YOUR COLOURFUL FRIENDS, YOU OLD FOOL.")
  (1516 "GOL" "THEY'RE PERFECTLY SAFE IN OUR CITADEL. OUR SPECIAL GUESTS.")
  (1680 "MAIA" "THEY HAVE GRACIOUSLY AGREED TO HELP US ON A LITTLE PROJECT.")
  (1813)
  (1828 "GOL" "YOU WERE WRONG, SAMOS. DARK ECO CAN BE CONTROLLED!")
  (1990)
  (1996 "GOL" "WE'VE LEARNED ITS SECRETS, AND NOW WE CAN RESHAPE THE WORLD TO OUR LIKING.")
  (2212)
  (2223 "SAGE" "YOU CAN'T CONTROL DARK ECO BY ITSELF! EVEN THE PRECURSORS COULDN'T-")
  (2357 "MAIA" "UNTIL NOW, WE'VE HAD TO SCRAPE BY WITH WHAT LITTLE DARK ECO")
  (2452 "MAIA" "WE COULD FIND NEAR THE SURFACE.")
  (2508)
  (2520 "MAIA" "BUT SOON, WE WILL HAVE ACCESS TO THE VAST STORES")
  (2611 "MAIA" "OF DARK ECO HIDDEN DEEP UNDERGROUND.")
  (2715 "SAGE" "NOT THE SILOS!")
  (2758)
  (2768 "GOL" "YES, THE SILOS!")
  (2841 "GOL" "THEY WILL BE OPENED, AND ALL THE DARK ECO IN THE WORLD WILL BE OURS!")
  (3028)
  (3034 "SAGE" "BUT THAT'S IMPOSSIBLE! ONLY A PRECURSOR ROBOT-")
  (3128 "MAIA" "OH, DON'T LOOK SO UPSET, SAMOS.")
  (3210 "MAIA" "WE'VE GOT BIG PLANS FOR YOU.")
  (3300)
  (3303 :offscreen "MAIA" "AH HA HA HA HA HA HA! AHH...")
  (3460)
  (3495 "DAXTER" "WAIT A MINUTE!")
  (3538)
  (3541 "DAXTER" "THAT WAS GOL?")
  (3586)
  (3595 "DAXTER" "THE SAME GOL WHO'S SUPPOSED TO CHANGE ME BACK?")
  (3690 "DAXTER" "GOL IS THE GUY TRYING TO KILL US?!")
  (3772)
  (3785 "DAXTER" "I'M DOOMED.")
  (3822)
  (3828 "SAGE" "WE MAY ALL BE DOOMED.")
  (3897)
  (3903 "SAGE" "IF THEY OPEN THE SILOS, THE DARK ECO WILL")
  (3995 "SAGE" "TWIST AND DESTROY EVERYTHING IT TOUCHES!")
  (4080 "SAGE" "WE SIMPLY MUST GET TO THEIR CITADEL, TO STOP THEM!")
  (4189)
  (4192 "KEIRA" "THE FASTEST WAY THERE IS THROUGH THE LAVA TUBE")
  (4276 "KEIRA" "AT THE BOTTOM OF THIS CRATER.")
  (4316)
  (4324 "KEIRA" "A FEW MORE POWER CELLS, AND YOUR ZOOMER'S HEAT SHIELD")
  (4398 "KEIRA" "SHOULD GET YOU ACROSS THE LAVA SAFELY.")
  (4460)
  (4464 "SAGE" "ALL RIGHT, MY BOY. YOU KNOW WHAT TO DO.")
  (4545 "SAGE" "TAKE THE FLEABAG AND GO ROUND UP MORE POWER CELLS.")
  (4664)
  )

("asstv103" :hint #x452
  (0 "KEIRA" "DON'T FORGET TO TURN ON THE TELEPORT GATE TO LET US THROUGH.")
  (160 "KEIRA" "YOU'VE GOT TO GO INTO THE RED SAGE'S LAB")
  (280 "KEIRA" "IN THE CENTRE OF THE VOLCANIC CRATER TO TURN IT ON.")
  (450 "KEIRA" "WE CAN'T COME THROUGH UNTIL IT'S BACK ONLINE.")
  )

;; -----------------
;; snowy
;; -----------------

;; -----------------
;; spidercave
;; -----------------

;; -----------------
;; lavatube
;; -----------------

;; -----------------
;; citadel
;; -----------------

("green-sagecage-introduction"
  (128 "SAGE" "IT'S ABOUT TIME YOU TWO DECIDED TO SHOW UP!")
  (207 "DAXTER" "NICE TO SEE YOU TOO!")
  (269)
  (275 "DAXTER" "DO THEY HAVE YOU MOPPING THE FLOORS NOW?")
  (343 "SAGE" "THERE'S NO TIME FOR JOKES, DAXTER. GOL AND MAIA KIDNAPPED US")
  (477 "SAGE" "TO SAP OUR ENERGIES TO POWER THEIR ABOMINABLE MACHINE.")
  (574)
  (583 :offscreen "SAGE" "IT APPEARS THEY HAVE COMBINED THE FUNCTIONAL REMAINS OF A PRECURSOR ROBOT")
  (709 :offscreen "SAGE" "WITH SCAVENGED ARTEFACTS FROM ACROSS THE LAND.")
  (800)
  (816 :offscreen "SAGE" "THEN THEY ADDED A FEW DIABOLICAL ADDITIONS OF THEIR OWN,")
  (926 :offscreen "SAGE" "CREATING THE ONE THING CAPABLE OF OPENING THE DARK ECO SILOS.")
  (1060 "SAGE" "IF YOU CAN FREE THE FOUR OF US, WE CAN USE OUR COMBINED POWERS")
  (1180 "SAGE" "TO BREAK THE FORCE SHIELD SURROUNDING THE ROBOT")
  (1265 "SAGE" "BEFORE THEY USE IT TO DESTROY THE WORLD.")
  )

;; -----------------
;; finalboss
;; -----------------

;; -----------------
;; title
;; -----------------

;; -----------------
;; uncategorized
;; -----------------

