(language-id 2)

;; -----------------
;; intro
;; -----------------

;; -----------------
;; sidekick
;; -----------------

;; -----------------
;; village1
;; -----------------

("assistant-introduction-blue-eco-switch"
  (23 "DAXTER" "HEY, BABY. WOLLEN WIR NICHT ZUSAMMEN EIN PAAR RUNDEN AUF DIESEM A-GRAV ZOOMER DREHEN?")
  (175)
  (200 "KEIRA" "REGEL NUMMER EINS: ICH VERABREDE MICH NICHT MIT TIEREN.")
  (308)
  (312 "DAXTER" "ACH, DU WEISST JA GAR NICHT, WAS DIR ENTGEHT, EH HEH HEH...")
  (430)
  (505 "KEIRA" "HÖR ZU, WENN IHR BESCHÄFTIGUNG BRAUCHT, MEIN VATER HAT VON EINEM")
  (635 "KEIRA" "ALTEN PRECURSOR-ROHRSYSTEM TIEF UNTER DER ERDE ERZÄHLT.")
  (739)
  (742 :offscreen "KEIRA" "AM ENDE VON EINIGEN ROHREN SIND ÖFFNUNGEN, AUS DENEN DAS ECO HERAUSSTRÖMT,")
  (855 :offscreen "KEIRA" "ANDERE SIND VERRIEGELT, SODASS DAS ECO EINGESCHLOSSEN IST.")
  (945)
  (954 "KEIRA" "ES MUSS MÖGLICH SEIN, DIE VERRIEGELTEN ÖFFNUNGEN AUFZUMACHEN.")
  (1052 :offscreen "KEIRA" "ICH HAB RAUSGEFUNDEN, DASS EIN TEIL DER ROHRE UNTER DEM VERBOTENEN TEMPEL LIEGT.")
  (1165 "KEIRA" "SUCHT DORT MAL NACH EINEM SCHALTER.")
  (1246)
  )

("assistant-introduction-race-bike"
  (9 "DAXTER" "HEY BABY, WAS IST'N DAS HIER?")
  (78 "KEIRA" "SEI VORSICHTIG! ICH VERSUCHE, HERAUSZUFINDEN, WIE MAN DEN ZOOMER MITHILFE DER")
  (205 "KEIRA" "PRECURSOR-TRANS-PADS TRANSPORTIEREN KANN.")
  (308)
  (312 :offscreen "KEIRA" "WENN IHR AN EINES DIESER PADS KOMMT, KANN ICH DIE POSITION EURES KOMMUNIKATORS ERMITTELN")
  (453 :offscreen "KEIRA" "UND EUCH DEN ZOOMER SCHICKEN!")
  (508 "KEIRA" "HALTET AUF DER NEBELINSEL AUSSCHAU NACH SOLCHEN TRANS-PADS, ODER SONSTWO!")
  (665)
  )

("assistant-reminder-1-blue-eco-switch"
  (23 "KEIRA" "WENN IHR IM VERBOTENEN PRECURSOR-TEMPEL SUCHT, SCHAFFT IHR ES BESTIMMT,")
  (160 "KEIRA" "DIE VERSCHLOSSENE BLAUE ECO-ÖFFNUNG AM WÄCHTERSTRAND AUFZUMACHEN.")
  (295)
  )

("assistant-reminder-1-generic"
  (25 "KEIRA" "HEY, JUNGS! SAMMELT WEITER ENERGIEZELLEN, IHR BRAUCHT SIE, UM WEITER NACH NORDEN ZU REISEN.")
  )

("assistant-reminder-1-race-bike"
  (25 "KEIRA" "ICH WEISS JETZT, WIE MAN DIE TRANS-PADS BENUTZT.")
  (106 "KEIRA" "GEHT ZUR NEBELINSEL UND ICH SCHICKE EUCH DEN ZOOMER RÜBER.")
  (229)
  )

("explorer-introduction"
  (23 "JAK'S ONKEL" "OH, HALLO, MEIN LIEBER JUNGE. DU KOMMST MIR JETZT ABER GERADE EIN WENIG UNGELEGEN.")
  (197 "JAKS ONKEL" "WEISST DU, ICH WOLLTE SCHON GESTERN ZU MEINER REISE AUFBRECHEN,")
  (300 "JAKS ONKEL" "ABER ICH HABE SCHEINBAR ZU WENIG PRECURSOR-ORBS.")
  (426)
  (430 "JAKS ONKEL" "ICH HÄTTE SCHWÖREN KÖNNEN, DASS ICH 90 STÜCK HATTE.")
  (538 "JAKS ONKEL" "ABER ICH VERMUTE, DEIN JUNGER FREUND, DIESER LÄSTIGE, FURCHTBAR HÄSSLICHE KLEINE KERL HIER,")
  (716 "JAKS ONKEL" "HAT MIR AUS JUX GERADE EIN PAAR ENTWENDET.")
  (829)
  (865 "JAKS ONKEL" "NUN DENN, WÜRDEST DU DEINEM LIEBEN ALTEN ONKEL FREUNDLICHERWEISE 90 PRECURSOR-ORBS LEIHEN,")
  (1043 "JAKS ONKEL" "DAMIT ER AUFBRECHEN KANN? ICH BIETE DIR EINE ENERGIEZELLE DAFÜR.")
  )

("explorer-reminder-1"
  (25 "JAKS ONKEL" "WAS? SO VIELE HAST DU NICHT? HARUMPH!")
  (148 "JAKS ONKEL" "TJA, MIT WENIGER ALS 90 PRECURSOR-ORBS KANN ICH NICHT AUFBRECHEN, MEIN JUNGE.")
  (370)
  )

("explorer-reminder-2"
  (33 "JAKS ONKEL" "NUN JA, 90 PRECURSOR-OBS FÜR EINE ENERGIEZELLE SIND EIN AUSGESPROCHEN FAIRES GESCHÄFT.")
  )

("explorer-resolution"
  (28 "JAKS ONKEL" "AH, IHR WOLLT DAS GESCHÄFT ALSO DOCH MACHEN? PRÄCHTIG, AUSGESPROCHEN PRÄCHTIG!")
  (179 "JAKS ONKEL" "HEY, HABT IHR DIE VEREINBARTEN PRECURSOR-ORBS?")
  (310)
  (324 "JAKS ONKEL" "HM, HOFFENTLICH VERGEUDET IHR DIESE SCHWER VERDIENTE ENERGIEZELLE NICHT. MACHTS GUT, CIAO CIAO, BYE BYE!")
  )

("farmer-introduction"
  (1 "FARMER" "MUSS DIE YAKOWS MELKEN, MUSS DIE YAKOWS MELKEN...")
  (113 "FARMER" "OH! IHR SEID'S... ICH RUH MICH NUR EIN BISSCHEN AUS. HAB DEN GANZEN TAG VERSUCHT, DIESE STREITLUSTIGEN KÜHE")
  (317 "FARMER" "ZURÜCK IN DEN PFERCH ZU KRIEGEN! EIN PAAR SELTSAME TYPEN WOLLTEN SIE SCHON STEHLEN.")
  (454)
  (456 "FARMER" "KÖNNTET IHR WOHL EINEM ALTEN MANN HELFEN UND SIE IN DEN PFERCH BRINGEN?")
  )

("farmer-reminder-1"
  (0 "FARMER" "HEY! MEINE YAKOWS SIND JA IMMER NOCH DRAUSSEN! SEID BITTE SO NETT UND HOLT SIE JETZT REIN.")
  )

("farmer-reminder-2"
  (0 "FARMER" "DIESE BLÖDEN YAKOWS STROLLEN IMMER NOCH RUM!")
  (85 "FARMER" "JETZT BRINGT SIE DOCH ENDLICH MAL IN DEN PFERCH!")
  )

("farmer-resolution"
  (0 "FARMER" "AH, GUT GEMACHT, MEIN JUNGE. DIE VERLAUSTEN VIECHER SIND JETZT IM PFERCH.")
  (134 "FARMER" "NUN KANN ICH BERUHIGT SCHLAFEN. HIER IST EINE ENERGIEZELLE FÜR DEINE MÜHE.")
  (340)
  )

("sage-introduction-misty-cannon"
  (50 "SAMOS" "OH, IHR SEID'S, DIE GROSSEN BEZWINGER.")
  (136 "SAMOS" "GUT, ICH HABE DA ETWAS ERNSTES MIT EUCH ZU BESPRECHEN.")
  (258)
  (261 :offscreen "SAMOS" "ES SCHEINT, ALS SEIEN DIE LURKER AUF DER NEBELINSEL ENORM AKTIV.")
  (375)
  (380 :offscreen "SAMOS" "VON MEINEM BEOBACHTUNGSTURM AUS KANN ICH ERKENNEN, WIE SIE DIE PRECURSOR-ECO-STATION BOMBARDIEREN.")
  (525)
  (528 "SAMOS" "FALLS SIE SIE ÖFFNEN UND DAS DUNKLE ECO FREISETZEN, WERDEN WIR AM ENDE")
  (663 "SAMOS" "NOCH SO HERUMLAUFEN WIE DIESE HÄSSLICHE KLEINE FLOHQUASTE HIER.")
  (788)
  (807 "SAMOS" "JAK, WIR MÜSSEN DEINE... TAUGLICHKEIT PRÜFEN.")
  (920 "SAMOS" "BRING DEN FISCHER DAZU, DIR SEIN BOOT ZU LEIHEN UND FAHR ZUR NEBELINSEL.")
  (1018 "SAMOS" "DU MUSST AUF DIE SPITZE DER PRECURSOR-ECO-STATION UND DIE VERMALEDEITE KANONE AUSSER GEFECHT SETZEN.")
  (1171)
  (1177 "DAXTER" "UND WAS... IST MIT MIR?")
  (1232)
  (1235 "SAMOS" "DU? DU KANNST MEINE FUSSBÖDEN WISCHEN, IN LETZTER ZEIT GLÄNZEN SIE NICHT MEHR SO SCHÖN.")
  )

("sage-reminder-1-ecorocks"
  (45 "SAMOS" "NA, IHR SEID MIR JA ZWEI TOLLE ABENTEURER!")
  (132 "SAMOS" "SCHON ZURÜCK UND HABT NOCH NICHT EINMAL MEINE BLOCKIERTEN ECO-ERNTER IN ORDNUNG GEBRACHT!")
  (244)
  (270 :offscreen "SAMOS" "SIE SIND AM ANDEREN ENDE DES STRANDES, JUNGS.")
  (365)
  (370 :offscreen "SAMOS" "JETZT...")
  (400 :offscreen "SAMOS" "MACHT ENDLICH!")
  )

("sage-reminder-1-generic"
  (54 "SAMOS" "WAS MACHT IHR DENN HIER? IHR SOLLT ENERGIEZELLEN SAMMELN!")
  (178)
  (181 "SAMOS" "LASST MICH IN FRIEDEN, BIS IHR GENUG HABT!")
  )

("sage-reminder-1-misty-cannon"
  (24 "SAMOS" "DAS BOMBARDMENT WIRD SCHLIMMER!")
  (86 :offscreen "SAMOS" "SUCH DEN FISCHER IM DSCHUNGEL, HOL DIR DIE ERLAUBNIS, SEIN BOOT ZU BENUTZEN")
  (200 :offscreen "SAMOS" "UND FAHR ZUR NEBELINSEL, UM ENDLICH DIE KANONE ZU STOPPEN.")
  (317)
  (320 "SAMOS" "UND DU, DAXTER. FANG AN, AUFZUWISCHEN. SIEHT JA SCHLIMM AUS HIER!")
  )

("sage-reminder-2-generic"
  (27 "SAMOS" "IHR ZWEI VERSTEHT DEN ERNST DER LAGE WOHL IMMER NOCH NICHT.")
  (137 "SAMOS" "HIER GEHT ES UM MEHR ALS NUR EINEN DUMMEN JUNGENSTREICH. HIER GEHT UM DAS LEBEN, SO, WIE WIR ES KENNEN.")
  (320)
  (323 "SAMOS" "JETZT MACHT EUCH ENDLICH AUF UND STELLT EUCH EUREM SCHICKSAL.")
  (455)
  )

;; -----------------
;; oracle
;; -----------------

;; -----------------
;; beach
;; -----------------

("bird-lady-beach-resolution"
  (30 "VOGEL-BEOBACHTERIN" "OH, JE, HOFFENTLICH GEHTS DEM ARMEN KLEINEN GUT. HIER, EINE ENERGIEZELLE FÜR EUREN MUT.")
  (243)
  (306 "FLUT FLUT" "MAMA!")
  (354)
  (406 "FLUT FLUT" "MAMA!")
  (430 "DAXTER" "OH, NEIN! NEIN! NEIN! NEIN! NEIN!")
  (533)
  (535 "VOGEL-BEOBACHTERIN" "SCHAUT MAL, IST DAS NICHT SÜSS? ES GLAUBT, DU WÄRST SEINE MAMA.")
  (696)
  (699 "DAXTER" "HÄ? ICH BIN NICHT DEINE MAMA! HAB ICH ETWA FEDERN?")
  (803)
  (807 "VOGEL-BEOBACHTERIN" "AH, LIEBE AUF DEN ERSTEN BLICK! OH...")
  (936)
  (939 "VOGEL-BEOBACHTERIN" "HÖRT MAL, JUNGS, ICH NEHME DAS KLEINE KÜKEN MIT INS DORF UND KÜMMERE MICH ZUSAMMEN MIT DEM WEISEN DARUM.")
  )

("bird-lady-introduction"
  (125 "VOGEL-BEOBACHTERIN" "ACH, HERRJE, SO EIN FURCHTBAR KRANKES VÖGELCHEN.")
  (245)
  (251 "DAXTER" "HAH! SIEHST AUCH NICHT GERADE GESUND AUS, LADY!")
  (326)
  (331 "VOGEL-BEOBACHTERIN" "OH, ENTSCHULDIGUNG. ICH DACHTE, DU WÄRST EIN ORANGEGEFLECKTER BAUCHRINGFRING.")
  (454)
  (457 "VOGEL-BEOBACHTERIN" "WISST IHR, GESTERN HABEN EIN PAAR SCHRECKLICH BÖSE WESEN HIER AM STRAND EINE FLUT-FLUT-MUTTER GEFANGEN.")
  (648)
  (654 :offscreen "VOGEL-BEOBACHTERIN" "JETZT LIEGT DIESES ARME KLEINE WAISENEI IM NEST OBEN AUF DER KLIPPE UND ICH KOMME NICHT DRAN.")
  (855 :offscreen "VOGEL-BEOBACHTERIN" "KÖNNT IHR DA DRAUFKLETTERN UND ES RUNTERSCHUBSEN? ICH HABE UNTEN ETWAS HEU HINGELEGT, UM ES AUFZUFANGEN.")
  (1041)
  (1044 "VOGEL-BEOBACHTERIN" "TUT EINER ALTEN FRAU EINEN GEFALLEN UND IHR BEKOMMT EINE ENERGIEZELLE DAFÜR.")
  (1198)
  )

("bird-lady-reminder-1"
  (56 "VOGEL-BEOBACHTERIN" "OH, HALLO NOCHMAL. HABT IHR JUNGS DAS BLAUE EI AUF DER KLIPPE GEFUNDEN?")
  (208)
  (211 "VOGEL-BEOBACHTERIN" "SCHUBST ES RUNTER UND IHR BEKOMMT EINE ENERGIEZELLE!")
  (348)
  )

("bird-lady-reminder-2"
  (58 "VOGEL-BEOBACHTERIN" "SEID IHR JUNGS ETWA IMMER NOCH HIER? HA, HA, HA!")
  (170)
  (174 "VOGEL-BEOBACHTERIN" "DEM ARMEN KEINEN BLAUEN EI AUF DEM ABHANG IST BESTIMMT SCHRECKLICH KALT.")
  (313)
  (316 "VOGEL-BEOBACHTERIN" "SCHUBST ES VON DER KLIPPE RUNTER UND RETTET ES, DAFÜR BEKOMMT IHR EINE ENERGIEZELLE!")
  )

("mayor-introduction"
  (31 "BÜRGERMEISTER" "OH... (MUTTERS) JETZT SAGT MIR BLOSS NICHT, DASS IHR ZWEI AUCH EIN PROBLEM HABT!")
  (171)
  (174 "BÜRGERMEISTER" "ERST WERDEN IN DER NÄHE DES DORFES GESICHTET UND JETZT DAS!")
  (313)
  (320 "BÜRGERMEISTER" "SEHT IHR DIE WINDMÜHLENFLÜGEL? DA OBEN, JUNGS, JA? DIE STEHEN STILL,")
  (479 "BÜRGERMEISTER" "DAS BEDEUTET, IM DORF GIBTS KEINEN STROM!")
  (569)
  (578 "BÜRGERMEISTER" "DER ECO-STRAHL AUS DEM DSCHUNGEL-TEMPEL IST UNTERBROCHEN WORDEN, JUNGS")
  (685)
  (689 "BÜRGERMEISTER" "UND NIEMAND TRAUT SICH, NACHZUSEHEN, WAS PASSIERT IST!")
  (850)
  (864 "DAXTER" "IST DIE RECHNUNG BEZAHLT?")
  (915)
  (917 "BÜRGERMEISTER" "JA? HMM, OH, DU BIST JA WITZIG.")
  (1071)
  (1074 "BÜRGERMEISTER" "WÜRDET IHR ZWEI DEN ECO-STRAHL REPARIEREN? FÜR EINE ENERGIEZELLE?")
  (1262 "BÜRGERMEISTER" "OH, NOCH ETWAS...")
  (1346 "BÜRGERMEISTER" "IHR ZWEI WOLLT NICHT ZUFÄLLIG EINE KLEINIGKEIT FÜR MEINE KAMPAGNE ZU MEINER WIEDERWAHL SPENDEN?")
  (1551 "BÜRGERMEISTER" "DAS WÄRE MIR GLATT NOCH EINE ENERGIEZELLE WERT!")
  (1668)
  (1671 "BÜRGERMEISTER" "DAS MINIMUM FÜR EINE SPENDE BETRÄGT, ÄHM, JA, BESCHEIDENE 90 PRECURSOR-ORBS!")
  (1797 "BÜRGERMEISTER" "90 PRECURSOR ORBS.")
  )

("mayor-reminder-beams"
  (25 "BÜRGERMEISTER" "SCHON ZURÜCK? UND OHNE DIE ECO-STRAHLEN ZU REPARIEREN?")
  (157 "BÜRGERMEISTER" "(SCHLUCHZT) EUER DORF BRAUCHT EUCH, JUNGS!")
  )

("mayor-reminder-donation"
  (26 "BÜRGERMEISTER" "AH, HERE TO MAKE A DONATION TO MY CAMPAIGN, OH HO HO HO.")
  (159 "BÜRGERMEISTER" "90 PRECURSOR ORBS BUYS YOU A POWER CELL, THANK YOU.")
  )

("mayor-resolution-beams"
  (28 "BÜRGERMEISTER" "OH HO HO, WAS FÜR EIN WUNDERVOLLER ANBLICK! ICH DANKE EUCH!")
  (190 "BÜRGERMEISTER" "UND DAS GANZE DORF WIRD MIR DANKEN -")
  (280 "BÜRGERMEISTER" "OH, JUNGS, DANK EUCH HABEN WIR WIEDER STROM UND MEINE WIEDERWAHL IST GESICHERT!")
  (472)
  (475 "BÜRGERMEISTER" "UND DAFÜR, MEIN JUNGE, HAST DU DIR EINE ENERGIEZELLE VERDIENT!")
  )

("mayor-resolution-donation"
  (28 "BÜRGERMEISTER" "IHR WOLLT ALSO ETWAS SPENDEN? GUT... HOFFENTLICH EIN SCHÖNES SÜMMCHEN!")
  (219)
  (220 "BÜRGERMEISTER" "JUHU! OHHH, DAS IST EINE GROSSZÜGIGE SPENDE!")
  (350 "BÜRGERMEISTER" "ICH-ICH-ICH HOFFE NUR, D-D-DA-DASS DIESE ENERGIEZELLE EUREN EINSATZ GEBÜHREND BELOHNT!")
  )

("sculptor-introduction"
  (30 "BILDHAUER" "HEY... DU HAARIGER KLEINER KUMPEL!")
  (154)
  (161 "BILDHAUER" "OH... ICH DACHTE, DU WÄRST MEINE MUSE.")
  (282)
  (285 "DAXTER" "DEINE WAS?")
  (334)
  (343 "BILDHAUER" "HAST DU NOCH NIE EINE MUSE GESEHEN?")
  (430)
  (434 "BILDHAUER" "DAS IST EINE KLEINES LEUCHTENDES EICHHÖRNCHEN, SO GROSS WIE DU, SEHR MUTIG UND IMMER GUT DRAUF!")
  (622)
  (632 "DAXTER" "OH, JETZT KAPIER ICH! WIE EIN KUMPELCHEN, HÄ?")
  (757)
  (763 "BILDHAUER" "ALSO, ES IST SO: OHNE MEINE MUSE KANN ICH NICHT BILDHAUERN.")
  (920)
  (923 "BILDHAUER" "ABER WENN SIE DA IST, SEHE ICH NUR SCHÖNHEIT IN ALLEN DINGEN, WISST IHR?")
  (1087)
  (1091 "BILDHAUER" "IM MOMENT KÖNNTE ICH MICH NICHT MAL AUS 'NER KISTE RAUSMEISSELN.")
  (1182)
  (1191 :offscreen "BILDHAUER" "ICH GLAUBE, SIE IST ZUR NEBELINSEL GELAUFEN.")
  (1278)
  (1281 "BILDHAUER" "ACH, ICH HOFFE BLOSS, IHR GEHTS GUT.")
  (1370)
  (1376 "BILDHAUER" "EINE ENERGIEZELLE, WENN IHR SIE ZURÜCKBRINGT!")
  (1441)
  (1467 "DAXTER" "MOMENT MAL! WIR WERDEN AUF KEINEN FALL ZURÜCK ZUR NEBELINSEL GEHEN!")
  (1646)
  (1649 "DAXTER" "ODER DOCH?")
  )

("sculptor-reminder-1"
  (27 "BILDHAUER" "OH, HEY, LEUTE! HABT IHR MEINE MUSE SCHON GEFUNDEN?")
  (169)
  )

("sculptor-resolution"
  (90 "BILDHAUER" "OH, MEINE MUSE! IHR HABT SIE GERETTET! OH, MANN, IHR SEID DIE GRÖSSTEN!")
  (230 "BILDHAUER" "HIER, NEHMT DIESE ENERGIEZELLE, ICH BRAUCHE SIE NICHT MEHR, MEINE INSPIRATION IST WIEDER DA!")
  )

;; -----------------
;; jungle
;; -----------------

("fisher-accept"
  (0 :offscreen "FISCHER" "MUSST DREI SACHEN WISSEN, WENN DU FISCHST. ERSTENS: KANNST ZWEI ARTEN VON FISCHEN FANGEN, EINPFÜNDER UND FÜNFPFÜNDER.")
  (275 :offscreen "FISCHER" "ZWEITENS: LÄSSTE 20 PFUND VON DEN GUTEN FISCHEN ENTWISCHEN, DU, DANN NEHM ICH DIR DAS NETZ WEG.")
  (470 :offscreen "FISCHER" "DRITTENS GIBTS GIFTIGE AALE IM FLUSS, AUCH WENN DU NUR EINEN VON DEN BURSCHEN ERWISCHST, VERGIFTET ER DEN GANZEN FANG!")
  )

("fisher-introduction"
  (0 "DAXTER" "WAS HAST'N DA IM KORB?")
  (50 "FISCHER" "ACH, NICHT DER REDE WERT.")
  (107)
  (110 "FISCHER" "DIE MONSTER DA AM OZEAN HABEN EIN STÜCK AUS MEINEM BOOT RAUSGEBISSEN")
  (210)
  (212 "FISCHER" "UND NUN VERLEIBEN SIE SICH MEINEN FANG EIN!")
  (290)
  (293 "FISCHER" "EGAL, WAS ICH MACHE, ICH FANG HIER IM FLUSS EINFACH KEINEN FISCH MEHR.")
  (419)
  (425 "DAXTER" "UUH, VIELLEICHT IST'S DEIN MUNDGERUCH.")
  (515)
  (525 "FISCHER" "MEINST, DU KANNST DAS BESSER? VERSUCH MAL, MIT 'NEM WINZIGEN NETZ FLUSSFISCHE ZU FANGEN!")
  (665)
  (671 "FISCHER" "KRIEGST 'NE ENERGIEZELLE VON MIR, WENN DU 200 PFUND VON DEN VIECHERN FÄNGST!")
  (808)
  (814 "FISCHER" "UND ICH LASS DICH UND DEN KNIRPS HIER MEIN SCHNELLBOOT BENUTZEN, UM ZUR NEBELINSEL ZU KOMMEN.")
  (955)
  (964 "FISCHER" "NA, WOLLT IHR ES VERSUCHEN?")
  )

("fisher-reject"
  (2 "FISCHER" "NAJA, NUN, WENN IHR ES EUCH ANDERS ÜBERLEGEN TUT, DANN WISST IHR JA, WO IHR MICH FINDET.")
  )

("fisher-reminder-1"
  (6 "FISCHER" "WOLLT'S WOHL MIT DEM FLUSS AUFNEHMEN, WAS?")
  )

("fisher-resolution"
  (0 "FISCHER" "IHR HABT'S GESCHAFFT! HABT 200 PFUND FISCH GEFANGEN!")
  (115)
  (120 "FISCHER" "NICHT SCHLECHT FÜR EIN PAAR LANDRATTEN!")
  (185)
  (199 "FISCHER" "HIER, DIE ENERGIEZELLE. UND IHR KÖNNT EUCH MEIN BOOT VOM DOCK IM DORF HOLEN, WENN IHR ES BRAUCHT!")
  )

;; -----------------
;; misty
;; -----------------

;; -----------------
;; firecanyon
;; -----------------

("assistant-firecanyon-resolution"
  (25 "KEIRA" "SUPER! IHR HABT DIE 20 ENERGIEZELLEN, UM MEINEN HITZESCHILD ZU AKTIVIEREN!")
  (147)
  (150 "KEIRA" "SEID ABER VORSICHTIG, DER SCHILD SCHÜTZT DEN ZOOMER NUR BIS ZU EINER TEMPERATUR VON 500 GRAD.")
  (310 "KEIRA" "ALSO LASST IHN NICHT ZU HEISS LAUFEN.")
  (352)
  (355 :offscreen "KEIRA" "WENN IHR ÜBER GLÜHENDE LAVA FLIEGT, HEIZT IHN DAS GANZ SCHÖN SCHNELL AUF.")
  (462)
  (466 "KEIRA" "WENN IHR 500 GRAD ERREICHT, IST ES AUS!")
  (554)
  (559 "DAXTER" "AUS?! DU MEINST WIE IN \"AUS UND VORBEI\"?!")
  (636)
  (639 "KEIRA" "DER FEUER-CANYON IST SEHR HEISS, ACHTET AUF SPRUNGMÖGLICHKEITEN, UM DEN ABSTAND ZUR LAVA ZU VERGRÖSSERN.")
  (797)
  (800 :offscreen "KEIRA" "ICH HABE AUCH MEHRERE BLAUE KÜHLBALLONS STEIGEN LASSEN, MIT DENEN IHR DIE TEMPERATUR DES SCHILDES SCHNELL SENKEN KÖNNT.")
  (956)
  (962 "KEIRA" "ACH, JA, WENN IHR DURCH DEN CANYON SEID, VERGESST JA NICHT, DAS TELEPORTTOR")
  (1063 "KEIRA" "IM LABOR DES BLAUEN WEISEN ZU AKTIVIEREN. DANN KÖNNEN WIR UNS ZU EUCH HINÜBERTELEPORTIEREN!")
  (1222 "KEIRA" "VIEL GLÜCK!")
  )

;; -----------------
;; swamp
;; -----------------

;; -----------------
;; citadel
;; -----------------

;; -----------------
;; finalboss
;; -----------------

("finalbosscam-white-eco"
  (143 :offscreen "GOL" "HELLES ECO?! ES EXISTIERT ALSO WIRKLICH!")
  (268 :offscreen "MAIA" "SIE DÜRFEN ES NICHT BEKOMMEN!")
  )

("green-sagecage-daxter-sacrifice"
  (0 "DAXTER" "HELLES ECO! DAS KÖNNTE MICH ZURÜCKVERWANDELN, HAH!")
  (114)
  (123 "DAXTER" "ODER... ES KÖNNTE DEN ROBOTER AUFHALTEN.")
  (235)
  (274 "DAXTER" "HMM... WUSCHELIG BLEIBEN ODER DIE WELT RETTEN? MAL NACHDENKEN...")
  (404)
  (437 "DAXTER" "OKAY, NA GUT, DANN RETTEN WIR EBEN DIE WELT, ABER MACHT SCHNELL, BEVOR ICH'S MIR ANDERS ÜBERLEGE!")
  (634)
  )

("green-sagecage-outro-beat-boss-a"
  (165 :offscreen "MAIA" "TU DOCH WAS!")
  (216)
  (596 :offscreen "GOL" "NEEEEIN!")
  )

("green-sagecage-outro-beat-boss-b"
  (522 "SAMOS" "NUN JA, ES SCHEINT, ALS HÄTTE ICH EUCH JUNGS FALSCH EINGESCHÄTZT,")
  (640 "SAMOS" "IHR HABT DOCH DAS ZEUG ZU HELDEN!")
  (745)
  (751 "KEIRA" "OH, DAXTER, JETZT MUSST DU IMMER SO BLEIBEN.")
  (845)
  (847 "DAXTER" "MACH DIR KEINE SORGEN UM MICH, SÜSSE. DU WEISST DOCH, ES HEISST: \"KLEINER KERL, ABER GROSS WAS DAHINTER.\"")
  (1096)
  (1100 "BLAUER WEISE" "JAK, DU BESITZT EIN UNGLAUBLICHES TALENT, ECO ZU KANALISIEREN!")
  (1219)
  (1222 "BLAUER WEISE" "SAMOS, VIELLEICHT HATTEST DU DOCH RECHT MIT DEM BURSCHEN!")
  (1321)
  (1323 "ROTER WEISE" "UND KEIRA, OHNE DEINE HILFE UND DEINEN EINFALLSREICHTUM WÄRE NICHTS DAVON MÖGLICH GEWESEN.")
  (1515 "ROTER WEISE" "HA, HA, HA. VIELLEICHT HABEN WIR JA EINEN NEUEN WEISEN GEFUNDEN, JETZT, WO GOL UND MAIA FORT SIND.")
  (1728)
  (1731 "SAMOS" "JA, GOL UND MAIA... DAS DUNKLE ECO HAT SIE MÖGLICHERWEISE GETÖTET.")
  (1916 :offscreen "SAGE" "MÖGLICHERWEISE...")
  (1999)
  (2003 "DAXTER" "ACH, WEN JUCKT'S? HOLT SIE HER, WIR MACHEN SIE NOCHMAL FERTIG! ODER, JAK?")
  (2168)
  (2172 "DAXTER" "ICH SAGTE, \"ODER, JAK?\"")
  (2256)
  (2302 "DAXTER" "WOW! NIMM MAL 'NE KALTE DUSCHE, DU HELD!")
  )

("green-sagecage-outro-beat-boss-enough-cells"
  (151 "SAMOS" "HEILIGE YAKOW! WAS IST DAS DENN?")
  (270 "KEIRA" "WOW, DAS IST EINE ALTE PRECURSOR-TÜR!")
  (342 :offscreen "KEIRA" "ES SCHEINT, ALS LIESSE SIE SICH ÖFFNEN, WENN WIR ALLE 100 LÖCHER MIT ENERGIEZELLEN FÜLLEN!")
  (485 "DAXTER" "ÄHM, WIR SIND HELDEN, WISST IHR NOCH? WIR HABEN 100 ENERGIEZELLEN!")
  )

("green-sagecage-outro-beat-boss-need-cells"
  (151 "SAMOS" "HEILIGE YAKOW! WAS IST DAS DENN?")
  (266 "KEIRA" "WOW, DAS IST EINE ALTE PRECURSOR-TÜR!")
  (342 :offscreen "KEIRA" "ES SCHEINT, ALS LIESSE SIE SICH ÖFFNEN, WENN WIR ALLE 100 LÖCHER MIT ENERGIEZELLEN FÜLLEN!")
  (485 "DAXTER" "OH, MANN, JETZT GEHT DAS SCHON WIEDER LOS!")
  )

("green-sagecage-outro-big-finish"
  (322 "DAXTER" "WOW! WAS... IST DAS?")
  (425)
  (428 "KEIRA" "OH, ES IST WUNDERSCHÖN...")
  (516)
  (519 "SAMOS" "BEI ALLEN PRECURSORN...")
  (602)
  )

;; -----------------
;; training
;; -----------------

;; -----------------
;; uncategorized
;; -----------------

