("ATO.DGO"
  ("gun-buoy.o" "gun-buoy")
  ("atoll-part.o" "atoll-part")
  ("atoll-obs.o" "atoll-obs")
  ("fodder.o" "fodder")
  ("tpage-856.go" "tpage-856")
  ("tpage-858.go" "tpage-858")
  ("tpage-857.go" "tpage-857")
  ("tpage-855.go" "tpage-855")
  ("tpage-1083.go" "tpage-1083")
  ("fodder-ag.go" "fodder")
  ("liftcat-ag.go" "liftcat")
  ("com-airlock-outer-ag.go" "com-airlock-outer")
  ("atoll-windmill-ag.go" "atoll-windmill")
  ("turbine-ag.go" "turbine")
  ("slider-ag.go" "slider")
  ("gun-buoy-ag.go" "gun-buoy")
  ("atoll-hatch-ag.go" "atoll-hatch")
  ("atoll-valve-ag.go" "atoll-valve")
  ("piston-ag.go" "piston")
  ("atollrotpipe-ag.go" "atollrotpipe")
  ("atoll-mar-symbol-ag.go" "atoll-mar-symbol")
  ("atoll-vis.go" "atoll-vis")
  )
