("CAB.DGO"
  ("casboss-texture.o" "casboss-texture")
  ("castle-baron.o" "castle-baron")
  ("castle-scenes.o" "castle-scenes")
  ("casboss-part.o" "casboss-part")
  ("tpage-2996.go" "tpage-2996")
  ("tpage-2997.go" "tpage-2997")
  ("tpage-3435.go" "tpage-3435")
  ("tpage-3458.go" "tpage-3458")
  ("tpage-3429.go" "tpage-3429")
  ("krew-highres-ag.go" "krew-highres")
  ("krew-lowres-ag.go" "krew-lowres")
  ("cboss-tractor-ag.go" "cboss-tractor")
  ("krew-clone-ag.go" "krew-clone")
  ("com-airlock-outer-ag.go" "com-airlock-outer")
  ("cboss-bomb-ag.go" "cboss-bomb")
  ("cboss-elevator-ag.go" "cboss-elevator")
  ("casboss-vis.go" "casboss-vis")
  )
