("CASEXT.DGO"
  ("tpage-2597.go" "tpage-2597")
  ("tpage-3424.go" "tpage-3424")
  ("tpage-3315.go" "tpage-3315")
  ("daxter-highres-ag.go" "daxter-highres")
  ("jak-highres-ag.go" "jak-highres")
  ("ashelin-highres-ag.go" "ashelin-highres")
  ("hellcat-ag.go" "hellcat")
  ("heart-of-mar-ag.go" "heart-of-mar")
  ("gun-upgrade-a-ag.go" "gun-upgrade-a")
  ("particleman-ag.go" "particleman")
  ("casext.go" "casext")
  )
