("CFA.DGO"
  ("ctyfarm-obs.o" "ctyfarm-obs")
  ("ctyfarma-part.o" "ctyfarma-part")
  ("ctyfarmb-part.o" "ctyfarmb-part")
  ("yakow.o" "yakow")
  ("tpage-2444.go" "tpage-2444")
  ("tpage-2445.go" "tpage-2445")
  ("tpage-2645.go" "tpage-2645")
  ("tpage-2644.go" "tpage-2644")
  ("tpage-2744.go" "tpage-2744")
  ("tpage-2791.go" "tpage-2791")
  ("tpage-2441.go" "tpage-2441")
  ("com-airlock-outer-ag.go" "com-airlock-outer")
  ("com-airlock-inner-ag.go" "com-airlock-inner")
  ("farm-chilirots-ag.go" "farm-chilirots")
  ("farm-cabbage-ag.go" "farm-cabbage")
  ("farm-marrow-ag.go" "farm-marrow")
  ("farm-beetree-ag.go" "farm-beetree")
  ("farm-small-cabbage-ag.go" "farm-small-cabbage")
  ("farm-sprinkler-barrels-ag.go" "farm-sprinkler-barrels")
  ("ctyfarma-vis.go" "ctyfarma-vis")
  )
