("CFB.DGO"
  ("ctyfarm-obs.o" "ctyfarm-obs")
  ("ctyfarma-part.o" "ctyfarma-part")
  ("ctyfarmb-part.o" "ctyfarmb-part")
  ("yakow.o" "yakow")
  ("tpage-3005.go" "tpage-3005")
  ("tpage-3009.go" "tpage-3009")
  ("tpage-3007.go" "tpage-3007")
  ("tpage-3008.go" "tpage-3008")
  ("tpage-3006.go" "tpage-3006")
  ("tpage-3004.go" "tpage-3004")
  ("tpage-2442.go" "tpage-2442")
  ("yakow-ag.go" "yakow")
  ("farm-chilirots-ag.go" "farm-chilirots")
  ("farm-cabbage-ag.go" "farm-cabbage")
  ("farm-marrow-ag.go" "farm-marrow")
  ("farm-beetree-ag.go" "farm-beetree")
  ("farm-small-cabbage-ag.go" "farm-small-cabbage")
  ("farm-sprinkler-barrels-ag.go" "farm-sprinkler-barrels")
  ("ctyfarmb-vis.go" "ctyfarmb-vis")
  )
