("CMA.DGO"
  ("ctymark-obs.o" "ctymark-obs")
  ("ctymarka-part.o" "ctymarka-part")
  ("ctymarkb-part.o" "ctymarkb-part")
  ("tpage-2739.go" "tpage-2739")
  ("tpage-2743.go" "tpage-2743")
  ("tpage-2740.go" "tpage-2740")
  ("tpage-2741.go" "tpage-2741")
  ("tpage-2742.go" "tpage-2742")
  ("tpage-1615.go" "tpage-1615")
  ("tpage-1643.go" "tpage-1643")
  ("market-sack-b-ag.go" "market-sack-b")
  ("market-sack-a-ag.go" "market-sack-a")
  ("market-crate-ag.go" "market-crate")
  ("market-basket-b-ag.go" "market-basket-b")
  ("market-basket-a-ag.go" "market-basket-a")
  ("cty-fruit-stand-ag.go" "cty-fruit-stand")
  ("ctymarka-vis.go" "ctymarka-vis")
  )
