("CMB.DGO"
  ("ctymark-obs.o" "ctymark-obs")
  ("ctymarka-part.o" "ctymarka-part")
  ("ctymarkb-part.o" "ctymarkb-part")
  ("tpage-2734.go" "tpage-2734")
  ("tpage-2738.go" "tpage-2738")
  ("tpage-2735.go" "tpage-2735")
  ("tpage-2737.go" "tpage-2737")
  ("tpage-2736.go" "tpage-2736")
  ("tpage-1616.go" "tpage-1616")
  ("tpage-1644.go" "tpage-1644")
  ("market-sack-b-ag.go" "market-sack-b")
  ("market-sack-a-ag.go" "market-sack-a")
  ("market-crate-ag.go" "market-crate")
  ("market-basket-b-ag.go" "market-basket-b")
  ("market-basket-a-ag.go" "market-basket-a")
  ("cty-fruit-stand-ag.go" "cty-fruit-stand")
  ("ctymarkb-vis.go" "ctymarkb-vis")
  )
