("COA.DGO"
  ("jak-pole+0-ag.go" "jak-pole+0")
  ("consite-texture.o" "consite-texture")
  ("consite-part.o" "consite-part")
  ("consite-scenes.o" "consite-scenes")
  ("consite-obs.o" "consite-obs")
  ("baron-consite+0-ag.go" "baron-consite+0")
  ("tpage-3030.go" "tpage-3030")
  ("tpage-3031.go" "tpage-3031")
  ("tpage-3029.go" "tpage-3029")
  ("tpage-3141.go" "tpage-3141")
  ("consite-break-scaffold-a-ag.go" "consite-break-scaffold-a")
  ("consite-break-scaffold-ag.go" "consite-break-scaffold")
  ("daxter-highres-ag.go" "daxter-highres")
  ("jak-highres-ag.go" "jak-highres")
  ("baron-highres-ag.go" "baron-highres")
  ("crimson-guard-highres-ag.go" "crimson-guard-highres")
  ("consite-bomb-elevator-ag.go" "consite-bomb-elevator")
  ("crimson-guard-lowres-ag.go" "crimson-guard-lowres")
  ("com-airlock-outer-ag.go" "com-airlock-outer")
  ("consite-silo-doors-ag.go" "consite-silo-doors")
  ("precursor-stone-ag.go" "precursor-stone")
  ("bomb-trigger-ag.go" "bomb-trigger")
  ("consite-vis.go" "consite-vis")
  )
