("CPA.DGO"
  ("ctypal-part.o" "ctypal-part")
  ("ctypal-obs.o" "ctypal-obs")
  ("tpage-2526.go" "tpage-2526")
  ("tpage-2527.go" "tpage-2527")
  ("tpage-3423.go" "tpage-3423")
  ("tpage-2528.go" "tpage-2528")
  ("tpage-1636.go" "tpage-1636")
  ("ctypal-baron-statue-broken-ag.go" "ctypal-baron-statue-broken")
  ("com-airlock-outer-ag.go" "com-airlock-outer")
  ("com-airlock-inner-ag.go" "com-airlock-inner")
  ("water-anim-ctypal-ag.go" "water-anim-ctypal")
  ("palace-door-ag.go" "palace-door")
  ("ctypal-broke-wall-ag.go" "ctypal-broke-wall")
  ("ctypal-vis.go" "ctypal-vis")
  )
