("CPO.DGO"
  ("ctyport-part.o" "ctyport-part")
  ("tpage-1557.go" "tpage-1557")
  ("tpage-1560.go" "tpage-1560")
  ("tpage-1558.go" "tpage-1558")
  ("tpage-1325.go" "tpage-1325")
  ("tpage-1645.go" "tpage-1645")
  ("barge-ag.go" "barge")
  ("mecha-daxter-ag.go" "mecha-daxter")
  ("farthy-ag.go" "farthy")
  ("air-train-ag.go" "air-train")
  ("hip-door-a-ag.go" "hip-door-a")
  ("ctyport-vis.go" "ctyport-vis")
  )
