("DEMO.DGO"
  ("demo-obs.o" "demo-obs")
  ("tpage-1872.go" "tpage-1872")
  ("tpage-1876.go" "tpage-1876")
  ("tpage-1868.go" "tpage-1868")
  ("daxter-highres-ag.go" "daxter-highres")
  ("jak-logo-ag.go" "jak-logo")
  ("jak-stand-ag.go" "jak-stand")
  ("demo.go" "demo")
  )
