("FEA.DGO"
  ("crimson-guard-level.o" "crimson-guard-level")
  ("guard-conversation.o" "guard-conversation")
  ("transport-level.o" "transport-level")
  ("jak-pole+0-ag.go" "jak-pole+0")
  ("forexita-part.o" "forexita-part")
  ("forexita-obs.o" "forexita-obs")
  ("tpage-1580.go" "tpage-1580")
  ("tpage-1583.go" "tpage-1583")
  ("tpage-1581.go" "tpage-1581")
  ("crimson-guard-ag.go" "crimson-guard")
  ("fort-lift-plat-ag.go" "fort-lift-plat")
  ("forexita-vis.go" "forexita-vis")
  )
