("FRB.DGO"
  ("fort-floor-spike.o" "fort-floor-spike")
  ("forrescb-part.o" "forrescb-part")
  ("forrescb-obs.o" "forrescb-obs")
  ("fort-turret.o" "fort-turret")
  ("spydroid.o" "spydroid")
  ("tpage-3172.go" "tpage-3172")
  ("tpage-3175.go" "tpage-3175")
  ("tpage-3173.go" "tpage-3173")
  ("tpage-3174.go" "tpage-3174")
  ("spydroid-ag.go" "spydroid")
  ("fort-turret-ag.go" "fort-turret")
  ("fort-entry-gate-ag.go" "fort-entry-gate")
  ("cty-guard-turret-button-ag.go" "cty-guard-turret-button")
  ("fort-elec-belt-ag.go" "fort-elec-belt")
  ("forrescb-vis.go" "forrescb-vis")
  )
