("GGA.DGO"
  ("gun-dummy.o" "gun-dummy")
  ("gungame-data.o" "gungame-data")
  ("gungame-obs.o" "gungame-obs")
  ("gungame-part.o" "gungame-part")
  ("tpage-1733.go" "tpage-1733")
  ("tpage-1735.go" "tpage-1735")
  ("tpage-1734.go" "tpage-1734")
  ("tpage-2405.go" "tpage-2405")
  ("daxter-highres-ag.go" "daxter-highres")
  ("jak-highres-ag.go" "jak-highres")
  ("gun-dummy-yellow-gun-ag.go" "gun-dummy-yellow-gun")
  ("gun-cit-d-ag.go" "gun-cit-d")
  ("gun-cit-a-ag.go" "gun-cit-a")
  ("gun-cit-b-ag.go" "gun-cit-b")
  ("gun-dummy-gold-ag.go" "gun-dummy-gold")
  ("gun-dummy-a-ag.go" "gun-dummy-a")
  ("gun-dummy-c-ag.go" "gun-dummy-c")
  ("gun-dummy-b-ag.go" "gun-dummy-b")
  ("gun-cit-c-ag.go" "gun-cit-c")
  ("gun-dummy-big-ag.go" "gun-dummy-big")
  ("fort-entry-gate-ag.go" "fort-entry-gate")
  ("hip-door-a-ag.go" "hip-door-a")
  ("yellow-barrel-ag.go" "yellow-barrel")
  ("dark-barrel-ag.go" "dark-barrel")
  ("gungame-vis.go" "gungame-vis")
  )
