("HIDEOUT.DGO"
  ("hideout-scenes.o" "hideout-scenes")
  ("hideout-part.o" "hideout-part")
  ("hideout-obs.o" "hideout-obs")
  ("tpage-932.go" "tpage-932")
  ("tpage-933.go" "tpage-933")
  ("tpage-2404.go" "tpage-2404")
  ("tpage-999.go" "tpage-999")
  ("daxter-highres-ag.go" "daxter-highres")
  ("jak-highres-ag.go" "jak-highres")
  ("hide-light-ag.go" "hide-light")
  ("hide-bike-ag.go" "hide-bike")
  ("hide-door-b-ag.go" "hide-door-b")
  ("gun-barrel-ag.go" "gun-barrel")
  ("hide-faucet-ag.go" "hide-faucet")
  ("particleman-ag.go" "particleman")
  ("hideout.go" "hideout")
  )
