("HIPHOG.DGO"
  ("hiphog-obs.o" "hiphog-obs")
  ("hiphog-part.o" "hiphog-part")
  ("hiphog-scenes.o" "hiphog-scenes")
  ("tpage-929.go" "tpage-929")
  ("tpage-930.go" "tpage-930")
  ("tpage-3042.go" "tpage-3042")
  ("tpage-998.go" "tpage-998")
  ("daxter-highres-ag.go" "daxter-highres")
  ("jak-highres-ag.go" "jak-highres")
  ("hip-whack-a-metal-ag.go" "hip-whack-a-metal")
  ("hip-trophy-g-ag.go" "hip-trophy-g")
  ("hip-trophy-d-ag.go" "hip-trophy-d")
  ("hip-trophy-c-ag.go" "hip-trophy-c")
  ("hip-trophy-a-ag.go" "hip-trophy-a")
  ("hip-trophy-f-ag.go" "hip-trophy-f")
  ("hip-trophy-i-ag.go" "hip-trophy-i")
  ("hip-trophy-m-ag.go" "hip-trophy-m")
  ("hip-door-a-ag.go" "hip-door-a")
  ("hip-trophy-n-ag.go" "hip-trophy-n")
  ("hip-trophy-j-ag.go" "hip-trophy-j")
  ("hip-mirror-ag.go" "hip-mirror")
  ("hiphog.go" "hiphog")
  )
