("INTROCST.DGO"
  ("intro-ocean.o" "intro-ocean")
  ("intro-scenes.o" "intro-scenes")
  ("intro-obs.o" "intro-obs")
  ("vortex-data.o" "vortex-data")
  ("vortex.o" "vortex")
  ("tpage-2568.go" "tpage-2568")
  ("tpage-2570.go" "tpage-2570")
  ("tpage-3264.go" "tpage-3264")
  ("daxter-highres-ag.go" "daxter-highres")
  ("jakone-highres-ag.go" "jakone-highres")
  ("errol-highres-ag.go" "errol-highres")
  ("crimson-guard-lowres-ag.go" "crimson-guard-lowres")
  ("time-map-ag.go" "time-map")
  ("rift-rider-heart-of-mar-ag.go" "rift-rider-heart-of-mar")
  ("rift-rider-dash-ag.go" "rift-rider-dash")
  ("meteor-ag.go" "meteor")
  ("rift-rider-break-b-ag.go" "rift-rider-break-b")
  ("vortex-light-ag.go" "vortex-light")
  ("rift-rider-chunk-a-ag.go" "rift-rider-chunk-a")
  ("rift-rider-break-c-ag.go" "rift-rider-break-c")
  ("particleman-ag.go" "particleman")
  ("rift-rider-bar-ag.go" "rift-rider-bar")
  ("introcst.go" "introcst")
  )
