("LDJAKBRN.DGO"
  ("tpage-2662.go" "tpage-2662")
  ("tpage-2657.go" "tpage-2657")
  ("tpage-3094.go" "tpage-3094")
  ("jak-highres-prison-ag.go" "jak-highres-prison")
  ("baron-highres-ag.go" "baron-highres")
  ("prsn-daxter-plat-ag.go" "prsn-daxter-plat")
  ("jak-clothes-ag.go" "jak-clothes")
  ("ldjakbrn.go" "ldjakbrn")
  )
