("LERLCHAL.DGO"
  ("race-h.o" "race-h")
  ("race-mesh.o" "race-mesh")
  ("race-part.o" "race-part")
  ("race-obs.o" "race-obs")
  ("vehicle-racer.o" "vehicle-racer")
  ("race-info.o" "race-info")
  ("race-manager.o" "race-manager")
  ("race-hud.o" "race-hud")
  ("pilot-recorder.o" "pilot-recorder")
  ("errol-chal-part.o" "errol-chal-part")
  ("errol-chal.o" "errol-chal")
  ("tpage-3159.go" "tpage-3159")
  ("tpage-3337.go" "tpage-3337")
  ("errol-racer-ag.go" "errol-racer")
  ("lerlchal.go" "lerlchal")
  )
