("LGARCSTA.DGO"
  ("tpage-2699.go" "tpage-2699")
  ("tpage-3512.go" "tpage-3512")
  ("tpage-3271.go" "tpage-3271")
  ("krew-highres-ag.go" "krew-highres")
  ("samos-highres-ag.go" "samos-highres")
  ("tess-highres-ag.go" "tess-highres")
  ("ashelin-highres-ag.go" "ashelin-highres")
  ("gold-key-ag.go" "sew-gold-key")
  ("lgarcsta.go" "lgarcsta")
  )
