("LHIPOUT.DGO"
  ("tpage-3440.go" "tpage-3440")
  ("tpage-3199.go" "tpage-3199")
  ("tpage-3200.go" "tpage-3200")
  ("tpage-3486.go" "tpage-3486")
  ("tpage-3242.go" "tpage-3242")
  ("tpage-3544.go" "tpage-3544")
  ("pecker-highres-ag.go" "pecker-highres")
  ("crocadog-highres-ag.go" "crocadog-highres")
  ("sig-highres-ag.go" "sig-highres")
  ("metalkor-chopped-ag.go" "metalkor-chopped")
  ("gold-key-ag.go" "sew-gold-key")
  ("kid-medallion-ag.go" "kid-medallion")
  ("hip-bottle-c-ag.go" "hip-bottle-c")
  ("hip-mug-ag.go" "hip-mug")
  ("particleman-ag.go" "particleman")
  ("lhipout.go" "lhipout")
  )
