("LKIDDOGE.DGO"
  ("ai-task-h.o" "ai-task-h")
  ("bot-h.o" "bot-h")
  ("bot.o" "bot")
  ("bot-states.o" "bot-states")
  ("hal-h.o" "hal-h")
  ("hal-task.o" "hal-task")
  ("hal.o" "hal")
  ("kidesc-h.o" "kidesc-h")
  ("crocesc-h.o" "crocesc-h")
  ("hal4-course.o" "hal4-course")
  ("kidesc-task.o" "kidesc-task")
  ("kidesc.o" "kidesc")
  ("kidesc-states.o" "kidesc-states")
  ("crocesc-task.o" "crocesc-task")
  ("crocesc.o" "crocesc")
  ("crocesc-states.o" "crocesc-states")
  ("kidesc4-course.o" "kidesc4-course")
  ("crocesc4-course.o" "crocesc4-course")
  ("tpage-2209.go" "tpage-2209")
  ("crocadog-escort-ag.go" "crocadog-escort")
  ("kid-escort-ag.go" "kid-escort")
  ("lkiddoge.go" "lkiddoge")
  )
