("LOUTCSTB.DGO"
  ("tpage-3186.go" "tpage-3186")
  ("tpage-3185.go" "tpage-3185")
  ("tpage-3187.go" "tpage-3187")
  ("tpage-3245.go" "tpage-3245")
  ("youngsamos-highres-ag.go" "youngsamos-highres")
  ("brutter-highres-ag.go" "brutter-highres")
  ("kid-highres-ag.go" "kid-highres")
  ("rift-ring-ag.go" "rift-ring")
  ("brutter-balloon-norift-ag.go" "brutter-balloon-norift")
  ("metalkor-chopped-ag.go" "metalkor-chopped")
  ("rift-rider-ag.go" "rift-rider")
  ("precursor-stone-ag.go" "precursor-stone")
  ("particleman-ag.go" "particleman")
  ("loutcstb.go" "loutcstb")
  )
