("LSAMERGD.DGO"
  ("samos-lsamergd+0-ag.go" "samos-lsamergd+0")
  ("tpage-2701.go" "tpage-2701")
  ("tpage-3248.go" "tpage-3248")
  ("samos-highres-ag.go" "samos-highres")
  ("errol-highres-ag.go" "errol-highres")
  ("crimson-guard-highres-ag.go" "crimson-guard-highres")
  ("crimson-guard-lowres-ag.go" "crimson-guard-lowres")
  ("lsamergd.go" "lsamergd")
  )
