("LTRNTESS.DGO"
  ("tess-ltrntess+0-ag.go" "tess-ltrntess+0")
  ("tpage-1764.go" "tpage-1764")
  ("tpage-3254.go" "tpage-3254")
  ("daxter-highres-ag.go" "daxter-highres")
  ("jak-highres-ag.go" "jak-highres")
  ("torn-highres-ag.go" "torn-highres")
  ("tess-highres-ag.go" "tess-highres")
  ("particleman-ag.go" "particleman")
  ("ltrntess.go" "ltrntess")
  )
