("LWHACK.DGO"
  ("daxter-mole+0-ag.go" "daxter-mole+0")
  ("tess-lwhack+0-ag.go" "tess-lwhack+0")
  ("whack.o" "whack")
  ("tpage-2889.go" "tpage-2889")
  ("tpage-3256.go" "tpage-3256")
  ("tess-highres-ag.go" "tess-highres")
  ("time-map-ag.go" "time-map")
  ("grunt-fma-ag.go" "grunt-fma")
  ("hip-mole-ag.go" "hip-mole")
  ("big-bopper-ag.go" "big-bopper")
  ("particleman-ag.go" "particleman")
  ("lwhack.go" "lwhack")
  )
