("LWIDEC.DGO"
  ("tpage-3039.go" "tpage-3039")
  ("tpage-3041.go" "tpage-3041")
  ("roboguard-ag.go" "roboguard")
  ("citizen-norm-ag.go" "citizen-norm")
  ("crimson-guard-ag.go" "crimson-guard")
  ("citizen-chick-ag.go" "citizen-chick")
  ("hellcat-ag.go" "hellcat")
  ("carc-ag.go" "carc")
  ("cara-ag.go" "cara")
  ("carb-ag.go" "carb")
  ("crimson-bike-ag.go" "crimson-bike")
  ("bikec-ag.go" "bikec")
  ("bikeb-ag.go" "bikeb")
  ("bikea-ag.go" "bikea")
  ("lwidec.go" "lwidec")
  )
