("LWIDEB.DGO"
  ("tpage-2972.go" "tpage-2972")
  ("grunt-ag.go" "grunt")
  ("citizen-norm-ag.go" "citizen-norm")
  ("crimson-guard-ag.go" "crimson-guard")
  ("predator-ag.go" "predator")
  ("flitter-ag.go" "flitter")
  ("cara-ag.go" "cara")
  ("citizen-norm-rider-ag.go" "citizen-norm-rider")
  ("crimson-bike-ag.go" "crimson-bike")
  ("bikea-ag.go" "bikea")
  ("lwideb.go" "lwideb")
  )
