("MCN.DGO"
  ("mincan-obs.o" "mincan-obs")
  ("canyon-scenes.o" "canyon-scenes")
  ("tpage-3341.go" "tpage-3341")
  ("tpage-3343.go" "tpage-3343")
  ("tpage-3342.go" "tpage-3342")
  ("tpage-3344.go" "tpage-3344")
  ("tpage-3471.go" "tpage-3471")
  ("daxter-highres-ag.go" "daxter-highres")
  ("jak-highres-ag.go" "jak-highres")
  ("ctypal-baron-statue-break-ag.go" "ctypal-baron-statue-break")
  ("mincan-cogs-ag.go" "mincan-cogs")
  ("ctypal-break-wall-ag.go" "ctypal-break-wall")
  ("mincan-lighthouse-ag.go" "mincan-lighthouse")
  ("water-anim-mincan-ag.go" "water-anim-mincan")
  ("mincan-lens-ag.go" "mincan-lens")
  ("shard-ag.go" "mtn-shard")
  ("gear-device-gear-ag.go" "mtn-gear-device-gear")
  ("mtn-lens-ag.go" "mtn-lens")
  ("particleman-ag.go" "particleman")
  ("mincan-vis.go" "mincan-vis")
  )
