("ONINTENT.DGO"
  ("onintent-part.o" "onintent-part")
  ("onintent-scenes.o" "onintent-scenes")
  ("onin-game.o" "onin-game")
  ("onin-game+0-ag.go" "onin-game+0")
  ("tpage-1031.go" "tpage-1031")
  ("tpage-1183.go" "tpage-1183")
  ("tpage-2676.go" "tpage-2676")
  ("tpage-1035.go" "tpage-1035")
  ("daxter-highres-ag.go" "daxter-highres")
  ("pecker-highres-ag.go" "pecker-highres")
  ("jak-highres-ag.go" "jak-highres")
  ("onin-highres-ag.go" "onin-highres")
  ("life-seed-ag.go" "life-seed")
  ("onin-brain-ag.go" "onin-brain")
  ("son-of-particleman-ag.go" "son-of-particleman")
  ("particleman-ag.go" "particleman")
  ("onintent.go" "onintent")
  )
