("ORACLE.DGO"
  ("oracle-texture.o" "oracle-texture")
  ("oracle-part.o" "oracle-part")
  ("oracle-scenes.o" "oracle-scenes")
  ("oracle-training.o" "oracle-training")
  ("tpage-2553.go" "tpage-2553")
  ("tpage-2863.go" "tpage-2863")
  ("tpage-2557.go" "tpage-2557")
  ("daxter-highres-ag.go" "daxter-highres")
  ("darkjak-highres-ag.go" "darkjak-highres")
  ("oracle-roof-banner-b-ag.go" "oracle-roof-banner-b")
  ("oracle-roof-banner-ag.go" "oracle-roof-banner")
  ("door-ag.go" "oracle-door")
  ("oracle-wall-banner-ag.go" "oracle-wall-banner")
  ("particleman-ag.go" "particleman")
  ("oracle.go" "oracle")
  )
