("OUTROCST.DGO"
  ("0credits-tx.go" "0credits-tx")
  ("1credits-tx.go" "1credits-tx")
  ("2credits-tx.go" "2credits-tx")
  ("3credits-tx.go" "3credits-tx")
  ("4credits-tx.go" "4credits-tx")
  ("5credits-tx.go" "5credits-tx")
  ("6credits-tx.go" "6credits-tx")
  ("7credits-tx.go" "7credits-tx")
  ("credits.o" "credits")
  ("outro-scenes.o" "outro-scenes")
  ("tpage-3182.go" "tpage-3182")
  ("tpage-3183.go" "tpage-3183")
  ("tpage-3263.go" "tpage-3263")
  ("tpage-3513.go" "tpage-3513")
  ("keira-highres-ag.go" "keira-highres")
  ("samos-highres-ag.go" "samos-highres")
  ("tess-highres-ag.go" "tess-highres")
  ("onin-highres-ag.go" "onin-highres")
  ("rift-break-ring-ag.go" "rift-break-ring")
  ("precursor-ag.go" "precursor")
  ("outrocst.go" "outrocst")
  )
