("PAC.DGO"
  ("jak-pole+0-ag.go" "jak-pole+0")
  ("palcab-part.o" "palcab-part")
  ("palcab-obs.o" "palcab-obs")
  ("searchlight.o" "searchlight")
  ("sew-gunturret.o" "sew-gunturret")
  ("pal-obs.o" "pal-obs")
  ("tpage-2354.go" "tpage-2354")
  ("tpage-2357.go" "tpage-2357")
  ("tpage-2355.go" "tpage-2355")
  ("tpage-2356.go" "tpage-2356")
  ("tpage-3371.go" "tpage-3371")
  ("tpage-2619.go" "tpage-2619")
  ("pal-gun-turret-ag.go" "pal-gun-turret")
  ("com-airlock-outer-ag.go" "com-airlock-outer")
  ("pal-electric-fan-ag.go" "pal-electric-fan")
  ("pal-cable-nut-ag.go" "pal-cable-nut")
  ("pal-flip-step-ag.go" "pal-flip-step")
  ("pal-rot-gun-ag.go" "pal-rot-gun")
  ("pal-falling-plat-ag.go" "pal-falling-plat")
  ("searchlight-ag.go" "searchlight")
  ("pal-windmill-ag.go" "pal-windmill")
  ("palcab-vis.go" "palcab-vis")
  )
