("PALBOSS.DGO"
  ("squid-part.o" "squid-part")
  ("squid-setup.o" "squid-setup")
  ("squid-extras.o" "squid-extras")
  ("squid-states.o" "squid-states")
  ("baron-squid+0-ag.go" "baron-squid+0")
  ("tpage-2679.go" "tpage-2679")
  ("tpage-2680.go" "tpage-2680")
  ("tpage-2797.go" "tpage-2797")
  ("tpage-3419.go" "tpage-3419")
  ("daxter-highres-ag.go" "daxter-highres")
  ("jak-highres-ag.go" "jak-highres")
  ("squid-ag.go" "squid")
  ("squid-break-ag.go" "squid-break")
  ("baron-highres-ag.go" "baron-highres")
  ("baron-ag.go" "baron")
  ("squid-collision-ag.go" "squid-collision")
  ("palboss.go" "palboss")
  )
