("PAR.DGO"
  ("palroof-part.o" "palroof-part")
  ("palroof-obs.o" "palroof-obs")
  ("palboss-texture.o" "palboss-texture")
  ("palboss-part.o" "palboss-part")
  ("palboss-scenes.o" "palboss-scenes")
  ("tpage-2360.go" "tpage-2360")
  ("tpage-2363.go" "tpage-2363")
  ("tpage-2361.go" "tpage-2361")
  ("tpage-2362.go" "tpage-2362")
  ("tpage-2521.go" "tpage-2521")
  ("tpage-2746.go" "tpage-2746")
  ("com-airlock-outer-ag.go" "com-airlock-outer")
  ("pal-prong-ag.go" "pal-prong")
  ("pal-flip-step-ag.go" "pal-flip-step")
  ("pal-lowrez-throne-ag.go" "pal-lowrez-throne")
  ("palroof-vis.go" "palroof-vis")
  )
