("PRI.DGO"
  ("intro-texture.o" "intro-texture")
  ("prison-part.o" "prison-part")
  ("prison-obs.o" "prison-obs")
  ("tpage-1578.go" "tpage-1578")
  ("tpage-1950.go" "tpage-1950")
  ("tpage-1579.go" "tpage-1579")
  ("tpage-2647.go" "tpage-2647")
  ("daxter-highres-ag.go" "daxter-highres")
  ("prsn-torture-ag.go" "prsn-torture")
  ("prsn-chair-shackle-ag.go" "prsn-chair-shackle")
  ("prsn-hang-cell-ag.go" "prsn-hang-cell")
  ("warp-gate-b-ag.go" "warp-gate-b")
  ("prsn-vent-fan-ag.go" "prsn-vent-fan")
  ("fort-entry-gate-ag.go" "fort-entry-gate")
  ("prsn-cell-door-ag.go" "prsn-cell-door")
  ("prison-vis.go" "prison-vis")
  )
