("SAG.DGO"
  ("tpage-881.go" "tpage-881")
  ("tpage-1131.go" "tpage-1131")
  ("tpage-882.go" "tpage-882")
  ("tpage-880.go" "tpage-880")
  ("daxter-highres-ag.go" "daxter-highres")
  ("jak-highres-ag.go" "jak-highres")
  ("torn-highres-ag.go" "torn-highres")
  ("ruins-tower-a-ag.go" "ruins-tower-a")
  ("ruins-tower-c-ag.go" "ruins-tower-c")
  ("ruins-tower-e-ag.go" "ruins-tower-e")
  ("ruins-tower-b-ag.go" "ruins-tower-b")
  ("ruins-tower-f-ag.go" "ruins-tower-f")
  ("ruins-tower-d-ag.go" "ruins-tower-d")
  ("life-seed-ag.go" "life-seed")
  ("ruins-tower-rp-ag.go" "ruins-tower-rp")
  ("sagehut-vis.go" "sagehut-vis")
  )
