("SEW.DGO"
  ("tpage-1059.go" "tpage-1059")
  ("tpage-1060.go" "tpage-1060")
  ("tpage-1066.go" "tpage-1066")
  ("tpage-2270.go" "tpage-2270")
  ("tpage-3479.go" "tpage-3479")
  ("daxter-highres-ag.go" "daxter-highres")
  ("grunt-ag.go" "grunt")
  ("jak-highres-ag.go" "jak-highres")
  ("amphibian-ag.go" "amphibian")
  ("sew-catwalk-ag.go" "sew-catwalk")
  ("sew-multi-blade-ag.go" "sew-multi-blade")
  ("fodder-ag.go" "fodder")
  ("sew-gunturret-ag.go" "sew-gunturret")
  ("mar-statue-ag.go" "sew-mar-statue")
  ("sew-twist-blade-ag.go" "sew-twist-blade")
  ("sew-tri-blade-ag.go" "sew-tri-blade")
  ("sew-single-blade-ag.go" "sew-single-blade")
  ("mine-a-ag.go" "sew-mine-a")
  ("sew-valve-ag.go" "sew-valve")
  ("mine-b-ag.go" "sew-mine-b")
  ("sew-arm-blade-ag.go" "sew-arm-blade")
  ("gold-key-ag.go" "sew-gold-key")
  ("light-switch-ag.go" "sew-light-switch")
  ("grill-ag.go" "sew-grill")
  ("sewer-vis.go" "sewer-vis")
  )
