("STA.DGO"
  ("hopper.o" "hopper")
  ("stadiumb-texture.o" "stadiumb-texture")
  ("stadium-part.o" "stadium-part")
  ("stadiumb-part.o" "stadiumb-part")
  ("stadium-obs.o" "stadium-obs")
  ("stadium-scenes.o" "stadium-scenes")
  ("tpage-2423.go" "tpage-2423")
  ("tpage-2426.go" "tpage-2426")
  ("tpage-2424.go" "tpage-2424")
  ("tpage-2575.go" "tpage-2575")
  ("tpage-1641.go" "tpage-1641")
  ("daxter-highres-ag.go" "daxter-highres")
  ("jak-highres-ag.go" "jak-highres")
  ("water-anim-stadium-ag.go" "water-anim-stadium")
  ("gar-door-ag.go" "gar-door")
  ("stadium-vis.go" "stadium-vis")
  )
