("STB.DGO"
  ("race-h.o" "race-h")
  ("race-mesh.o" "race-mesh")
  ("race-part.o" "race-part")
  ("race-obs.o" "race-obs")
  ("vehicle-racer.o" "vehicle-racer")
  ("race-info.o" "race-info")
  ("race-manager.o" "race-manager")
  ("race-hud.o" "race-hud")
  ("pilot-recorder.o" "pilot-recorder")
  ("racebike.o" "racebike")
  ("stadium-race-obs.o" "stadium-race-obs")
  ("jak-pidax+0-ag.go" "jak-pidax+0")
  ("tpage-3451.go" "tpage-3451")
  ("tpage-3454.go" "tpage-3454")
  ("tpage-3452.go" "tpage-3452")
  ("tpage-3453.go" "tpage-3453")
  ("tpage-3109.go" "tpage-3109")
  ("race-bike-c-ag.go" "race-bike-c")
  ("race-bike-b-ag.go" "race-bike-b")
  ("race-bike-a-ag.go" "race-bike-a")
  ("stdmb-race-hatch-ag.go" "stdmb-race-hatch")
  ("stad-force-field-ag.go" "stad-force-field")
  ("stadiumb-vis.go" "stadiumb-vis")
  )
