("STC.DGO"
  ("race-h.o" "race-h")
  ("race-mesh.o" "race-mesh")
  ("race-part.o" "race-part")
  ("race-obs.o" "race-obs")
  ("vehicle-racer.o" "vehicle-racer")
  ("race-info.o" "race-info")
  ("race-manager.o" "race-manager")
  ("race-hud.o" "race-hud")
  ("pilot-recorder.o" "pilot-recorder")
  ("racebike.o" "racebike")
  ("stadium-race-obs.o" "stadium-race-obs")
  ("jak-pidax+0-ag.go" "jak-pidax+0")
  ("tpage-3442.go" "tpage-3442")
  ("tpage-3445.go" "tpage-3445")
  ("tpage-3443.go" "tpage-3443")
  ("tpage-3444.go" "tpage-3444")
  ("tpage-3351.go" "tpage-3351")
  ("race-bike-c-ag.go" "race-bike-c")
  ("race-bike-b-ag.go" "race-bike-b")
  ("race-bike-a-ag.go" "race-bike-a")
  ("stdmb-race-hatch-ag.go" "stdmb-race-hatch")
  ("stad-c-force-field-ag.go" "stad-c-force-field")
  ("stadiumc-vis.go" "stadiumc-vis")
  )
