("STD.DGO"
  ("race-h.o" "race-h")
  ("race-mesh.o" "race-mesh")
  ("race-part.o" "race-part")
  ("race-obs.o" "race-obs")
  ("vehicle-racer.o" "vehicle-racer")
  ("race-info.o" "race-info")
  ("race-manager.o" "race-manager")
  ("race-hud.o" "race-hud")
  ("pilot-recorder.o" "pilot-recorder")
  ("racebike.o" "racebike")
  ("stadium-race-obs.o" "stadium-race-obs")
  ("jak-pidax+0-ag.go" "jak-pidax+0")
  ("tpage-3447.go" "tpage-3447")
  ("tpage-3450.go" "tpage-3450")
  ("tpage-3448.go" "tpage-3448")
  ("tpage-3449.go" "tpage-3449")
  ("tpage-3352.go" "tpage-3352")
  ("race-bike-c-ag.go" "race-bike-c")
  ("race-bike-b-ag.go" "race-bike-b")
  ("race-bike-a-ag.go" "race-bike-a")
  ("stdmb-race-hatch-ag.go" "stdmb-race-hatch")
  ("stad-d-force-field-ag.go" "stad-d-force-field")
  ("stadiumd-vis.go" "stadiumd-vis")
  )
