("TBO.DGO"
  ("baron-widow+0-ag.go" "baron-widow+0")
  ("tpage-1628.go" "tpage-1628")
  ("tpage-1629.go" "tpage-1629")
  ("tpage-2229.go" "tpage-2229")
  ("tpage-2247.go" "tpage-2247")
  ("tomb-boss-catwalk-ag.go" "tomb-boss-catwalk")
  ("tomb-boss-bridge-ag.go" "tomb-boss-bridge")
  ("widow-ag.go" "widow")
  ("tomb-boss-pillar-ag.go" "tomb-boss-pillar")
  ("spydroid-ag.go" "spydroid")
  ("baron-pod-ag.go" "baron-pod")
  ("tomb-boss-firepot-ag.go" "tomb-boss-firepot")
  ("baron-ag.go" "baron")
  ("tomb-boss-debris-ag.go" "tomb-boss-debris")
  ("heart-mar-ag.go" "heart-mar")
  ("widow-bomb-ag.go" "widow-bomb")
  ("tomb-wing-door-ag.go" "tomb-wing-door")
  ("particleman-ag.go" "particleman")
  ("tombboss-vis.go" "tombboss-vis")
  )
