("TOB.DGO"
  ("jak-pole+0-ag.go" "jak-pole+0")
  ("tpage-1596.go" "tpage-1596")
  ("tpage-1597.go" "tpage-1597")
  ("tomb-stair-block-ag.go" "tomb-stair-block")
  ("tomb-baby-spider-ag.go" "tomb-baby-spider")
  ("water-anim-tomb-dark-eco-ag.go" "water-anim-tomb-dark-eco")
  ("tomb-elevator-ag.go" "tomb-elevator")
  ("tomb-plat-wall-ag.go" "tomb-plat-wall")
  ("tomb-button-ag.go" "tomb-button")
  ("tomb-stair-block-spikes-ag.go" "tomb-stair-block-spikes")
  ("tomb-boulder-door-ag.go" "tomb-boulder-door")
  ("tomb-move-swing-pole-ag.go" "tomb-move-swing-pole")
  ("tombb-vis.go" "tombb-vis")
  )
