("TOC.DGO"
  ("tpage-1598.go" "tpage-1598")
  ("tpage-1599.go" "tpage-1599")
  ("tpage-1832.go" "tpage-1832")
  ("water-anim-tomb-ag.go" "water-anim-tomb")
  ("tomb-baby-spider-ag.go" "tomb-baby-spider")
  ("tomb-beetle-ag.go" "tomb-beetle")
  ("tomb-door-ag.go" "tomb-door")
  ("tomb-vibe-ag.go" "tomb-vibe")
  ("tomb-simon-button-ag.go" "tomb-simon-button")
  ("tomb-plat-simon-ag.go" "tomb-plat-simon")
  ("tomb-wing-door-ag.go" "tomb-wing-door")
  ("tomb-button-ag.go" "tomb-button")
  ("tomb-beetle-door-ag.go" "tomb-beetle-door")
  ("tombc-vis.go" "tombc-vis")
  )
