("TOD.DGO"
  ("com-elevator.o" "com-elevator")
  ("youngsamos-tombd+0-ag.go" "youngsamos-tombd+0")
  ("kid-tombd+0-ag.go" "kid-tombd+0")
  ("tpage-1626.go" "tpage-1626")
  ("tpage-1627.go" "tpage-1627")
  ("tpage-3275.go" "tpage-3275")
  ("daxter-highres-ag.go" "daxter-highres")
  ("youngsamos-highres-ag.go" "youngsamos-highres")
  ("jak-highres-ag.go" "jak-highres")
  ("crocadog-highres-ag.go" "crocadog-highres")
  ("kor-highres-ag.go" "kor-highres")
  ("kid-highres-ag.go" "kid-highres")
  ("com-airlock-outer-ag.go" "com-airlock-outer")
  ("tomb-mar-door-ag.go" "tomb-mar-door")
  ("com-elevator-ag.go" "com-elevator")
  ("tombd-vis.go" "tombd-vis")
  )
