("TOE.DGO"
  ("target-indax.o" "target-indax")
  ("jak-indax+0-ag.go" "jak-indax+0")
  ("tomb-boulder.o" "tomb-boulder")
  ("tpage-2374.go" "tpage-2374")
  ("tpage-2375.go" "tpage-2375")
  ("tpage-2376.go" "tpage-2376")
  ("tomb-boulder-ag.go" "tomb-boulder")
  ("tomb-baby-spider-ag.go" "tomb-baby-spider")
  ("tomb-plat-pillar-ag.go" "tomb-plat-pillar")
  ("spider-eyes-ag.go" "spider-eyes")
  ("tomb-bounce-web-ag.go" "tomb-bounce-web")
  ("tombe-vis.go" "tombe-vis")
  )
