("VI1.DGO"
  ("tpage-3034.go" "tpage-3034")
  ("tpage-3037.go" "tpage-3037")
  ("tpage-3035.go" "tpage-3035")
  ("tpage-3038.go" "tpage-3038")
  ("tpage-3036.go" "tpage-3036")
  ("tpage-2761.go" "tpage-2761")
  ("tpage-3516.go" "tpage-3516")
  ("daxter-highres-ag.go" "daxter-highres")
  ("darkjak-highres-ag.go" "darkjak-highres")
  ("metalkor-torso-ag.go" "metalkor-torso")
  ("rift-ring-ag.go" "rift-ring")
  ("vil-break-support-ag.go" "vil-break-support")
  ("intro-flamer-ag.go" "intro-flamer")
  ("rift-rider-donut-ag.go" "rift-rider-donut")
  ("vil-windmill-sail-ag.go" "vil-windmill-sail")
  ("vil-windspinner-ag.go" "vil-windspinner")
  ("vil-sagesail-ag.go" "vil-sagesail")
  ("particleman-ag.go" "particleman")
  ("village1-vis.go" "village1-vis")
  )
