("VIN.DGO"
  ("vinroom-part.o" "vinroom-part")
  ("vinroom-scenes.o" "vinroom-scenes")
  ("vinroom-obs.o" "vinroom-obs")
  ("kid-tombd+0-ag.go" "kid-tombd+0")
  ("tpage-778.go" "tpage-778")
  ("tpage-779.go" "tpage-779")
  ("tpage-3278.go" "tpage-3278")
  ("tpage-979.go" "tpage-979")
  ("daxter-highres-ag.go" "daxter-highres")
  ("vin-ag.go" "vin")
  ("jak-highres-ag.go" "jak-highres")
  ("crocadog-highres-ag.go" "crocadog-highres")
  ("kor-highres-ag.go" "kor-highres")
  ("kid-highres-ag.go" "kid-highres")
  ("ecowell-a-ag.go" "ecowell-a")
  ("ecowell-b-ag.go" "ecowell-b")
  ("ecowell-c-ag.go" "ecowell-c")
  ("ecowell-d-ag.go" "ecowell-d")
  ("plasmitebox-ag.go" "plasmitebox")
  ("warp-gate-ag.go" "warp-gate")
  ("vin-door-ag.go" "vin-door")
  ("vin-turbine-ag.go" "vin-turbine")
  ("pow-mov-plat-ag.go" "pow-mov-plat")
  ("palmpilot-ag.go" "palmpilot")
  ("particleman-ag.go" "particleman")
  ("vinroom-vis.go" "vinroom-vis")
  )
