(group-name "common")
(language-id 13) ;; this file is for brazilian portuguese ptbr
(text-version jak1-v2)

;; Modify these files instead:
;; - /localization/jak1/text/text_pt-BR.json
;; AUTOGENERATED STRINGS BELOW
