name: Build (C/P Actions)

on: [push, pull_request]

jobs:
  freebsd:
    runs-on: ubuntu-latest
    name: FreeBSD
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - name: Build
      uses: cross-platform-actions/action@v0.19.1
      with:
        operating_system: freebsd
        version: '13.2'
        shell: bash
        run: |
          sudo pkg update
          sudo pkg install -y \
              gmake \
              pkgconf \
              libXcursor \
              libXext \
              libXinerama \
              libXi \
              libXfixes \
              libXrandr \
              libXScrnSaver \
              libXxf86vm \
              wayland \
              wayland-protocols \
              libxkbcommon \
              mesa-libs \
              libglvnd \
              evdev-proto \
              libinotify \
              alsa-lib \
              jackit \
              pipewire \
              pulseaudio \
              sndio \
              dbus \
              zh-fcitx \
              ibus \
              libudev-devd
          mkdir build_autotools
          export CPPFLAGS="-I/usr/local/include"
          export LDFLAGS="-L/usr/local/lib"
          (cd build_autotools && ../configure --disable-static)
          gmake -C build_autotools -j`sysctl -n hw.ncpu` V=1
