version: 3

vars:
  GOALC_BIN_RELEASE_DIR: "./out/build/Release/bin"
  GK_BIN_RELEASE_DIR: "./out/build/Release/bin"
  DECOMP_BIN_DEBUG_DIR: "./out/build/Debug/bin"
  DECOMP_BIN_RELEASE_DIR: "./out/build/Release/bin"
  MEMDUMP_BIN_RELEASE_DIR: "./out/build/Release/bin"
  TYPESEARCH_BIN_RELEASE_DIR: "./out/build/Release/bin"
  OFFLINETEST_BIN_RELEASE_DIR: "./out/build/Release/bin"
  GOALCTEST_BIN_RELEASE_DIR: "./out/build/Release/bin"
  GOALCTEST_BIN_DEBUG_DIR: "./out/build/Debug/bin"
  FORMATTER_BIN_RELEASE_DIR: "./out/build/Release/bin"
  EXE_FILE_EXTENSION: ".exe"
  PYTHON: "python"
  DEFAULT_CMAKE_RELEASE_PRESET: "Release-windows-clang"
  DEFAULT_CMAKE_DEBUG_PRESET: "Debug-windows-clang"
  CMAKE_GEN_BUILD_DIR_RELEASE: ""
  CMAKE_GEN_BUILD_DIR_DEBUG: ""
  CMAKE_BUILD_DIR_RELEASE: "--build ./out/build/Release"
  CMAKE_BUILD_DIR_DEBUG: "--build ./out/build/Debug"
