version: 3

vars:
  GOALC_BIN_RELEASE_DIR: "./build/goalc"
  GK_BIN_RELEASE_DIR: "./build/game"
  DECOMP_BIN_DEBUG_DIR: "./build/decompiler"
  DECOMP_BIN_RELEASE_DIR: "./build/decompiler"
  MEMDUMP_BIN_RELEASE_DIR: "./build/tools"
  TYPESEARCH_BIN_RELEASE_DIR: "./build/tools"
  OFFLINETEST_BIN_RELEASE_DIR: "./build"
  GOALCTEST_BIN_RELEASE_DIR: "./build"
  FORMATTER_BIN_RELEASE_DIR: "./build/tools"
  EXE_FILE_EXTENSION: ""
  PYTHON: "python3"
  DEFAULT_CMAKE_RELEASE_PRESET: "Release-linux-clang"
  DEFAULT_CMAKE_DEBUG_PRESET: "Debug-linux-clang"
  CMAKE_GEN_BUILD_DIR_RELEASE: "-B build"
  CMAKE_GEN_BUILD_DIR_DEBUG: "-B build"
  CMAKE_BUILD_DIR_RELEASE: "--build build"
  CMAKE_BUILD_DIR_DEBUG: "--build build"
